/**
 * BLASPHEMOUS EDICT — the play-weighted program, #509 (EDHREC #509).
 *   "You may pay {B} rather than pay this spell's mana cost if there are thirteen or more creatures on the battlefield.
 *    Each player sacrifices thirteen creatures of their choice."
 *
 * Two lines, two readers:
 *  - THE ALTERNATIVE COST (CR 118.9): the trap form's conditional fixed-mana cost, with its condition written last
 *    (textNormalize.TRAILING_CONDITIONAL_FIXED_MANA_ALT_COST_RE — one sentence for the strip and the offer). The condition is a new
 *    interveningIf reader, "there are N or more creatures on the battlefield": every player's creatures, LAYER-AWARE
 *    (permanentIsCreature — an animated land counts). It is read as the cast begins (CR 601.2b, 601.2f lock the cost in before any
 *    mana ability is activated, 601.2g), so twelve creatures never see the {B} cost. A static tax applies to the alternative cost
 *    too (CR 118.9d): with Thalia out the variant costs {1}{B}.
 *  - THE EDICT: "each player sacrifices <N> creatures [of their choice]" → { op: "sacrifice", who: "eachPlayer", what: "creature",
 *    count: N }. Every player chooses their OWN creatures (CR 701.21a) — the active player first, then turn order (CR 101.4) — each
 *    choice logged as it is made (CR 101.4b); a player with N or fewer has no choice and loses them all (CR 609.3). Nothing leaves
 *    the battlefield until the last player has chosen: the whole set goes as ONE event (removal.sacrificeCreaturesTogether), so a
 *    Blood Artist sacrificed with the rest sees every creature that died (CR 603.10a). The AI's pick is the shared edict policy
 *    (autoPickSacrificeCandidate — its least valuable), one creature at a time.
 *
 * The same two readers complete six more cards, each witnessed here: Barter in Blood, Taste of Death, Tergrid's Shadow (an instant —
 * the APNAP witness), Rankle's Prank (the sacrifice mode, alone and with the other two), Abyssal Gorestalker (an enters trigger)
 * and Planar Collapse (an upkeep intervening-if). Necrotic Hex stays parked on its tapped-token line.
 *
 * Real oracle fixtures (bundled Scryfall, the 2026-10-01 data, generated by cardIndex.publicCard — never typed by hand).
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, createGameState, createPermanent } from "./gameState.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { advanceStep, chooseTriggerTargets, finalizeStackResolution, flushTriggers, resolveTopOfStack, runStepActions } from "./gameEngine.js";
import { autoPickDiscardCandidate, autoPickSacrificeCandidate, resolveDiscardChoice, resolveSacrificeChoice } from "./effects/runProgram.js";
import { classifyCard } from "./coverage.js";
import { parseEffectClause, parseEffectProgram, programConfidence } from "./effects/parser.js";
import { extractAltCost } from "./effects/castModifiers.js";
import { conditionalFixedManaAltCostOf, fixedManaAltCostOf } from "./effects/textNormalize.js";
import { evaluateInterveningIf, interveningIfParseable, spellConditionParseable } from "./interveningIf.js";
import { permanentIsCreature } from "./layers.js";
import { advanceUntilDecision, applySacrificeChoice } from "./learnSession.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const EDICT = {"name":"Blasphemous Edict","type":"Sorcery","mana":"{3}{B}{B}","cmc":5,"keywords":[],"colors":["B"],"oracle":"You may pay {B} rather than pay this spell's mana cost if there are thirteen or more creatures on the battlefield.\nEach player sacrifices thirteen creatures of their choice."}; // native-spell
const BARTER = {"name":"Barter in Blood","type":"Sorcery","mana":"{2}{B}{B}","cmc":4,"keywords":[],"colors":["B"],"oracle":"Each player sacrifices two creatures of their choice."}; // native-spell
const TASTE = {"name":"Taste of Death","type":"Sorcery","mana":"{4}{B}{B}","cmc":6,"keywords":["Food"],"colors":["B"],"oracle":"Each player sacrifices three creatures of their choice. You create three Food tokens. (They're artifacts with \"{2}, {T}, Sacrifice this token: You gain 3 life.\")"}; // native-spell
const TERGRID = {"name":"Tergrid's Shadow","type":"Instant","mana":"{3}{B}{B}","cmc":5,"keywords":["Foretell"],"colors":["B"],"oracle":"Each player sacrifices two creatures.\nForetell {2}{B}{B} (During your turn, you may pay {2} and exile this card from your hand face down. Cast it on a later turn for its foretell cost.)"}; // native-spell
const GORESTALKER = {"name":"Abyssal Gorestalker","type":"Creature — Horror","mana":"{4}{B}{B}","cmc":6,"power":"6","toughness":"6","keywords":[],"colors":["B"],"oracle":"When this creature enters, each player sacrifices two creatures of their choice."}; // native-trigger
const PLANAR = {"name":"Planar Collapse","type":"Enchantment","mana":"{1}{W}","cmc":2,"keywords":[],"colors":["W"],"oracle":"At the beginning of your upkeep, if there are four or more creatures on the battlefield, sacrifice this enchantment and destroy all creatures. They can't be regenerated."}; // native-trigger
const RANKLE = {"name":"Rankle's Prank","type":"Sorcery","mana":"{2}{B}{B}","cmc":4,"keywords":[],"colors":["B"],"oracle":"Choose one or more —\n• Each player discards two cards.\n• Each player loses 4 life.\n• Each player sacrifices two creatures of their choice."}; // native-spell
const NECROTIC = {"name":"Necrotic Hex","type":"Sorcery","mana":"{6}{B}","cmc":7,"keywords":[],"colors":["B"],"oracle":"Each player sacrifices six creatures of their choice. You create six tapped 2/2 black Zombie creature tokens."}; // arbiter-spell
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const BLOOD_ARTIST = {"name":"Blood Artist","type":"Creature — Vampire","mana":"{1}{B}","cmc":2,"power":"0","toughness":"1","keywords":[],"colors":["B"],"oracle":"Whenever this creature or another creature dies, target player loses 1 life and you gain 1 life."}; // native-trigger
const MUTAVAULT = {"name":"Mutavault","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{1}: This land becomes a 2/2 creature with all creature types until end of turn. It's still a land."}; // land
const SWAMP = {"name":"Swamp","type":"Basic Land — Swamp","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {B}.)"}; // land
const PLAINS = {"name":"Plains","type":"Basic Land — Plains","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {W}.)"}; // land
const THALIA = {"name":"Thalia, Guardian of Thraben","type":"Legendary Creature — Human Soldier","mana":"{1}{W}","cmc":2,"power":"2","toughness":"1","keywords":["First strike"],"colors":["W"],"oracle":"First strike\nNoncreature spells cost {1} more to cast."}; // native-static
const DRUDGE = {"name":"Drudge Skeletons","type":"Creature — Skeleton","mana":"{1}{B}","cmc":2,"power":"1","toughness":"1","keywords":["Heal","Regenerate"],"colors":["B"],"oracle":"{B}: Regenerate this creature. (The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)"}; // native-activated
const MYR = {"name":"Darksteel Myr","type":"Artifact Creature — Myr","mana":"{3}","cmc":3,"power":"0","toughness":"1","keywords":["Indestructible"],"colors":[],"oracle":"Indestructible (Damage and effects that say \"destroy\" don't destroy this creature. If its toughness is 0 or less, it still dies.)"}; // native-body
const ELVES = {"name":"Llanowar Elves","type":"Creature — Elf Druid","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G}."}; // native-mana
const GIANT = {"name":"Hill Giant","type":"Creature — Giant","mana":"{3}{R}","cmc":4,"power":"3","toughness":"3","keywords":[],"colors":["R"],"oracle":""}; // native-body

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const many = (n, card, controller, prefix) => Array.from({ length: n }, (_, i) => P(`${prefix}${i + 1}`, card, controller));
const H = (id, card) => ({ ...card, id });
function board({ user = [], ai = [], hand = [], aiHand = [], pool = {}, active = "user", life = {} } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  const lib = (who) => [1, 2, 3].map((i) => ({ ...BEARS, id: `${who}-lib${i}` }));
  return { ...g, turn: 5, activePlayer: active, priorityHolder: active, phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: { ...g.players,
      user: { ...g.players.user, battlefield: user, hand, manaPool: { ...g.players.user.manaPool, ...pool }, library: lib("user"), ...(life.user != null ? { life: life.user } : {}) },
      ai: { ...g.players.ai, battlefield: ai, hand: aiHand, library: lib("ai"), ...(life.ai != null ? { life: life.ai } : {}) } } };
}
const castsOf = (s, who, cardId) => legalActionsForPlayer({ ...s, priorityHolder: who }, who).filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
const castAlt = (s, cardId = "edict") => castsOf(s, "user", cardId).find((a) => a.altManaCost === "own");
const activations = (s, permId) => legalActionsForPlayer(s, "user").filter((a) => a.kind === "activate-ability" && a.permanentId === permId);
// The learnSession settle, verbatim: settle the pick, then finalize (flush what it woke) once nothing is pending any more.
const settle = (s, pick) => { const n = resolveSacrificeChoice(s, pick); return n.pendingChoice ? n : finalizeStackResolution(n); };
const autoSettle = (s) => { let n = s; for (let i = 0; i < 60 && n.pendingChoice?.kind === "sacrifice-choice"; i++) n = settle(n, autoPickSacrificeCandidate(n, n.pendingChoice)); return n; };
const ids = (zone) => zone.map((x) => x.id).sort();
const names = (zone) => zone.map((x) => x.card?.name ?? x.name).sort();
const creaturesOf = (s, who) => s.players[who].battlefield.filter((p) => permanentIsCreature(s, p.id)).map((p) => p.id).sort();
const errors = (s) => (s.log || []).filter((e) => e.kind === "stack-resolve-error");
const thirteenOrMore = "there are thirteen or more creatures on the battlefield";

describe("the cards and their parse", () => {
  it("classify: Blasphemous Edict native-spell — and the six cards the same two readers complete; Necrotic Hex stays parked", () => {
    const row = { edict: classifyCard(EDICT), barter: classifyCard(BARTER), taste: classifyCard(TASTE), tergrid: classifyCard(TERGRID), rankle: classifyCard(RANKLE),
      gorestalker: classifyCard(GORESTALKER), planar: classifyCard(PLANAR), necrotic: classifyCard(NECROTIC) };
    console.log("  WITNESS classify", JSON.stringify(row)); // vitest 4 needs --disable-console-intercept
    expect(row).toEqual({ edict: "native-spell", barter: "native-spell", taste: "native-spell", tergrid: "native-spell", rankle: "native-spell",
      gorestalker: "native-trigger", planar: "native-trigger", necrotic: "arbiter-spell" });
  });

  it("line 1 — a CONDITIONAL fixed-mana alternative cost, never the unconditional one", () => {
    expect(extractAltCost(EDICT.oracle)).toEqual({ altCost: { kind: "fixedMana", pips: "{B}", condition: `if:${thirteenOrMore}` }, rest: "Each player sacrifices thirteen creatures of their choice." });
    expect(conditionalFixedManaAltCostOf(EDICT)).toEqual({ pips: "{B}", condition: thirteenOrMore });
    expect(fixedManaAltCostOf(EDICT)).toBeNull(); // read as unconditional, {B} would be offered on an empty board
  });

  it("line 2 — one sacrifice atom: each player, creatures, thirteen", () => {
    const p = parseEffectProgram(EDICT);
    expect({ confidence: programConfidence(p), atoms: p.atoms }).toEqual({ confidence: "high", atoms: [{ op: "sacrifice", who: "eachPlayer", what: "creature", count: 13 }] });
  });

  it("near misses stay unparsed: another subject, another pool, an X count", () => {
    const atoms = (clause) => parseEffectClause(clause, "Sorcery")?.atoms ?? [];
    expect({
      eachOpponent: atoms("Each opponent sacrifices two creatures of their choice."),
      target: atoms("Target player sacrifices two creatures of their choice."),
      lands: atoms("Each player sacrifices two lands of their choice."),
      x: atoms("Each player sacrifices X creatures of their choice."),
    }).toEqual({ eachOpponent: [], target: [], lands: [], x: [] });
  });

  it("the condition is readable by the spell gate (and the trigger gate), and only for creatures", () => {
    expect({ spell: spellConditionParseable(thirteenOrMore), trigger: interveningIfParseable("there are four or more creatures on the battlefield"),
      lands: spellConditionParseable("there are thirteen or more lands on the battlefield") }).toEqual({ spell: true, trigger: true, lands: false });
  });

  it("SYNTHETIC SHAPE (the strip gate): a trailing condition the reader cannot parse keeps the sentence — the card stays parked", () => {
    const unread = { name: "Unread Edict", type: "Sorcery", mana: "{3}{B}{B}", cmc: 5, keywords: [], oracle: "You may pay {B} rather than pay this spell's mana cost if you have the high ground.\nEach player sacrifices thirteen creatures of their choice." };
    expect({ alt: extractAltCost(unread.oracle).altCost, tier: classifyCard(unread) }).toEqual({ alt: null, tier: "arbiter-spell" });
  });
});

describe("⭐ the {B} cost — offered only while thirteen or more creatures are on the battlefield", () => {
  const edictIn = (user, ai, extra = {}) => board({ user, ai, hand: [H("edict", EDICT)], ...extra });

  it("⭐ twelve creatures: no {B} cast; thirteen across both battlefields: {B}, and casting it taps the Swamp", () => {
    const twelve = edictIn([P("sw", SWAMP), ...many(6, BEARS, "user", "ub")], many(6, BEARS, "ai", "ab"));
    const thirteen = edictIn([P("sw", SWAMP), ...many(6, BEARS, "user", "ub")], many(7, BEARS, "ai", "ab"));
    const offer = castsOf(thirteen, "user", "edict");
    const cast = dispatchAction(thirteen, offer[0]);
    const row = { twelve: castsOf(twelve, "user", "edict").length, offered: offer.length, cost: { B: offer[0].cost.B, generic: offer[0].cost.generic }, kind: offer[0].altManaCost,
      onStack: cast.stack.map((o) => o.source?.name), swampTapped: cast.players.user.battlefield.find((p) => p.id === "sw").tapped,
      reads: [evaluateInterveningIf(twelve, thirteenOrMore, "user"), evaluateInterveningIf(thirteen, thirteenOrMore, "user")] };
    console.log("  WITNESS edictCost", JSON.stringify(row));
    expect(row).toEqual({ twelve: 0, offered: 1, cost: { B: 1, generic: 0 }, kind: "own", onStack: ["Blasphemous Edict"], swampTapped: true, reads: [false, true] });
  });

  it("⭐ layer-aware: Mutavault is no creature until it animates — then it is the thirteenth", () => {
    const s0 = edictIn([P("sw", SWAMP), P("mv", MUTAVAULT), ...many(6, BEARS, "user", "ub")], many(6, BEARS, "ai", "ab"), { pool: { C: 1 } });
    const animate = activations(s0, "mv").find((a) => !a.isManaAbility && a.cost?.generic === 1);
    const s1 = resolveTopOfStack(dispatchAction(s0, animate));
    const row = { before: castsOf(s0, "user", "edict").length, mutavaultIsCreature: permanentIsCreature(s1, "mv"), after: castsOf(s1, "user", "edict").length };
    console.log("  WITNESS edictLayerAware", JSON.stringify(row));
    expect(row).toEqual({ before: 0, mutavaultIsCreature: true, after: 1 });
  });

  it("CR 118.9d — an opponent's Thalia taxes the alternative cost too: {1}{B}, so one Swamp no longer pays for it", () => {
    const ai = [P("thalia", THALIA, "ai"), ...many(6, BEARS, "ai", "ab")];
    const swampOnly = edictIn([P("sw", SWAMP), ...many(6, BEARS, "user", "ub")], ai);
    const withPlains = edictIn([P("sw", SWAMP), P("pl", PLAINS), ...many(6, BEARS, "user", "ub")], ai);
    const taxed = castAlt(withPlains);
    const row = { swampOnly: castsOf(swampOnly, "user", "edict").length, cost: taxed ? { B: taxed.cost.B, generic: taxed.cost.generic } : null,
      tappedBoth: taxed ? dispatchAction(withPlains, taxed).players.user.battlefield.filter((p) => p.tapped).map((p) => p.id).sort() : null };
    console.log("  WITNESS edictThaliaTax", JSON.stringify(row));
    expect(row).toEqual({ swampOnly: 0, cost: { B: 1, generic: 1 }, tappedBoth: ["pl", "sw"] });
  });

  it("the printed cost is still offered beside it, when it is payable itself", () => {
    const lands = many(5, SWAMP, "user", "sw");
    const at13 = castsOf(edictIn([...lands, ...many(6, BEARS, "user", "ub")], many(7, BEARS, "ai", "ab")), "user", "edict");
    const at12 = castsOf(edictIn([...lands, ...many(6, BEARS, "user", "ub")], many(6, BEARS, "ai", "ab")), "user", "edict");
    expect({ at13: at13.map((a) => a.altManaCost ?? "printed").sort(), at12: at12.map((a) => a.altManaCost ?? "printed") }).toEqual({ at13: ["own", "printed"], at12: ["printed"] });
  });
});

describe("⭐ the edict — each player chooses thirteen of their own creatures, and they all go together", () => {
  it("⭐ the active player chooses first, only among their own; every choice is logged as it is made; nothing leaves until the last", () => {
    // user (active, the caster): 13 Bears + a Hill Giant — a real choice of 13 of 14. AI: 12 Bears + Llanowar Elves + 2 Hill Giants — 13 of 15.
    const user = [P("sw", SWAMP), ...many(13, BEARS, "user", "ub"), P("ug", GIANT)];
    const ai = [...many(12, BEARS, "ai", "ab"), P("ae", ELVES, "ai"), P("ag1", GIANT, "ai"), P("ag2", GIANT, "ai")];
    const s0 = board({ user, ai, hand: [H("edict", EDICT)] });
    let s = resolveTopOfStack(dispatchAction(s0, castAlt(s0)));
    const first = { controller: s.pendingChoice?.controller, candidates: s.pendingChoice?.candidates.map((c) => c.id).sort() };
    // The human keeps ONE Bear and gives up the Giant — their choice, not the least-valuable policy.
    const userPicks = ["ug", ...Array.from({ length: 12 }, (_, i) => `ub${i + 1}`)];
    for (const id of userPicks) s = settle(s, id);
    const midway = { controller: s.pendingChoice?.controller, candidates: s.pendingChoice?.candidates.length, userCreaturesStillThere: creaturesOf(s, "user").length,
      logged: (s.log || []).filter((e) => e.kind === "sacrifice-chosen").map((e) => e.chosen).sort() };
    s = autoSettle(s);
    const row = { first: { controller: first.controller, count: first.candidates.length, onlyOwn: first.candidates.every((id) => id.startsWith("u")) }, midway,
      userLeft: creaturesOf(s, "user"), aiLeft: creaturesOf(s, "ai"), userGraveyard: s.players.user.graveyard.length, aiGraveyard: s.players.ai.graveyard.length,
      edictInGraveyard: s.players.user.graveyard.some((c) => c.name === "Blasphemous Edict"), stack: s.stack.length, errors: errors(s).length };
    console.log("  WITNESS edictChoices", JSON.stringify(row));
    expect(row).toEqual({ first: { controller: "user", count: 14, onlyOwn: true },
      midway: { controller: "ai", candidates: 15, userCreaturesStillThere: 14, logged: [...userPicks].sort() },
      userLeft: ["ub13"], aiLeft: ["ag1", "ag2"], userGraveyard: 14, aiGraveyard: 13, edictInGraveyard: true, stack: 0, errors: 0 });
  });

  it("thirteen exactly, or fewer: every creature goes and nobody is asked; a player with none loses nothing; lands stay", () => {
    const s0 = board({ user: [P("sw", SWAMP), ...many(13, BEARS, "user", "ub")], ai: [P("aland", SWAMP, "ai"), ...many(5, ELVES, "ai", "ae")], hand: [H("edict", EDICT)] });
    const s = resolveTopOfStack(dispatchAction(s0, castAlt(s0)));
    const row = { paused: !!s.pendingChoice, userCreatures: creaturesOf(s, "user"), aiCreatures: creaturesOf(s, "ai"), lands: [ids(s.players.user.battlefield), ids(s.players.ai.battlefield)],
      graveyards: [s.players.user.graveyard.length, s.players.ai.graveyard.length] };
    expect(row).toEqual({ paused: false, userCreatures: [], aiCreatures: [], lands: [["sw"], ["aland"]], graveyards: [14, 5] });
    const empty = board({ user: [P("sw", SWAMP), ...many(14, BEARS, "user", "ub")], ai: [], hand: [H("edict", EDICT)] });
    const done = autoSettle(resolveTopOfStack(dispatchAction(empty, castAlt(empty))));
    expect({ ai: done.players.ai.graveyard.length, userLeft: creaturesOf(done, "user").length }).toEqual({ ai: 0, userLeft: 1 });
  });

  it("⭐ one event (CR 603.10a): a Blood Artist sacrificed with the rest sees every creature that died — its own and the opponent's", () => {
    const s0 = board({ user: [P("sw", SWAMP), P("artist", BLOOD_ARTIST), ...many(12, BEARS, "user", "ub")], ai: many(4, BEARS, "ai", "ab"), hand: [H("edict", EDICT)] });
    const s = resolveTopOfStack(dispatchAction(s0, castAlt(s0)));
    const row = { died: s.players.user.graveyard.length - 1 + s.players.ai.graveyard.length, artistTriggers: s.stack.filter((o) => o.source?.name === "Blood Artist").length };
    console.log("  WITNESS edictOneEvent", JSON.stringify(row));
    expect(row).toEqual({ died: 17, artistTriggers: 17 });
  });

  it("⭐ an animated land is a creature the edict takes; the edict never touches a land that is only a land", () => {
    const s0 = board({ user: [P("sw", SWAMP), P("mv", MUTAVAULT), ...many(12, BEARS, "user", "ub")], ai: [P("ab1", BEARS, "ai")], hand: [H("edict", EDICT)], pool: { C: 1 } });
    const s1 = resolveTopOfStack(dispatchAction(s0, activations(s0, "mv").find((a) => !a.isManaAbility && a.cost?.generic === 1)));
    const s = resolveTopOfStack(dispatchAction(s1, castAlt(s1)));
    const row = { paused: !!s.pendingChoice, battlefield: ids(s.players.user.battlefield), mutavaultInGraveyard: s.players.user.graveyard.some((c) => c.name === "Mutavault") };
    console.log("  WITNESS edictAnimatedLand", JSON.stringify(row));
    expect(row).toEqual({ paused: false, battlefield: ["sw"], mutavaultInGraveyard: true });
  });

  it("SYNTHETIC PICK (the lock-in guard): a pick outside the offer — the opponent's creature, a land — is never taken; the same player is asked again", () => {
    const s0 = board({ user: [P("sw", SWAMP), ...many(14, BEARS, "user", "ub")], ai: many(2, BEARS, "ai", "ab"), hand: [H("edict", EDICT)] });
    const paused = resolveTopOfStack(dispatchAction(s0, castAlt(s0)));
    const wrong = settle(settle(paused, "ab1"), "sw");
    const row = { controller: wrong.pendingChoice?.controller, candidates: wrong.pendingChoice?.candidates.length, batch: wrong.pendingChoice?.batch.length,
      aiCreatures: creaturesOf(wrong, "ai"), chosenLogged: (wrong.log || []).filter((e) => e.kind === "sacrifice-chosen").length };
    expect(row).toEqual({ controller: "user", candidates: 14, batch: 0, aiCreatures: ["ab1", "ab2"], chosenLogged: 0 });
  });

  it("through the session driver: the human picks their thirteen; the AI's thirteen are chosen for it", () => {
    const s0 = board({ user: [P("sw", SWAMP), ...many(14, BEARS, "user", "ub")], ai: [...many(13, BEARS, "ai", "ab"), P("ag", GIANT, "ai")], hand: [H("edict", EDICT)] });
    const paused = resolveTopOfStack(dispatchAction(s0, castAlt(s0)));
    let r = { session: { id: "s", status: "active", difficulty: "beginner", state: paused, decisionLog: [] } };
    for (let i = 1; i <= 13; i++) r = applySacrificeChoice(r.session, { cardId: `ub${i}` });
    const s = r.session.state;
    expect({ decision: r.decision.kind, userLeft: creaturesOf(s, "user"), aiLeft: creaturesOf(s, "ai") }).toEqual({ decision: expect.not.stringMatching(/^sacrifice-choice$/), userLeft: ["ub14"], aiLeft: ["ag"] });
  });
});

describe("the cards the same arm completes", () => {
  it("⭐ Tergrid's Shadow, cast in the opponent's turn — the ACTIVE player chooses first (CR 101.4), then the caster", () => {
    const s0 = board({ active: "ai", user: [...many(5, SWAMP, "user", "sw"), ...many(3, BEARS, "user", "ub")], ai: [...many(2, BEARS, "ai", "ab"), P("ae", ELVES, "ai")], hand: [H("ts", TERGRID)] });
    const offer = castsOf(s0, "user", "ts");
    let s = resolveTopOfStack(dispatchAction({ ...s0, priorityHolder: "user" }, offer[0]));
    const order = [];
    for (let i = 0; i < 10 && s.pendingChoice?.kind === "sacrifice-choice"; i++) { order.push(s.pendingChoice.controller); s = settle(s, autoPickSacrificeCandidate(s, s.pendingChoice)); }
    const row = { offered: offer.length, order, userLeft: creaturesOf(s, "user").length, aiLeft: creaturesOf(s, "ai") };
    console.log("  WITNESS tergridApnap", JSON.stringify(row));
    expect(row).toEqual({ offered: 1, order: ["ai", "ai", "user", "user"], userLeft: 1, aiLeft: ["ab2"] });
  });

  it("Barter in Blood: two apiece — the player with one creature loses it", () => {
    const s0 = board({ user: [...many(4, SWAMP, "user", "sw"), ...many(3, BEARS, "user", "ub")], ai: [P("ab1", BEARS, "ai")], hand: [H("bb", BARTER)] });
    const s = autoSettle(resolveTopOfStack(dispatchAction(s0, castsOf(s0, "user", "bb")[0])));
    expect({ user: creaturesOf(s, "user").length, ai: creaturesOf(s, "ai"), barter: s.players.user.graveyard.some((c) => c.name === "Barter in Blood") }).toEqual({ user: 1, ai: [], barter: true });
  });

  it("⭐ Taste of Death: three apiece, THEN three Food tokens for the caster", () => {
    const s0 = board({ user: [...many(6, SWAMP, "user", "sw"), ...many(4, BEARS, "user", "ub")], ai: many(3, BEARS, "ai", "ab"), hand: [H("tod", TASTE)] });
    const paused = resolveTopOfStack(dispatchAction(s0, castsOf(s0, "user", "tod")[0]));
    const foodsWhilePaused = paused.players.user.battlefield.filter((p) => p.card?.name === "Food").length;
    const s = autoSettle(paused);
    const row = { foodsWhilePaused, user: creaturesOf(s, "user").length, ai: creaturesOf(s, "ai").length, foods: [s.players.user.battlefield.filter((p) => p.card?.name === "Food").length, s.players.ai.battlefield.filter((p) => p.card?.name === "Food").length] };
    console.log("  WITNESS tasteOfDeath", JSON.stringify(row));
    expect(row).toEqual({ foodsWhilePaused: 0, user: 1, ai: 0, foods: [3, 0] });
  });

  it("⭐ Abyssal Gorestalker: its enters trigger — two apiece, and the Gorestalker itself may be one of the caster's", () => {
    const s0 = board({ user: [P("ub1", BEARS)], ai: many(3, BEARS, "ai", "ab"), hand: [H("gs", GORESTALKER)], pool: { B: 2, C: 4 } });
    let s = resolveTopOfStack(dispatchAction(s0, castsOf(s0, "user", "gs")[0])); // the creature spell resolves; its trigger goes on the stack
    const triggered = s.stack.map((o) => o.source?.name);
    s = autoSettle(resolveTopOfStack(s));
    const row = { triggered, user: ids(s.players.user.battlefield), userGraveyard: names(s.players.user.graveyard), ai: creaturesOf(s, "ai").length };
    console.log("  WITNESS gorestalker", JSON.stringify(row));
    expect(row).toEqual({ triggered: ["Abyssal Gorestalker"], user: [], userGraveyard: ["Abyssal Gorestalker", "Grizzly Bears"], ai: 1 });
  });

  it("⭐ Rankle's Prank: the sacrifice mode alone — and all three modes, in printed order", () => {
    const deal = () => board({ user: [...many(4, SWAMP, "user", "sw"), ...many(3, BEARS, "user", "ub")], ai: many(3, BEARS, "ai", "ab"),
      hand: [H("rp", RANKLE), H("h1", BEARS), H("h2", GIANT)], aiHand: [H("a1", BEARS), H("a2", GIANT), H("a3", ELVES)], life: { user: 20, ai: 20 } });
    const s0 = deal();
    const mode = (want) => castsOf(s0, "user", "rp").find((a) => JSON.stringify(a.chosenMode) === JSON.stringify(want));
    const sacOnly = autoSettle(resolveTopOfStack(dispatchAction(s0, mode([2]))));
    let all = resolveTopOfStack(dispatchAction(s0, mode([0, 1, 2])));
    const kinds = [];
    for (let i = 0; i < 20 && all.pendingChoice; i++) {
      const pc = all.pendingChoice;
      kinds.push(pc.kind);
      const n = pc.kind === "sacrifice-choice" ? resolveSacrificeChoice(all, autoPickSacrificeCandidate(all, pc)) : resolveDiscardChoice(all, autoPickDiscardCandidate(all, pc));
      all = n.pendingChoice ? n : finalizeStackResolution(n);
    }
    const row = { sacOnly: { user: creaturesOf(sacOnly, "user").length, ai: creaturesOf(sacOnly, "ai").length, life: [sacOnly.players.user.life, sacOnly.players.ai.life], hands: [sacOnly.players.user.hand.length, sacOnly.players.ai.hand.length] },
      all: { kinds, user: creaturesOf(all, "user").length, ai: creaturesOf(all, "ai").length, life: [all.players.user.life, all.players.ai.life], hands: [all.players.user.hand.length, all.players.ai.hand.length],
        prank: all.players.user.graveyard.some((c) => c.name === "Rankle's Prank"), errors: errors(all).length } };
    console.log("  WITNESS ranklesPrank", JSON.stringify(row));
    expect(row).toEqual({ sacOnly: { user: 1, ai: 1, life: [20, 20], hands: [2, 3] },
      all: { kinds: ["discard", "discard", "sacrifice-choice", "sacrifice-choice", "sacrifice-choice", "sacrifice-choice"], user: 1, ai: 1, life: [16, 16], hands: [0, 1], prank: true, errors: 0 } });
  });

  it("⭐ CR 800.4a in a pod — Rankle's Prank: a player its life-loss mode eliminates while a choice is open is passed over; the rest still sacrifice", () => {
    const g = createGameState({ mode: "commander", userDeck: [], opponentDecks: [[], [], []] });
    const seat = (pid, bf, extra = {}) => ({ ...g.players[pid], battlefield: bf, hand: [], library: [1, 2, 3].map((i) => ({ ...BEARS, id: `${pid}-lib${i}` })), ...extra });
    const s0 = { ...g, turn: 5, activePlayer: "user", priorityHolder: "user", phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
      players: { user: seat("user", [...many(4, SWAMP, "user", "sw"), ...many(3, BEARS, "user", "ub")], { hand: [H("rp", RANKLE)], life: 20 }),
        ai1: seat("ai1", many(3, BEARS, "ai1", "xb"), { life: 3 }), ai2: seat("ai2", many(3, BEARS, "ai2", "yb"), { life: 20 }), ai3: seat("ai3", many(2, BEARS, "ai3", "zb"), { life: 20 }) } };
    const cast = castsOf(s0, "user", "rp").find((a) => JSON.stringify(a.chosenMode) === "[1,2]");
    const paused = resolveTopOfStack(dispatchAction(s0, cast)); // every player lost 4; the user's choice (the active player's) is open
    let r = advanceUntilDecision({ id: "s", status: "active", difficulty: "beginner", state: paused, decisionLog: [] });
    const atChoice = { decision: r.decision.kind, ai1InGame: !!r.session.state.players.ai1 };
    r = applySacrificeChoice(r.session, { cardId: "ub1" });
    r = applySacrificeChoice(r.session, { cardId: "ub2" });
    const s = r.session.state;
    const row = { atChoice, decision: r.decision.kind, user: creaturesOf(s, "user"), ai2: creaturesOf(s, "ai2").length, ai3: creaturesOf(s, "ai3").length,
      life: [s.players.user.life, s.players.ai2.life, s.players.ai3.life], prank: s.players.user.graveyard.some((c) => c.name === "Rankle's Prank") };
    console.log("  WITNESS ranklesPrankPod", JSON.stringify(row));
    expect(row).toEqual({ atChoice: { decision: "sacrifice-choice", ai1InGame: false }, decision: expect.not.stringMatching(/^(sacrifice-choice|dispatch-error)$/),
      user: ["ub3"], ai2: 1, ai3: 0, life: [16, 16, 16], prank: true });
  });

  it("⭐ Planar Collapse at your upkeep: four creatures — it goes, every creature is destroyed (a regeneration shield or not), indestructible stays; three — nothing", () => {
    const upkeep = (user, ai) => {
      const g = createGameState({ userDeck: [], aiDeck: [] });
      let s = runStepActions(advanceStep({ ...g, turn: 5, phase: "beginning", step: "untap", activePlayer: "user", priorityHolder: "user", stack: [], pendingTriggers: [],
        players: { ...g.players, user: { ...g.players.user, battlefield: user }, ai: { ...g.players.ai, battlefield: ai } } }));
      s = flushTriggers(s, { chooseTargets: chooseTriggerTargets });
      for (let i = 0; i < 8 && (s.stack || []).length; i++) s = flushTriggers(resolveTopOfStack(s), { chooseTargets: chooseTriggerTargets });
      return s;
    };
    // A regeneration shield from an earlier {B} activation (gameState.addRegenShield's own field) — it survives into the upkeep.
    const four = upkeep([P("pc", PLANAR), P("ub", BEARS), P("dr", DRUDGE, "user", { regenShields: 1 })], [P("ab", BEARS, "ai"), P("myr", MYR, "ai")]);
    const three = upkeep([P("pc", PLANAR), P("ub", BEARS), P("dr", DRUDGE, "user", { regenShields: 1 })], [P("ab", BEARS, "ai")]);
    const row = { four: { step: four.step, user: ids(four.players.user.battlefield), ai: ids(four.players.ai.battlefield), graveyard: names(four.players.user.graveyard) },
      three: { user: ids(three.players.user.battlefield), ai: ids(three.players.ai.battlefield), shieldStillUp: three.players.user.battlefield.find((p) => p.id === "dr").regenShields } };
    console.log("  WITNESS planarCollapse", JSON.stringify(row));
    expect(row).toEqual({ four: { step: "upkeep", user: [], ai: ["myr"], graveyard: ["Drudge Skeletons", "Grizzly Bears", "Planar Collapse"] },
      three: { user: ["dr", "pc", "ub"], ai: ["ab"], shieldStillUp: 1 } });
  });
});
