/**
 * CLOUD KEY — the play-weighted program, #608 (EDHREC #608).
 *   "As this artifact enters, choose artifact, creature, enchantment, instant, or sorcery.
 *    Spells you cast of the chosen type cost {1} less to cast."
 *
 * Two lines, one leaf (chosenCardType.js):
 *  - THE CHOICE (CR 614.1c — an "As [this permanent] enters" ability is a replacement effect; CR 614.12a — its choice is made
 *    before the permanent enters). A CARD type, stored in its own field `chosenCardType` — never in `chosenType`, whose readers
 *    take it for a creature type — and always one of the five printed words. Made on EVERY entry: the resolving spell
 *    (resolvers.enterPermanent, which a clone entering as a copy also takes — CR 707.5), the put-onto-the-battlefield entry
 *    (zones.enterCardFromZone: a search, a reanimation, a blink's return — a new object, a new choice, CR 400.7), The Ur-Dragon's
 *    put-from-hand, and a token created as a copy (CR 707.5). The AI's pick is the documented policy
 *    choicePolicy.autoPickCardType: the option naming the most cards still to cast in the hand and library (the entering card
 *    itself left out), ties in printed order.
 *  - THE DISCOUNT (CR 601.2f, 118.7a — generic mana only, never below {0}): a spell its controller casts that has the chosen
 *    card type, judged on the face being cast (CR 709.3b split, 715.3a adventure, 712.11b modal DFC, 712.8c a transforming
 *    card's front face); a spell with several card types has each (CR 205.2b); a spell cast bestowed is an Aura enchantment
 *    spell and no creature spell (CR 702.103b, 205.1a). Opponents' spells are untouched; two Keys stack.
 *
 * Real oracle fixtures (bundled Scryfall, the 2026-10-01 data, generated by cardIndex.publicCard — never typed by hand).
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, createGameState, createPermanent } from "./gameState.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { finalizeStackResolution, resolveTopOfStack, runStepActions } from "./gameEngine.js";
import { resolveCloneChoice } from "./resolvers.js";
import { resolveTutorChoice } from "./effects/runProgram.js";
import { classifyCard, isKeywordOnly } from "./coverage.js";
import { clauseProducesStatic, collectCostReducers, costReductionForSpell, parseStaticAbilities, staticAbilitiesCoverCard } from "./staticAbilityParser.js";
import { CARD_TYPE_CHOOSER_LINE_RE, CHOSEN_CARD_TYPE_OPTIONS, CHOSEN_CARD_TYPE_REDUCER_LINE_RE, chosenCardTypeOnEnter, chosenCardTypeReducer, chosenCardTypeResidue, spellHasChosenCardType } from "./chosenCardType.js";
import { autoPickCardType } from "./choicePolicy.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const CLOUD_KEY = {"name":"Cloud Key","type":"Artifact","mana":"{3}","cmc":3,"keywords":[],"colors":[],"oracle":"As this artifact enters, choose artifact, creature, enchantment, instant, or sorcery.\nSpells you cast of the chosen type cost {1} less to cast."}; // native-static
const URZAS_INCUBATOR = {"name":"Urza's Incubator","type":"Artifact","mana":"{3}","cmc":3,"keywords":[],"colors":[],"oracle":"As this artifact enters, choose a creature type.\nCreature spells of the chosen type cost {2} less to cast."}; // native-static
const GATHERING_STONE = {"name":"Gathering Stone","type":"Artifact","mana":"{4}","cmc":4,"keywords":[],"colors":[],"oracle":"As this artifact enters, choose a creature type.\nSpells you cast of the chosen type cost {1} less to cast.\nWhen this artifact enters and at the beginning of your upkeep, look at the top card of your library. If it's a card of the chosen type, you may reveal it and put it into your hand. If you don't put the card into your hand, you may put it into your graveyard."}; // body-only
const STENN = {"name":"Stenn, Paranoid Partisan","type":"Legendary Creature — Human Wizard","mana":"{W}{U}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["U","W"],"oracle":"As Stenn enters, choose a card type other than creature or land.\nSpells you cast of the chosen type cost {1} less to cast.\n{1}{W}{U}: Exile Stenn. Return it to the battlefield under its owner's control at the beginning of the next end step."}; // body-only
const UMORI = {"name":"Umori, the Collector","type":"Legendary Creature — Ooze","mana":"{2}{B/G}{B/G}","cmc":4,"power":"4","toughness":"5","keywords":["Companion"],"colors":["B","G"],"oracle":"Companion — Each nonland card in your starting deck shares a card type. (If this card is your chosen companion, you may put it into your hand from outside the game for {3} as a sorcery.)\nAs Umori enters, choose a card type.\nSpells you cast of the chosen type cost {1} less to cast."}; // body-only
const LIGHTNING_BOLT = {"name":"Lightning Bolt","type":"Instant","mana":"{R}","cmc":1,"keywords":[],"colors":["R"],"oracle":"Lightning Bolt deals 3 damage to any target."}; // native-spell
const DIVINATION = {"name":"Divination","type":"Sorcery","mana":"{2}{U}","cmc":3,"keywords":[],"colors":["U"],"oracle":"Draw two cards."}; // native-spell
const MIND_STONE = {"name":"Mind Stone","type":"Artifact","mana":"{2}","cmc":2,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{1}, {T}, Sacrifice this artifact: Draw a card."}; // native-mana
const DARKSTEEL_MYR = {"name":"Darksteel Myr","type":"Artifact Creature — Myr","mana":"{3}","cmc":3,"power":"0","toughness":"1","keywords":["Indestructible"],"colors":[],"oracle":"Indestructible (Damage and effects that say \"destroy\" don't destroy this creature. If its toughness is 0 or less, it still dies.)"}; // native-body
const HILL_GIANT = {"name":"Hill Giant","type":"Creature — Giant","mana":"{3}{R}","cmc":4,"power":"3","toughness":"3","keywords":[],"colors":["R"],"oracle":""}; // native-body
const GRIZZLY_BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const GLORIOUS_ANTHEM = {"name":"Glorious Anthem","type":"Enchantment","mana":"{1}{W}{W}","cmc":3,"keywords":[],"colors":["W"],"oracle":"Creatures you control get +1/+1."}; // native-static
const BOON_SATYR = {"name":"Boon Satyr","type":"Enchantment Creature — Satyr","mana":"{1}{G}{G}","cmc":3,"power":"4","toughness":"2","keywords":["Bestow","Flash"],"colors":["G"],"oracle":"Flash\nBestow {3}{G}{G} (If you cast this card for its bestow cost, it's an Aura spell with enchant creature. It becomes a creature again if it's not attached.)\nEnchanted creature gets +4/+2."}; // native-aura
const MURDEROUS_RIDER = {"name":"Murderous Rider // Swift End","type":"Creature — Zombie Knight // Instant — Adventure","mana":"{1}{B}{B} // {1}{B}{B}","cmc":3,"power":"2","toughness":"3","keywords":["Lifelink"],"layout":"adventure","colors":["B"],"oracle":"Murderous Rider - Creature — Zombie Knight {1}{B}{B}\nLifelink\nWhen this creature dies, put it on the bottom of its owner's library.\n//\nSwift End - Instant — Adventure {1}{B}{B}\nDestroy target creature or planeswalker. You lose 2 life. (Then exile this card. You may cast the creature later from exile.)"}; // native-mixed
const FIRE_ICE = {"name":"Fire // Ice","type":"Instant // Instant","mana":"{1}{R} // {1}{U}","cmc":4,"keywords":[],"layout":"split","colors":["R","U"],"oracle":"Fire - Instant {1}{R}\nFire deals 2 damage divided as you choose among one or two targets.\n//\nIce - Instant {1}{U}\nTap target permanent.\nDraw a card."}; // native-spell
const BIRGI = {"name":"Birgi, God of Storytelling // Harnfel, Horn of Bounty","type":"Legendary Creature — God // Legendary Artifact","mana":"{2}{R}","cmc":3,"power":"3","toughness":"3","keywords":[],"layout":"modal_dfc","colors":[],"oracle":"Birgi, God of Storytelling - Legendary Creature — God {2}{R}\nWhenever you cast a spell, add {R}. Until end of turn, you don't lose this mana as steps and phases end.\nCreatures you control can boast twice during each of your turns rather than once.\n//\nHarnfel, Horn of Bounty - Legendary Artifact {4}{R}\nDiscard a card: Exile the top two cards of your library. You may play those cards this turn."}; // native-mixed
const ELBRUS = {"name":"Elbrus, the Binding Blade // Withengar Unbound","type":"Legendary Artifact — Equipment // Legendary Creature — Demon","mana":"{7}","cmc":7,"keywords":["Flying","Transform","Trample","Equip","Intimidate"],"layout":"transform","colors":[],"oracle":"Elbrus, the Binding Blade - Legendary Artifact — Equipment {7}\nEquipped creature gets +1/+0.\nWhen equipped creature deals combat damage to a player, unattach Elbrus, then transform it.\nEquip {1}\n//\nWithengar Unbound - Legendary Creature — Demon \nFlying, intimidate, trample (A creature with intimidate can't be blocked except by artifact creatures and/or creatures that share a color with it.)\nWhenever a player loses the game, put thirteen +1/+1 counters on Withengar Unbound."}; // body-only
const FOUNDRY_INSPECTOR = {"name":"Foundry Inspector","type":"Artifact Creature — Construct","mana":"{3}","cmc":3,"power":"3","toughness":"2","keywords":[],"colors":[],"oracle":"Artifact spells you cast cost {1} less to cast."}; // native-static
const WHIR = {"name":"Whir of Invention","type":"Instant","mana":"{X}{U}{U}{U}","cmc":3,"keywords":["Improvise"],"colors":["U"],"oracle":"Improvise (Your artifacts can help cast this spell. Each artifact you tap after you're done activating mana abilities pays for {1}.)\nSearch your library for an artifact card with mana value X or less, put it onto the battlefield, then shuffle."}; // native-spell
const ARGIVIAN_RESTORATION = {"name":"Argivian Restoration","type":"Sorcery","mana":"{2}{U}{U}","cmc":4,"keywords":[],"colors":["U"],"oracle":"Return target artifact card from your graveyard to the battlefield."}; // native-spell
const GHOSTLY_FLICKER = {"name":"Ghostly Flicker","type":"Instant","mana":"{2}{U}","cmc":3,"keywords":[],"colors":["U"],"oracle":"Exile two target artifacts, creatures, and/or lands you control, then return those cards to the battlefield under your control."}; // native-spell
const SCULPTING_STEEL = {"name":"Sculpting Steel","type":"Artifact","mana":"{3}","cmc":3,"keywords":[],"colors":[],"oracle":"You may have this artifact enter as a copy of any artifact on the battlefield."}; // native-clone
const FLASH_PHOTOGRAPHY = {"name":"Flash Photography","type":"Sorcery","mana":"{2}{U}{U}","cmc":4,"keywords":["Flashback"],"colors":["U"],"oracle":"You may cast this spell as though it had flash if it targets a permanent you control.\nCreate a token that's a copy of target permanent.\nFlashback {4}{U}{U}"}; // native-spell
const UR_DRAGON = {"name":"The Ur-Dragon","type":"Legendary Creature — Dragon Avatar","mana":"{4}{W}{U}{B}{R}{G}","cmc":9,"power":"10","toughness":"10","keywords":["Flying","Eminence"],"colors":["B","G","R","U","W"],"oracle":"Eminence — As long as The Ur-Dragon is in the command zone or on the battlefield, other Dragon spells you cast cost {1} less to cast.\nFlying\nWhenever one or more Dragons you control attack, draw that many cards, then you may put a permanent card from your hand onto the battlefield."}; // native-mixed
const SHIVAN_DRAGON = {"name":"Shivan Dragon","type":"Creature — Dragon","mana":"{4}{R}{R}","cmc":6,"power":"5","toughness":"5","keywords":["Flying"],"colors":["R"],"oracle":"Flying\n{R}: This creature gets +1/+0 until end of turn."}; // native-activated
const DELVER = {"name":"Delver of Secrets // Insectile Aberration","type":"Creature — Human Wizard // Creature — Human Insect","mana":"{U}","cmc":1,"power":"1","toughness":"1","keywords":["Flying","Transform"],"layout":"transform","colors":[],"oracle":"Delver of Secrets - Creature — Human Wizard {U}\nAt the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform this creature.\n//\nInsectile Aberration - Creature — Human Insect \nFlying"}; // body-only
const VALAKUT_AWAKENING = {"name":"Valakut Awakening // Valakut Stoneforge","type":"Instant // Land","mana":"{2}{R}","cmc":3,"keywords":[],"layout":"modal_dfc","colors":[],"oracle":"Valakut Awakening - Instant {2}{R}\nPut any number of cards from your hand on the bottom of your library, then draw that many cards plus one.\n//\nValakut Stoneforge - Land \nThis land enters tapped.\n{T}: Add {R}."}; // land-partial
const DRYAD_ARBOR = {"name":"Dryad Arbor","type":"Land Creature — Forest Dryad","mana":"","cmc":0,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"(This land isn't a spell, it's affected by summoning sickness, and it has \"{T}: Add {G}.\")"}; // land
const SEAT_OF_THE_SYNOD = {"name":"Seat of the Synod","type":"Artifact Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {U}."}; // land
const ISLAND = {"name":"Island","type":"Basic Land — Island","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {U}.)"}; // land
const MOUNTAIN = {"name":"Mountain","type":"Basic Land — Mountain","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {R}.)"}; // land
const FOREST = {"name":"Forest","type":"Basic Land — Forest","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {G}.)"}; // land
const PLAINS = {"name":"Plains","type":"Basic Land — Plains","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {W}.)"}; // land
const SWAMP = {"name":"Swamp","type":"Basic Land — Swamp","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {B}.)"}; // land

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const many = (n, card, controller, prefix) => Array.from({ length: n }, (_, i) => P(`${prefix}${i + 1}`, card, controller));
const H = (id, card) => ({ ...card, id });
// A Cloud Key already on the battlefield with its choice made (null: one that made none — a face-down Key turned face up).
const key = (id, chosenCardType, controller = "user") => P(id, CLOUD_KEY, controller, chosenCardType ? { chosenCardType } : {});
const bearsLibrary = (who) => [1, 2, 3].map((i) => H(`${who}-lib${i}`, GRIZZLY_BEARS));
function board({ user = [], ai = [], hand = [], aiHand = [], library, graveyard = [], active = "user" } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  return { ...g, turn: 5, activePlayer: active, priorityHolder: active, phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: { ...g.players,
      user: { ...g.players.user, battlefield: user, hand, graveyard, library: library ?? bearsLibrary("user") },
      ai: { ...g.players.ai, battlefield: ai, hand: aiHand, library: bearsLibrary("ai") } } };
}
// Two of each basic: every colour the price list needs, generic to spare.
const lands = () => [PLAINS, ISLAND, SWAMP, MOUNTAIN, FOREST].flatMap((land, i) => many(2, land, "user", `l${i}-`));
const castsOf = (s, who, cardId) => legalActionsForPlayer({ ...s, priorityHolder: who }, who).filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
// A cost as printed: the generic number, then each coloured pip ({0} when nothing is left to pay).
const printed = (cost) => `${cost.generic ? `{${cost.generic}}` : ""}${["W", "U", "B", "R", "G", "C"].map((c) => `{${c}}`.repeat(cost[c] || 0)).join("")}` || "{0}";
// Every cast the player is offered, by the face being cast (and bestow), at the cost it is offered for.
function priceList(s, who = "user") {
  const seen = {};
  for (const a of legalActionsForPlayer({ ...s, priorityHolder: who }, who)) {
    if (a.kind !== "cast-spell") continue;
    const k = `${a.faceCard?.name ?? a.name}${a.bestow ? " (bestow)" : ""}`;
    (seen[k] ??= new Set()).add(printed(a.cost));
  }
  return Object.fromEntries(Object.entries(seen).map(([k, v]) => [k, [...v].sort().join(" | ")]));
}
const keysOn = (s, who = "user") => s.players[who].battlefield.filter((p) => p.card?.name === "Cloud Key")
  .map((p) => ({ token: !!p.card.token, chosenCardType: p.chosenCardType, chosenType: p.chosenType }));
const errors = (s) => (s.log || []).filter((e) => /error/.test(String(e.kind)));

// The price-list hand: a spell of every kind the discount has to judge.
const PRICE_HAND = [H("bolt", LIGHTNING_BOLT), H("div", DIVINATION), H("ms", MIND_STONE), H("myr", DARKSTEEL_MYR), H("giant", HILL_GIANT),
  H("anthem", GLORIOUS_ANTHEM), H("satyr", BOON_SATYR), H("rider", MURDEROUS_RIDER), H("fi", FIRE_ICE), H("birgi", BIRGI), H("elbrus", ELBRUS)];
// Every cast at its printed cost.
const FULL_PRICE = {
  "Lightning Bolt": "{R}", "Divination": "{2}{U}", "Mind Stone": "{2}", "Darksteel Myr": "{3}", "Hill Giant": "{3}{R}",
  "Glorious Anthem": "{1}{W}{W}", "Boon Satyr": "{1}{G}{G}", "Boon Satyr (bestow)": "{3}{G}{G}",
  "Murderous Rider": "{1}{B}{B}", "Swift End": "{1}{B}{B}", "Fire": "{1}{R}", "Ice": "{1}{U}",
  "Birgi, God of Storytelling": "{2}{R}", "Harnfel, Horn of Bounty": "{4}{R}", "Elbrus, the Binding Blade // Withengar Unbound": "{7}",
};
const priceBoard = (battlefield) => board({ user: [...lands(), P("bear", GRIZZLY_BEARS), ...battlefield], hand: PRICE_HAND });
const [CHOOSER_LINE, REDUCER_LINE] = CLOUD_KEY.oracle.split("\n");

describe("the card and its parse", () => {
  it("classify: Cloud Key native-static — and the same reducer line beside any other chooser stays parked", () => {
    const row = { cloudKey: classifyCard(CLOUD_KEY), gatheringStone: classifyCard(GATHERING_STONE), stenn: classifyCard(STENN), umori: classifyCard(UMORI),
      urzasIncubator: classifyCard(URZAS_INCUBATOR) };
    console.log("  WITNESS classify", JSON.stringify(row)); // vitest 4 needs --disable-console-intercept
    expect(row).toEqual({ cloudKey: "native-static", gatheringStone: "body-only", stenn: "body-only", umori: "body-only", urzasIncubator: "native-static" });
  });

  it("line 1 is the chooser — exactly the printed list of five; line 2 is the reducer — {1}; nothing else is left", () => {
    const raw = { name: CLOUD_KEY.name, type_line: CLOUD_KEY.type, oracle_text: CLOUD_KEY.oracle }; // the bundled Scryfall field names
    expect({ chooser: CARD_TYPE_CHOOSER_LINE_RE.test(CHOOSER_LINE), reducer: REDUCER_LINE.match(CHOSEN_CARD_TYPE_REDUCER_LINE_RE)?.[1],
      options: CHOSEN_CARD_TYPE_OPTIONS, reducerOf: chosenCardTypeReducer(CLOUD_KEY), residue: chosenCardTypeResidue(CLOUD_KEY),
      raw: { reducerOf: chosenCardTypeReducer(raw), residue: chosenCardTypeResidue(raw) } })
      .toEqual({ chooser: true, reducer: "1", options: ["Artifact", "Creature", "Enchantment", "Instant", "Sorcery"], reducerOf: { amount: 1 }, residue: [],
        raw: { reducerOf: { amount: 1 }, residue: [] } });
    // Stenn's "a card type other than creature or land", Umori's "a card type", the creature-type choosers: other choices, never this one.
    expect([STENN, UMORI, GATHERING_STONE, URZAS_INCUBATOR].map((c) => c.oracle.split("\n").some((l) => CARD_TYPE_CHOOSER_LINE_RE.test(l)))).toEqual([false, false, false, false]);
  });

  it("⭐ the reducer is a CARD-type descriptor, never the creature-type one — and it exists only beside its own chooser", () => {
    const reducersOf = (card) => parseStaticAbilities(card).filter((d) => d.costReduction).map((d) => d.costReduction);
    expect({ cloudKey: reducersOf(CLOUD_KEY), gatheringStone: reducersOf(GATHERING_STONE), stenn: reducersOf(STENN), umori: reducersOf(UMORI), urzasIncubator: reducersOf(URZAS_INCUBATOR) })
      .toEqual({ cloudKey: [{ chosenCardType: true, amount: 1 }], gatheringStone: [], stenn: [], umori: [], urzasIncubator: [{ chosenType: true, amount: 2 }] });
  });

  it("both lines stay residue to every per-clause path — only the whole-card classifier credits them", () => {
    expect({ chooser: clauseProducesStatic(CHOOSER_LINE), reducer: clauseProducesStatic(REDUCER_LINE), staticLane: staticAbilitiesCoverCard(CLOUD_KEY, (c) => isKeywordOnly(c, CLOUD_KEY.name)) })
      .toEqual({ chooser: false, reducer: false, staticLane: false });
  });

  it("SYNTHETIC SHAPES (the whole-card gates): a reducer with no chooser, a chooser with no reducer, an extra line, a line carrying more — each parks", () => {
    const shape = (oracle) => ({ ...CLOUD_KEY, name: "Synthetic Key", oracle });
    const row = {
      reducerOnly: classifyCard(shape(REDUCER_LINE)),                                   // no choice for the reducer to read
      chooserOnly: classifyCard(shape(CHOOSER_LINE)),                                   // a choice nothing reads
      extraLine: classifyCard(shape(`${CHOOSER_LINE}\n${REDUCER_LINE}\nSpells your opponents cast of the chosen type cost {1} more to cast.`)),
      chooserThenMore: classifyCard(shape(`${CHOOSER_LINE} Draw a card.\n${REDUCER_LINE}`)),
      moreThenChooser: classifyCard(shape(`Draw a card. ${CHOOSER_LINE}\n${REDUCER_LINE}`)),
      reducerThenMore: classifyCard(shape(`${CHOOSER_LINE}\n${REDUCER_LINE} Draw a card.`)),
      moreThenReducer: classifyCard(shape(`${CHOOSER_LINE}\nDraw a card. ${REDUCER_LINE}`)),
    };
    expect(row).toEqual({ reducerOnly: "body-only", chooserOnly: "body-only", extraLine: "body-only",
      chooserThenMore: "body-only", moreThenChooser: "body-only", reducerThenMore: "body-only", moreThenReducer: "body-only" });
    expect(parseStaticAbilities(shape(REDUCER_LINE)).some((d) => d.costReduction)).toBe(false); // and the runtime builds no reducer either
  });
});

describe("the choice — always one of the five, by the documented policy", () => {
  const deal = ({ hand = [], library = [] } = {}) => board({ hand, library });
  const pick = (s, opts) => autoPickCardType(s, "user", CHOSEN_CARD_TYPE_OPTIONS, opts);

  it("the type with the most cards still to cast — hand and library together; an artifact creature counts for both (CR 205.2b)", () => {
    const row = {
      librarySorceries: pick(deal({ hand: [H("b", LIGHTNING_BOLT)], library: [H("d1", DIVINATION), H("d2", DIVINATION)] })),
      handInstants: pick(deal({ hand: [H("b1", LIGHTNING_BOLT), H("b2", LIGHTNING_BOLT)], library: [H("d1", DIVINATION)] })),
      myrAndGiant: pick(deal({ library: [H("m", DARKSTEEL_MYR), H("g", HILL_GIANT)] })),
      myrAndStone: pick(deal({ library: [H("m", DARKSTEEL_MYR), H("s", MIND_STONE)] })),
      rawTypeLine: pick(deal({ library: [{ id: "d1", name: DIVINATION.name, type_line: DIVINATION.type }] })), // the bundled Scryfall field name
    };
    expect(row).toEqual({ librarySorceries: "Sorcery", handInstants: "Instant", myrAndGiant: "Creature", myrAndStone: "Artifact", rawTypeLine: "Sorcery" });
  });

  it("a land is never cast (CR 305.9): Dryad Arbor and Seat of the Synod count for nothing; a modal DFC's spell face does", () => {
    const row = {
      lands: pick(deal({ library: [H("s1", SEAT_OF_THE_SYNOD), H("s2", SEAT_OF_THE_SYNOD), H("a1", DRYAD_ARBOR), H("a2", DRYAD_ARBOR), H("b", LIGHTNING_BOLT)] })),
      mdfc: pick(deal({ library: [H("v1", VALAKUT_AWAKENING), H("v2", VALAKUT_AWAKENING), H("g", HILL_GIANT)] })),
    };
    expect(row).toEqual({ lands: "Instant", mdfc: "Instant" });
  });

  it("a card counts once per type, however many faces show it — Delver's two creature faces are one creature", () => {
    expect(pick(deal({ library: [H("dv", DELVER), H("b1", LIGHTNING_BOLT), H("b2", LIGHTNING_BOLT)] }))).toBe("Instant");
  });

  it("ties break in printed order; nothing to count → the first option; never an option it was not handed", () => {
    const row = {
      tie: pick(deal({ library: [H("b", LIGHTNING_BOLT), H("d", DIVINATION)] })),
      nothing: pick(deal()),
      narrower: autoPickCardType(deal({ library: [H("g1", HILL_GIANT), H("g2", HILL_GIANT)] }), "user", ["Instant", "Sorcery"]),
    };
    expect(row).toEqual({ tie: "Instant", nothing: "Artifact", narrower: "Instant" });
  });

  it("the entering card itself is left out of the count", () => {
    const s = deal({ library: [H("ck", CLOUD_KEY), H("bear", GRIZZLY_BEARS)] });
    expect({ leftOut: pick(s, { excludeCardId: "ck" }), counted: pick(s) }).toEqual({ leftOut: "Creature", counted: "Artifact" });
  });

  it("chosenCardTypeOnEnter: Cloud Key's chooser makes the choice; a creature-type chooser, or none, makes no card-type choice", () => {
    const s = deal({ library: [H("d", DIVINATION)] });
    expect({ cloudKey: chosenCardTypeOnEnter(s, H("ck", CLOUD_KEY), "user"), incubator: chosenCardTypeOnEnter(s, H("ui", URZAS_INCUBATOR), "user"),
      gatheringStone: chosenCardTypeOnEnter(s, H("gs", GATHERING_STONE), "user"), bears: chosenCardTypeOnEnter(s, H("gb", GRIZZLY_BEARS), "user") })
      .toEqual({ cloudKey: { chosenCardType: "Sorcery" }, incubator: {}, gatheringStone: {}, bears: {} });
  });
});

describe("⭐ cast and resolved — the choice is stored, in its own field", () => {
  it("⭐ Cloud Key resolves: chosenCardType is one of the five (Instant — the most cards still to cast), chosenType stays empty, and it discounts at once", () => {
    const s0 = board({ user: many(5, ISLAND, "user", "is"), hand: [H("ck", CLOUD_KEY), H("b", LIGHTNING_BOLT), H("fi", FIRE_ICE)],
      library: [H("l1", DIVINATION), H("l2", HILL_GIANT), H("l3", LIGHTNING_BOLT)] });
    const offer = castsOf(s0, "user", "ck");
    const s1 = resolveTopOfStack(dispatchAction(s0, offer[0]));
    const row = { offered: offer.map((a) => printed(a.cost)), keys: keysOn(s1), oneOfFive: CHOSEN_CARD_TYPE_OPTIONS.includes(keysOn(s1)[0]?.chosenCardType),
      ice: priceList(s1).Ice, errors: errors(s1).length };
    console.log("  WITNESS castAndResolve", JSON.stringify(row));
    expect(row).toEqual({ offered: ["{3}"], keys: [{ token: false, chosenCardType: "Instant", chosenType: undefined }], oneOfFive: true, ice: "{U}", errors: 0 });
  });

  it("a creature-type chooser is untouched beside it: Urza's Incubator resolves with chosenType and no chosenCardType", () => {
    const s0 = board({ user: [...many(3, ISLAND, "user", "is"), P("gb", GRIZZLY_BEARS)], hand: [H("ui", URZAS_INCUBATOR)] });
    const inc = resolveTopOfStack(dispatchAction(s0, castsOf(s0, "user", "ui")[0])).players.user.battlefield.find((p) => p.card.name === "Urza's Incubator");
    expect({ chosenType: inc.chosenType, hasChosenCardType: "chosenCardType" in inc }).toEqual({ chosenType: "Bear", hasChosenCardType: false });
  });
});

describe("⭐ the discount — {1} off a spell of the chosen type, generic mana only", () => {
  it("⭐ each chosen type against one hand: only that type's spells drop {1}; every other cast stays at full price", () => {
    const row = { noKey: priceList(priceBoard([])), noChoice: priceList(priceBoard([key("ck", null)])),
      ...Object.fromEntries(CHOSEN_CARD_TYPE_OPTIONS.map((t) => [t, priceList(priceBoard([key("ck", t)]))])) };
    console.log("  WITNESS discountTable", JSON.stringify(row));
    expect(row).toEqual({
      noKey: FULL_PRICE,
      noChoice: FULL_PRICE, // a Key that made no choice discounts nothing
      Artifact: { ...FULL_PRICE, "Mind Stone": "{1}", "Darksteel Myr": "{2}", "Harnfel, Horn of Bounty": "{3}{R}", "Elbrus, the Binding Blade // Withengar Unbound": "{6}" },
      Creature: { ...FULL_PRICE, "Darksteel Myr": "{2}", "Hill Giant": "{2}{R}", "Boon Satyr": "{G}{G}", "Murderous Rider": "{B}{B}", "Birgi, God of Storytelling": "{1}{R}" },
      Enchantment: { ...FULL_PRICE, "Glorious Anthem": "{W}{W}", "Boon Satyr": "{G}{G}", "Boon Satyr (bestow)": "{2}{G}{G}" },
      Instant: { ...FULL_PRICE, "Swift End": "{B}{B}", "Fire": "{R}", "Ice": "{U}" },
      Sorcery: { ...FULL_PRICE, "Divination": "{1}{U}" },
    });
  });

  it("⭐ an artifact creature is an artifact spell AND a creature spell (CR 205.2b): Darksteel Myr drops under either", () => {
    expect(["Artifact", "Creature", "Instant"].map((t) => priceList(priceBoard([key("ck", t)]))["Darksteel Myr"])).toEqual(["{2}", "{2}", "{3}"]);
  });

  it("⭐ the face being cast decides: an adventurer's two halves, a modal DFC's two faces, a transforming card's front face", () => {
    const at = (t) => priceList(priceBoard([key("ck", t)]));
    const row = {
      instant: { swiftEnd: at("Instant")["Swift End"], rider: at("Instant")["Murderous Rider"] },        // CR 715.3a — the Adventure is an instant
      creature: { swiftEnd: at("Creature")["Swift End"], rider: at("Creature")["Murderous Rider"], birgi: at("Creature")["Birgi, God of Storytelling"], harnfel: at("Creature")["Harnfel, Horn of Bounty"] },
      artifact: { birgi: at("Artifact")["Birgi, God of Storytelling"], harnfel: at("Artifact")["Harnfel, Horn of Bounty"] }, // CR 712.11b
      elbrus: { artifact: at("Artifact")["Elbrus, the Binding Blade // Withengar Unbound"], creature: at("Creature")["Elbrus, the Binding Blade // Withengar Unbound"] }, // CR 712.8c — its back face is a creature, its front an artifact
    };
    expect(row).toEqual({ instant: { swiftEnd: "{B}{B}", rider: "{1}{B}{B}" },
      creature: { swiftEnd: "{1}{B}{B}", rider: "{B}{B}", birgi: "{1}{R}", harnfel: "{4}{R}" },
      artifact: { birgi: "{2}{R}", harnfel: "{3}{R}" }, elbrus: { artifact: "{6}", creature: "{7}" } });
  });

  it("⭐ bestow: a bestowed spell is an Aura enchantment spell and no creature spell (CR 702.103b, 205.1a)", () => {
    const satyr = (t) => { const p = priceList(priceBoard([key("ck", t)])); return [p["Boon Satyr"], p["Boon Satyr (bestow)"]]; };
    expect({ creature: satyr("Creature"), enchantment: satyr("Enchantment"), artifact: satyr("Artifact") })
      .toEqual({ creature: ["{G}{G}", "{3}{G}{G}"], enchantment: ["{G}{G}", "{2}{G}{G}"], artifact: ["{1}{G}{G}", "{3}{G}{G}"] });
    expect([spellHasChosenCardType(BOON_SATYR, "Creature", { bestowed: true }), spellHasChosenCardType(BOON_SATYR, "Enchantment", { bestowed: true }),
      spellHasChosenCardType(BOON_SATYR, "Creature")]).toEqual([false, true, true]);
  });

  it("⭐ two Keys stack, and a Key stacks with another reducer — generic only: never below {0}, never a coloured pip", () => {
    const two = (a, b, extra = []) => priceList(priceBoard([key("k1", a), key("k2", b), ...extra]));
    const row = {
      twoSorcery: two("Sorcery", "Sorcery").Divination,
      sorceryAndInstant: { divination: two("Sorcery", "Instant").Divination, ice: two("Sorcery", "Instant").Ice },
      twoInstant: { fire: two("Instant", "Instant").Fire, bolt: two("Instant", "Instant")["Lightning Bolt"], swiftEnd: two("Instant", "Instant")["Swift End"] },
      withInspector: { mindStone: two("Artifact", "Instant", [P("fi", FOUNDRY_INSPECTOR)])["Mind Stone"], myr: two("Artifact", "Instant", [P("fi", FOUNDRY_INSPECTOR)])["Darksteel Myr"] },
      threeOnTwo: two("Artifact", "Artifact", [P("fi", FOUNDRY_INSPECTOR)])["Mind Stone"],
    };
    console.log("  WITNESS stacking", JSON.stringify(row));
    expect(row).toEqual({ twoSorcery: "{U}", sorceryAndInstant: { divination: "{1}{U}", ice: "{U}" }, twoInstant: { fire: "{R}", bolt: "{R}", swiftEnd: "{B}{B}" },
      withInspector: { mindStone: "{0}", myr: "{1}" }, threeOnTwo: "{0}" });
  });

  it("⭐ the cast is paid at the discounted cost: two Islands cast Divination beside a Sorcery Key — and cannot without it", () => {
    const withKey = board({ user: [key("ck", "Sorcery"), ...many(2, ISLAND, "user", "is")], hand: [H("div", DIVINATION)] });
    const without = board({ user: many(2, ISLAND, "user", "is"), hand: [H("div", DIVINATION)] });
    const offer = castsOf(withKey, "user", "div");
    const cast = dispatchAction(withKey, offer[0]);
    const resolved = resolveTopOfStack(cast);
    const row = { without: castsOf(without, "user", "div").length, offered: offer.map((a) => printed(a.cost)), tapped: cast.players.user.battlefield.filter((p) => p.tapped).map((p) => p.id).sort(),
      onStack: cast.stack.map((o) => o.source?.name), drew: resolved.players.user.hand.length, errors: errors(resolved).length };
    console.log("  WITNESS paidDiscounted", JSON.stringify(row));
    expect(row).toEqual({ without: 0, offered: ["{1}{U}"], tapped: ["is1", "is2"], onStack: ["Divination"], drew: 2, errors: 0 });
  });

  it("⭐ only its controller's spells: a Key never discounts an opponent's cast, in either direction", () => {
    const deal = (userKey, aiKey) => board({ active: "ai", user: [key("uk", userKey), ...many(3, ISLAND, "user", "uis")], ai: [key("ak", aiKey, "ai"), ...many(3, ISLAND, "ai", "ais")],
      hand: [H("fi", FIRE_ICE)], aiHand: [H("div", DIVINATION)] });
    const crossed = deal("Sorcery", "Instant"); // each Key names the type the OTHER player is casting
    const own = deal("Instant", "Sorcery");     // each Key names its own controller's type
    const row = { crossed: { aiDivination: priceList(crossed, "ai").Divination, userIce: priceList(crossed, "user").Ice },
      own: { aiDivination: priceList(own, "ai").Divination, userIce: priceList(own, "user").Ice } };
    console.log("  WITNESS controllerOnly", JSON.stringify(row));
    expect(row).toEqual({ crossed: { aiDivination: "{2}{U}", userIce: "{1}{U}" }, own: { aiDivination: "{1}{U}", userIce: "{U}" } });
  });

  it("the reducer pairs with its source's chosenCardType — never with a chosenType — and reads a raw type_line too", () => {
    expect(collectCostReducers([key("ck", "Sorcery"), P("ui", URZAS_INCUBATOR, "user", { chosenType: "Bear" })]))
      .toEqual([{ chosenCardType: true, amount: 1, sourceChosenCardType: "Sorcery" }, { chosenType: true, amount: 2, sourceChosenType: "Bear" }]);
    const raw = { name: DIVINATION.name, type_line: DIVINATION.type }; // the bundled Scryfall field name
    expect([costReductionForSpell(collectCostReducers([key("ck", "Sorcery")]), raw), costReductionForSpell(collectCostReducers([key("ck", "Instant")]), raw)]).toEqual([1, 0]);
  });
});

describe("⭐ the choice on every entry — not only when it is cast (CR 614.12a)", () => {
  it("⭐ searched onto the battlefield (Whir of Invention, X=3): the choice is made, and the Key is not counted as a card still to cast", () => {
    const s0 = board({ user: many(6, ISLAND, "user", "is"), hand: [H("whir", WHIR)], library: [H("ck", CLOUD_KEY), H("bear", GRIZZLY_BEARS)] });
    let s = resolveTopOfStack(dispatchAction(s0, castsOf(s0, "user", "whir").find((a) => a.xValue === 3)));
    const offered = s.pendingChoice?.candidates?.map((c) => c.id);
    s = resolveTutorChoice(s, "ck");
    // The library still holds the Key itself as the choice is made: counted, Artifact 1 = Creature 1 would tie to Artifact.
    const row = { offered, keys: keysOn(s), library: s.players.user.library.map((c) => c.id), errors: errors(s).length };
    console.log("  WITNESS whir", JSON.stringify(row));
    expect(row).toEqual({ offered: ["ck"], keys: [{ token: false, chosenCardType: "Creature", chosenType: undefined }], library: ["bear"], errors: 0 });
  });

  it("returned from the graveyard (Argivian Restoration): the choice is made as it enters", () => {
    const s0 = board({ user: many(4, ISLAND, "user", "is"), hand: [H("ar", ARGIVIAN_RESTORATION), H("b", LIGHTNING_BOLT)], graveyard: [H("ck", CLOUD_KEY)],
      library: [H("d1", DIVINATION), H("d2", DIVINATION)] });
    const s = resolveTopOfStack(dispatchAction(s0, castsOf(s0, "user", "ar").find((a) => a.targets?.some((t) => t.id === "ck"))));
    expect({ keys: keysOn(s), graveyard: s.players.user.graveyard.map((c) => c.name), errors: errors(s).length })
      .toEqual({ keys: [{ token: false, chosenCardType: "Sorcery", chosenType: undefined }], graveyard: ["Argivian Restoration"], errors: 0 });
  });

  it("⭐ blinked (Ghostly Flicker): a new object makes a new choice (CR 400.7) — and the new choice is the one that discounts", () => {
    const s0 = board({ user: [key("ck", "Artifact"), ...many(5, ISLAND, "user", "is")], hand: [H("gf", GHOSTLY_FLICKER), H("div", DIVINATION), H("ms", MIND_STONE)],
      library: [H("d1", DIVINATION), H("d2", DIVINATION)] });
    const before = priceList(s0)["Mind Stone"];
    const s = resolveTopOfStack(dispatchAction(s0, castsOf(s0, "user", "gf").find((a) => a.targets?.map((t) => t.id).join() === "ck,is1")));
    const row = { before, keys: keysOn(s), divination: priceList(s).Divination, mindStone: priceList(s)["Mind Stone"], errors: errors(s).length };
    console.log("  WITNESS flicker", JSON.stringify(row));
    expect(row).toEqual({ before: "{1}", keys: [{ token: false, chosenCardType: "Sorcery", chosenType: undefined }], divination: "{1}{U}", mindStone: "{2}", errors: 0 });
  });

  it("⭐ a clone entering as a copy (Sculpting Steel) makes its OWN choice (CR 707.5) — the original keeps its own, and each discounts its type", () => {
    const s0 = board({ user: [key("ck", "Artifact"), ...many(6, ISLAND, "user", "is")], hand: [H("ss", SCULPTING_STEEL), H("div", DIVINATION), H("ms", MIND_STONE)],
      library: [H("d1", DIVINATION), H("d2", DIVINATION)] });
    const steel = castsOf(s0, "user", "ss");
    let s = resolveTopOfStack(dispatchAction(s0, steel[0]));
    const candidates = s.pendingChoice?.candidates?.map((c) => c.id);
    s = finalizeStackResolution(resolveCloneChoice(s, "ck"));
    const row = { steelCost: steel.map((a) => printed(a.cost)), candidates, keys: keysOn(s), divination: priceList(s).Divination, mindStone: priceList(s)["Mind Stone"], errors: errors(s).length };
    console.log("  WITNESS sculptingSteel", JSON.stringify(row));
    expect(row).toEqual({ steelCost: ["{2}"], candidates: ["ck"],
      keys: [{ token: false, chosenCardType: "Artifact", chosenType: undefined }, { token: false, chosenCardType: "Sorcery", chosenType: undefined }],
      divination: "{1}{U}", mindStone: "{1}", errors: 0 });
  });

  it("⭐ a token copy (Flash Photography) makes its own choice too", () => {
    const s0 = board({ user: [key("ck", "Artifact"), ...many(6, ISLAND, "user", "is")], hand: [H("fp", FLASH_PHOTOGRAPHY), H("div", DIVINATION), H("ms", MIND_STONE)],
      library: [H("d1", DIVINATION), H("d2", DIVINATION)] });
    const s = resolveTopOfStack(dispatchAction(s0, castsOf(s0, "user", "fp").find((a) => a.targets?.some((t) => t.id === "ck"))));
    const row = { keys: keysOn(s), divination: priceList(s).Divination, mindStone: priceList(s)["Mind Stone"], errors: errors(s).length };
    console.log("  WITNESS flashPhotography", JSON.stringify(row));
    expect(row).toEqual({ keys: [{ token: false, chosenCardType: "Artifact", chosenType: undefined }, { token: true, chosenCardType: "Sorcery", chosenType: undefined }],
      divination: "{1}{U}", mindStone: "{1}", errors: 0 });
  });

  it("⭐ put onto the battlefield from the hand by The Ur-Dragon's attack trigger: the choice is made, the Key left out of the hand's count", () => {
    const g = createGameState({ userDeck: [], aiDeck: [] });
    const s0 = { ...g, turn: 5, activePlayer: "user", priorityHolder: "user", phase: "combat", step: "declare-blockers", stack: [], pendingTriggers: [],
      combat: { attackers: [{ permanentId: "shivan", attackingPlayer: "user", defender: "ai" }], blockers: [] },
      players: { ...g.players, user: { ...g.players.user, battlefield: [P("ur", UR_DRAGON), P("shivan", SHIVAN_DRAGON)], hand: [H("ck", CLOUD_KEY)], library: [H("b", LIGHTNING_BOLT)] },
        ai: { ...g.players.ai, battlefield: [], hand: [], library: [] } } };
    // One Dragon attacked: the Bolt is drawn, then the Key is put in. Counted, the Key would tie Artifact 1 = Instant 1 → Artifact.
    const s = runStepActions(s0);
    const row = { keys: keysOn(s), hand: s.players.user.hand.map((c) => c.id), errors: errors(s).length };
    console.log("  WITNESS urDragon", JSON.stringify(row));
    expect(row).toEqual({ keys: [{ token: false, chosenCardType: "Instant", chosenType: undefined }], hand: ["b"], errors: 0 });
  });
});
