/**
 * CULLING RITUAL — the play-weighted program, #587 (EDHREC #587).
 *   "Destroy each nonland permanent with mana value 2 or less. Add {B} or {G} for each permanent destroyed this way."
 *
 * One atom, mass-destroy-add-mana-per-destroyed (templateMatchers.matchMassDestroyManaPerDestroyed — the second sentence counts
 * what the first destroyed, so the two collapse together, Blood Money's discipline). At resolution (removal.js):
 *  - THE SET (CR 608.2h — fixed as the effect is applied): every nonland permanent on every battlefield whose mana value is 2 or
 *    less (shared.nonlandPermanentsWithManaValueAtMost). Mana value is the OBJECT's (CR 202.3): a layer-1 copy's copiable values
 *    (CR 707.2), a double-faced card's front face (CR 712.8d), an adventurer's creature card (CR 715.4), {X} as 0 (CR 202.3e), and
 *    0 for a token that isn't a copy (CR 202.1b) and a face-down permanent (CR 708.2a). Land is the object's type too — except
 *    that a multi-face permanent is read off its front face, the face the engine always has up.
 *  - DESTROYED THIS WAY (CR 701.8a/b): read through the destroy's own replacement ladder (spellEffects.destructionReplacementFor)
 *    on the board as the destruction begins — indestructible (CR 702.12b), a shield counter (CR 122.1c), a regeneration shield
 *    (CR 701.8c) and umbra armor (CR 702.89a) keep a permanent out of the count. A permanent sent to exile instead of its graveyard
 *    was still destroyed and counts. An Aura that survives its own destruction but falls off its destroyed host (CR 704.5m) does
 *    not count.
 *  - THE MANA: the controller's pool (CR 106.4), one {B} or {G} per permanent destroyed; the choice is per mana (CR 608.2d; the
 *    card's ruling "You aren't limited to one color"). House policy: round-robin in printed order, {B} first.
 *
 * Accepted under-read (pinned below): an umbra-armor Aura ABOVE the bound, destroyed in place of a host in the set, is not counted.
 *
 * Real oracle fixtures (bundled Scryfall, the 2026-10-01 data, generated by cardIndex.publicCard — never typed by hand). Board
 * states (counters, shields, attachments, a layer effect) are built directly where a test says so; the SYNTHETIC tests are labelled.
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, createGameState, createPermanent, findPermanent } from "./gameState.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { advanceStep, resolveTopOfStack } from "./gameEngine.js";
import { classifyCard } from "./coverage.js";
import { parseEffectClause, parseEffectProgram, programConfidence, programContainsCreatureMassRemoval, programContainsMassRemoval } from "./effects/parser.js";
import { applyCreateNamedToken, applyCreateTokenCopy } from "./effects/atoms/tokens.js";
import { manifestCard } from "./effects/atoms/manifest.js";
import { mdfcFaceCards, spellMdfcFaceCards } from "./modalDfc.js";
import { creatureFaceCard } from "./adventure.js";
import { addContinuousEffect, permanentTypes } from "./layers.js";
import { ATOM_RESOLVERS } from "./effects/effectAtoms.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const CULLING = {"name":"Culling Ritual","type":"Sorcery","mana":"{2}{B}{G}","cmc":4,"keywords":[],"colors":["B","G"],"oracle":"Destroy each nonland permanent with mana value 2 or less. Add {B} or {G} for each permanent destroyed this way."}; // native-spell
const ELVES = {"name":"Llanowar Elves","type":"Creature — Elf Druid","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G}."}; // native-mana
const SIGNET = {"name":"Arcane Signet","type":"Artifact","mana":"{2}","cmc":2,"keywords":[],"colors":[],"oracle":"{T}: Add one mana of any color in your commander's color identity."}; // native-mana
const SOL_RING = {"name":"Sol Ring","type":"Artifact","mana":"{1}","cmc":1,"keywords":[],"colors":[],"oracle":"{T}: Add {C}{C}."}; // native-mana
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const RELIC = {"name":"Darksteel Relic","type":"Artifact","mana":"{0}","cmc":0,"keywords":["Indestructible"],"colors":[],"oracle":"Indestructible (Effects that say \"destroy\" don't destroy this artifact.)"}; // native-body
const ANTHEM = {"name":"Glorious Anthem","type":"Enchantment","mana":"{1}{W}{W}","cmc":3,"keywords":[],"colors":["W"],"oracle":"Creatures you control get +1/+1."}; // native-static
const STUDY = {"name":"Rhystic Study","type":"Enchantment","mana":"{2}{U}","cmc":3,"keywords":[],"colors":["U"],"oracle":"Whenever an opponent casts a spell, you may draw a card unless that player pays {1}."}; // native-trigger
const ARENA = {"name":"Phyrexian Arena","type":"Enchantment","mana":"{1}{B}{B}","cmc":3,"keywords":[],"colors":["B"],"oracle":"At the beginning of your upkeep, you draw a card and lose 1 life."}; // native-trigger
const FOREST = {"name":"Forest","type":"Basic Land — Forest","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {G}.)"}; // land
const SWAMP = {"name":"Swamp","type":"Basic Land — Swamp","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {B}.)"}; // land
const MUTAVAULT = {"name":"Mutavault","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{1}: This land becomes a 2/2 creature with all creature types until end of turn. It's still a land."}; // land
const ARBOR = {"name":"Dryad Arbor","type":"Land Creature — Forest Dryad","mana":"","cmc":0,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"(This land isn't a spell, it's affected by summoning sickness, and it has \"{T}: Add {G}.\")"}; // land
const BALLISTA = {"name":"Walking Ballista","type":"Artifact Creature — Construct","mana":"{X}{X}","cmc":0,"power":"0","toughness":"0","keywords":[],"colors":[],"oracle":"This creature enters with X +1/+1 counters on it.\n{4}: Put a +1/+1 counter on this creature.\nRemove a +1/+1 counter from this creature: It deals 1 damage to any target."}; // native-activated
const TIBALT = {"name":"Tibalt, the Fiend-Blooded","type":"Legendary Planeswalker — Tibalt","mana":"{R}{R}","cmc":2,"loyalty":"2","keywords":[],"colors":["R"],"oracle":"+1: Draw a card, then discard a card at random.\n−4: Tibalt deals damage equal to the number of cards in target player's hand to that player.\n−6: Gain control of all creatures until end of turn. Untap them. They gain haste until end of turn."}; // playable-pw
const PACIFISM = {"name":"Pacifism","type":"Enchantment — Aura","mana":"{1}{W}","cmc":2,"keywords":["Enchant"],"colors":["W"],"oracle":"Enchant creature\nEnchanted creature can't attack or block."}; // native-aura
const RANCOR = {"name":"Rancor","type":"Enchantment — Aura","mana":"{G}","cmc":1,"keywords":["Enchant"],"colors":["G"],"oracle":"Enchant creature\nEnchanted creature gets +2/+0 and has trample.\nWhen this Aura is put into a graveyard from the battlefield, return it to its owner's hand."}; // native-aura
const HYENA_UMBRA = {"name":"Hyena Umbra","type":"Enchantment — Aura","mana":"{W}","cmc":1,"keywords":["Umbra armor","Enchant"],"colors":["W"],"oracle":"Enchant creature\nEnchanted creature gets +1/+1 and has first strike.\nUmbra armor (If enchanted creature would be destroyed, instead remove all damage from it and destroy this Aura.)"}; // native-aura
const SNAKE_UMBRA = {"name":"Snake Umbra","type":"Enchantment — Aura","mana":"{2}{G}","cmc":3,"keywords":["Umbra armor","Enchant"],"colors":["G"],"oracle":"Enchant creature\nEnchanted creature gets +1/+1 and has \"Whenever this creature deals damage to an opponent, you may draw a card.\"\nUmbra armor (If enchanted creature would be destroyed, instead remove all damage from it and destroy this Aura.)"}; // native-aura
const AZCANTA = {"name":"Search for Azcanta // Azcanta, the Sunken Ruin","type":"Legendary Enchantment // Legendary Land","mana":"{1}{U}","cmc":2,"keywords":["Surveil","Transform"],"layout":"transform","colors":[],"oracle":"Search for Azcanta - Legendary Enchantment {1}{U}\nAt the beginning of your upkeep, surveil 1. Then if you have seven or more cards in your graveyard, you may transform Search for Azcanta. (Look at the top card of your library. You may put that card into your graveyard.)\n//\nAzcanta, the Sunken Ruin - Legendary Land \n(Transforms from Search for Azcanta.)\n{T}: Add {U}.\n{2}{U}, {T}: Look at the top four cards of your library. You may reveal a noncreature, nonland card from among them and put it into your hand. Put the rest on the bottom of your library in any order."}; // body-only
const DELVER = {"name":"Delver of Secrets // Insectile Aberration","type":"Creature — Human Wizard // Creature — Human Insect","mana":"{U}","cmc":1,"power":"1","toughness":"1","keywords":["Flying","Transform"],"layout":"transform","colors":[],"oracle":"Delver of Secrets - Creature — Human Wizard {U}\nAt the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform this creature.\n//\nInsectile Aberration - Creature — Human Insect \nFlying"}; // body-only
const BONECRUSHER = {"name":"Bonecrusher Giant // Stomp","type":"Creature — Giant // Instant — Adventure","mana":"{2}{R} // {1}{R}","cmc":3,"power":"4","toughness":"3","keywords":[],"layout":"adventure","colors":["R"],"oracle":"Bonecrusher Giant - Creature — Giant {2}{R}\nWhenever this creature becomes the target of a spell, this creature deals 2 damage to that spell's controller.\n//\nStomp - Instant — Adventure {1}{R}\nDamage can't be prevented this turn. Stomp deals 2 damage to any target."}; // body-only
const VALKI = {"name":"Valki, God of Lies // Tibalt, Cosmic Impostor","type":"Legendary Creature — God // Legendary Planeswalker — Tibalt","mana":"{1}{B}","cmc":2,"power":"2","toughness":"1","keywords":[],"layout":"modal_dfc","colors":[],"oracle":"Valki, God of Lies - Legendary Creature — God {1}{B}\nWhen Valki enters, each opponent reveals their hand. For each opponent, exile a creature card they revealed this way until Valki leaves the battlefield.\n{X}: Choose a creature card exiled with Valki with mana value X. Valki becomes a copy of that card.\n//\nTibalt, Cosmic Impostor - Legendary Planeswalker — Tibalt {5}{B}{R}\nAs Tibalt enters, you get an emblem with \"You may play cards exiled with Tibalt, Cosmic Impostor, and you may spend mana as though it were mana of any color to cast those spells.\"\n+2: Exile the top card of each player's library.\n−3: Exile target artifact or creature.\n−8: Exile all graveyards. Add {R}{R}{R}."}; // body-only
const AKOUM = {"name":"Akoum Warrior // Akoum Teeth","type":"Creature — Minotaur Warrior // Land","mana":"{5}{R}","cmc":6,"power":"4","toughness":"5","keywords":["Trample"],"layout":"modal_dfc","colors":[],"oracle":"Akoum Warrior - Creature — Minotaur Warrior {5}{R}\nTrample\n//\nAkoum Teeth - Land \nThis land enters tapped.\n{T}: Add {R}."}; // native-body
const TRANSRELIQUAT = {"name":"Mizzium Transreliquat","type":"Artifact","mana":"{3}","cmc":3,"keywords":[],"colors":[],"oracle":"{3}: This artifact becomes a copy of target artifact until end of turn.\n{1}{U}{R}: This artifact becomes a copy of target artifact, except it has this ability."}; // native-activated
const LEYLINE = {"name":"Leyline of the Void","type":"Enchantment","mana":"{2}{B}{B}","cmc":4,"keywords":[],"colors":["B"],"oracle":"If this card is in your opening hand, you may begin the game with it on the battlefield.\nIf a card would be put into an opponent's graveyard from anywhere, exile it instead."}; // native-static
const DRUDGE = {"name":"Drudge Skeletons","type":"Creature — Skeleton","mana":"{1}{B}","cmc":2,"power":"1","toughness":"1","keywords":["Heal","Regenerate"],"colors":["B"],"oracle":"{B}: Regenerate this creature. (The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)"}; // native-activated
const BLOOD_ARTIST = {"name":"Blood Artist","type":"Creature — Vampire","mana":"{1}{B}","cmc":2,"power":"0","toughness":"1","keywords":[],"colors":["B"],"oracle":"Whenever this creature or another creature dies, target player loses 1 life and you gain 1 life."}; // native-trigger
const GAZE = {"name":"Gaze of Granite","type":"Sorcery","mana":"{X}{B}{B}{G}","cmc":3,"keywords":[],"colors":["B","G"],"oracle":"Destroy each nonland permanent with mana value X or less."}; // arbiter-spell
const PEST_CONTROL = {"name":"Pest Control","type":"Sorcery","mana":"{W}{B}","cmc":2,"keywords":["Cycling"],"colors":["B","W"],"oracle":"Destroy all nonland permanents with mana value 1 or less.\nCycling {2} ({2}, Discard this card: Draw a card.)"}; // arbiter-spell
const BLOOD_MONEY = {"name":"Blood Money","type":"Sorcery","mana":"{5}{B}{B}","cmc":7,"keywords":["Treasure"],"colors":["B"],"oracle":"Destroy all creatures. For each nontoken creature destroyed this way, you create a tapped Treasure token."}; // native-spell
const HIDETSUGU = {"name":"Hidetsugu Consumes All // Vessel of the All-Consuming","type":"Enchantment — Saga // Enchantment Creature — Ogre Shaman","mana":"{1}{B}{R}","cmc":3,"keywords":["Transform","Trample"],"layout":"transform","colors":[],"oracle":"Hidetsugu Consumes All - Enchantment — Saga {1}{B}{R}\n(As this Saga enters and after your draw step, add a lore counter.)\nI — Destroy each nonland permanent with mana value 1 or less.\nII — Exile all graveyards.\nIII — Exile this Saga, then return it to the battlefield transformed under your control.\n//\nVessel of the All-Consuming - Enchantment Creature — Ogre Shaman \nTrample\nWhenever this creature deals damage, put a +1/+1 counter on it.\nWhenever this creature deals damage to a player, if it has dealt 10 or more damage to that player this turn, they lose the game."}; // body-only

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const H = (id, card) => ({ ...card, id });
// Attach aura `auraId` to host `hostId` on a list of permanents (both sides of the link, as the engine stores it).
const attach = (perms, auraId, hostId) => perms.map((p) => (p.id === auraId ? { ...p, attachedTo: hostId } : p.id === hostId ? { ...p, attachments: [...(p.attachments || []), auraId] } : p));
// The caster's mana: exactly {2}{B}{G} from four basics, so the pool is empty once Culling Ritual is cast.
const MANA = () => [P("sw1", SWAMP), P("sw2", SWAMP), P("fo1", FOREST), P("fo2", FOREST)];
function board({ user = [], ai = [], hand = [H("cull", CULLING)], pool = {} } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  const lib = (who) => [1, 2, 3].map((i) => ({ ...BEARS, id: `${who}-lib${i}` }));
  return { ...g, turn: 5, activePlayer: "user", priorityHolder: "user", phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: { ...g.players,
      user: { ...g.players.user, battlefield: [...MANA(), ...user], hand, manaPool: { ...g.players.user.manaPool, ...pool }, library: lib("user") },
      ai: { ...g.players.ai, battlefield: ai, hand: [], library: lib("ai") } } };
}
const castCull = (s) => {
  const offers = legalActionsForPlayer(s, "user").filter((a) => a.kind === "cast-spell" && a.cardId === "cull");
  expect(offers.length).toBeGreaterThan(0);
  return dispatchAction(s, offers[0]);
};
// Cast Culling Ritual through the real offer → dispatch → resolve path; returns the state after it resolved.
const cull = (s) => resolveTopOfStack(castCull(s));
const ids = (s, who) => s.players[who].battlefield.map((p) => p.id).sort();
const gy = (s, who) => s.players[who].graveyard.map((c) => c.name).sort();
const pool = (s, who = "user") => Object.fromEntries(Object.entries(s.players[who].manaPool).filter(([, n]) => n > 0));
const cullLog = (s) => (s.log || []).filter((e) => e.effect === "mass-destroy-add-mana-per-destroyed");
const errors = (s) => (s.log || []).filter((e) => e.kind === "stack-resolve-error");
const ctxUser = { controller: "user", sourceId: null, cardName: "test", targets: [] };

describe("the card and its parse", () => {
  it("classify: Culling Ritual native-spell; the neighbours this slice must not touch stay where they were", () => {
    const row = { culling: classifyCard(CULLING), gaze: classifyCard(GAZE), pestControl: classifyCard(PEST_CONTROL), hidetsugu: classifyCard(HIDETSUGU), bloodMoney: classifyCard(BLOOD_MONEY) };
    console.log("  WITNESS classify", JSON.stringify(row)); // vitest 4 needs --disable-console-intercept
    expect(row).toEqual({ culling: "native-spell", gaze: "arbiter-spell", pestControl: "arbiter-spell", hidetsugu: "body-only", bloodMoney: "native-spell" });
  });

  it("the parse: ONE atom — the bound, the two printed colors in printed order, no target", () => {
    const p = parseEffectProgram(CULLING);
    expect({ confidence: programConfidence(p), atoms: p.atoms, xSpell: p.xSpell })
      .toEqual({ confidence: "high", atoms: [{ op: "mass-destroy-add-mana-per-destroyed", mvMax: 2, colors: ["B", "G"], targetType: null }], xSpell: false });
    expect(typeof ATOM_RESOLVERS["mass-destroy-add-mana-per-destroyed"]).toBe("function");
  });

  it("near misses stay unparsed: either sentence alone, another bound direction, one color, another count noun, a rider before or after", () => {
    const atoms = (clause) => parseEffectClause(clause, "Sorcery")?.atoms ?? [];
    expect({
      destroyOnly: atoms("Destroy each nonland permanent with mana value 2 or less."),
      manaOnly: atoms("Add {B} or {G} for each permanent destroyed this way."),
      greater: atoms("Destroy each nonland permanent with mana value 2 or greater. Add {B} or {G} for each permanent destroyed this way."),
      oneColor: atoms("Destroy each nonland permanent with mana value 2 or less. Add {B} for each permanent destroyed this way."),
      creatureCount: atoms("Destroy each nonland permanent with mana value 2 or less. Add {B} or {G} for each creature destroyed this way."),
      riderAfter: atoms("Destroy each nonland permanent with mana value 2 or less. Add {B} or {G} for each permanent destroyed this way. You gain 2 life."),
      riderBefore: atoms("Each player loses 2 life. Destroy each nonland permanent with mana value 2 or less. Add {B} or {G} for each permanent destroyed this way."),
    }).toEqual({ destroyOnly: [], manaOnly: [], greater: [], oneColor: [], creatureCount: [], riderAfter: [], riderBefore: [] });
  });

  it("the AI holds it like any symmetric wipe — and never unlocks it as a creature wipe", () => {
    const p = parseEffectProgram(CULLING);
    expect({ held: programContainsMassRemoval(p), creatureWipe: programContainsCreatureMassRemoval(p) }).toEqual({ held: true, creatureWipe: false });
  });

  it("SYNTHETIC SHAPE (the rider stamp): a \"can't be regenerated\" sentence the parse text strips is put back on the atom", () => {
    const p = parseEffectClause("Destroy each nonland permanent with mana value 2 or less. They can't be regenerated. Add {B} or {G} for each permanent destroyed this way.", "Sorcery");
    expect(p.atoms).toEqual([{ op: "mass-destroy-add-mana-per-destroyed", mvMax: 2, colors: ["B", "G"], targetType: null, cannotRegenerate: true }]);
  });
});

describe("⭐ the sweep — cast, resolved, counted", () => {
  it("⭐ a mixed board: exactly the nonland permanents at mana value 2 or less die, on both sides; one mana per death, {B} first, alternating", () => {
    // user (the caster): four basics (they pay for the spell), Llanowar Elves (1), Arcane Signet (2), Walking Ballista ({X}{X} → 0),
    // Darksteel Relic (0, indestructible), Glorious Anthem (3), Mutavault (a land, 0), a Treasure token (0).
    // ai: Grizzly Bears (2), Sol Ring (1), Tibalt, the Fiend-Blooded (2), Phyrexian Arena (3), Dryad Arbor (a land creature, 0), a Forest.
    const user = [P("elves", ELVES), P("signet", SIGNET), P("ballista", BALLISTA, "user", { counters: { "+1/+1": 2 } }), P("relic", RELIC), P("anthem", ANTHEM), P("vault", MUTAVAULT)];
    const ai = [P("bears", BEARS, "ai"), P("ring", SOL_RING, "ai"), P("tibalt", TIBALT, "ai", { counters: { loyalty: 2 } }), P("arena", ARENA, "ai"), P("arbor", ARBOR, "ai"), P("afo", FOREST, "ai")];
    const s0 = applyCreateNamedToken(board({ user, ai }), { op: "create-named-token", token: "treasure", count: 1, targetType: null }, ctxUser);
    const treasure = s0.players.user.battlefield.find((p) => p.card?.token)?.id;
    const cast = castCull(s0);
    const s = resolveTopOfStack(cast);
    const row = {
      treasureMinted: !!treasure, poolAfterCast: pool(cast),
      user: ids(s, "user"), ai: ids(s, "ai"),
      userGraveyard: gy(s, "user"), aiGraveyard: gy(s, "ai"),
      pool: pool(s), logged: cullLog(s).map((e) => ({ destroyed: e.destroyed, mana: e.mana })), stack: s.stack.length, errors: errors(s).length,
    };
    console.log("  WITNESS mixedBoard", JSON.stringify(row));
    expect(row).toEqual({
      treasureMinted: true, poolAfterCast: {},
      user: ["anthem", "fo1", "fo2", "relic", "sw1", "sw2", "vault"], ai: ["afo", "arbor", "arena"],
      // the Treasure is a token: destroyed (and counted) but it ceases to exist rather than reaching the graveyard (CR 111.7)
      userGraveyard: ["Arcane Signet", "Culling Ritual", "Llanowar Elves", "Walking Ballista"], aiGraveyard: ["Grizzly Bears", "Sol Ring", "Tibalt, the Fiend-Blooded"],
      pool: { B: 4, G: 3 }, logged: [{ destroyed: 7, mana: { B: 4, G: 3 } }], stack: 0, errors: 0,
    });
  });

  it("the count follows the deaths: none, one, two, three — the spell itself never counts", () => {
    const run = (ai) => { const s = cull(board({ ai })); return { pool: pool(s), destroyed: cullLog(s)[0]?.destroyed }; };
    const row = {
      none: run([P("arena", ARENA, "ai")]),
      one: run([P("bears", BEARS, "ai")]),
      two: run([P("bears", BEARS, "ai"), P("ring", SOL_RING, "ai")]),
      three: run([P("bears", BEARS, "ai"), P("ring", SOL_RING, "ai"), P("elves", ELVES, "ai")]),
    };
    console.log("  WITNESS counts", JSON.stringify(row));
    expect(row).toEqual({ none: { pool: {}, destroyed: 0 }, one: { pool: { B: 1 }, destroyed: 1 }, two: { pool: { B: 1, G: 1 }, destroyed: 2 }, three: { pool: { B: 2, G: 1 }, destroyed: 3 } });
  });

  it("the mana is ordinary pool mana: it pays for the next spell this main phase, and empties when the step ends (CR 106.4)", () => {
    // Two deaths → {B}{G}. The four basics all went into Culling Ritual, so only the pool can pay Grizzly Bears' {1}{G}.
    const s = cull(board({ ai: [P("bears", BEARS, "ai"), P("ring", SOL_RING, "ai")], hand: [H("cull", CULLING), H("hb", BEARS)] }));
    const bearsOffer = legalActionsForPlayer(s, "user").find((a) => a.kind === "cast-spell" && a.cardId === "hb");
    const paid = bearsOffer ? dispatchAction(s, bearsOffer) : null;
    const next = advanceStep(s);
    expect({ now: pool(s), bearsCastable: !!bearsOffer, poolAfterBears: paid ? pool(paid) : null, afterStep: pool(next) })
      .toEqual({ now: { B: 1, G: 1 }, bearsCastable: true, poolAfterBears: {}, afterStep: {} });
  });

  it("⭐ one event: a Blood Artist destroyed with the rest sees every creature that died — its own and the opponent's", () => {
    const s = cull(board({ user: [P("artist", BLOOD_ARTIST), P("elves", ELVES)], ai: [P("bears", BEARS, "ai")] }));
    const row = { died: gy(s, "user").length - 1 + gy(s, "ai").length, artistTriggers: s.stack.filter((o) => o.source?.name === "Blood Artist").length, pool: pool(s) };
    console.log("  WITNESS oneEvent", JSON.stringify(row));
    expect(row).toEqual({ died: 3, artistTriggers: 3, pool: { B: 2, G: 1 } });
  });
});

describe("⭐ destroyed this way — only what the destroy really destroyed", () => {
  it("⭐ indestructible, a shield counter, a regeneration shield: each survives and adds nothing; the shields are spent", () => {
    const ai = [P("relic", RELIC, "ai"), P("bears", BEARS, "ai", { counters: { shield: 1 } }), P("drudge", DRUDGE, "ai", { regenShields: 1 }), P("ring", SOL_RING, "ai")];
    const s = cull(board({ ai }));
    const bears = findPermanent(s, "bears")?.permanent;
    const drudge = findPermanent(s, "drudge")?.permanent;
    const row = { ai: ids(s, "ai"), aiGraveyard: gy(s, "ai"), bearsShield: bears?.counters?.shield ?? 0, drudge: { shields: drudge?.regenShields ?? 0, tapped: drudge?.tapped }, pool: pool(s) };
    console.log("  WITNESS saved", JSON.stringify(row));
    expect(row).toEqual({ ai: ["bears", "drudge", "relic"], aiGraveyard: ["Sol Ring"], bearsShield: 0, drudge: { shields: 0, tapped: true }, pool: { B: 1 } });
  });

  it("⭐ umbra armor: the host lives, the Umbra (in the set) is destroyed in its place — one permanent destroyed, one mana", () => {
    const ai = attach([P("bears", BEARS, "ai", { damageMarked: 1 }), P("umbra", HYENA_UMBRA, "ai")], "umbra", "bears");
    const s = cull(board({ ai }));
    const row = { ai: ids(s, "ai"), aiGraveyard: gy(s, "ai"), bearsDamage: findPermanent(s, "bears")?.permanent.damageMarked, pool: pool(s) };
    console.log("  WITNESS umbra", JSON.stringify(row));
    expect(row).toEqual({ ai: ["bears"], aiGraveyard: ["Hyena Umbra"], bearsDamage: 0, pool: { B: 1 } });
  });

  it("ACCEPTED UNDER-READ: an Umbra above the bound saves its host and is destroyed instead, but is not counted — no mana", () => {
    const ai = attach([P("bears", BEARS, "ai"), P("umbra", SNAKE_UMBRA, "ai")], "umbra", "bears");
    const s = cull(board({ ai }));
    expect({ ai: ids(s, "ai"), aiGraveyard: gy(s, "ai"), pool: pool(s) }).toEqual({ ai: ["bears"], aiGraveyard: ["Snake Umbra"], pool: {} });
  });

  it("⭐ an Aura that falls off a destroyed host: counted when it was destroyed with it, NOT when its own destruction was replaced", () => {
    // Rancor (1) on Grizzly Bears (2): both in the set, both destroyed in the one event — two mana (Rancor's return trigger fires).
    const both = cull(board({ ai: attach([P("bears", BEARS, "ai"), P("rancor", RANCOR, "ai")], "rancor", "bears") }));
    // Pacifism (2) with a shield counter on the opponent's Bears: its own destruction is replaced (the shield goes), then it is put
    // into the graveyard because its host is gone (CR 704.5m) — it was never destroyed. One mana, for the Bears. Both seat orders:
    // the caster's Pacifism is reached first; the opponent's own Pacifism (listed after its host) falls off before it is reached.
    const userAura = { ...board({ ai: [P("bears", BEARS, "ai", { attachments: ["paci"] })], user: [P("paci", PACIFISM, "user", { counters: { shield: 1 }, attachedTo: "bears" })] }) };
    const aiAura = board({ ai: attach([P("bears", BEARS, "ai"), P("paci", PACIFISM, "ai", { counters: { shield: 1 } })], "paci", "bears") });
    const a = cull(userAura);
    const b = cull(aiAura);
    const row = {
      both: { aiGraveyard: gy(both, "ai"), pool: pool(both), rancorReturn: both.stack.some((o) => o.source?.name === "Rancor") },
      casterAura: { userGraveyard: gy(a, "user"), aiGraveyard: gy(a, "ai"), pool: pool(a) },
      ownAura: { aiGraveyard: gy(b, "ai"), pool: pool(b) },
    };
    console.log("  WITNESS fallenAura", JSON.stringify(row));
    expect(row).toEqual({
      both: { aiGraveyard: ["Grizzly Bears", "Rancor"], pool: { B: 1, G: 1 }, rancorReturn: true },
      casterAura: { userGraveyard: ["Culling Ritual", "Pacifism"], aiGraveyard: ["Grizzly Bears"], pool: { B: 1 } },
      ownAura: { aiGraveyard: ["Grizzly Bears", "Pacifism"], pool: { B: 1 } },
    });
  });

  it("a permanent destroyed but exiled instead of reaching a graveyard (Leyline of the Void) was still destroyed, and counts", () => {
    const s = cull(board({ user: [P("leyline", LEYLINE)], ai: [P("bears", BEARS, "ai"), P("ring", SOL_RING, "ai")] }));
    expect({ aiGraveyard: gy(s, "ai"), aiExile: s.players.ai.exile.map((c) => c.name).sort(), pool: pool(s) })
      .toEqual({ aiGraveyard: [], aiExile: ["Grizzly Bears", "Sol Ring"], pool: { B: 1, G: 1 } });
  });

  it("SYNTHETIC (the rider stamp at resolution): with cannotRegenerate on the atom, a regeneration shield saves nothing — destroyed and counted", () => {
    const atom = parseEffectClause("Destroy each nonland permanent with mana value 2 or less. They can't be regenerated. Add {B} or {G} for each permanent destroyed this way.", "Sorcery").atoms[0];
    const s0 = board({ ai: [P("drudge", DRUDGE, "ai", { regenShields: 1 })] });
    const s = ATOM_RESOLVERS[atom.op](s0, atom, ctxUser);
    expect({ ai: ids(s, "ai"), aiGraveyard: gy(s, "ai"), pool: pool(s) }).toEqual({ ai: [], aiGraveyard: ["Drudge Skeletons"], pool: { B: 1 } });
  });
});

describe("⭐ mana value and land — read off the object on the battlefield", () => {
  it("⭐ double-faced and adventure cards: the face that is up decides (CR 712.8d/f, 715.4)", () => {
    const [valki, tibaltFace] = spellMdfcFaceCards(VALKI);
    const [, akoumTeeth] = mdfcFaceCards(AKOUM);
    const user = [
      P("delver", DELVER),                             // transforming, front up: a creature, mana value 1 → destroyed
      P("azcanta", AZCANTA),                           // transforming, front up: a legendary ENCHANTMENT (its back is the land), 2 → destroyed
      P("giant", creatureFaceCard(BONECRUSHER)),       // an adventurer on the battlefield: its creature card, 3 → stays
    ];
    // A modal face enters as its face view with the whole card kept as printedCard (actionDispatcher's face cast), so the
    // graveyard receives the real two-face card.
    const ai = [
      P("valki", valki, "ai", { printedCard: { ...VALKI, id: "c-valki" } }),                                 // modal, Valki face up: 2 → destroyed
      P("tibalt", tibaltFace, "ai", { printedCard: { ...VALKI, id: "c-tibalt" }, counters: { loyalty: 5 } }), // modal, Tibalt face up: {5}{B}{R} → 7 → stays
      P("teeth", akoumTeeth, "ai", { printedCard: { ...AKOUM, id: "c-teeth" } }),                            // modal, the land face up: a land → stays
    ];
    const s = cull(board({ user, ai }));
    const row = { user: ids(s, "user").filter((id) => !/^(sw|fo)/.test(id)), ai: ids(s, "ai"), userGraveyard: gy(s, "user"), aiGraveyard: gy(s, "ai"), pool: pool(s),
      azcantaReadAsLandByTheLayerDerive: permanentTypes(board({ user: [P("azcanta", AZCANTA)] }), "azcanta").types.includes("Land") };
    console.log("  WITNESS faces", JSON.stringify(row));
    expect(row).toEqual({ user: ["giant"], ai: ["teeth", "tibalt"],
      userGraveyard: ["Culling Ritual", "Delver of Secrets // Insectile Aberration", "Search for Azcanta // Azcanta, the Sunken Ruin"],
      aiGraveyard: ["Valki, God of Lies // Tibalt, Cosmic Impostor"], pool: { B: 2, G: 1 },
      azcantaReadAsLandByTheLayerDerive: true }); // why the front face is read for a " // " permanent
  });

  it("⭐ tokens: a token that is not a copy has mana value 0 (swept); a token copy has its original's (CR 707.2)", () => {
    let s0 = board({ user: [P("study", STUDY), P("ring", SOL_RING)] });
    s0 = applyCreateTokenCopy(s0, { op: "create-token-copy", copySource: "target", count: 1 }, { ...ctxUser, targets: [{ type: "permanent", id: "study" }] });
    s0 = applyCreateTokenCopy(s0, { op: "create-token-copy", copySource: "target", count: 1 }, { ...ctxUser, targets: [{ type: "permanent", id: "ring" }] });
    s0 = applyCreateNamedToken(s0, { op: "create-named-token", token: "treasure", count: 1, targetType: null }, ctxUser);
    const tokensBefore = s0.players.user.battlefield.filter((p) => p.card?.token).map((p) => p.card.name).sort();
    const s = cull(s0);
    const row = { tokensBefore, tokensAfter: s.players.user.battlefield.filter((p) => p.card?.token).map((p) => p.card.name).sort(), pool: pool(s) };
    console.log("  WITNESS tokens", JSON.stringify(row));
    // Sol Ring (the card) + the Sol Ring token + the Treasure: three destroyed; both Rhystic Studies (3) stay
    expect(row).toEqual({ tokensBefore: ["Rhystic Study", "Sol Ring", "Treasure"], tokensAfter: ["Rhystic Study"], pool: { B: 2, G: 1 } });
  });

  it("a face-down permanent has mana value 0 (CR 708.2a): the manifested Glorious Anthem is destroyed — the card reaches the graveyard", () => {
    const s0 = board({});
    const withLib = { ...s0, players: { ...s0.players, ai: { ...s0.players.ai, library: [{ ...ANTHEM, id: "anthem-card" }, ...s0.players.ai.library] } } };
    const manifested = manifestCard(withLib, "ai", withLib.players.ai.library[0]);
    const faceDown = manifested.players.ai.battlefield.find((p) => p.faceDown);
    const s = cull(manifested);
    expect({ faceDown: !!faceDown, ai: ids(s, "ai"), aiGraveyard: gy(s, "ai"), pool: pool(s) }).toEqual({ faceDown: true, ai: [], aiGraveyard: ["Glorious Anthem"], pool: { B: 1 } });
  });

  it("⭐ a copy effect changes the mana value: Mizzium Transreliquat (3) that became a copy of Sol Ring (1) is destroyed", () => {
    // The opponent's Transreliquat copies the opponent's Sol Ring through its own activated ability ({3}, paid from its pool, on
    // its own priority), then the caster casts Culling Ritual. The same Transreliquat with no copy effect is spared.
    const s0 = board({ ai: [P("tr", TRANSRELIQUAT, "ai"), P("ring", SOL_RING, "ai")] });
    const asAi = { ...s0, activePlayer: "ai", priorityHolder: "ai", players: { ...s0.players, ai: { ...s0.players.ai, manaPool: { ...s0.players.ai.manaPool, C: 3 } } } };
    const offer = legalActionsForPlayer(asAi, "ai").find((a) => a.kind === "activate-ability" && a.permanentId === "tr" && (a.targets || []).some((t) => t.id === "ring"));
    const copied = resolveTopOfStack(dispatchAction(asAi, offer));
    const s = cull({ ...copied, activePlayer: "user", priorityHolder: "user" });
    const untouched = cull(board({ ai: [P("tr", TRANSRELIQUAT, "ai")] }));
    const row = { copyOf: (copied.continuousEffects || []).filter((e) => e.layer === 1 && e.affects?.permanentId === "tr").map((e) => e.copiableCard?.name),
      untouched: ids(untouched, "ai"), ai: ids(s, "ai"), aiGraveyard: gy(s, "ai"), pool: pool(s) };
    console.log("  WITNESS copy", JSON.stringify(row));
    expect(row).toEqual({ copyOf: ["Sol Ring"], untouched: ["tr"], ai: [], aiGraveyard: ["Mizzium Transreliquat", "Sol Ring"], pool: { B: 1, G: 1 } });
  });

  it("SYNTHETIC LAYER EFFECT (the land guard): a creature a layer-4 effect makes a land is a land — never destroyed, never counted", () => {
    const s0 = board({ ai: [P("bears", BEARS, "ai"), P("ring", SOL_RING, "ai")] });
    const { state: s1 } = addContinuousEffect(s0, { layer: 4, op: { layerOp: "addCardType", types: ["Land"] }, affects: { mode: "self", permanentId: "bears" }, duration: { kind: "permanent" }, source: { kind: "resolution", permanentId: "bears", cardName: "synthetic" } });
    const s = cull(s1);
    expect({ bearsIsLand: permanentTypes(s1, "bears").types.includes("Land"), ai: ids(s, "ai"), pool: pool(s) }).toEqual({ bearsIsLand: true, ai: ["bears"], pool: { B: 1 } });
  });
});
