/**
 * ABRUPT DECAY (#742), CHAIN REACTION (#708), PRIEST OF TITANIA (#766) — the play-weighted program.
 *
 * ABRUPT DECAY — "This spell can't be countered. / Destroy target nonland permanent with mana value 3 or less."
 *  - The uncounterable sentence was already enforced (staticAbilityParser.stackSpellIsUncounterable reads the on-card text: a
 *    counterspell's target enumeration skips the spell, and every counter that does reach it — Kira's trigger, a ward payment —
 *    leaves it on the stack, CR 701.6a). The parse peels the sentence (textNormalize.stripUncounterableRider).
 *  - What parked it was the target: removal.js's mana-value-filtered arm now admits "nonland permanent" — the nonlandPermanent
 *    pool (not a land after layer 4, CR 205.2a, 613.1d: an animated Mutavault is still a land) with the manaValue restriction.
 *  - The restriction reads the OBJECT's mana value (layers.permanentManaValue, CR 202.3): a layer-1 copy's copiable values
 *    (CR 707.2 — a Mizzium Transreliquat that became a copy of Gilded Lotus is a 5), 0 for a token that isn't a copy (CR 202.1b),
 *    the original's for a token copy. The same reader Culling Ritual's mass set uses.
 *
 * CHAIN REACTION — "Chain Reaction deals X damage to each creature, where X is the number of creatures on the battlefield."
 *  - The count (countForSpec "creaturesOnBattlefield", admitted only by the "deals X damage …, where X is" arm): every creature on
 *    every battlefield, the caster's included, read ONCE as the spell resolves, before any damage (CR 608.2h; the card's ruling).
 *  - "Each creature" (spellEffects.applyDamageEffect's eachCreature sweep) and the count ask ONE question —
 *    layers.permanentHasCardType(…, "Creature"): an animated land is counted and dealt damage; a front-face-up Saga whose back face
 *    is a creature (Fable of the Mirror-Breaker), a God below its devotion (Thassa) and a bestowed Aura (Boon Satyr) are neither.
 *    The sweep used to read the printed "Creature" substring, which said the opposite on all four.
 *
 * PRIEST OF TITANIA — "{T}: Add {G} for each Elf on the battlefield."
 *  - manaModel.parseManaMetric reads "<subtype> on the battlefield" (and "the number of <subtype>s on the battlefield") as
 *    countForSpec's subtypeOnBattlefield, the curated COUNT_SUBTYPE word only: every Elf on every battlefield, the Priest
 *    included (the card's ruling), a changeling or an animated Mutavault ("all creature types") included.
 *  - A permanent's type read is its FRONT FACE (shared.countMatchesPerm, CR 712.8d): Invasion of Lorwyn is a Battle whose back
 *    face is an Elf, and it no longer counts; Fable of the Mirror-Breaker no longer counts as a creature for Gaea's Cradle.
 *  - Both mana readers see the amount: manaSources (the planner) and actionsTapForMana (the explicit tap). Summoning sickness
 *    applies (CR 302.6). The same arm brings Wirewood Channeler ("X mana of any one color, where X is the number of Elves on the
 *    battlefield" — one colour per tap) and corrects Cloudpost's runtime amount (it was a flat {C}).
 *
 * Accepted under-reads: a double-faced permanent is never offered to Abrupt Decay (spellEffects.addPermanents skips every " // "
 * permanent — the targeted permanent pool's standing omission; pinned below); the engine keeps a spell that can't be countered off
 * a counterspell's target list, where the card's ruling lets a counterspell target it and do nothing (pinned below); the Priest's
 * Elf count reads the printed front-face subtypes plus every creature type, so a permanent that became an Elf through a layer-1
 * copy effect or a layer-4 type grant is not counted (a corpus scan, 2026-10-02, found no native effect that makes an Elf stop being
 * one, so the read does not over-count today).
 *
 * Real oracle fixtures (bundled Scryfall, generated by cardIndex.publicCard — never typed by hand). Board states are built
 * directly; the one SYNTHETIC test is labelled.
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, createGameState, createPermanent, findPermanent } from "./gameState.js";
import { legalActionsForPlayer, filterActions, parseManaCost } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { resolveTopOfStack } from "./gameEngine.js";
import { classifyCard } from "./coverage.js";
import { parseEffectClause, parseEffectProgram, programConfidence } from "./effects/parser.js";
import { manaProduction, manaSources, planPayment } from "./manaModel.js";
import { applyCreateNamedToken, applyCreateTokenCopy } from "./effects/atoms/tokens.js";
import { permanentTypes } from "./layers.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const ABRUPT_DECAY = {"name":"Abrupt Decay","type":"Instant","mana":"{B}{G}","cmc":2,"keywords":[],"colors":["B","G"],"oracle":"This spell can't be countered.\nDestroy target nonland permanent with mana value 3 or less."}; // native-spell
const CHAIN_REACTION = {"name":"Chain Reaction","type":"Sorcery","mana":"{2}{R}{R}","cmc":4,"keywords":[],"colors":["R"],"oracle":"Chain Reaction deals X damage to each creature, where X is the number of creatures on the battlefield."}; // native-spell
const PRIEST = {"name":"Priest of Titania","type":"Creature — Elf Druid","mana":"{1}{G}","cmc":2,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G} for each Elf on the battlefield."}; // native-mana
const CHANNELER = {"name":"Wirewood Channeler","type":"Creature — Elf Druid","mana":"{3}{G}","cmc":4,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":"{T}: Add X mana of any one color, where X is the number of Elves on the battlefield."}; // native-mana
const CLOUDPOST = {"name":"Cloudpost","type":"Land — Locus","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"This land enters tapped.\n{T}: Add {C} for each Locus on the battlefield."}; // land
const GLIMMERPOST = {"name":"Glimmerpost","type":"Land — Locus","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"When this land enters, you gain 1 life for each Locus on the battlefield.\n{T}: Add {C}."}; // land-partial
const COUNTERSPELL = {"name":"Counterspell","type":"Instant","mana":"{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Counter target spell."}; // native-spell
const KIRA = {"name":"Kira, Great Glass-Spinner","type":"Legendary Creature — Spirit","mana":"{1}{U}{U}","cmc":3,"power":"2","toughness":"2","keywords":["Flying"],"colors":["U"],"oracle":"Flying\nCreatures you control have \"Whenever this creature becomes the target of a spell or ability for the first time each turn, counter that spell or ability.\""}; // native-trigger
const HONOR_GUARD = {"name":"Tomakul Honor Guard","type":"Creature — Human Soldier","mana":"{1}{G}","cmc":2,"power":"3","toughness":"1","keywords":["Ward"],"colors":["G"],"oracle":"Ward {2} (Whenever this creature becomes the target of a spell or ability an opponent controls, counter it unless that player pays {2}.)"}; // native-body
const CROSSROADS = {"name":"Concordant Crossroads","type":"World Enchantment","mana":"{G}","cmc":1,"keywords":[],"colors":["G"],"oracle":"All creatures have haste."}; // native-static
const ISLAND = {"name":"Island","type":"Basic Land — Island","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {U}.)"}; // land
const SWAMP = {"name":"Swamp","type":"Basic Land — Swamp","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {B}.)"}; // land
const FOREST = {"name":"Forest","type":"Basic Land — Forest","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {G}.)"}; // land
const MOUNTAIN = {"name":"Mountain","type":"Basic Land — Mountain","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {R}.)"}; // land
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const ELVES = {"name":"Llanowar Elves","type":"Creature — Elf Druid","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G}."}; // native-mana
const MYSTIC = {"name":"Elvish Mystic","type":"Creature — Elf Druid","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G}."}; // native-mana
const ARCHDRUID = {"name":"Elvish Archdruid","type":"Creature — Elf Druid","mana":"{1}{G}{G}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":"Other Elf creatures you control get +1/+1.\n{T}: Add {G} for each Elf you control."}; // native-mana
const OUTCAST = {"name":"Changeling Outcast","type":"Creature — Shapeshifter","mana":"{B}","cmc":1,"power":"1","toughness":"1","keywords":["Changeling"],"colors":["B"],"oracle":"Changeling (This card is every creature type.)\nThis creature can't block and can't be blocked."}; // native-body
const LORWYN = {"name":"Invasion of Lorwyn // Winnowing Forces","type":"Battle — Siege // Creature — Elf Warrior","mana":"{4}{B}{G}","cmc":6,"keywords":["Transform"],"layout":"transform","colors":[],"oracle":"Invasion of Lorwyn - Battle — Siege {4}{B}{G}\n(As a Siege enters, choose an opponent to protect it. You and others can attack it. When it's defeated, exile it, then cast it transformed.)\nWhen this Siege enters, destroy target non-Elf creature an opponent controls with power X or less, where X is the number of lands you control.\n//\nWinnowing Forces - Creature — Elf Warrior \nWinnowing Forces's power and toughness are each equal to the number of lands you control."}; // body-only
const FABLE = {"name":"Fable of the Mirror-Breaker // Reflection of Kiki-Jiki","type":"Enchantment — Saga // Enchantment Creature — Goblin Shaman","mana":"{2}{R}","cmc":3,"keywords":["Transform","Treasure"],"layout":"transform","colors":[],"oracle":"Fable of the Mirror-Breaker - Enchantment — Saga {2}{R}\n(As this Saga enters and after your draw step, add a lore counter.)\nI — Create a 2/2 red Goblin Shaman creature token with \"Whenever this token attacks, create a Treasure token.\"\nII — You may discard up to two cards. If you do, draw that many cards.\nIII — Exile this Saga, then return it to the battlefield transformed under your control.\n//\nReflection of Kiki-Jiki - Enchantment Creature — Goblin Shaman \n{1}, {T}: Create a token that's a copy of another target nonlegendary creature you control, except it has haste. Sacrifice it at the beginning of the next end step."}; // body-only
const CRADLE = {"name":"Gaea's Cradle","type":"Legendary Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {G} for each creature you control."}; // land
const STUDY = {"name":"Rhystic Study","type":"Enchantment","mana":"{2}{U}","cmc":3,"keywords":[],"colors":["U"],"oracle":"Whenever an opponent casts a spell, you may draw a card unless that player pays {1}."}; // native-trigger
const TITHE = {"name":"Smothering Tithe","type":"Enchantment","mana":"{3}{W}","cmc":4,"keywords":["Treasure"],"colors":["W"],"oracle":"Whenever an opponent draws a card, that player may pay {2}. If the player doesn't, you create a Treasure token. (It's an artifact with \"{T}, Sacrifice this token: Add one mana of any color.\")"}; // native-trigger
const SOL_RING = {"name":"Sol Ring","type":"Artifact","mana":"{1}","cmc":1,"keywords":[],"colors":[],"oracle":"{T}: Add {C}{C}."}; // native-mana
const GILDED_LOTUS = {"name":"Gilded Lotus","type":"Artifact","mana":"{5}","cmc":5,"keywords":[],"colors":[],"oracle":"{T}: Add three mana of any one color."}; // native-mana
const TRANSRELIQUAT = {"name":"Mizzium Transreliquat","type":"Artifact","mana":"{3}","cmc":3,"keywords":[],"colors":[],"oracle":"{3}: This artifact becomes a copy of target artifact until end of turn.\n{1}{U}{R}: This artifact becomes a copy of target artifact, except it has this ability."}; // native-activated
const MUTAVAULT = {"name":"Mutavault","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{1}: This land becomes a 2/2 creature with all creature types until end of turn. It's still a land."}; // land
const DELVER = {"name":"Delver of Secrets // Insectile Aberration","type":"Creature — Human Wizard // Creature — Human Insect","mana":"{U}","cmc":1,"power":"1","toughness":"1","keywords":["Flying","Transform"],"layout":"transform","colors":[],"oracle":"Delver of Secrets - Creature — Human Wizard {U}\nAt the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform this creature.\n//\nInsectile Aberration - Creature — Human Insect \nFlying"}; // body-only
const SERRA = {"name":"Serra Angel","type":"Creature — Angel","mana":"{3}{W}{W}","cmc":5,"power":"4","toughness":"4","keywords":["Flying","Vigilance"],"colors":["W"],"oracle":"Flying\nVigilance (Attacking doesn't cause this creature to tap.)"}; // native-body
const DREADMAW = {"name":"Colossal Dreadmaw","type":"Creature — Dinosaur","mana":"{4}{G}{G}","cmc":6,"power":"6","toughness":"6","keywords":["Trample"],"colors":["G"],"oracle":"Trample (This creature can deal excess combat damage to the player or planeswalker it's attacking.)"}; // native-body
const FOG_OF_WAR = {"name":"Fog of War","type":"Instant","mana":"{2}{G}","cmc":3,"keywords":[],"colors":["G"],"oracle":"You gain 1 life for each creature on the battlefield. Prevent all combat damage that would be dealt this turn by creatures with power 3 or less."}; // arbiter-spell
const CONGREGATE = {"name":"Congregate","type":"Instant","mana":"{3}{W}","cmc":4,"keywords":[],"colors":["W"],"oracle":"Target player gains 2 life for each creature on the battlefield."}; // arbiter-spell
const DEPLOY = {"name":"Deploy to the Front","type":"Sorcery","mana":"{5}{W}{W}","cmc":7,"keywords":[],"colors":["W"],"oracle":"Create X 1/1 white Soldier creature tokens, where X is the number of creatures on the battlefield."}; // arbiter-spell
const WITHERBLOOM_CHARM = {"name":"Witherbloom Charm","type":"Instant","mana":"{B}{G}","cmc":2,"keywords":[],"colors":["B","G"],"oracle":"Choose one —\n• You may sacrifice a permanent. If you do, draw two cards.\n• You gain 5 life.\n• Destroy target nonland permanent with mana value 2 or less."}; // arbiter-spell
const GEMPALM = {"name":"Gempalm Incinerator","type":"Creature — Goblin","mana":"{2}{R}","cmc":3,"power":"2","toughness":"1","keywords":["Cycling"],"colors":["R"],"oracle":"Cycling {1}{R} ({1}{R}, Discard this card: Draw a card.)\nWhen you cycle this card, you may have it deal X damage to target creature, where X is the number of Goblins on the battlefield."}; // body-only
const GUIDANCE = {"name":"Elvish Guidance","type":"Enchantment — Aura","mana":"{2}{G}","cmc":3,"keywords":["Enchant"],"colors":["G"],"oracle":"Enchant land\nWhenever enchanted land is tapped for mana, its controller adds an additional {G} for each Elf on the battlefield."}; // body-only
const MAELSTROM_PULSE = {"name":"Maelstrom Pulse","type":"Sorcery","mana":"{1}{B}{G}","cmc":3,"keywords":[],"colors":["B","G"],"oracle":"Destroy target nonland permanent and all other permanents with the same name as that permanent."}; // arbiter-spell
const BANISHER = {"name":"Darkstar Banisher","type":"Creature — Bat Cleric","mana":"{1}{W}{B}","cmc":3,"power":"2","toughness":"2","keywords":["Flying","Seek"],"colors":["B","W"],"oracle":"Flying\nWhen Darkstar Banisher enters, exile target nonland permanent with mana value 4 or less an opponent controls.\nWhen Darkstar Banisher leaves the battlefield, the exiled card's owner seeks a card that shares a card type with the exiled card."}; // body-only
const PYROCLASM = {"name":"Pyroclasm","type":"Sorcery","mana":"{1}{R}","cmc":2,"keywords":[],"colors":["R"],"oracle":"Pyroclasm deals 2 damage to each creature."}; // native-spell
const THASSA = {"name":"Thassa, God of the Sea","type":"Legendary Enchantment Creature — God","mana":"{2}{U}","cmc":3,"power":"5","toughness":"5","keywords":["Indestructible","Scry"],"colors":["U"],"oracle":"Indestructible\nAs long as your devotion to blue is less than five, Thassa isn't a creature. (Each {U} in the mana costs of permanents you control counts toward your devotion to blue.)\nAt the beginning of your upkeep, scry 1.\n{1}{U}: Target creature you control can't be blocked this turn."}; // native-mixed
const BOON_SATYR = {"name":"Boon Satyr","type":"Enchantment Creature — Satyr","mana":"{1}{G}{G}","cmc":3,"power":"4","toughness":"2","keywords":["Bestow","Flash"],"colors":["G"],"oracle":"Flash\nBestow {3}{G}{G} (If you cast this card for its bestow cost, it's an Aura spell with enchant creature. It becomes a creature again if it's not attached.)\nEnchanted creature gets +4/+2."}; // native-aura

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const H = (id, card) => ({ ...card, id });
function board({ user = [], ai = [], hand = [], aiHand = [], pool = {}, aiPool = {} } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  const lib = (who) => [1, 2, 3].map((i) => ({ ...BEARS, id: `${who}-lib${i}` }));
  return { ...g, turn: 5, activePlayer: "user", priorityHolder: "user", phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: { ...g.players,
      user: { ...g.players.user, battlefield: user, hand, manaPool: { ...g.players.user.manaPool, ...pool }, library: lib("user") },
      ai: { ...g.players.ai, battlefield: ai, hand: aiHand, manaPool: { ...g.players.ai.manaPool, ...aiPool }, library: lib("ai") } } };
}
const casts = (s, who, cardId) => legalActionsForPlayer(s, who).filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
const offeredTargets = (s, cardId = "decay") => [...new Set(casts(s, "user", cardId).map((a) => a.targets?.[0]?.id))].sort();
const castAt = (s, cardId, targetId) => {
  const offer = casts(s, "user", cardId).find((a) => a.targets?.[0]?.id === targetId);
  expect(offer, `${cardId} → ${targetId}`).toBeTruthy();
  return dispatchAction(s, offer);
};
const castUntargeted = (s, cardId) => {
  const offer = casts(s, "user", cardId)[0];
  expect(offer, cardId).toBeTruthy();
  return dispatchAction(s, offer);
};
const pass = (s, who) => dispatchAction(s, legalActionsForPlayer(s, who).find((a) => a.kind === "pass-priority"));
const ids = (s, who) => s.players[who].battlefield.map((p) => p.id).sort();
const gy = (s, who) => s.players[who].graveyard.map((c) => c.name).sort();
const dmg = (s, id) => findPermanent(s, id)?.permanent.damageMarked ?? null;
const taps = (s, permId) => filterActions(legalActionsForPlayer(s, "user"), "tap-for-mana").filter((a) => a.permanentId === permId).map((a) => ({ color: a.color, amount: a.amount }));
const sourceOf = (s, permId) => manaSources(s, "user").filter((x) => x.permanentId === permId).map((x) => ({ colors: x.colors, amount: x.amount }));
const uncounterable = (s) => (s.log || []).filter((e) => e.effect === "counter-uncounterable").map((e) => e.via || null);
const ctxUser = { controller: "user", sourceId: null, cardName: "test", targets: [] };
// Activate a permanent's ability through the real offer → dispatch → resolve path (the activator holds priority, its pool pays).
function activate(s, who, permId, targetId = null) {
  const asWho = { ...s, activePlayer: who, priorityHolder: who };
  const offer = legalActionsForPlayer(asWho, who).find((a) => a.kind === "activate-ability" && a.permanentId === permId && (!targetId || (a.targets || []).some((t) => t.id === targetId)));
  expect(offer, `activate ${permId}`).toBeTruthy();
  return { ...resolveTopOfStack(dispatchAction(asWho, offer)), activePlayer: s.activePlayer, priorityHolder: s.priorityHolder };
}
// The mana the caster pays with, exactly the spell's cost so the pool is empty once it is cast.
const DECAY_MANA = () => [P("sw", SWAMP), P("fo", FOREST)];
const CHAIN_MANA = () => [P("m1", MOUNTAIN), P("m2", MOUNTAIN), P("m3", MOUNTAIN), P("m4", MOUNTAIN)];

describe("the cards and their parse", () => {
  it("classify: the three targets and Wirewood Channeler go native; Cloudpost stays land; the neighbours stay where they were", () => {
    const row = {
      decay: classifyCard(ABRUPT_DECAY), chain: classifyCard(CHAIN_REACTION), priest: classifyCard(PRIEST), channeler: classifyCard(CHANNELER),
      cloudpost: classifyCard(CLOUDPOST), glimmerpost: classifyCard(GLIMMERPOST), archdruid: classifyCard(ARCHDRUID), cradle: classifyCard(CRADLE),
      pyroclasm: classifyCard(PYROCLASM), fogOfWar: classifyCard(FOG_OF_WAR), congregate: classifyCard(CONGREGATE), deploy: classifyCard(DEPLOY),
      witherbloomCharm: classifyCard(WITHERBLOOM_CHARM), maelstromPulse: classifyCard(MAELSTROM_PULSE), banisher: classifyCard(BANISHER),
      gempalm: classifyCard(GEMPALM), guidance: classifyCard(GUIDANCE),
    };
    console.log("  WITNESS classify", JSON.stringify(row)); // vitest 4 needs --disable-console-intercept
    expect(row).toEqual({
      decay: "native-spell", chain: "native-spell", priest: "native-mana", channeler: "native-mana",
      cloudpost: "land", glimmerpost: "land-partial", archdruid: "native-mana", cradle: "land",
      pyroclasm: "native-spell", fogOfWar: "arbiter-spell", congregate: "arbiter-spell", deploy: "arbiter-spell",
      witherbloomCharm: "arbiter-spell", maelstromPulse: "arbiter-spell", banisher: "body-only",
      gempalm: "body-only", guidance: "body-only",
    });
  });

  it("the parse: Abrupt Decay is one targeted destroy with the mana-value bound; the uncounterable sentence leaves no atom", () => {
    const p = parseEffectProgram(ABRUPT_DECAY);
    expect({ confidence: programConfidence(p), atoms: p.atoms }).toEqual({
      confidence: "high", atoms: [{ op: "destroy", targetType: "nonlandPermanent", restrictions: [{ kind: "manaValue", op: "<=", value: 3 }] }],
    });
  });

  it("the parse: Chain Reaction is one eachCreature damage atom whose amount is the all-seats creature count", () => {
    const p = parseEffectProgram(CHAIN_REACTION);
    expect({ confidence: programConfidence(p), atoms: p.atoms }).toEqual({
      confidence: "high", atoms: [{ op: "deal-damage", targetType: "eachCreature", amountCount: { kind: "creaturesOnBattlefield" } }],
    });
  });

  it("the mana: Priest, Channeler and Cloudpost read the all-seats subtype count; Archdruid keeps its own-board count", () => {
    expect({
      priest: manaProduction(PRIEST), channeler: manaProduction(CHANNELER), cloudpost: manaProduction(CLOUDPOST), archdruid: manaProduction(ARCHDRUID)?.amountSpec,
    }).toEqual({
      priest: { colors: ["G"], amount: 0, amountSpec: { kind: "subtypeOnBattlefield", subtype: "Elf" }, requiresTap: true },
      channeler: { colors: ["W", "U", "B", "R", "G"], amount: 0, amountSpec: { kind: "subtypeOnBattlefield", subtype: "Elf" }, requiresTap: true },
      cloudpost: { colors: ["C"], amount: 0, amountSpec: { kind: "subtypeOnBattlefield", subtype: "Locus" }, requiresTap: true },
      archdruid: { kind: "permanentsYouControl", subtype: "Elf" },
    });
  });

  it("near misses stay unparsed: a controller-scoped mana-value target, and the all-seats creature count outside the damage arm", () => {
    const atoms = (clause, type) => parseEffectClause(clause, type)?.atoms ?? [];
    expect({
      opponentControls: atoms("Exile target nonland permanent with mana value 4 or less an opponent controls.", "Instant"),
      gainLife: atoms("Target player gains 2 life for each creature on the battlefield.", "Instant"),
      tokens: atoms("Create X 1/1 white Soldier creature tokens, where X is the number of creatures on the battlefield.", "Sorcery"),
      otherCreatures: atoms("Chain Reaction deals X damage to each creature, where X is the number of other creatures on the battlefield.", "Sorcery"),
    }).toEqual({ opponentControls: [], gainLife: [], tokens: [], otherCreatures: [] });
  });

  it("SYNTHETIC (the vocabulary gate): a word outside the curated subtype list parks the mana ability; a listed one reads", () => {
    const probe = (oracle) => manaProduction({ id: "c-probe", name: "Synthetic Gate Probe", type: "Creature — Elf Druid", mana: "{1}{G}", power: "1", toughness: "1", oracle });
    expect({
      unlisted: probe("{T}: Add {G} for each Sprocket on the battlefield."),
      listed: probe("{T}: Add {G} for each Goblin on the battlefield.")?.amountSpec,
    }).toEqual({ unlisted: null, listed: { kind: "subtypeOnBattlefield", subtype: "Goblin" } });
  });
});

describe("⭐ Abrupt Decay — can't be countered", () => {
  it("⭐ an opponent's Counterspell is not offered against it (it is offered against a counterable spell); Abrupt Decay resolves", () => {
    const mk = (hand) => board({ user: DECAY_MANA(), ai: [P("bears", BEARS, "ai"), P("is1", ISLAND, "ai"), P("is2", ISLAND, "ai")], hand, aiHand: [H("cs", COUNTERSPELL)] });
    // the control: the same Counterspell answers a Grizzly Bears spell
    const bearsCast = pass(castUntargeted(mk([H("hb", BEARS)]), "hb"), "user");
    // Abrupt Decay at the opponent's Grizzly Bears: the caster passes, the opponent holds priority with {U}{U} open
    const decayCast = pass(castAt(mk([H("decay", ABRUPT_DECAY)]), "decay", "bears"), "user");
    const done = pass(decayCast, "ai");
    const row = {
      counterspellVsBears: casts(bearsCast, "ai", "cs").map((a) => a.targets?.[0]?.name),
      counterspellVsDecay: casts(decayCast, "ai", "cs").length,
      aiPriority: decayCast.priorityHolder,
      ai: ids(done, "ai"), aiGraveyard: gy(done, "ai"), userGraveyard: gy(done, "user"), stack: done.stack.length,
    };
    console.log("  WITNESS counterspell", JSON.stringify(row));
    expect(row).toEqual({
      counterspellVsBears: ["Grizzly Bears"], counterspellVsDecay: 0, aiPriority: "ai",
      ai: ["is1", "is2"], aiGraveyard: ["Grizzly Bears"], userGraveyard: ["Abrupt Decay"], stack: 0,
    });
  });

  it("⭐ Kira's counter trigger and a ward payment both meet a spell that can't be countered: no payment asked, the target is destroyed", () => {
    const kiraCast = castAt(board({ user: DECAY_MANA(), ai: [P("kira", KIRA, "ai")], hand: [H("decay", ABRUPT_DECAY)] }), "decay", "kira");
    const kiraDone = resolveTopOfStack(kiraCast);
    const wardCast = castAt(board({ user: DECAY_MANA(), ai: [P("guard", HONOR_GUARD, "ai")], hand: [H("decay", ABRUPT_DECAY)] }), "decay", "guard");
    const wardDone = resolveTopOfStack(wardCast);
    const row = {
      kira: { refused: uncounterable(kiraCast), stack: kiraCast.stack.map((o) => o.source?.name), aiGraveyard: gy(kiraDone, "ai") },
      ward: { refused: uncounterable(wardCast), pendingChoice: wardCast.pendingChoice?.kind ?? null, stack: wardCast.stack.map((o) => o.source?.name), aiGraveyard: gy(wardDone, "ai") },
    };
    console.log("  WITNESS kiraWard", JSON.stringify(row));
    expect(row).toEqual({
      kira: { refused: ["kira"], stack: ["Abrupt Decay"], aiGraveyard: ["Kira, Great Glass-Spinner"] },
      ward: { refused: ["Tomakul Honor Guard"], pendingChoice: null, stack: ["Abrupt Decay"], aiGraveyard: ["Tomakul Honor Guard"] },
    });
  });
});

describe("⭐ Abrupt Decay — a nonland permanent with mana value 3 or less, read off the object", () => {
  it("⭐ the offered targets: mana value 3 or less on both sides, never a land (an animated Mutavault included), never a 4", () => {
    // user: Grizzly Bears (2), Rhystic Study (3), a Forest, a Mutavault animated by its own ability ({1} from the pool).
    // ai: Smothering Tithe (4), Sol Ring (1), Serra Angel (5), an Island.
    let s0 = board({ user: [...DECAY_MANA(), P("bears", BEARS), P("study", STUDY), P("vault", MUTAVAULT), P("forest2", FOREST)],
      ai: [P("tithe", TITHE, "ai"), P("ring", SOL_RING, "ai"), P("serra", SERRA, "ai"), P("isl", ISLAND, "ai")], hand: [H("decay", ABRUPT_DECAY)], pool: { C: 1 } });
    s0 = activate(s0, "user", "vault");
    const row = { vaultIsCreature: permanentTypes(s0, "vault").types.includes("Creature"), offered: offeredTargets(s0) };
    console.log("  WITNESS targets", JSON.stringify(row));
    expect(row).toEqual({ vaultIsCreature: true, offered: ["bears", "ring", "study"] });
    const done = resolveTopOfStack(castAt(s0, "decay", "study"));
    expect({ user: ids(done, "user").filter((id) => !["sw", "fo"].includes(id)), userGraveyard: gy(done, "user") })
      .toEqual({ user: ["bears", "forest2", "vault"], userGraveyard: ["Abrupt Decay", "Rhystic Study"] });
  });

  it("⭐ tokens: a token that isn't a copy has mana value 0 (offered); a token copy has its original's — a copy of Smothering Tithe is a 4", () => {
    let s0 = board({ user: DECAY_MANA(), ai: [P("tithe", TITHE, "ai"), P("ring", SOL_RING, "ai")], hand: [H("decay", ABRUPT_DECAY)] });
    const ctxAi = { ...ctxUser, controller: "ai" };
    s0 = applyCreateTokenCopy(s0, { op: "create-token-copy", copySource: "target", count: 1 }, { ...ctxAi, targets: [{ type: "permanent", id: "tithe" }] });
    s0 = applyCreateTokenCopy(s0, { op: "create-token-copy", copySource: "target", count: 1 }, { ...ctxAi, targets: [{ type: "permanent", id: "ring" }] });
    s0 = applyCreateNamedToken(s0, { op: "create-named-token", token: "treasure", count: 1, targetType: null }, ctxAi);
    const name = (id) => findPermanent(s0, id)?.permanent.card.name;
    const offeredNames = offeredTargets(s0).map((id) => `${name(id)}${findPermanent(s0, id)?.permanent.card.token ? " (token)" : ""}`).sort();
    console.log("  WITNESS tokens", JSON.stringify(offeredNames));
    expect(offeredNames).toEqual(["Sol Ring", "Sol Ring (token)", "Treasure (token)"]);
  });

  it("⭐ a copy effect changes the mana value: Mizzium Transreliquat (3) that became a copy of Gilded Lotus (5) is not a target", () => {
    // The opponent's Transreliquat copies the opponent's Gilded Lotus through its own activated ability ({3} from its pool). The
    // same Transreliquat with no copy effect is a legal target.
    const base = () => board({ user: DECAY_MANA(), ai: [P("tr", TRANSRELIQUAT, "ai"), P("lotus", GILDED_LOTUS, "ai")], hand: [H("decay", ABRUPT_DECAY)], aiPool: { C: 3 } });
    const copied = activate(base(), "ai", "tr", "lotus");
    const row = {
      copyOf: (copied.continuousEffects || []).filter((e) => e.layer === 1 && e.affects?.permanentId === "tr").map((e) => e.copiableCard?.name),
      uncopied: offeredTargets(base()), copied: offeredTargets(copied),
    };
    console.log("  WITNESS copy", JSON.stringify(row));
    expect(row).toEqual({ copyOf: ["Gilded Lotus"], uncopied: ["tr"], copied: [] });
  });

  it("ACCEPTED UNDER-OFFER: a double-faced permanent is never a target (the targeted permanent pool skips every \" // \" permanent)", () => {
    const s0 = board({ user: DECAY_MANA(), ai: [P("delver", DELVER, "ai"), P("bears", BEARS, "ai")], hand: [H("decay", ABRUPT_DECAY)] });
    expect(offeredTargets(s0)).toEqual(["bears"]);
  });
});

describe("⭐ Chain Reaction — X is every creature on the battlefield, counted once", () => {
  it("⭐ five creatures across two players: X = 5 for each of them, the caster's own included; the survivor keeps 5 damage", () => {
    const s0 = board({ user: [...CHAIN_MANA(), P("bears", BEARS), P("elves", ELVES)],
      ai: [P("serra", SERRA, "ai"), P("maw", DREADMAW, "ai"), P("aibears", BEARS, "ai"), P("forest", FOREST, "ai")], hand: [H("chain", CHAIN_REACTION)] });
    const done = resolveTopOfStack(castUntargeted(s0, "chain"));
    const row = {
      user: ids(done, "user").filter((id) => !/^m\d$/.test(id)), ai: ids(done, "ai"),
      userGraveyard: gy(done, "user"), aiGraveyard: gy(done, "ai"), dreadmawDamage: dmg(done, "maw"), stack: done.stack.length,
    };
    console.log("  WITNESS fiveCreatures", JSON.stringify(row));
    expect(row).toEqual({
      user: [], ai: ["forest", "maw"],
      userGraveyard: ["Chain Reaction", "Grizzly Bears", "Llanowar Elves"], aiGraveyard: ["Grizzly Bears", "Serra Angel"],
      dreadmawDamage: 5, stack: 0,
    });
  });

  it("⭐ the X is the board's creatures, not its cards: an animated Mutavault counts and is dealt X; a face-up Saga, a God below its devotion and a bestowed Aura are neither", () => {
    // A: the opponent's Colossal Dreadmaw and the caster's Fable of the Mirror-Breaker (a Saga whose BACK face is a creature) → X = 1.
    const a = resolveTopOfStack(castUntargeted(board({ user: [...CHAIN_MANA(), P("fable", FABLE)], ai: [P("maw", DREADMAW, "ai")], hand: [H("chain", CHAIN_REACTION)] }), "chain"));
    // B: the Dreadmaw and the caster's Mutavault, animated by its own ability → X = 2; the 2/2 Mutavault dies to it.
    const b0 = activate(board({ user: [...CHAIN_MANA(), P("vault", MUTAVAULT)], ai: [P("maw", DREADMAW, "ai")], hand: [H("chain", CHAIN_REACTION)], pool: { C: 1 } }), "user", "vault");
    const b = resolveTopOfStack(castUntargeted(b0, "chain"));
    // C: the caster's Thassa, God of the Sea (devotion to blue 1 — not a creature) and a Boon Satyr bestowed on the opponent's
    // Dreadmaw (a bestowed Aura, CR 702.103b) → X = 1.
    const c = resolveTopOfStack(castUntargeted(board({ user: [...CHAIN_MANA(), P("thassa", THASSA)],
      ai: [P("maw", DREADMAW, "ai", { attachments: ["satyr"] }), P("satyr", BOON_SATYR, "ai", { attachedTo: "maw", bestowed: true })], hand: [H("chain", CHAIN_REACTION)] }), "chain"));
    const row = {
      fable: { dreadmawDamage: dmg(a, "maw"), fableDamage: dmg(a, "fable") },
      mutavault: { dreadmawDamage: dmg(b, "maw"), userGraveyard: gy(b, "user") },
      godAndBestow: { dreadmawDamage: dmg(c, "maw"), thassaDamage: dmg(c, "thassa"), satyrDamage: dmg(c, "satyr") },
    };
    console.log("  WITNESS boardCreatures", JSON.stringify(row));
    expect(row).toEqual({
      fable: { dreadmawDamage: 1, fableDamage: 0 },
      mutavault: { dreadmawDamage: 2, userGraveyard: ["Chain Reaction", "Mutavault"] },
      godAndBestow: { dreadmawDamage: 1, thassaDamage: 0, satyrDamage: 0 },
    });
  });

  it("the shared sweep: Pyroclasm's \"each creature\" now deals its damage to an animated Mutavault and none to Fable", () => {
    const s0 = activate(board({ user: [P("m1", MOUNTAIN), P("m2", MOUNTAIN), P("vault", MUTAVAULT), P("fable", FABLE)], hand: [H("pyro", PYROCLASM)], pool: { C: 1 } }), "user", "vault");
    const done = resolveTopOfStack(castUntargeted(s0, "pyro"));
    expect({ userGraveyard: gy(done, "user"), fableDamage: dmg(done, "fable") }).toEqual({ userGraveyard: ["Mutavault", "Pyroclasm"], fableDamage: 0 });
  });
});

describe("⭐ Priest of Titania — {G} for each Elf on every battlefield", () => {
  // The caster's Llanowar Elves entered this turn: an Elf that counts, never a mana source of its own (so the planner's sum is the
  // Priest's amount plus one Forest).
  const priestBoard = (extraAi = []) => board({
    user: [P("priest", PRIEST), P("elves", ELVES, "user", { summoningSick: true }), P("fo", FOREST)],
    ai: [P("mystic", MYSTIC, "ai"), P("arch", ARCHDRUID, "ai"), P("lorwyn", LORWYN, "ai"), P("bears", BEARS, "ai"), ...extraAi],
    hand: [H("dm", DREADMAW)],
  });

  it("⭐ the Elves on both sides, the Priest itself and a changeling count; a Battle with an Elf back face does not", () => {
    const withOutcast = priestBoard([P("outcast", OUTCAST, "ai")]);
    const without = priestBoard();
    const tap = filterActions(legalActionsForPlayer(withOutcast, "user"), "tap-for-mana").find((a) => a.permanentId === "priest");
    const tapped = dispatchAction(withOutcast, tap);
    const row = {
      offer: taps(withOutcast, "priest"), planner: sourceOf(withOutcast, "priest"), poolAfterTap: tapped.players.user.manaPool.G,
      withoutChangeling: taps(without, "priest"),
    };
    console.log("  WITNESS priest", JSON.stringify(row));
    expect(row).toEqual({
      offer: [{ color: "G", amount: 5 }], planner: [{ colors: ["G"], amount: 5 }], poolAfterTap: 5,
      withoutChangeling: [{ color: "G", amount: 4 }],
    });
  });

  it("⭐ the planner pays with it: Colossal Dreadmaw ({4}{G}{G}) is castable from the Priest's 5 and a Forest, not from its 4", () => {
    const withOutcast = priestBoard([P("outcast", OUTCAST, "ai")]);
    const cast = dispatchAction(withOutcast, casts(withOutcast, "user", "dm")[0]);
    const row = {
      castableWith5: casts(withOutcast, "user", "dm").length > 0, castableWith4: casts(priestBoard(), "user", "dm").length > 0,
      tapped: cast.players.user.battlefield.filter((p) => p.tapped).map((p) => p.id).sort(), stack: cast.stack.map((o) => o.source?.name),
    };
    console.log("  WITNESS planner", JSON.stringify(row));
    expect(row).toEqual({ castableWith5: true, castableWith4: false, tapped: ["fo", "priest"], stack: ["Colossal Dreadmaw"] });
  });

  it("an animated Mutavault (all creature types) is an Elf while it is a creature", () => {
    const s0 = board({ user: [P("priest", PRIEST), P("vault", MUTAVAULT)], pool: { C: 1 } });
    expect({ before: taps(s0, "priest"), after: taps(activate(s0, "user", "vault"), "priest") })
      .toEqual({ before: [{ color: "G", amount: 1 }], after: [{ color: "G", amount: 2 }] });
  });

  it("⭐ summoning sickness: cast this turn it can't tap (CR 302.6) — not offered, not a payment source; with haste it can", () => {
    const enter = (extra = []) => {
      const s0 = board({ user: [P("f1", FOREST), P("f2", FOREST), P("elves", ELVES), ...extra], hand: [H("priest", PRIEST)] });
      const s = resolveTopOfStack(castUntargeted(s0, "priest"));
      return { s, priestId: s.players.user.battlefield.find((p) => p.card?.name === "Priest of Titania")?.id };
    };
    const sick = enter();
    const hasty = enter([P("crossroads", CROSSROADS)]);
    const row = {
      sick: { entered: !!sick.priestId, summoningSick: findPermanent(sick.s, sick.priestId)?.permanent.summoningSick, offer: taps(sick.s, sick.priestId), planner: sourceOf(sick.s, sick.priestId) },
      haste: { offer: taps(hasty.s, hasty.priestId), planner: sourceOf(hasty.s, hasty.priestId) },
    };
    console.log("  WITNESS sickness", JSON.stringify(row));
    expect(row).toEqual({
      sick: { entered: true, summoningSick: true, offer: [], planner: [] },
      haste: { offer: [{ color: "G", amount: 2 }], planner: [{ colors: ["G"], amount: 2 }] },
    });
  });

  it("⭐ Wirewood Channeler: X mana of ONE color per tap — {U}{U}{U} from one tap, never {G}{U}", () => {
    const s = board({ user: [P("chan", CHANNELER), P("elves", ELVES)], ai: [P("mystic", MYSTIC, "ai")] });
    const only = manaSources(s, "user").filter((x) => x.permanentId === "chan");
    const empty = { W: 0, U: 0, B: 0, R: 0, G: 0, C: 0 };
    const uuu = planPayment(empty, only, parseManaCost("{U}{U}{U}"));
    const row = {
      offer: taps(s, "chan"),
      uuu: uuu ? uuu.taps.map((t) => ({ color: t.color, amount: t.amount })) : null,
      gu: planPayment(empty, only, parseManaCost("{G}{U}")),
    };
    console.log("  WITNESS channeler", JSON.stringify(row));
    expect(row).toEqual({
      offer: ["W", "U", "B", "R", "G"].map((color) => ({ color, amount: 3 })),
      uuu: [{ color: "U", amount: 3 }], gu: null,
    });
  });

  it("⭐ Cloudpost counts every Locus on every battlefield (it tapped for a flat {C} before); Gaea's Cradle counts no Saga", () => {
    const post = board({ user: [P("cp", CLOUDPOST)], ai: [P("gp", GLIMMERPOST, "ai")] });
    const cradle = board({ user: [P("cradle", CRADLE), P("fable", FABLE), P("bears", BEARS)] });
    expect({ cloudpost: taps(post, "cp"), cradle: taps(cradle, "cradle") })
      .toEqual({ cloudpost: [{ color: "C", amount: 2 }], cradle: [{ color: "G", amount: 1 }] });
  });
});
