/**
 * THE DESTROY EVENT — one simultaneous event, read from the board as it began (a fix slice).
 *
 * A destroy that names several permanents destroys them at once (CR 701.8a). Replacement effects watch for the event and apply
 * as it would happen (CR 614.1), so every replacement that existed as the destruction began applies to it — even one whose
 * source is destroyed in the same event. The engine used to walk the target list one permanent at a time against a board it
 * had already partly destroyed: an Aura or a lord processed before the creature it protected was gone by the time the creature
 * was asked, and a "die → exile instead" or "graveyard → exile instead" source processed first no longer redirected the rest.
 * What this file pins:
 *
 *  1. THE LADDER (spellEffects.applyDestroyEffect): each permanent's destruction replacement — indestructible (CR 702.12b), a
 *     shield counter (CR 122.1c), a regeneration shield (CR 701.19a; "can't be regenerated", CR 701.19c), umbra armor
 *     (CR 702.89a) — is decided against the board as the event began. The decision is one function, gameState's
 *     destructionReplacementFor, which the lethal-damage state-based action (CR 704.5g) reads too: there is no second copy.
 *     Culling Ritual's "destroyed this way" count reads it on the same board, so the count and the destroy agree.
 *  2. WHERE IT WENT: "dies" means put into a graveyard from the battlefield (CR 700.4). A permanent a replacement keeps out of
 *     the graveyard — shuffled into its owner's library (Progenitus), exiled (Misery's Shadow, Rest in Peace, Dauthi
 *     Voidwalker) — did not die, and no dies trigger, batch watcher or death tally may say it did. One look-back constructor
 *     (gameState.deathLookback) builds the entry every death site hands the dies triggers, its flags read off the same card the
 *     zone move reads (a face-down permanent's real card, CR 400.6).
 *  3. AS IT LAST EXISTED: a leaves-the-battlefield ability looks back in time (CR 603.10a), so the look-back is the permanent's
 *     layer-aware characteristics, not its printed card: a crewed Vehicle or an animated land destroyed or sacrificed died as a
 *     creature. The one-permanent edict's victim pool reads the permanent the same way.
 *  4. BLOOD MONEY prints no "can't be regenerated": regeneration saves a creature from it. Its op now takes the parser's rider
 *     stamp like every destroy, so a rider would be honoured (a clearly labelled synthetic witness below).
 *
 * Real oracle fixtures (bundled Scryfall, generated by cardIndex.publicCard — never typed by hand). Everything runs through the
 * engine's entry points: legalActionsForPlayer → dispatchAction → resolveTopOfStack (the lethal-damage state-based action
 * through destroyLethalCreatures, the function every damage site calls).
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, attachPermanent, createGameState, createPermanent, destroyLethalCreatures, destructionReplacementFor } from "./gameState.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { chooseTriggerTargets, finalizeStackResolution, flushTriggers, resolveTopOfStack } from "./gameEngine.js";
import { resolveSacrificeChoice } from "./effects/runProgram.js";
import { manifestCard } from "./effects/atoms/manifest.js";
import { checkDiesTriggers } from "./triggers.js";
import { classifyCard } from "./coverage.js";
import { parseEffectProgram, programConfidence } from "./effects/parser.js";
import { permanentIsCreature } from "./layers.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const UMBRA = {"name":"Hyena Umbra","type":"Enchantment — Aura","mana":"{W}","cmc":1,"keywords":["Umbra armor","Enchant"],"colors":["W"],"oracle":"Enchant creature\nEnchanted creature gets +1/+1 and has first strike.\nUmbra armor (If enchanted creature would be destroyed, instead remove all damage from it and destroy this Aura.)"}; // native-aura
const WARD = {"name":"Timely Ward","type":"Enchantment — Aura","mana":"{2}{W}","cmc":3,"keywords":["Enchant"],"colors":["W"],"oracle":"You may cast this spell as though it had flash if it targets a commander.\nEnchant creature\nEnchanted creature has indestructible."}; // native-aura
const WRATH = {"name":"Wrath of God","type":"Sorcery","mana":"{2}{W}{W}","cmc":4,"keywords":[],"colors":["W"],"oracle":"Destroy all creatures. They can't be regenerated."}; // native-spell
const DAY = {"name":"Day of Judgment","type":"Sorcery","mana":"{2}{W}{W}","cmc":4,"keywords":[],"colors":["W"],"oracle":"Destroy all creatures."}; // native-spell
const VENGEANCE = {"name":"Akroma's Vengeance","type":"Sorcery","mana":"{4}{W}{W}","cmc":6,"keywords":["Cycling"],"colors":["W"],"oracle":"Destroy all artifacts, creatures, and enchantments.\nCycling {3} ({3}, Discard this card: Draw a card.)"}; // native-spell
const DISK = {"name":"Nevinyrral's Disk","type":"Artifact","mana":"{4}","cmc":4,"keywords":[],"colors":[],"oracle":"This artifact enters tapped.\n{1}, {T}: Destroy all artifacts, creatures, and enchantments."}; // native-activated
const BLOOD_MONEY = {"name":"Blood Money","type":"Sorcery","mana":"{5}{B}{B}","cmc":7,"keywords":["Treasure"],"colors":["B"],"oracle":"Destroy all creatures. For each nontoken creature destroyed this way, you create a tapped Treasure token."}; // native-spell
const PROGENITUS = {"name":"Progenitus","type":"Legendary Creature — Hydra Avatar","mana":"{W}{W}{U}{U}{B}{B}{R}{R}{G}{G}","cmc":10,"power":"10","toughness":"10","keywords":["Protection"],"colors":["B","G","R","U","W"],"oracle":"Protection from everything\nIf Progenitus would be put into a graveyard from anywhere, reveal Progenitus and shuffle it into its owner's library instead."}; // native-body
const ARTIST = {"name":"Blood Artist","type":"Creature — Vampire","mana":"{1}{B}","cmc":2,"power":"0","toughness":"1","keywords":[],"colors":["B"],"oracle":"Whenever this creature or another creature dies, target player loses 1 life and you gain 1 life."}; // native-trigger
const OPPORTUNIST = {"name":"Morbid Opportunist","type":"Creature — Human Rogue","mana":"{2}{B}","cmc":3,"power":"1","toughness":"3","keywords":[],"colors":["B"],"oracle":"Whenever one or more other creatures die, draw a card. This ability triggers only once each turn."}; // native-trigger
const EDICT = {"name":"Diabolic Edict","type":"Instant","mana":"{1}{B}","cmc":2,"keywords":[],"colors":["B"],"oracle":"Target player sacrifices a creature of their choice."}; // native-spell
const MUTAVAULT = {"name":"Mutavault","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{1}: This land becomes a 2/2 creature with all creature types until end of turn. It's still a land."}; // land
const COPTER = {"name":"Smuggler's Copter","type":"Artifact — Vehicle","mana":"{2}","cmc":2,"power":"3","toughness":"3","keywords":["Flying","Crew"],"colors":[],"oracle":"Flying\nWhenever this Vehicle attacks or blocks, you may draw a card. If you do, discard a card.\nCrew 1 (Tap any number of creatures you control with total power 1 or more: This Vehicle becomes an artifact creature until end of turn.)"}; // native-trigger
const RIP = {"name":"Rest in Peace","type":"Enchantment","mana":"{1}{W}","cmc":2,"keywords":[],"colors":["W"],"oracle":"When this enchantment enters, exile all graveyards.\nIf a card or token would be put into a graveyard from anywhere, exile it instead."}; // native-mixed
const BOA = {"name":"River Boa","type":"Creature — Snake","mana":"{1}{G}","cmc":2,"power":"2","toughness":"1","keywords":["Landwalk","Regenerate","Islandwalk"],"colors":["G"],"oracle":"Islandwalk (This creature can't be blocked as long as defending player controls an Island.)\n{G}: Regenerate this creature."}; // native-activated
const PURIFY = {"name":"Purify","type":"Sorcery","mana":"{3}{W}{W}","cmc":5,"keywords":[],"colors":["W"],"oracle":"Destroy all artifacts and enchantments."}; // native-spell
const WALLS = {"name":"The Walls of Ba Sing Se","type":"Legendary Artifact Creature — Wall","mana":"{8}","cmc":8,"power":"0","toughness":"30","keywords":["Defender"],"colors":[],"oracle":"Defender\nOther permanents you control have indestructible."}; // native-static
const SHADOW = {"name":"Misery's Shadow","type":"Creature — Shade","mana":"{1}{B}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["B"],"oracle":"If a creature an opponent controls would die, exile it instead.\n{1}: This creature gets +1/+1 until end of turn."}; // native-mixed
const MEMNITE = {"name":"Memnite","type":"Artifact Creature — Construct","mana":"{0}","cmc":0,"power":"1","toughness":"1","keywords":[],"colors":[],"oracle":""}; // native-body
const REALITY_SHIFT = {"name":"Reality Shift","type":"Instant","mana":"{1}{U}","cmc":2,"keywords":["Manifest"],"colors":["U"],"oracle":"Exile target creature. Its controller manifests the top card of their library. (That player puts the top card of their library onto the battlefield face down as a 2/2 creature. If it's a creature card, it can be turned face up any time for its mana cost.)"}; // native-spell
const BARTER = {"name":"Barter in Blood","type":"Sorcery","mana":"{2}{B}{B}","cmc":4,"keywords":[],"colors":["B"],"oracle":"Each player sacrifices two creatures of their choice."}; // native-spell
const DAUTHI = {"name":"Dauthi Voidwalker","type":"Creature — Dauthi Rogue","mana":"{B}{B}","cmc":2,"power":"3","toughness":"2","keywords":["Shadow"],"colors":["B"],"oracle":"Shadow (This creature can block or be blocked by only creatures with shadow.)\nIf a card would be put into an opponent's graveyard from anywhere, instead exile it with a void counter on it.\n{T}, Sacrifice this creature: Choose an exiled card an opponent owns with a void counter on it. You may play it this turn without paying its mana cost."}; // native-mixed
const PARHELION = {"name":"Parhelion II","type":"Legendary Artifact — Vehicle","mana":"{6}{W}{W}","cmc":8,"power":"5","toughness":"5","keywords":["Flying","Vigilance","First strike","Crew"],"colors":["W"],"oracle":"Flying, first strike, vigilance\nWhenever Parhelion II attacks, create two 4/4 white Angel creature tokens with flying and vigilance that are attacking.\nCrew 4 (Tap any number of creatures you control with total power 4 or more: This Vehicle becomes an artifact creature until end of turn.)"}; // native-trigger
const ABOMINATION = {"name":"Smothering Abomination","type":"Creature — Eldrazi","mana":"{2}{B}{B}","cmc":4,"power":"4","toughness":"3","keywords":["Flying","Devoid"],"colors":[],"oracle":"Devoid (This card has no color.)\nFlying\nAt the beginning of your upkeep, sacrifice a creature.\nWhenever you sacrifice a creature, draw a card."}; // native-trigger
const TROLL = {"name":"Horned Troll","type":"Creature — Troll","mana":"{2}{G}","cmc":3,"power":"2","toughness":"2","keywords":["Regenerate"],"colors":["G"],"oracle":"{G}: Regenerate this creature."}; // native-activated
const SHEOLDRED = {"name":"Sheoldred's Edict","type":"Instant","mana":"{1}{B}","cmc":2,"keywords":[],"colors":["B"],"oracle":"Choose one —\n• Each opponent sacrifices a nontoken creature of their choice.\n• Each opponent sacrifices a creature token of their choice.\n• Each opponent sacrifices a planeswalker of their choice."}; // native-spell
const SOUL_SHATTER = {"name":"Soul Shatter","type":"Instant","mana":"{2}{B}","cmc":3,"keywords":[],"colors":["B"],"oracle":"Each opponent sacrifices a creature or planeswalker with the greatest mana value among creatures and planeswalkers they control."}; // native-spell
const DOWNFALL = {"name":"Hero's Downfall","type":"Instant","mana":"{1}{B}{B}","cmc":3,"keywords":[],"colors":["B"],"oracle":"Destroy target creature or planeswalker."}; // native-spell
const CELEBRANT = {"name":"Cruel Celebrant","type":"Creature — Vampire","mana":"{W}{B}","cmc":2,"power":"1","toughness":"2","keywords":[],"colors":["B","W"],"oracle":"Whenever this creature or another creature or planeswalker you control dies, each opponent loses 1 life and you gain 1 life."}; // native-trigger
const JACE = {"name":"Jace Beleren","type":"Legendary Planeswalker — Jace","mana":"{1}{U}{U}","cmc":3,"loyalty":"3","keywords":["Mill"],"colors":["U"],"oracle":"+2: Each player draws a card.\n−1: Target player draws a card.\n−10: Target player mills twenty cards."}; // native-planeswalker
const CULLING = {"name":"Culling Ritual","type":"Sorcery","mana":"{2}{B}{G}","cmc":4,"keywords":[],"colors":["B","G"],"oracle":"Destroy each nonland permanent with mana value 2 or less. Add {B} or {G} for each permanent destroyed this way."}; // native-spell

// SYNTHETIC (labelled — no printed card carries it): Blood Money with Wrath of God's own rider sentence spliced in after its
// first sentence, both halves taken from the fixtures above. It exists only to witness that the parser's "can't be regenerated"
// stamp reaches Blood Money's op, so a rider-carrying wording could never resolve with regeneration still saving creatures.
const RIDER = WRATH.oracle.slice("Destroy all creatures. ".length); // "They can't be regenerated."
const BLOOD_MONEY_WITH_RIDER = { ...BLOOD_MONEY, name: "Blood Money (synthetic rider)", oracle: BLOOD_MONEY.oracle.replace("Destroy all creatures. ", `Destroy all creatures. ${RIDER} `) };

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const H = (id, card) => ({ ...card, id });
function board({ user = [], ai = [], hand = [], pool = {}, aiLibrary = null, active = "user" } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  const lib = (who) => [1, 2, 3].map((i) => ({ ...BEARS, id: `${who}-lib${i}` }));
  return { ...g, turn: 5, activePlayer: active, priorityHolder: active, phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: { ...g.players,
      user: { ...g.players.user, battlefield: user, hand, manaPool: { ...g.players.user.manaPool, ...pool }, library: lib("user") },
      ai: { ...g.players.ai, battlefield: ai, hand: [], library: aiLibrary || lib("ai") } } };
}
const withPool = (s, who, pool) => ({ ...s, players: { ...s.players, [who]: { ...s.players[who], manaPool: { ...s.players[who].manaPool, ...pool } } } });
const attach = (s, auraId, hostId) => attachPermanent(s, { equipId: auraId, targetId: hostId });
const actionsOf = (s, who) => legalActionsForPlayer({ ...s, priorityHolder: who }, who);
const castsOf = (s, cardId) => actionsOf(s, "user").filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
// Cast (the first offer, or the one `pick` chooses) and resolve it — the dies triggers it wakes are flushed onto the stack.
const cast = (s, cardId, pick = () => true) => resolveTopOfStack(dispatchAction({ ...s, priorityHolder: "user" }, castsOf(s, cardId).find(pick)));
// Activate a permanent's non-mana ability (the one `pick` chooses) for `who` and resolve it.
const activate = (s, permId, who = "user", pick = () => true) => {
  const a = actionsOf(s, who).find((x) => x.kind === "activate-ability" && x.permanentId === permId && !x.isManaAbility && pick(x));
  return resolveTopOfStack(dispatchAction({ ...s, priorityHolder: who }, a));
};
// Mutavault's "{1}: This land becomes a 2/2 creature …" through its own activation, paid from a {C} put in the pool.
const animate = (s, permId, who = "user") => activate(withPool(s, who, { C: 1 }), permId, who, (x) => x.cost?.generic === 1);
const crew = (s, vehicleId) => dispatchAction(s, actionsOf(s, "user").find((a) => a.kind === "crew-vehicle" && a.permanentId === vehicleId));
const perm = (s, id) => Object.values(s.players).flatMap((p) => p.battlefield).find((p) => p.id === id) || null;
const names = (zone) => zone.map((c) => c.name).sort();
const count = (zone, name) => zone.filter((c) => c.name === name).length;
const triggersOf = (s, name) => s.stack.filter((o) => o.source?.name === name).length;
const errors = (s) => (s.log || []).filter((e) => e.kind === "stack-resolve-error");
const died = (s) => ({ user: s.players.user.creaturesDiedThisTurn || 0, ai: s.players.ai.creaturesDiedThisTurn || 0 });

describe("the cards and their parse", () => {
  it("classify: the wipes, edicts, savers, redirectors and watchers this file drives (a fix slice moves no tier)", () => {
    const row = Object.fromEntries(Object.entries({ WRATH, DAY, VENGEANCE, PURIFY, DISK, BLOOD_MONEY, CULLING, EDICT, SHEOLDRED, SOUL_SHATTER, BARTER, REALITY_SHIFT, DOWNFALL,
      UMBRA, WARD, WALLS, BOA, TROLL, PROGENITUS, SHADOW, DAUTHI, RIP, ARTIST, OPPORTUNIST, ABOMINATION, CELEBRANT, MUTAVAULT, COPTER, PARHELION, JACE })
      .map(([k, c]) => [k, classifyCard(c)]));
    expect(row).toEqual({ WRATH: "native-spell", DAY: "native-spell", VENGEANCE: "native-spell", PURIFY: "native-spell", DISK: "native-activated",
      BLOOD_MONEY: "native-spell", CULLING: "native-spell", EDICT: "native-spell", SHEOLDRED: "native-spell", SOUL_SHATTER: "native-spell", BARTER: "native-spell",
      REALITY_SHIFT: "native-spell", DOWNFALL: "native-spell", UMBRA: "native-aura", WARD: "native-aura", WALLS: "native-static", BOA: "native-activated",
      TROLL: "native-activated", PROGENITUS: "native-body", SHADOW: "native-mixed", DAUTHI: "native-mixed", RIP: "native-mixed", ARTIST: "native-trigger",
      OPPORTUNIST: "native-trigger", ABOMINATION: "native-trigger", CELEBRANT: "native-trigger", MUTAVAULT: "land", COPTER: "native-trigger",
      PARHELION: "native-trigger", JACE: "native-planeswalker" });
  });

  it("parse: the wipes are one destroy atom each; Wrath carries the rider, Blood Money prints none", () => {
    const prog = (c) => { const p = parseEffectProgram(c); return { confidence: programConfidence(p), atoms: p.atoms }; };
    expect({ wrath: prog(WRATH), day: prog(DAY), vengeance: prog(VENGEANCE), purify: prog(PURIFY), bloodMoney: prog(BLOOD_MONEY) }).toEqual({
      wrath: { confidence: "high", atoms: [{ op: "destroy", targetType: "eachCreature", cannotRegenerate: true }] },
      day: { confidence: "high", atoms: [{ op: "destroy", targetType: "eachCreature" }] },
      vengeance: { confidence: "high", atoms: [{ op: "destroy", targetType: "eachArtifactCreatureOrEnchantment" }] },
      purify: { confidence: "high", atoms: [{ op: "destroy", targetType: "eachArtifactOrEnchantment" }] },
      bloodMoney: { confidence: "high", atoms: [{ op: "mass-destroy-treasure-per-nontoken", targetType: "eachCreature" }] },
    });
  });

  it("SYNTHETIC (the rider stamp): Blood Money's op takes the 'can't be regenerated' stamp a destroy takes", () => {
    const p = parseEffectProgram(BLOOD_MONEY_WITH_RIDER);
    expect({ confidence: programConfidence(p), atoms: p.atoms }).toEqual({ confidence: "high",
      atoms: [{ op: "mass-destroy-treasure-per-nontoken", targetType: "eachCreature", cannotRegenerate: true }] });
  });
});

describe("⭐ one event — every destruction replacement is read from the board as the destruction began", () => {
  it("⭐ a lord destroyed in the same Wrath still makes the others indestructible (CR 702.12b), in either battlefield order", () => {
    const run = (order) => {
      const walls = P("walls", WALLS), bears = P("ub", BEARS);
      const s = cast(board({ user: order === "lordFirst" ? [walls, bears] : [bears, walls], ai: [P("ab", BEARS, "ai")], hand: [H("wrath", WRATH)], pool: { W: 4 } }), "wrath");
      return { battlefield: s.players.user.battlefield.map((p) => p.id), userGraveyard: names(s.players.user.graveyard), aiGraveyard: names(s.players.ai.graveyard) };
    };
    const want = { battlefield: ["ub"], userGraveyard: ["The Walls of Ba Sing Se", "Wrath of God"], aiGraveyard: ["Grizzly Bears"] };
    expect({ lordFirst: run("lordFirst"), lordLast: run("lordLast") }).toEqual({ lordFirst: want, lordLast: want });
  });

  it("⭐ umbra armor in Purify (CR 702.89a): the artifact creature stays with its damage removed, the Aura goes to the graveyard once — in either order", () => {
    const run = (order) => {
      const mem = P("mem", MEMNITE, "user", { damageMarked: 1 }), umb = P("umb", UMBRA);
      let s = attach(board({ user: [...(order === "auraFirst" ? [umb, mem] : [mem, umb]), P("artist", ARTIST)], hand: [H("pur", PURIFY)], pool: { W: 5 } }), "umb", "mem");
      s = cast(s, "pur");
      const m = perm(s, "mem");
      return { memnite: m ? { damage: m.damageMarked, attachments: m.attachments } : null, umbras: count(s.players.user.graveyard, "Hyena Umbra"), artist: triggersOf(s, "Blood Artist") };
    };
    const want = { memnite: { damage: 0, attachments: [] }, umbras: 1, artist: 0 };
    expect({ auraFirst: run("auraFirst"), hostFirst: run("hostFirst") }).toEqual({ auraFirst: want, hostFirst: want });
  });

  it("⭐ an indestructible-granting Aura destroyed in the same Purify still protects its host — in either order", () => {
    const run = (order) => {
      const mem = P("mem", MEMNITE), ward = P("ward", WARD);
      const s = cast(attach(board({ user: order === "auraFirst" ? [ward, mem] : [mem, ward], hand: [H("pur", PURIFY)], pool: { W: 5 } }), "ward", "mem"), "pur");
      return { battlefield: s.players.user.battlefield.map((p) => p.id), graveyard: names(s.players.user.graveyard) };
    };
    const want = { battlefield: ["mem"], graveyard: ["Purify", "Timely Ward"] };
    expect({ auraFirst: run("auraFirst"), hostFirst: run("hostFirst") }).toEqual({ auraFirst: want, hostFirst: want });
  });

  it("⭐ Culling Ritual (battlefield order): its \"destroyed this way\" count and its destroy agree — the umbra's host stays, in either order", () => {
    const run = (order) => {
      const mem = P("mem", MEMNITE, "user", { damageMarked: 1 }), umb = P("umb", UMBRA);
      let s = attach(board({ user: [...(order === "auraFirst" ? [umb, mem] : [mem, umb]), P("ub", BEARS)], hand: [H("cr", CULLING)], pool: { B: 2, G: 2 } }), "umb", "mem");
      s = cast(s, "cr");
      const m = perm(s, "mem");
      const counted = (s.log || []).find((e) => e.effect === "mass-destroy-add-mana-per-destroyed")?.destroyed;
      return { memnite: m ? { damage: m.damageMarked } : null, graveyard: names(s.players.user.graveyard), counted };
    };
    // Destroyed this way: the umbra (in its host's place) and the Bears — two, and the destroy destroys exactly those two.
    const want = { memnite: { damage: 0 }, graveyard: ["Culling Ritual", "Grizzly Bears", "Hyena Umbra"], counted: 2 };
    expect({ auraFirst: run("auraFirst"), hostFirst: run("hostFirst") }).toEqual({ auraFirst: want, hostFirst: want });
  });

  it("Akroma's Vengeance: the umbra's host survives undamaged, the umbra goes once, Blood Artist sees only its own death", () => {
    let s = attach(board({ user: [P("ub", BEARS, "user", { damageMarked: 2 }), P("umb", UMBRA), P("artist", ARTIST)], hand: [H("av", VENGEANCE)], pool: { W: 6 } }), "umb", "ub");
    s = cast(s, "av");
    expect({ bears: perm(s, "ub")?.damageMarked, graveyard: names(s.players.user.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s), errors: errors(s).length })
      .toEqual({ bears: 0, graveyard: ["Akroma's Vengeance", "Blood Artist", "Hyena Umbra"], artist: 1, died: { user: 1, ai: 0 }, errors: 0 });
  });

  it("Nevinyrral's Disk (its own activation): the same event — the Disk goes too, the umbra once, the host stays", () => {
    let s = attach(board({ user: [P("disk", DISK), P("ub", BEARS), P("umb", UMBRA), P("artist", ARTIST)], pool: { C: 1 } }), "umb", "ub");
    s = activate(s, "disk");
    expect({ battlefield: s.players.user.battlefield.map((p) => p.id), graveyard: names(s.players.user.graveyard), artist: triggersOf(s, "Blood Artist") })
      .toEqual({ battlefield: ["ub"], graveyard: ["Blood Artist", "Hyena Umbra", "Nevinyrral's Disk"], artist: 1 });
  });

  it("regeneration (CR 701.19a): Day of Judgment — the shield is used, the damage removed, the creature tapped; Wrath's rider (CR 701.19c) lets nothing regenerate", () => {
    const shielded = () => {
      const s = activate(board({ user: [P("troll", TROLL, "user", { damageMarked: 1 })], hand: [H("day", DAY), H("wrath", WRATH)], pool: { G: 1 } }), "troll");
      return withPool(s, "user", { W: 4 });
    };
    const before = perm(shielded(), "troll");
    const day = cast(shielded(), "day");
    const t = perm(day, "troll");
    const wrath = cast(shielded(), "wrath");
    expect({ shieldsBefore: before.regenShields, day: t && { tapped: t.tapped, damage: t.damageMarked, shields: t.regenShields }, wrathGraveyard: names(wrath.players.user.graveyard) })
      .toEqual({ shieldsBefore: 1, day: { tapped: true, damage: 0, shields: 0 }, wrathGraveyard: ["Horned Troll", "Wrath of God"] });
  });

  it("a shield counter (CR 122.1c) is removed instead — not tapped — even by Wrath's rider", () => {
    const s = cast(board({ user: [P("ub", BEARS, "user", { counters: { shield: 1 } })], hand: [H("wrath", WRATH)], pool: { W: 4 } }), "wrath");
    const b = perm(s, "ub");
    expect(b && { tapped: b.tapped, counters: b.counters }).toEqual({ tapped: false, counters: {} });
  });

  it("⭐ Misery's Shadow destroyed in the same Wrath still exiles the opponents' creatures (CR 614.1): they never died", () => {
    const s = cast(board({ user: [P("shadow", SHADOW)], ai: [P("ab", BEARS, "ai"), P("aartist", ARTIST, "ai")], hand: [H("wrath", WRATH)], pool: { W: 4 } }), "wrath");
    // The opponent's Blood Artist was exiled, not killed — but it left in the same event, so it still sees the one creature that
    // did die (CR 603.10a): Misery's Shadow.
    const exiledLog = (s.log || []).filter((e) => e.kind === "creature-exiled-instead" && e.via === "destroy").map((e) => e.cardName).sort();
    expect({ aiExile: names(s.players.ai.exile), aiGraveyard: names(s.players.ai.graveyard), userGraveyard: names(s.players.user.graveyard), aiArtist: triggersOf(s, "Blood Artist"), died: died(s), exiledLog })
      .toEqual({ aiExile: ["Blood Artist", "Grizzly Bears"], aiGraveyard: [], userGraveyard: ["Misery's Shadow", "Wrath of God"], aiArtist: 1, died: { user: 1, ai: 0 },
        exiledLog: ["Blood Artist", "Grizzly Bears"] });
  });

  it("⭐ Dauthi Voidwalker destroyed in the same Wrath still exiles the opponent's card with a void counter", () => {
    const s = cast(board({ user: [P("dauthi", DAUTHI)], ai: [P("ab", BEARS, "ai")], hand: [H("wrath", WRATH)], pool: { W: 4 } }), "wrath");
    expect({ aiExile: s.players.ai.exile.map((c) => [c.name, !!c._voidCounter]), aiGraveyard: names(s.players.ai.graveyard), userGraveyard: names(s.players.user.graveyard), died: died(s) })
      .toEqual({ aiExile: [["Grizzly Bears", true]], aiGraveyard: [], userGraveyard: ["Dauthi Voidwalker", "Wrath of God"], died: { user: 1, ai: 0 } });
  });

  it("⭐ Rest in Peace destroyed in the same Purify still exiles the rest of the event: the opponent's Memnite never died", () => {
    const s = cast(board({ user: [P("rip", RIP)], ai: [P("am", MEMNITE, "ai"), P("aartist", ARTIST, "ai")], hand: [H("pur", PURIFY)], pool: { W: 5 } }), "pur");
    expect({ aiExile: names(s.players.ai.exile), aiGraveyard: names(s.players.ai.graveyard), userExile: names(s.players.user.exile), aiArtist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ aiExile: ["Memnite"], aiGraveyard: [], userExile: ["Rest in Peace"], aiArtist: 0, died: { user: 0, ai: 0 } });
  });

  it("an umbra that also carries a shield counter: the event completes and the host stays (the Aura's own fate is the umbra-armor simplification, unpinned)", () => {
    const mem = P("mem", MEMNITE), umb = P("umb", UMBRA, "user", { counters: { shield: 1 } });
    const s = cast(attach(board({ user: [mem, umb], hand: [H("pur", PURIFY)], pool: { W: 5 } }), "umb", "mem"), "pur");
    expect({ host: !!perm(s, "mem"), errors: errors(s).length, purifyResolved: count(s.players.user.graveyard, "Purify") }).toEqual({ host: true, errors: 0, purifyResolved: 1 });
  });
});

describe("⭐ the death events agree with where the card went (CR 700.4)", () => {
  it("⭐ Wrath of God on Progenitus: shuffled into its owner's library, so Blood Artist sees one death — its own", () => {
    const s = cast(board({ user: [P("prog", PROGENITUS), P("artist", ARTIST)], hand: [H("wrath", WRATH)], pool: { W: 4 } }), "wrath");
    expect({ inLibrary: count(s.players.user.library, "Progenitus"), graveyard: names(s.players.user.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ inLibrary: 1, graveyard: ["Blood Artist", "Wrath of God"], artist: 1, died: { user: 1, ai: 0 } });
  });

  it("⭐ a batch watcher sees no death either: Morbid Opportunist (saved by its umbra) draws nothing off a Progenitus shuffled away", () => {
    const s = cast(attach(board({ user: [P("opp", OPPORTUNIST), P("umb", UMBRA), P("prog", PROGENITUS)], hand: [H("wrath", WRATH)], pool: { W: 4 } }), "umb", "opp"), "wrath");
    expect({ opportunist: !!perm(s, "opp"), progenitusInLibrary: count(s.players.user.library, "Progenitus"), draws: triggersOf(s, "Morbid Opportunist"), died: died(s) })
      .toEqual({ opportunist: true, progenitusInLibrary: 1, draws: 0, died: { user: 0, ai: 0 } });
  });

  it("⭐ a FACE-DOWN Progenitus (manifested by Reality Shift) is shuffled away too — its real card decides (CR 400.6)", () => {
    let s = board({ user: [P("artist", ARTIST)], ai: [P("ab", BEARS, "ai")], hand: [H("rs", REALITY_SHIFT), H("wrath", WRATH)], pool: { U: 2 },
      aiLibrary: [{ ...PROGENITUS, id: "ai-prog" }, { ...BEARS, id: "ai-lib2" }] });
    s = cast(s, "rs", (a) => a.targets?.[0]?.id === "ab");
    const manifested = s.players.ai.battlefield.filter((p) => p.faceDown).map((p) => p.faceUpCard?.name);
    s = cast(withPool(s, "user", { W: 4 }), "wrath");
    expect({ manifested, aiLibrary: names(s.players.ai.library), aiGraveyard: names(s.players.ai.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ manifested: ["Progenitus"], aiLibrary: ["Grizzly Bears", "Progenitus"], aiGraveyard: [], artist: 1, died: { user: 1, ai: 0 } });
  });

  it("⭐ the lethal-damage state-based action reads the same card: a face-down Progenitus dealt lethal damage is shuffled away, no death", () => {
    let s = board({ user: [P("artist", ARTIST)], aiLibrary: [{ ...PROGENITUS, id: "ai-prog" }] });
    s = manifestCard(s, "ai", s.players.ai.library[0]);
    const fd = s.players.ai.battlefield.find((p) => p.faceDown);
    s = { ...s, players: { ...s.players, ai: { ...s.players.ai, battlefield: s.players.ai.battlefield.map((p) => (p.id === fd.id ? { ...p, damageMarked: 2 } : p)) } } };
    const r = destroyLethalCreatures(s);
    const out = flushTriggers(checkDiesTriggers(r.state, r.dead), { chooseTargets: chooseTriggerTargets });
    expect({ dead: r.dead.map((d) => ({ shuffledInstead: d.shuffledInstead })), aiLibrary: names(out.players.ai.library), artist: triggersOf(out, "Blood Artist"), died: died(out) })
      .toEqual({ dead: [{ shuffledInstead: true }], aiLibrary: ["Progenitus"], artist: 0, died: { user: 0, ai: 0 } });
  });

  it("⭐ a SACRIFICED Progenitus (Diabolic Edict) is shuffled away: no death", () => {
    const s = cast(board({ user: [P("artist", ARTIST)], ai: [P("aprog", PROGENITUS, "ai")], hand: [H("edict", EDICT)], pool: { B: 2 } }), "edict", (a) => a.targets?.[0]?.id === "ai");
    expect({ aiLibrary: count(s.players.ai.library, "Progenitus"), aiGraveyard: names(s.players.ai.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ aiLibrary: 1, aiGraveyard: [], artist: 0, died: { user: 0, ai: 0 } });
  });

  it("a sacrificed creature granted 'When this creature dies, exile it' dies, then is exiled — the look-back the sacrifice builds is the shared one", () => {
    const s = cast(board({ user: [P("artist", ARTIST)], ai: [P("ab", BEARS, "ai", { grantDiesExile: true })], hand: [H("edict", EDICT)], pool: { B: 2 } }), "edict", (a) => a.targets?.[0]?.id === "ai");
    expect({ aiExile: names(s.players.ai.exile), aiGraveyard: names(s.players.ai.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ aiExile: ["Grizzly Bears"], aiGraveyard: [], artist: 1, died: { user: 0, ai: 1 } });
  });

  it("Rest in Peace stays put through a Wrath: everything is exiled, nothing died (regression)", () => {
    const s = cast(board({ user: [P("rip", RIP), P("artist", ARTIST)], ai: [P("ab", BEARS, "ai")], hand: [H("wrath", WRATH)], pool: { W: 4 } }), "wrath");
    expect({ userExile: names(s.players.user.exile), aiExile: names(s.players.ai.exile), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ userExile: ["Blood Artist", "Wrath of God"], aiExile: ["Grizzly Bears"], artist: 0, died: { user: 0, ai: 0 } });
  });
});

describe("⭐ the look-back is the permanent as it last existed (CR 603.10a) — a creature by its layers, not its printed card", () => {
  it("⭐ an animated Mutavault destroyed by Wrath died as a creature: Blood Artist sees two deaths", () => {
    let s = animate(board({ user: [P("mv", MUTAVAULT), P("artist", ARTIST)], hand: [H("wrath", WRATH)] }), "mv");
    const animated = permanentIsCreature(s, "mv");
    s = cast(withPool(s, "user", { W: 4 }), "wrath");
    expect({ animated, graveyard: names(s.players.user.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ animated: true, graveyard: ["Blood Artist", "Mutavault", "Wrath of God"], artist: 2, died: { user: 2, ai: 0 } });
  });

  it("⭐ a batch watcher counts it too: Morbid Opportunist (saved by its umbra) draws off the animated Mutavault alone dying", () => {
    let s = attach(board({ user: [P("opp", OPPORTUNIST), P("umb", UMBRA), P("mv", MUTAVAULT)], hand: [H("wrath", WRATH)] }), "umb", "opp");
    s = cast(withPool(animate(s, "mv"), "user", { W: 4 }), "wrath");
    expect({ opportunist: !!perm(s, "opp"), graveyard: names(s.players.user.graveyard), draws: triggersOf(s, "Morbid Opportunist"), died: died(s) })
      .toEqual({ opportunist: true, graveyard: ["Hyena Umbra", "Mutavault", "Wrath of God"], draws: 1, died: { user: 1, ai: 0 } });
  });

  it("⭐ a crewed Smuggler's Copter destroyed by Wrath died as a creature", () => {
    let s = crew(board({ user: [P("copter", COPTER), P("ub", BEARS), P("artist", ARTIST)], hand: [H("wrath", WRATH)], pool: { W: 4 } }), "copter");
    const crewed = permanentIsCreature(s, "copter");
    s = cast(s, "wrath");
    expect({ crewed, graveyard: names(s.players.user.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ crewed: true, graveyard: ["Blood Artist", "Grizzly Bears", "Smuggler's Copter", "Wrath of God"], artist: 3, died: { user: 3, ai: 0 } });
  });

  it("a destroyed planeswalker dies too (CR 700.4): Hero's Downfall on Jace Beleren — Cruel Celebrant sees it, once", () => {
    const s = cast(board({ ai: [P("ajace", JACE, "ai", { counters: { loyalty: 3 } }), P("acc", CELEBRANT, "ai")], hand: [H("hd", DOWNFALL)], pool: { B: 3 } }), "hd", (a) => a.targets?.[0]?.id === "ajace");
    expect({ aiGraveyard: names(s.players.ai.graveyard), celebrant: triggersOf(s, "Cruel Celebrant"), died: died(s) })
      .toEqual({ aiGraveyard: ["Jace Beleren"], celebrant: 1, died: { user: 0, ai: 0 } });
  });

  it("an UNcrewed Copter destroyed by Akroma's Vengeance was an artifact, not a creature: no creature death for it", () => {
    const s = cast(board({ user: [P("copter", COPTER), P("artist", ARTIST)], hand: [H("av", VENGEANCE)], pool: { W: 6 } }), "av");
    expect({ graveyard: names(s.players.user.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ graveyard: ["Akroma's Vengeance", "Blood Artist", "Smuggler's Copter"], artist: 1, died: { user: 1, ai: 0 } });
  });

  // The opponent animates its Mutavault in its own turn; the user answers with an instant.
  const aiAnimated = (ai, hand, user = []) => animate(board({ active: "ai", user, ai, hand }), "amv", "ai");

  it("⭐ Diabolic Edict: an opponent's animated Mutavault is the creature it takes, and it died as one", () => {
    let s = aiAnimated([P("amv", MUTAVAULT, "ai")], [H("edict", EDICT)], [P("artist", ARTIST)]);
    s = cast(withPool(s, "user", { B: 2 }), "edict", (a) => a.targets?.[0]?.id === "ai");
    expect({ aiBattlefield: s.players.ai.battlefield.map((p) => p.id), aiGraveyard: names(s.players.ai.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ aiBattlefield: [], aiGraveyard: ["Mutavault"], artist: 1, died: { user: 0, ai: 1 } });
  });

  it("⭐ Diabolic Edict with a real choice: the animated Mutavault is offered beside the Bears, and chosen, it dies as a creature", () => {
    let s = aiAnimated([P("amv", MUTAVAULT, "ai"), P("ab", BEARS, "ai")], [H("edict", EDICT)], [P("artist", ARTIST)]);
    s = cast(withPool(s, "user", { B: 2 }), "edict", (a) => a.targets?.[0]?.id === "ai");
    const offer = { controller: s.pendingChoice?.controller, candidates: (s.pendingChoice?.candidates || []).map((c) => c.id).sort() };
    const settled = finalizeStackResolution(resolveSacrificeChoice(s, "amv"));
    expect({ offer, aiBattlefield: settled.players.ai.battlefield.map((p) => p.id), artist: triggersOf(settled, "Blood Artist"), died: died(settled) })
      .toEqual({ offer: { controller: "ai", candidates: ["ab", "amv"] }, aiBattlefield: ["ab"], artist: 1, died: { user: 0, ai: 1 } });
  });

  it("⭐ Sheoldred's Edict (a nontoken creature) and Soul Shatter (a creature or planeswalker) take an animated Mutavault too", () => {
    const run = (card, id, pool, pick = () => true) => {
      let s = aiAnimated([P("amv", MUTAVAULT, "ai")], [H(id, card)]);
      s = cast(withPool(s, "user", pool), id, pick);
      return { aiGraveyard: names(s.players.ai.graveyard), died: died(s).ai };
    };
    expect({ sheoldred: run(SHEOLDRED, "she", { B: 2 }, (a) => a.chosenMode === 0 || (Array.isArray(a.chosenMode) && a.chosenMode[0] === 0)), soulShatter: run(SOUL_SHATTER, "ss", { B: 3 }) })
      .toEqual({ sheoldred: { aiGraveyard: ["Mutavault"], died: 1 }, soulShatter: { aiGraveyard: ["Mutavault"], died: 1 } });
  });

  it("⭐ Barter in Blood (one sacrifice event): an animated Mutavault is among the deaths Blood Artist sees", () => {
    let s = animate(board({ user: [P("mv", MUTAVAULT), P("artist", ARTIST)], ai: [P("ab1", BEARS, "ai"), P("ab2", BEARS, "ai")], hand: [H("bb", BARTER)] }), "mv");
    s = cast(withPool(s, "user", { B: 4 }), "bb");
    expect({ userGraveyard: names(s.players.user.graveyard), artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ userGraveyard: ["Barter in Blood", "Blood Artist", "Mutavault"], artist: 4, died: { user: 2, ai: 2 } });
  });

  it("⭐ 'Whenever you sacrifice a creature' sees the animated Mutavault as a creature (the sacrifice look-back)", () => {
    let s = animate(board({ user: [P("abom", ABOMINATION), P("mv", MUTAVAULT)], hand: [H("edict", EDICT)] }), "mv");
    s = cast(withPool(s, "user", { B: 2 }), "edict", (a) => a.targets?.[0]?.id === "user");
    const offer = (s.pendingChoice?.candidates || []).map((c) => c.id).sort();
    const settled = finalizeStackResolution(resolveSacrificeChoice(s, "mv"));
    expect({ offer, battlefield: settled.players.user.battlefield.map((p) => p.id), draws: triggersOf(settled, "Smothering Abomination") })
      .toEqual({ offer: ["abom", "mv"], battlefield: ["abom"], draws: 1 });
  });

  it("⭐ the same in one sacrifice EVENT: Barter in Blood — the user gives up the animated Mutavault and the Bears, the Abomination draws twice", () => {
    let s = animate(board({ user: [P("abom", ABOMINATION), P("mv", MUTAVAULT), P("ub", BEARS)], ai: [P("ab1", BEARS, "ai"), P("ab2", BEARS, "ai")], hand: [H("bb", BARTER)] }), "mv");
    s = cast(withPool(s, "user", { B: 4 }), "bb");
    const offer = { controller: s.pendingChoice?.controller, candidates: (s.pendingChoice?.candidates || []).map((c) => c.id).sort() };
    s = resolveSacrificeChoice(s, "mv");
    s = finalizeStackResolution(resolveSacrificeChoice(s, "ub"));
    expect({ offer, battlefield: s.players.user.battlefield.map((p) => p.id), draws: triggersOf(s, "Smothering Abomination") })
      .toEqual({ offer: { controller: "user", candidates: ["abom", "mv", "ub"] }, battlefield: ["abom"], draws: 2 });
  });

  it("⭐ Blood Money: an animated Mutavault is a nontoken creature destroyed this way — a Treasure for it", () => {
    let s = animate(board({ user: [P("mv", MUTAVAULT)], ai: [P("ab", BEARS, "ai")], hand: [H("bm", BLOOD_MONEY)] }), "mv");
    s = cast(withPool(s, "user", { B: 7 }), "bm");
    const treasures = s.players.user.battlefield.filter((p) => p.card?.name === "Treasure");
    expect({ treasures: treasures.length, tapped: treasures.every((p) => p.tapped), graveyard: names(s.players.user.graveyard) })
      .toEqual({ treasures: 2, tapped: true, graveyard: ["Blood Money", "Mutavault"] });
  });

  it("⭐ the legend rule (CR 704.5j): a crewed Parhelion II put into the graveyard by a second copy died as a creature", () => {
    let s = crew(board({ user: [P("ph1", PARHELION), P("ub1", BEARS), P("ub2", BEARS), P("artist", ARTIST)], hand: [H("ph2", PARHELION)], pool: { W: 8 } }), "ph1");
    const crewed = permanentIsCreature(s, "ph1");
    s = cast(s, "ph2");
    expect({ crewed, battlefield: s.players.user.battlefield.map((p) => (p.id === "ph1" ? "the crewed one" : p.card.name)).sort(), graveyard: names(s.players.user.graveyard),
      artist: triggersOf(s, "Blood Artist"), died: died(s) })
      .toEqual({ crewed: true, battlefield: ["Blood Artist", "Grizzly Bears", "Grizzly Bears", "Parhelion II"], graveyard: ["Parhelion II"], artist: 1, died: { user: 1, ai: 0 } });
  });
});

describe("Blood Money prints no rider: regeneration saves a creature from it", () => {
  const regenerating = (card) => {
    const s = activate(board({ user: [P("troll", TROLL)], ai: [P("ab", BEARS, "ai")], hand: [H("bm", card)], pool: { G: 1 } }), "troll");
    return cast(withPool(s, "user", { B: 7 }), "bm");
  };
  it("the printed card: the Troll regenerates (tapped) and is not destroyed this way — one Treasure, for the Bears", () => {
    const s = regenerating(BLOOD_MONEY);
    expect({ troll: perm(s, "troll") && { tapped: perm(s, "troll").tapped }, treasures: s.players.user.battlefield.filter((p) => p.card?.name === "Treasure").length })
      .toEqual({ troll: { tapped: true }, treasures: 1 });
  });
  it("SYNTHETIC (the rider stamp at runtime): with the rider, the Troll can't regenerate — destroyed this way, two Treasures", () => {
    const s = regenerating(BLOOD_MONEY_WITH_RIDER);
    expect({ troll: !!perm(s, "troll"), treasures: s.players.user.battlefield.filter((p) => p.card?.name === "Treasure").length }).toEqual({ troll: false, treasures: 2 });
  });
});

describe("one ladder — the destroy effect and the lethal-damage state-based action read the same replacements", () => {
  // Four creatures, one saver each: indestructible through an Aura, a shield counter, a regeneration shield (the Troll's own
  // activation), umbra armor. Damage, when wanted, is marked AFTER the activation resolves (its resolution runs the
  // state-based actions itself).
  const savers = () => {
    let s = board({ user: [P("w", BEARS), P("ward", WARD), P("sh", BEARS, "user", { counters: { shield: 1 } }), P("troll", TROLL), P("u", BEARS), P("umb", UMBRA)],
      hand: [H("day", DAY)], pool: { G: 1 } });
    s = attach(attach(s, "ward", "w"), "umb", "u");
    return withPool(activate(s, "troll"), "user", { W: 4 });
  };
  const lethal = (s) => ({ ...s, players: { ...s.players, user: { ...s.players.user, battlefield: s.players.user.battlefield.map((p) =>
    (["w", "sh", "troll"].includes(p.id) ? { ...p, damageMarked: 2 } : p.id === "u" ? { ...p, damageMarked: 3 } : p)) } } });
  const after = (s) => ({
    battlefield: s.players.user.battlefield.map((p) => p.id).sort(), graveyard: names(s.players.user.graveyard).filter((n) => n !== "Day of Judgment"),
    shield: perm(s, "sh")?.counters?.shield ?? 0, trollTapped: perm(s, "troll")?.tapped, damage: ["w", "sh", "troll", "u"].map((id) => perm(s, id)?.damageMarked),
  });

  it("destructionReplacementFor names each saver; the rider removes only the regeneration", () => {
    const s = savers();
    const p = (id) => perm(s, id);
    expect({ ward: destructionReplacementFor(s, p("w")), shield: destructionReplacementFor(s, p("sh")), regen: destructionReplacementFor(s, p("troll")),
      regenWithRider: destructionReplacementFor(s, p("troll"), true), umbra: destructionReplacementFor(s, p("u")), none: destructionReplacementFor(s, p("ward")) })
      .toEqual({ ward: { kind: "indestructible" }, shield: { kind: "shield" }, regen: { kind: "regenerate" }, regenWithRider: null, umbra: { kind: "umbraArmor", auraId: "umb" }, none: null });
  });

  it("⭐ lethal damage (CR 704.5g) and Day of Judgment save the same four, the same way", () => {
    const sba = after(destroyLethalCreatures(lethal(savers())).state);
    const day = after(cast(savers(), "day"));
    // Kept apart from the comparison: the marked damage. Indestructible keeps it (the creature was never destroyed); a shield
    // counter replaces the destruction without removing damage (CR 122.1c); regeneration (CR 701.19a) and umbra armor
    // (CR 702.89a) remove it. Day of Judgment's board carried none.
    expect({ sba: { ...sba, damage: undefined }, day: { ...day, damage: undefined }, sbaDamage: sba.damage, dayDamage: day.damage }).toEqual({
      sba: { battlefield: ["sh", "troll", "u", "w", "ward"], graveyard: ["Hyena Umbra"], shield: 0, trollTapped: true, damage: undefined },
      day: { battlefield: ["sh", "troll", "u", "w", "ward"], graveyard: ["Hyena Umbra"], shield: 0, trollTapped: true, damage: undefined },
      sbaDamage: [2, 2, 0, 0], dayDamage: [0, 0, 0, 0] });
  });

  it("⭐ the lethal-damage action meets a creature carrier of a graveyard replacement as the event began: Dauthi's opponent's card is exiled", () => {
    const s = board({ user: [P("dauthi", DAUTHI, "user", { damageMarked: 2 })], ai: [P("ab", BEARS, "ai", { damageMarked: 2 })] });
    const r = destroyLethalCreatures(s);
    expect({ aiExile: r.state.players.ai.exile.map((c) => [c.name, !!c._voidCounter]), aiGraveyard: names(r.state.players.ai.graveyard), userGraveyard: names(r.state.players.user.graveyard) })
      .toEqual({ aiExile: [["Grizzly Bears", true]], aiGraveyard: [], userGraveyard: ["Dauthi Voidwalker"] });
  });
});
