/**
 * EVERY CREATURE TYPE OFF THE BATTLEFIELD — the play-weighted program, P·39b: Maskwood Nexus (EDHREC #490).
 *
 *   Maskwood Nexus: "Creatures you control are every creature type. The same is true for creature spells you control and creature
 *   cards you own that aren't on the battlefield."
 *
 * The first sentence is a layer-4 static (CR 613.1d) — staticAbilityParser's allCreatureTypes arm, a DYNAMIC effect on the
 * creatures its controller controls, read by layers.permIsEveryCreatureType like P·39a's fixed effects (the derive) and, without
 * recursion, by effectiveTypeIdentity for the selectors. The second sentence is everyCreatureType.cardIsEveryCreatureType: a
 * creature SPELL its controller controls, or a creature CARD its owner owns in a hand, a library, a graveyard or the command zone.
 * Changeling (CR 702.73a) answers the same question in every zone. Only a creature takes a creature type (CR 205.3d).
 *
 * Every reader that asks a spell's or a card's creature type asks it: the tutors and digs (Kinnan's "non-Human creature card" — a
 * NEGATED reader, which would otherwise put a Human onto the battlefield), the graveyard filters (Overlord of the Balemurk's
 * "non-Avatar creature card"), the cast triggers, the cost reducers, flash and cast-from-top permissions, Root Sliver, the spend
 * restrictions (Cavern of Souls), Path of Ancestry, the reveal lands and reveal costs, the enters-with-counter statics, Essence Flux,
 * the graveyard counts and conditions, and the look-back of a creature that died.
 *
 * Real oracle fixtures (bundled Scryfall, the 2026-10-01 data, generated by cardIndex.publicCard — never typed by hand). Each
 * witness is a pair or more: the plain answer, the answer under Maskwood Nexus, and where it matters the answer under an
 * OPPONENT's Maskwood (whose grant reaches only its own controller's objects).
 */
import { describe, it, expect, beforeEach } from "vitest";
import { createGameState, createPermanent, _resetIdsForTests } from "./gameState.js";
import { permIsEveryCreatureType, deriveCharacteristics, permanentHasKeyword, addContinuousEffect } from "./layers.js";
import { cardIsEveryCreatureType, grantsEveryCreatureType } from "./everyCreatureType.js";
import { classifyCard } from "./coverage.js";
import { parseStaticAbilities, stackSpellIsUncounterable } from "./staticAbilityParser.js";
import { parseEffectClause, parseEffectProgram } from "./effects/parser.js";
import { parseActivatedAbilities } from "./effects/abilities.js";
import { detectTriggers, checkCastTriggers, checkDiesTriggers } from "./triggers.js";
import { applyTutor, applyImpulseDigAtom, applyLookTopTakeAtom, applyChosenTypeRevealToHand, applyRevealPutFiltered } from "./effects/atoms/library.js";
import { autoPickTutorCandidate } from "./effects/runProgram.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { resolveTopOfStack } from "./gameEngine.js";
import { evaluateInterveningIf } from "./interveningIf.js";
import { revealLandEntersTapped } from "./landEntersTapped.js";
import { applyReturnFromGraveyardPick } from "./effects/atoms/zones.js";
import { enumerateTargets } from "./spellEffects.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (oracle verified against bundled Scryfall data) ──────────
const MASKWOOD = {"name":"Maskwood Nexus","type":"Artifact","mana":"{4}","cmc":4,"keywords":[],"colors":[],"oracle":"Creatures you control are every creature type. The same is true for creature spells you control and creature cards you own that aren't on the battlefield.\n{3}, {T}: Create a 2/2 blue Shapeshifter creature token with changeling. (It is every creature type.)"}; // native-mixed
const ARCANE_ADAPTATION = {"name":"Arcane Adaptation","type":"Enchantment","mana":"{2}{U}","cmc":3,"keywords":[],"colors":["U"],"oracle":"As this enchantment enters, choose a creature type.\nCreatures you control are the chosen type in addition to their other types. The same is true for creature spells you control and creature cards you own that aren't on the battlefield."}; // body-only
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const OUTCAST = {"name":"Changeling Outcast","type":"Creature — Shapeshifter","mana":"{B}","cmc":1,"power":"1","toughness":"1","keywords":["Changeling"],"colors":["B"],"oracle":"Changeling (This card is every creature type.)\nThis creature can't block and can't be blocked."}; // native-body
const BELONGING = {"name":"Belonging","type":"Creature — Elemental Incarnation","mana":"{5}{W}","cmc":6,"power":"6","toughness":"6","keywords":["Encore"],"colors":["W"],"oracle":"When this creature enters, create three 1/1 colorless Shapeshifter creature tokens with changeling. (They're every creature type.)\nEncore {6}{W}{W} ({6}{W}{W}, Exile this card from your graveyard: For each opponent, create a token copy that attacks that opponent this turn if able. They gain haste. Sacrifice them at the beginning of the next end step. Activate only as a sorcery.)"}; // native-trigger
const SOL_RING = {"name":"Sol Ring","type":"Artifact","mana":"{1}","cmc":1,"keywords":[],"colors":[],"oracle":"{T}: Add {C}{C}."}; // native-mana
const LEGION = {"name":"Sliver Legion","type":"Legendary Creature — Sliver","mana":"{W}{U}{B}{R}{G}","cmc":5,"power":"7","toughness":"7","keywords":[],"colors":["B","G","R","U","W"],"oracle":"All Sliver creatures get +1/+1 for each other Sliver on the battlefield."}; // native-static
const ISLAND = {"name":"Island","type":"Basic Land — Island","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {U}.)"}; // land
const BONESPLITTER = {"name":"Bonesplitter","type":"Artifact — Equipment","mana":"{1}","cmc":1,"keywords":["Equip"],"colors":[],"oracle":"Equipped creature gets +2/+0.\nEquip {1}"}; // native-equipment
const GOBLIN_MATRON = {"name":"Goblin Matron","type":"Creature — Goblin","mana":"{2}{R}","cmc":3,"power":"1","toughness":"1","keywords":[],"colors":["R"],"oracle":"When this creature enters, you may search your library for a Goblin card, reveal that card, put it into your hand, then shuffle."}; // native-trigger
const STONEFORGE = {"name":"Stoneforge Mystic","type":"Creature — Kor Artificer","mana":"{1}{W}","cmc":2,"power":"1","toughness":"2","keywords":[],"colors":["W"],"oracle":"When this creature enters, you may search your library for an Equipment card, reveal it, put it into your hand, then shuffle.\n{1}{W}, {T}: You may put an Equipment card from your hand onto the battlefield."}; // native-mixed
const KINNAN = {"name":"Kinnan, Bonder Prodigy","type":"Legendary Creature — Human Druid","mana":"{G}{U}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G","U"],"oracle":"Whenever you tap a nonland permanent for mana, add one mana of any type that permanent produced.\n{5}{G}{U}: Look at the top five cards of your library. You may put a non-Human creature card from among them onto the battlefield. Put the rest on the bottom of your library in a random order."}; // native-mixed
const ICON = {"name":"Icon of Ancestry","type":"Artifact","mana":"{3}","cmc":3,"keywords":[],"colors":[],"oracle":"As this artifact enters, choose a creature type.\nCreatures you control of the chosen type get +1/+1.\n{3}, {T}: Look at the top three cards of your library. You may reveal a creature card of the chosen type from among them and put it into your hand. Put the rest on the bottom of your library in a random order."}; // native-mixed
const HERALDS_HORN = {"name":"Herald's Horn","type":"Artifact","mana":"{3}","cmc":3,"keywords":[],"colors":[],"oracle":"As this artifact enters, choose a creature type.\nCreature spells you cast of the chosen type cost {1} less to cast.\nAt the beginning of your upkeep, look at the top card of your library. If it's a creature card of the chosen type, you may reveal it and put it into your hand."}; // native-mixed
const RINGLEADER = {"name":"Goblin Ringleader","type":"Creature — Goblin","mana":"{3}{R}","cmc":4,"power":"2","toughness":"2","keywords":["Haste"],"colors":["R"],"oracle":"Haste (This creature can attack and {T} as soon as it comes under your control.)\nWhen this creature enters, reveal the top four cards of your library. Put all Goblin cards revealed this way into your hand and the rest on the bottom of your library in any order."}; // native-trigger
const WAYFINDER = {"name":"Merfolk Wayfinder","type":"Creature — Merfolk Scout","mana":"{2}{U}","cmc":3,"power":"1","toughness":"2","keywords":["Flying"],"colors":["U"],"oracle":"Flying\nWhen this creature enters, reveal the top three cards of your library. Put all Island cards revealed this way into your hand and the rest on the bottom of your library in any order."}; // native-trigger
const ANCESTORS = {"name":"For the Ancestors","type":"Instant","mana":"{2}{G}","cmc":3,"keywords":["Flashback"],"colors":["G"],"oracle":"Choose a creature type. Look at the top six cards of your library. You may reveal any number of cards of the chosen type from among them and put the revealed cards into your hand. Put the rest on the bottom of your library in a random order.\nFlashback {3}{G} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"}; // native-spell
const GISHATH = {"name":"Gishath, Sun's Avatar","type":"Legendary Creature — Dinosaur Avatar","mana":"{5}{R}{G}{W}","cmc":8,"power":"7","toughness":"6","keywords":["Vigilance","Haste","Trample"],"colors":["G","R","W"],"oracle":"Vigilance, trample, haste\nWhenever Gishath deals combat damage to a player, reveal that many cards from the top of your library. Put any number of Dinosaur creature cards from among them onto the battlefield and the rest on the bottom of your library in a random order."}; // native-trigger
const OVERLORD = {"name":"Overlord of the Balemurk","type":"Enchantment Creature — Avatar Horror","mana":"{3}{B}{B}","cmc":5,"power":"5","toughness":"5","keywords":["Impending","Mill"],"colors":["B"],"oracle":"Impending 5—{1}{B} (If you cast this spell for its impending cost, it enters with five time counters and isn't a creature until the last is removed. At the beginning of your end step, remove a time counter from it.)\nWhenever this permanent enters or attacks, mill four cards, then you may return a non-Avatar creature card or a planeswalker card from your graveyard to your hand."}; // native-trigger
const MANTLE = {"name":"Mantle of the Ancients","type":"Enchantment — Aura","mana":"{3}{W}{W}","cmc":5,"keywords":["Enchant"],"colors":["W"],"oracle":"Enchant creature you control\nWhen this Aura enters, return any number of target Aura and/or Equipment cards from your graveyard to the battlefield attached to enchanted creature.\nEnchanted creature gets +1/+1 for each Aura and Equipment attached to it."}; // native-aura
const BIRTH_RITE = {"name":"Boggart Birth Rite","type":"Kindred Sorcery — Goblin","mana":"{B}","cmc":1,"keywords":[],"colors":["B"],"oracle":"Return target Goblin card from your graveyard to your hand."}; // native-spell
const EXTINCTION = {"name":"Return from Extinction","type":"Sorcery","mana":"{1}{B}","cmc":2,"keywords":[],"colors":["B"],"oracle":"Choose one —\n• Return target creature card from your graveyard to your hand.\n• Return two target creature cards that share a creature type from your graveyard to your hand."}; // native-spell
const FIREBRAND = {"name":"Vengeful Firebrand","type":"Creature — Elemental Warrior","mana":"{3}{R}","cmc":4,"power":"5","toughness":"2","keywords":[],"colors":["R"],"oracle":"This creature has haste as long as a Warrior card is in your graveyard.\n{R}: This creature gets +1/+0 until end of turn."}; // native-mixed
const DAWNHAND = {"name":"Dawnhand Eulogist","type":"Creature — Elf Warlock","mana":"{3}{B}","cmc":4,"power":"3","toughness":"3","keywords":["Menace","Mill"],"colors":["B"],"oracle":"Menace (This creature can't be blocked except by two or more creatures.)\nWhen this creature enters, mill three cards. Then if there is an Elf card in your graveyard, each opponent loses 2 life and you gain 2 life. (To mill three cards, put the top three cards of your library into your graveyard.)"}; // native-trigger
const WARCHIEF = {"name":"Goblin Warchief","type":"Creature — Goblin Warrior","mana":"{1}{R}{R}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["R"],"oracle":"Goblin spells you cast cost {1} less to cast.\nGoblins you control have haste."}; // native-static
const STONYBROOK = {"name":"Stonybrook Banneret","type":"Creature — Merfolk Wizard","mana":"{1}{U}","cmc":2,"power":"1","toughness":"1","keywords":["Landwalk","Islandwalk"],"colors":["U"],"oracle":"Islandwalk (This creature can't be blocked as long as defending player controls an Island.)\nMerfolk spells and Wizard spells you cast cost {1} less to cast."}; // native-static
const HERO_IROAS = {"name":"Hero of Iroas","type":"Creature — Human Soldier","mana":"{1}{W}","cmc":2,"power":"2","toughness":"2","keywords":["Heroic"],"colors":["W"],"oracle":"Aura spells you cast cost {1} less to cast.\nHeroic — Whenever you cast a spell that targets this creature, put a +1/+1 counter on this creature."}; // native-mixed
const INCUBATOR = {"name":"Urza's Incubator","type":"Artifact","mana":"{3}","cmc":3,"keywords":[],"colors":[],"oracle":"As this artifact enters, choose a creature type.\nCreature spells of the chosen type cost {2} less to cast."}; // native-static
const EDGEWALKER = {"name":"Edgewalker","type":"Creature — Human Cleric","mana":"{1}{W}{B}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["B","W"],"oracle":"Cleric spells you cast cost {W}{B} less to cast. This effect reduces only the amount of colored mana you pay. (For example, if you cast a Cleric spell with mana cost {1}{W}, it costs {1} to cast.)"}; // native-static
const MOROPHON = {"name":"Morophon, the Boundless","type":"Legendary Creature — Shapeshifter","mana":"{7}","cmc":7,"power":"6","toughness":"6","keywords":["Changeling"],"colors":[],"oracle":"Changeling (This card is every creature type.)\nAs Morophon enters, choose a creature type.\nSpells of the chosen type you cast cost {W}{U}{B}{R}{G} less to cast. This effect reduces only the amount of colored mana you pay.\nOther creatures you control of the chosen type get +1/+1."}; // native-static
const RATTLECHAINS = {"name":"Rattlechains","type":"Creature — Spirit","mana":"{1}{U}","cmc":2,"power":"2","toughness":"1","keywords":["Flying","Flash"],"colors":["U"],"oracle":"Flash\nFlying\nWhen this creature enters, target Spirit gains hexproof until end of turn.\nYou may cast Spirit spells as though they had flash."}; // native-mixed
const KORLESSA = {"name":"Korlessa, Scale Singer","type":"Legendary Creature — Dragon Bard","mana":"{G}{U}","cmc":2,"power":"1","toughness":"4","keywords":[],"colors":["G","U"],"oracle":"You may look at the top card of your library any time.\nYou may cast Dragon spells from the top of your library."}; // native-static
const ROOT_SLIVER = {"name":"Root Sliver","type":"Creature — Sliver","mana":"{3}{G}","cmc":4,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":"This spell can't be countered.\nSliver spells can't be countered."}; // native-static
const COUNTERSPELL = {"name":"Counterspell","type":"Instant","mana":"{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Counter target spell."}; // native-spell
const HUNTMASTER = {"name":"Lys Alana Huntmaster","type":"Creature — Elf Warrior","mana":"{2}{G}{G}","cmc":4,"power":"3","toughness":"3","keywords":[],"colors":["G"],"oracle":"Whenever you cast an Elf spell, you may create a 1/1 green Elf Warrior creature token."}; // native-trigger
const ARMORY_PALADIN = {"name":"Armory Paladin","type":"Creature — Human Knight","mana":"{1}{R}{W}","cmc":3,"power":"3","toughness":"3","keywords":["Trample"],"colors":["R","W"],"oracle":"Trample\nWhenever you cast an Aura or Equipment spell, exile the top card of your library. You may play that card until the end of your next turn."}; // native-trigger
const ELDER_PINE = {"name":"Elder Pine of Jukai","type":"Creature — Spirit","mana":"{2}{G}","cmc":3,"power":"2","toughness":"1","keywords":["Soulshift"],"colors":["G"],"oracle":"Whenever you cast a Spirit or Arcane spell, reveal the top three cards of your library. Put all land cards revealed this way into your hand and the rest on the bottom of your library in any order.\nSoulshift 2 (When this creature dies, you may return target Spirit card with mana value 2 or less from your graveyard to your hand.)"}; // native-trigger
const HANDSERVANT = {"name":"Elvish Handservant","type":"Creature — Elf Warrior","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"Whenever a player casts a Giant spell, you may put a +1/+1 counter on this creature."}; // native-trigger
const VANQUISHER = {"name":"Vanquisher's Banner","type":"Artifact","mana":"{5}","cmc":5,"keywords":[],"colors":[],"oracle":"As this artifact enters, choose a creature type.\nCreatures you control of the chosen type get +1/+1.\nWhenever you cast a creature spell of the chosen type, draw a card."}; // native-mixed
const RIVAZ = {"name":"Rivaz of the Claw","type":"Legendary Creature — Lizard Warlock","mana":"{1}{B}{R}","cmc":3,"power":"3","toughness":"3","keywords":["Menace"],"colors":["B","R"],"oracle":"Menace\n{T}: Add two mana in any combination of colors. Spend this mana only to cast Dragon creature spells.\nOnce during each of your turns, you may cast a Dragon creature spell from your graveyard.\nWhenever you cast a Dragon creature spell from your graveyard, it gains \"When this creature dies, exile it.\""}; // native-mana
const VISION = {"name":"Vision, Spectral Synthezoid","type":"Legendary Artifact Creature — Robot Hero","mana":"{6}{U}{U}","cmc":8,"power":"2","toughness":"5","keywords":["Flying"],"colors":["U"],"oracle":"Flying\nOnce during each of your turns, you may cast a noncreature or Robot spell from your hand without paying its mana cost."}; // native-static
const SILVERGILL = {"name":"Silvergill Adept","type":"Creature — Merfolk Wizard","mana":"{1}{U}","cmc":2,"power":"2","toughness":"1","keywords":[],"colors":["U"],"oracle":"As an additional cost to cast this spell, reveal a Merfolk card from your hand or pay {3}.\nWhen this creature enters, draw a card."}; // native-trigger
const CAVERN = {"name":"Cavern of Souls","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"As this land enters, choose a creature type.\n{T}: Add {C}.\n{T}: Add one mana of any color. Spend this mana only to cast a creature spell of the chosen type, and that spell can't be countered."}; // land
const GUIDELIGHT = {"name":"Guidelight Optimizer","type":"Artifact Creature — Robot","mana":"{1}{U}","cmc":2,"power":"2","toughness":"1","keywords":[],"colors":["U"],"oracle":"{T}: Add {U}. Spend this mana only to cast an artifact spell or activate an ability."}; // native-mana
const PATH_ANCESTRY = {"name":"Path of Ancestry","type":"Land","mana":"","cmc":0,"keywords":["Scry"],"colors":[],"oracle":"This land enters tapped.\n{T}: Add one mana of any color in your commander's color identity. When that mana is spent to cast a creature spell that shares a creature type with your commander, scry 1. (Look at the top card of your library. You may put that card on the bottom.)"}; // land
const GILT_LEAF = {"name":"Gilt-Leaf Palace","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"As this land enters, you may reveal an Elf card from your hand. If you don't, this land enters tapped.\n{T}: Add {B} or {G}."}; // land
const FURYCALM = {"name":"Furycalm Snarl","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"As this land enters, you may reveal a Mountain or Plains card from your hand. If you don't, this land enters tapped.\n{T}: Add {R} or {W}."}; // land
const BRAMBLEWOOD = {"name":"Bramblewood Paragon","type":"Creature — Elf Warrior","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":"Each other Warrior creature you control enters with an additional +1/+1 counter on it.\nEach creature you control with a +1/+1 counter on it has trample."}; // native-static
const ESSENCE_FLUX = {"name":"Essence Flux","type":"Instant","mana":"{U}","cmc":1,"keywords":[],"colors":["U"],"oracle":"Exile target creature you control, then return that card to the battlefield under its owner's control. If it's a Spirit, put a +1/+1 counter on it."}; // native-spell
const HEADLESS = {"name":"Headless Rider","type":"Creature — Zombie","mana":"{2}{B}","cmc":3,"power":"3","toughness":"1","keywords":[],"colors":["B"],"oracle":"Whenever this creature or another nontoken Zombie you control dies, create a 2/2 black Zombie creature token."}; // native-trigger
const SHIVAN = {"name":"Shivan Dragon","type":"Creature — Dragon","mana":"{4}{R}{R}","cmc":6,"power":"5","toughness":"5","keywords":["Flying"],"colors":["R"],"oracle":"Flying\n{R}: This creature gets +1/+0 until end of turn."}; // native-activated
const LLANOWAR = {"name":"Llanowar Elves","type":"Creature — Elf Druid","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G}."}; // native-mana
const FOREST = {"name":"Forest","type":"Basic Land — Forest","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {G}.)"}; // land
const MOUNTAIN = {"name":"Mountain","type":"Basic Land — Mountain","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {R}.)"}; // land
const WESTVALE = {"name":"Westvale Abbey // Ormendahl, Profane Prince","type":"Land // Legendary Creature — Demon","mana":"","cmc":0,"keywords":["Flying","Lifelink","Indestructible","Transform","Haste"],"layout":"transform","colors":[],"oracle":"Westvale Abbey - Land \n{T}: Add {C}.\n{5}, {T}, Pay 1 life: Create a 1/1 white and black Human Cleric creature token.\n{5}, {T}, Sacrifice five creatures: Transform this land, then untap it.\n//\nOrmendahl, Profane Prince - Legendary Creature — Demon \nFlying, lifelink, indestructible, haste"}; // land-partial
const ELITE_VANGUARD = {"name":"Elite Vanguard","type":"Creature — Human Soldier","mana":"{W}","cmc":1,"power":"2","toughness":"1","keywords":[],"colors":["W"],"oracle":""}; // native-body
const TARFIRE = {"name":"Tarfire","type":"Kindred Instant — Goblin","mana":"{R}","cmc":1,"keywords":[],"colors":["R"],"oracle":"Tarfire deals 2 damage to any target."}; // native-spell
const NAMELESS = {"name":"Nameless Inversion","type":"Kindred Instant — Shapeshifter","mana":"{1}{B}","cmc":2,"keywords":["Changeling"],"colors":["B"],"oracle":"Changeling (This card is every creature type.)\nTarget creature gets +3/-3 and loses all creature types until end of turn."}; // arbiter-spell
const LEYLINE_LIFEFORCE = {"name":"Leyline of Lifeforce","type":"Enchantment","mana":"{2}{G}{G}","cmc":4,"keywords":[],"colors":["G"],"oracle":"If this card is in your opening hand, you may begin the game with it on the battlefield.\nCreature spells can't be countered."}; // native-static
const RAMUNAP = {"name":"Ramunap Hydra","type":"Creature — Snake Hydra","mana":"{3}{G}","cmc":4,"power":"3","toughness":"3","keywords":["Reach","Vigilance","Trample"],"colors":["G"],"oracle":"Reach, vigilance, trample\nThis creature gets +1/+1 as long as you control a Desert.\nThis creature gets +1/+1 as long as there is a Desert card in your graveyard."}; // native-static
const DESERTS_HOLD = {"name":"Desert's Hold","type":"Enchantment — Aura","mana":"{2}{W}","cmc":3,"keywords":["Enchant"],"colors":["W"],"oracle":"Enchant creature\nWhen this Aura enters, if you control a Desert or there is a Desert card in your graveyard, you gain 3 life.\nEnchanted creature can't attack or block, and its activated abilities can't be activated."}; // native-aura
const AUTOMATON = {"name":"Universal Automaton","type":"Artifact Creature — Shapeshifter","mana":"{1}","cmc":1,"power":"1","toughness":"1","keywords":["Changeling"],"colors":[],"oracle":"Changeling (This card is every creature type.)"}; // native-body
const TEFERI = {"name":"Teferi, Temporal Archmage","type":"Legendary Planeswalker — Teferi","mana":"{4}{U}{U}","cmc":6,"loyalty":"5","keywords":[],"colors":["U"],"oracle":"+1: Look at the top two cards of your library. Put one of them into your hand and the other on the bottom of your library.\n−1: Untap up to four target permanents.\n−10: You get an emblem with \"You may activate loyalty abilities of planeswalkers you control on any player's turn any time you could cast an instant.\"\nTeferi, Temporal Archmage can be your commander."}; // arbiter-pw
const ORVAR = {"name":"Orvar, the All-Form","type":"Legendary Creature — Shapeshifter","mana":"{3}{U}","cmc":4,"power":"3","toughness":"3","keywords":["Changeling"],"colors":["U"],"oracle":"Changeling\nWhenever you cast an instant or sorcery spell, if it targets one or more other permanents you control, create a token that's a copy of one of those permanents.\nWhen a spell or ability an opponent controls causes you to discard this card, create a token that's a copy of target permanent."}; // body-only
const SIGARDAS_AID = {"name":"Sigarda's Aid","type":"Enchantment","mana":"{W}","cmc":1,"keywords":[],"colors":["W"],"oracle":"You may cast Aura and Equipment spells as though they had flash.\nWhenever an Equipment you control enters, you may attach it to target creature you control."}; // native-mixed
const NEKRATAAL_AVATAR = {"name":"Nekrataal Avatar","type":"Vanguard","mana":"","cmc":0,"keywords":[],"layout":"vanguard","colors":[],"oracle":"Creature spells you cast cost {B} less to cast. This effect reduces only the amount of colored mana you pay."}; // native-static
const MYSTIC_FORGE = {"name":"Mystic Forge","type":"Artifact","mana":"{4}","cmc":4,"keywords":[],"colors":[],"oracle":"You may look at the top card of your library any time.\nYou may cast artifact spells and colorless spells from the top of your library.\n{T}, Pay 1 life: Exile the top card of your library."}; // native-mixed

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const K = (id, card) => ({ id, ...card }); // a card in a hand, a library, a graveyard or the command zone
function board(user = [], ai = [], { hand = [], library = [], graveyard = [], command = [], aiHand = [], aiLibrary = [], aiGraveyard = [], pool = {}, extra = {} } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  return { ...g, turn: 3, activePlayer: "user", priorityHolder: "user", phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: { ...g.players,
      user: { ...g.players.user, battlefield: user, hand, library, graveyard, command, manaPool: { ...g.players.user.manaPool, ...pool } },
      ai: { ...g.players.ai, battlefield: ai, hand: aiHand, library: aiLibrary, graveyard: aiGraveyard } }, ...extra };
}
const MW = (controller = "user") => P(`mw-${controller}`, MASKWOOD, controller);
const pt = (s, id) => { const c = deriveCharacteristics(s, id); return [c.power, c.toughness]; };
const CTX = { controller: "user", cardName: "witness" };
const offered = (s) => (s.pendingChoice?.candidates || []).map((c) => c.id).sort();
const trigAtoms = (card, event) => parseEffectClause(detectTriggers(card).find((t) => t.event === event).effectClause, card.type).atoms;
const actAtoms = (card, i = 0) => parseActivatedAbilities(card)[i].program.atoms;
const handIds = (s) => (s.players.user.hand || []).map((c) => c.id).sort();
const firedFrom = (s, sourceId) => (s.pendingTriggers || []).filter((t) => (t.sourcePermanentId ?? t.source?.id ?? t.context?.sourcePermanentId) === sourceId).length;
const handBearZone = () => ({ hand: [K("bear", BEARS)], pool: { G: 2 } });

describe("the card", () => {
  it("⭐ classifies native-mixed — the grant and the Shapeshifter token; the zone sentence is stripped only right after the grant", () => {
    // The anchoring's witness is synthetic: no printed card puts a MODELED first sentence before this zone sentence yet (Arcane
    // Adaptation, Biotransference, Conspiracy and Roshan stay parked on their own first sentences). A modeled anthem followed by the
    // zone sentence must stay residue — nothing models that card's zone half.
    const anthemThenZone = { name: "Synthetic Anthem", type: "Enchantment", mana: "{2}{W}", cmc: 3, keywords: [], oracle: "Creatures you control get +1/+1. The same is true for creature spells you control and creature cards you own that aren't on the battlefield." };
    const anthemOnly = { ...anthemThenZone, oracle: "Creatures you control get +1/+1." };
    expect({ maskwood: classifyCard(MASKWOOD), arcane: classifyCard(ARCANE_ADAPTATION), anthemOnly: classifyCard(anthemOnly), anthemThenZone: classifyCard(anthemThenZone) })
      .toEqual({ maskwood: "native-mixed", arcane: "body-only", anthemOnly: "native-static", anthemThenZone: "body-only" });
  });
  it("the grant: a layer-4 every-creature-type effect on the creatures its controller controls (CR 613.1d)", () => {
    expect(parseStaticAbilities(MASKWOOD)).toEqual([{ layer: 4, op: { allCreatureTypes: true }, affects: { mode: "dynamic", selector: { cardTypes: ["Creature"], controllerScope: "you" } }, duration: { kind: "permanent" } }]);
  });
  it("its {3}, {T} ability makes a 2/2 blue Shapeshifter with changeling", () => {
    expect(actAtoms(MASKWOOD)).toEqual([{ op: "create-token", count: 1, power: 2, toughness: 2, descriptor: "blue shapeshifter", targetType: null, changeling: true }]);
  });
  it("the grant recognizer reads the exact two sentences — Arcane Adaptation's chosen-type grant is not it", () => {
    expect({ maskwood: grantsEveryCreatureType(MASKWOOD), arcane: grantsEveryCreatureType(ARCANE_ADAPTATION), bears: grantsEveryCreatureType(BEARS) })
      .toEqual({ maskwood: true, arcane: false, bears: false });
  });
});

describe("sentence two — the zone answer (everyCreatureType.cardIsEveryCreatureType)", () => {
  it("⭐ a creature card its holder's Maskwood reaches is every creature type; another player's Maskwood never reaches it", () => {
    const mine = board([MW()]);
    const theirs = board([], [MW("ai")]);
    expect({ mine: cardIsEveryCreatureType(mine, BEARS, "user"), theirs: cardIsEveryCreatureType(theirs, BEARS, "user"), plain: cardIsEveryCreatureType(board(), BEARS, "user") })
      .toEqual({ mine: true, theirs: false, plain: false });
  });
  it("only a creature card takes a creature type (CR 205.3d): an instant, a Kindred Goblin instant, a land and Westvale Abbey (a land whose BACK face is a creature) stay as printed", () => {
    const s = board([MW()]);
    expect([COUNTERSPELL, TARFIRE, FOREST, WESTVALE].map((c) => cardIsEveryCreatureType(s, c, "user"))).toEqual([false, false, false, false]);
  });
  it("a changeling is every creature type in every zone, with no Maskwood and no state (CR 702.73a); a card that only MAKES changelings (Belonging) is not", () => {
    expect({ outcast: cardIsEveryCreatureType(null, OUTCAST, "user"), belonging: cardIsEveryCreatureType(board([MW("ai")]), BELONGING, "user"), noState: cardIsEveryCreatureType(null, BEARS, "user"), noCard: cardIsEveryCreatureType(board([MW()]), undefined, "user") })
      .toEqual({ outcast: true, belonging: false, noState: false, noCard: false });
  });
});

describe("sentence one — creatures you control (the layer engine)", () => {
  it("⭐ your creatures are every creature type; an opponent's are not; a noncreature artifact — Maskwood itself, Sol Ring — never is", () => {
    const s = board([MW(), P("bear", BEARS), P("ring", SOL_RING)], [P("ob", BEARS, "ai")]);
    expect({ bear: permIsEveryCreatureType(s, "bear"), opp: permIsEveryCreatureType(s, "ob"), maskwood: permIsEveryCreatureType(s, "mw-user"), ring: permIsEveryCreatureType(s, "ring") })
      .toEqual({ bear: true, opp: false, maskwood: false, ring: false });
  });
  it("⭐ the selectors read it without deriving: Sliver Legion counts your Bears as a Sliver — never Maskwood itself — and an opponent's Maskwood never reaches your Bears", () => {
    const mine = board([MW(), P("sl", LEGION), P("bear", BEARS)]);
    const theirs = board([P("sl", LEGION), P("bear", BEARS)], [MW("ai")]);
    expect({ mine: [pt(mine, "sl"), pt(mine, "bear")], theirs: [pt(theirs, "sl"), pt(theirs, "bear")] })
      .toEqual({ mine: [[8, 8], [3, 3]], theirs: [[7, 7], [2, 2]] });
  });
  it("the selector read takes ONLY the printed shape: a narrower dynamic grant (synthetic — no printed card makes one) is left to the derive, never widened to a white creature it does not name", () => {
    const s0 = board([P("sl", LEGION), P("ve", ELITE_VANGUARD)]);
    const s = addContinuousEffect(s0, { layer: 4, op: { allCreatureTypes: true }, affects: { mode: "dynamic", selector: { cardTypes: ["Creature"], controllerScope: "you", colors: ["G"] } }, duration: { kind: "permanent" }, source: { kind: "static", permanentId: "sl", cardName: "Synthetic" } }).state;
    expect({ legion: pt(s, "sl"), vanguard: pt(s, "ve") }).toEqual({ legion: [7, 7], vanguard: [2, 1] });
  });
});

describe("the library — tutors, digs, reveals", () => {
  it("⭐ Goblin Matron's \"search your library for a Goblin card\" finds any creature card under Maskwood — never a land, never Westvale Abbey's creature back", () => {
    const lib = [K("bear", BEARS), K("forest", FOREST), K("abbey", WESTVALE), K("tarfire", TARFIRE)];
    const atom = trigAtoms(GOBLIN_MATRON, "etb")[0];
    const plain = applyTutor(board([], [], { library: lib }), atom, CTX);
    const under = applyTutor(board([MW()], [], { library: lib }), atom, CTX);
    const theirs = applyTutor(board([], [MW("ai")], { library: lib }), atom, CTX);
    expect({ plain: offered(plain), under: offered(under), theirs: offered(theirs) }).toEqual({ plain: ["tarfire"], under: ["bear", "tarfire"], theirs: ["tarfire"] });
  });
  it("a changeling in the library is a Goblin card with no Maskwood (CR 702.73a); Belonging, which only makes changelings, is not", () => {
    const s = applyTutor(board([], [], { library: [K("oc", OUTCAST), K("bel", BELONGING)] }), trigAtoms(GOBLIN_MATRON, "etb")[0], CTX);
    expect(offered(s)).toEqual(["oc"]);
  });
  it("⭐ Stoneforge Mystic's \"an Equipment card\" is never met by every creature type (CR 205.3d)", () => {
    const s = applyTutor(board([MW()], [], { library: [K("bear", BEARS), K("oc", OUTCAST), K("bs", BONESPLITTER)] }), trigAtoms(STONEFORGE, "etb")[0], CTX);
    expect(offered(s)).toEqual(["bs"]);
  });
  it("the auto-pick's re-check agrees with the pool: Maskwood's Bears is the one Goblin card, and it is picked", () => {
    const s = applyTutor(board([MW()], [], { library: [K("bear", BEARS), K("forest", FOREST)] }), trigAtoms(GOBLIN_MATRON, "etb")[0], CTX);
    expect(autoPickTutorCandidate(s, s.pendingChoice)).toBe("bear");
  });
  it("⭐ Kinnan's \"non-Human creature card\" (the NEGATED reader): under Maskwood the Bears is a Human and is refused; a changeling is refused with or without it", () => {
    const lib = [K("bear", BEARS), K("oc", OUTCAST), K("ev", ELITE_VANGUARD), K("forest", FOREST), K("ring", SOL_RING)];
    const atom = actAtoms(KINNAN)[0];
    const plain = applyImpulseDigAtom(board([], [], { library: lib }), atom, CTX);
    const under = applyImpulseDigAtom(board([MW()], [], { library: lib }), atom, CTX);
    expect({ plain: offered(plain), under: offered(under) }).toEqual({ plain: ["bear"], under: [] });
  });
  it("Icon of Ancestry (Elf chosen): \"a creature card of the chosen type\" — the Bears under Maskwood; an Elf without it", () => {
    const lib = [K("bear", BEARS), K("le", LLANOWAR), K("forest", FOREST)];
    const icon = P("icon", ICON, "user", { chosenType: "Elf" });
    const atom = actAtoms(ICON)[0];
    const plain = applyImpulseDigAtom(board([icon], [], { library: lib }), atom, { ...CTX, sourceId: "icon" });
    const under = applyImpulseDigAtom(board([icon, MW()], [], { library: lib }), atom, { ...CTX, sourceId: "icon" });
    expect({ plain: offered(plain), under: offered(under) }).toEqual({ plain: ["le"], under: ["bear", "le"] });
  });
  it("Herald's Horn (Elf chosen) takes a Bears off the top under Maskwood", () => {
    const horn = P("horn", HERALDS_HORN, "user", { chosenType: "Elf" });
    const atom = trigAtoms(HERALDS_HORN, "upkeep")[0];
    const plain = applyLookTopTakeAtom(board([horn], [], { library: [K("bear", BEARS)] }), atom, { ...CTX, sourceId: "horn" });
    const under = applyLookTopTakeAtom(board([horn, MW()], [], { library: [K("bear", BEARS)] }), atom, { ...CTX, sourceId: "horn" });
    expect({ plain: offered(plain), under: offered(under) }).toEqual({ plain: [], under: ["bear"] });
  });
  it("⭐ Goblin Ringleader puts every revealed creature card into hand under Maskwood — and the Kindred Goblin instant either way", () => {
    const lib = [K("bear", BEARS), K("tarfire", TARFIRE), K("forest", FOREST), K("ev", ELITE_VANGUARD)];
    const atom = trigAtoms(RINGLEADER, "etb")[0];
    expect({ plain: handIds(applyChosenTypeRevealToHand(board([], [], { library: lib }), atom, CTX)), under: handIds(applyChosenTypeRevealToHand(board([MW()], [], { library: lib }), atom, CTX)) })
      .toEqual({ plain: ["tarfire"], under: ["bear", "ev", "tarfire"] });
  });
  it("⭐ Merfolk Wayfinder's \"all Island cards\" takes the Island — and never a changeling or a Maskwood creature (an Island is not a creature type)", () => {
    const lib = [K("island", ISLAND), K("oc", OUTCAST), K("bear", BEARS)];
    expect(handIds(applyChosenTypeRevealToHand(board([MW()], [], { library: lib }), trigAtoms(WAYFINDER, "etb")[0], CTX))).toEqual(["island"]);
  });
  it("Elder Pine of Jukai's \"all land cards\" takes the lands it reveals", () => {
    const lib = [K("forest", FOREST), K("bear", BEARS), K("island", ISLAND)];
    expect(handIds(applyChosenTypeRevealToHand(board([], [], { library: lib }), trigAtoms(ELDER_PINE, "cast")[0], CTX))).toEqual(["forest", "island"]);
  });
  it("⭐ For the Ancestors chooses the creature type the most cards share — every-type cards fit any, so when they are all there is, all of them are taken; an Equipment is never the choice", () => {
    const atom = parseEffectProgram(ANCESTORS).atoms[0];
    const allEvery = handIds(applyChosenTypeRevealToHand(board([MW()], [], { library: [K("bear", BEARS), K("ev", ELITE_VANGUARD), K("forest", FOREST)] }), atom, CTX));
    const mixed = handIds(applyChosenTypeRevealToHand(board([], [], { library: [K("oc", OUTCAST), K("ev", ELITE_VANGUARD), K("bs1", BONESPLITTER), K("bs2", BONESPLITTER)] }), atom, CTX));
    expect({ allEvery, mixed }).toEqual({ allEvery: ["bear", "ev"], mixed: ["ev", "oc"] });
  });
  it("Gishath's \"Dinosaur creature cards\" puts a Bears onto the battlefield under Maskwood", () => {
    const atom = trigAtoms(GISHATH, "combatDamageToPlayer")[0];
    const lib = [K("bear", BEARS), K("forest", FOREST)];
    const put = (s) => (s.players.user.battlefield || []).map((p) => p.card?.name).filter((n) => n === "Grizzly Bears").length;
    expect({ plain: put(applyRevealPutFiltered(board([], [], { library: lib }), atom, { ...CTX, combatDamageAmount: 2 })), under: put(applyRevealPutFiltered(board([MW()], [], { library: lib }), atom, { ...CTX, combatDamageAmount: 2 })) })
      .toEqual({ plain: 0, under: 1 });
  });
});

describe("the graveyard — returns, targets, shared types", () => {
  it("⭐ Overlord of the Balemurk's \"non-Avatar creature card\" (the NEGATED reader): a changeling is an Avatar and is never returned; under Maskwood no creature card is a non-Avatar", () => {
    const atom = trigAtoms(OVERLORD, "etb")[1];
    const gy = [K("bear", BEARS), K("oc", OUTCAST)];
    const plain = applyReturnFromGraveyardPick(board([], [], { graveyard: gy }), atom, CTX);
    const under = applyReturnFromGraveyardPick(board([MW()], [], { graveyard: gy }), atom, CTX);
    expect({ plain: handIds(plain), under: handIds(under) }).toEqual({ plain: ["bear"], under: [] });
  });
  it("⭐ Boggart Birth Rite's \"target Goblin card\": a changeling card always, a Maskwood creature card too — never a land", () => {
    const atom = parseEffectProgram(BIRTH_RITE).atoms[0];
    const gy = [K("bear", BEARS), K("oc", OUTCAST), K("forest", FOREST)];
    const ids = (s) => enumerateTargets(s, "user", atom).map((t) => t.id).sort();
    expect({ plain: ids(board([], [], { graveyard: gy })), under: ids(board([MW()], [], { graveyard: gy })), theirs: ids(board([], [MW("ai")], { graveyard: gy })) })
      .toEqual({ plain: ["oc"], under: ["bear", "oc"], theirs: ["oc"] });
  });
  it("Mantle of the Ancients' \"Aura and/or Equipment cards\" is never met by every creature type (CR 205.3d)", () => {
    const atom = trigAtoms(MANTLE, "etb")[0];
    const ids = enumerateTargets(board([MW()], [], { graveyard: [K("oc", OUTCAST), K("bear", BEARS), K("bs", BONESPLITTER)] }), "user", atom).map((t) => t.id);
    expect(ids).toEqual(["bs"]);
  });
  it("Return from Extinction's \"two creature cards that share a creature type\": a Bears and a Human share one under Maskwood", () => {
    const s0 = (user) => board(user, [], { hand: [K("rfe", EXTINCTION)], graveyard: [K("bear", BEARS), K("ev", ELITE_VANGUARD)], pool: { B: 2 } });
    const pairs = (s) => legalActionsForPlayer(s, "user").filter((a) => a.kind === "cast-spell" && a.cardId === "rfe" && a.targets?.length === 2).length;
    expect({ plain: pairs(s0([])), under: pairs(s0([MW()])) }).toEqual({ plain: 0, under: 1 });
  });
});

describe("graveyard counts and conditions", () => {
  it("⭐ Vengeful Firebrand has haste while a Warrior card is in your graveyard — a Bears under Maskwood, a changeling without it", () => {
    const fb = (user, gy) => permanentHasKeyword(board([P("vf", FIREBRAND), ...user], [], { graveyard: gy }), "vf", "Haste");
    expect({ plain: fb([], [K("bear", BEARS)]), under: fb([MW()], [K("bear", BEARS)]), changeling: fb([], [K("oc", OUTCAST)]) })
      .toEqual({ plain: false, under: true, changeling: true });
  });
  it("Ramunap Hydra's \"a Desert card in your graveyard\" is never met by every creature type (CR 205.3d)", () => {
    expect(pt(board([P("rh", RAMUNAP), MW()], [], { graveyard: [K("oc", OUTCAST), K("bear", BEARS)] }), "rh")).toEqual([3, 3]);
  });
  it("⭐ Dawnhand Eulogist's \"if there is an Elf card in your graveyard\" — a Bears under Maskwood, a changeling without it; Desert's Hold's Desert never", () => {
    const elf = (user, gy) => evaluateInterveningIf(board(user, [], { graveyard: gy }), trigAtoms(DAWNHAND, "etb")[1].condition, "user");
    const desertsHold = detectTriggers(DESERTS_HOLD).find((t) => t.event === "etb").interveningIf;
    const desert = evaluateInterveningIf(board([MW()], [], { graveyard: [K("oc", OUTCAST), K("bear", BEARS)] }), desertsHold, "user");
    expect({ plain: elf([], [K("bear", BEARS)]), under: elf([MW()], [K("bear", BEARS)]), changeling: elf([], [K("oc", OUTCAST)]), desert })
      .toEqual({ plain: false, under: true, changeling: true, desert: false });
  });
});

describe("casting — costs, permissions, counters", () => {
  const casts = (s, cardId) => legalActionsForPlayer(s, "user").filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
  const cost = (s, cardId) => { const c = casts(s, cardId)[0]?.cost; return c ? ["generic", "W", "U", "B", "R", "G"].map((k) => c[k] || 0).join(",") : null; };
  const handBear = { hand: [K("bear", BEARS)], pool: { G: 2 } };
  it("⭐ Goblin Warchief's \"Goblin spells you cast cost {1} less\" reaches a Bears under Maskwood", () => {
    expect({ plain: cost(board([P("gw", WARCHIEF)], [], handBear), "bear"), under: cost(board([P("gw", WARCHIEF), MW()], [], handBear), "bear") })
      .toEqual({ plain: "1,0,0,0,0,1", under: "0,0,0,0,0,1" });
  });
  it("Stonybrook Banneret's \"Merfolk spells and Wizard spells\" union reaches it", () => {
    expect({ plain: cost(board([P("sb", STONYBROOK)], [], handBear), "bear"), under: cost(board([P("sb", STONYBROOK), MW()], [], handBear), "bear") })
      .toEqual({ plain: "1,0,0,0,0,1", under: "0,0,0,0,0,1" });
  });
  it("Hero of Iroas's \"Aura spells cost {1} less\" never does (CR 205.3d)", () => {
    expect(cost(board([P("hi", HERO_IROAS), MW()], [], handBear), "bear")).toBe("1,0,0,0,0,1");
  });
  it("⭐ Urza's Incubator (Elf chosen) takes {2} off a Shivan Dragon under Maskwood", () => {
    const s = (user) => board([P("ui", INCUBATOR, "user", { chosenType: "Elf" }), ...user], [], { hand: [K("sd", SHIVAN)], pool: { R: 6 } });
    expect({ plain: cost(s([]), "sd"), under: cost(s([MW()]), "sd") }).toEqual({ plain: "4,0,0,0,2,0", under: "2,0,0,0,2,0" });
  });
  it("Edgewalker's \"Cleric spells cost {W}{B} less\" takes the {W} off an Elite Vanguard under Maskwood", () => {
    const s = (user) => board([P("ew", EDGEWALKER), ...user], [], { hand: [K("ev", ELITE_VANGUARD)], pool: { W: 1 } });
    expect({ plain: cost(s([]), "ev"), under: cost(s([MW()]), "ev") }).toEqual({ plain: "0,1,0,0,0,0", under: "0,0,0,0,0,0" });
  });
  it("Morophon (Elf chosen) takes an {R} off a Shivan Dragon under Maskwood", () => {
    const s = (user) => board([P("mo", MOROPHON, "user", { chosenType: "Elf" }), ...user], [], { hand: [K("sd", SHIVAN)], pool: { R: 6 } });
    expect({ plain: cost(s([]), "sd"), under: cost(s([MW()]), "sd") }).toEqual({ plain: "4,0,0,0,2,0", under: "4,0,0,0,1,0" });
  });
  it("⭐ Rattlechains' \"cast Spirit spells as though they had flash\": a Bears on an opponent's turn, under Maskwood", () => {
    const s = (user) => board([P("rc", RATTLECHAINS), ...user], [], { ...handBear, extra: { activePlayer: "ai", priorityHolder: "user" } });
    expect({ plain: casts(s([]), "bear").length, under: casts(s([MW()]), "bear").length > 0 }).toEqual({ plain: 0, under: true });
  });
  it("Korlessa's \"cast Dragon spells from the top of your library\": a Bears, under Maskwood", () => {
    const s = (user) => board([P("ko", KORLESSA), ...user], [], { library: [K("bear", BEARS)], pool: { G: 2 } });
    const fromTop = (st) => casts(st, "bear").filter((a) => a.fromZone === "library").length > 0;
    expect({ plain: fromTop(s([])), under: fromTop(s([MW()])) }).toEqual({ plain: false, under: true });
  });
  it("Vision's \"cast a noncreature or Robot spell … without paying its mana cost\": a Bears, under Maskwood", () => {
    const s = (user) => board([P("vis", VISION), ...user], [], { hand: [K("bear", BEARS)] });
    const free = (st) => casts(st, "bear").filter((a) => a.freeCastOnceSourceId === "vis").length > 0;
    expect({ plain: free(s([])), under: free(s([MW()])) }).toEqual({ plain: false, under: true });
  });
  it("⭐ Rivaz of the Claw's \"cast a Dragon creature spell from your graveyard\": a Bears, under Maskwood — and the cast fires its exile rider", () => {
    const s = (user) => board([P("rz", RIVAZ), ...user], [], { graveyard: [K("bear", BEARS)], pool: { G: 2 } });
    const fromGy = (st) => casts(st, "bear").filter((a) => a.fromZone === "graveyard" && a.dragonGyCastSourceId === "rz").length > 0;
    const rider = (st) => firedFrom(checkCastTriggers(st, { spellCard: K("bear", BEARS), casterId: "user", castFromZone: "graveyard" }), "rz");
    expect({ plain: fromGy(s([])), under: fromGy(s([MW()])), riderPlain: rider(s([])), riderUnder: rider(s([MW()])) })
      .toEqual({ plain: false, under: true, riderPlain: 0, riderUnder: 1 });
  });
  it("⭐ Silvergill Adept's \"reveal a Merfolk card from your hand\" accepts a Bears under Maskwood", () => {
    const s = (user) => board(user, [], { hand: [K("sa", SILVERGILL), K("bear", BEARS)], pool: { U: 1, C: 4 } });
    const reveal = (st) => casts(st, "sa").filter((a) => a.revealCardId === "bear").length > 0;
    expect({ plain: reveal(s([])), under: reveal(s([MW()])) }).toEqual({ plain: false, under: true });
  });
  it("a reveal cost that names a NON-creature type is never paid by every creature type (synthetic — no printed reveal cost names one yet)", () => {
    const SYNTHETIC_REVEAL = { name: "Synthetic Reveal", type: "Sorcery", mana: "{U}", cmc: 1, keywords: [], oracle: "As an additional cost to cast this spell, reveal a Forest card from your hand or pay {3}.\nDraw a card." };
    const s = (hand) => board([], [], { hand: [K("syn", SYNTHETIC_REVEAL), ...hand], pool: { U: 1, C: 3 } });
    const revealIds = (st) => casts(st, "syn").map((a) => a.revealCardId).filter(Boolean);
    expect({ forest: revealIds(s([K("forest", FOREST)])), changeling: revealIds(s([K("oc", OUTCAST)])) }).toEqual({ forest: ["forest"], changeling: [] });
  });
  it("⭐ Cavern of Souls (Elf chosen) pays for a Bears under Maskwood — offered AND paid (the dispatcher plans with the same answer)", () => {
    const s = (user) => board([P("cv", CAVERN, "user", { chosenType: "Elf" }), P("mt", MOUNTAIN), ...user], [], { hand: [K("bear", BEARS)] });
    const under = s([MW()]);
    const act = casts(under, "bear")[0];
    const after = act ? dispatchAction(under, act) : null;
    expect({ plain: casts(s([]), "bear").length, under: !!act, onStack: (after?.stack || []).some((o) => o.source?.name === "Grizzly Bears") })
      .toEqual({ plain: 0, under: true, onStack: true });
  });
  it("Guidelight Optimizer's \"only to cast an artifact spell\" never pays for an every-type creature spell (CR 205.3d)", () => {
    const s = board([P("go", GUIDELIGHT), P("mt", MOUNTAIN), MW()], [], { hand: [K("rc", RATTLECHAINS)] });
    expect(casts(s, "rc").length).toBe(0);
  });
  it("⭐ Root Sliver's \"Sliver spells can't be countered\": your Bears spell under your Maskwood — not an opponent's, not without it; a Kindred changeling instant is no creature spell for Leyline of Lifeforce", () => {
    const spell = (card, controller) => ({ id: "st-1", kind: "spell", source: { id: "c-spell", ...card }, controller });
    const s = board([P("rs", ROOT_SLIVER), MW()]);
    const plain = board([P("rs", ROOT_SLIVER)]);
    const leyline = board([P("ll", LEYLINE_LIFEFORCE), MW()]);
    expect({ mine: stackSpellIsUncounterable(s, spell(BEARS, "user")), theirs: stackSpellIsUncounterable(s, spell(BEARS, "ai")), plain: stackSpellIsUncounterable(plain, spell(BEARS, "user")), kindred: stackSpellIsUncounterable(leyline, spell(NAMELESS, "user")) })
      .toEqual({ mine: true, theirs: false, plain: false, kindred: false });
  });
});

describe("cast triggers — the spell's controller holds the answer", () => {
  const cast = (s, card, casterId = "user", extra = {}) => checkCastTriggers(s, { spellCard: K("spell", card), casterId, ...extra });
  it("⭐ Lys Alana Huntmaster's \"whenever you cast an Elf spell\" fires for a Bears under Maskwood", () => {
    expect({ plain: firedFrom(cast(board([P("hm", HUNTMASTER)]), BEARS), "hm"), under: firedFrom(cast(board([P("hm", HUNTMASTER), MW()]), BEARS), "hm") }).toEqual({ plain: 0, under: 1 });
  });
  it("Armory Paladin's \"an Aura or Equipment spell\" never does (CR 205.3d); Elder Pine's \"a Spirit or Arcane spell\" does", () => {
    const s = board([P("ap", ARMORY_PALADIN), P("ep", ELDER_PINE), MW()]);
    const after = cast(s, BEARS);
    expect({ paladin: firedFrom(after, "ap"), pine: firedFrom(after, "ep") }).toEqual({ paladin: 0, pine: 1 });
  });
  it("⭐ Elvish Handservant's \"a player casts a Giant spell\": an opponent's Bears under THEIR Maskwood — never under yours", () => {
    const theirs = cast(board([P("hs", HANDSERVANT)], [MW("ai")]), BEARS, "ai");
    const yours = cast(board([P("hs", HANDSERVANT), MW()]), BEARS, "ai");
    expect({ theirs: firedFrom(theirs, "hs"), yours: firedFrom(yours, "hs") }).toEqual({ theirs: 1, yours: 0 });
  });
  it("Vanquisher's Banner (Elf chosen): \"a creature spell of the chosen type\" draws for a Bears under Maskwood", () => {
    const s = (user) => board([P("vb", VANQUISHER, "user", { chosenType: "Elf" }), ...user]);
    expect({ plain: firedFrom(cast(s([]), BEARS), "vb"), under: firedFrom(cast(s([MW()]), BEARS), "vb") }).toEqual({ plain: 0, under: 1 });
  });
});

describe("Path of Ancestry — the commander's creature type", () => {
  const PATH_BOARD = (user, command, hand) => board([P("path", PATH_ANCESTRY), ...user], [], { hand, command: command.map((c) => ({ ...c, isCommander: true })) });
  const withIdentity = (s, identity) => ({ ...s, players: { ...s.players, user: { ...s.players.user, commanderIdentity: identity } } });
  const scried = (s, cardId) => {
    const act = legalActionsForPlayer(s, "user").find((a) => a.kind === "cast-spell" && a.cardId === cardId);
    if (!act) return "no cast";
    const after = dispatchAction(s, act);
    const pend = (after.pendingTriggers || []).filter((t) => t.event === "manaSpentRider").length;
    const stacked = (after.stack || []).filter((o) => o.descriptor?.event === "manaSpentRider" || o.event === "manaSpentRider" || o.source?.name === "Path of Ancestry").length;
    return pend + stacked;
  };
  it("⭐ a Bears and an Elf commander share a type under Maskwood (Path's scry) — not without it", () => {
    const s = (user) => withIdentity(PATH_BOARD([P("f1", FOREST), ...user], [K("cmd", LLANOWAR)], [K("bear", BEARS)]), ["G"]);
    expect({ plain: scried(s([]), "bear"), under: scried(s([MW()]), "bear") }).toEqual({ plain: 0, under: 1 });
  });
  it("a changeling spell shares a type with any creature commander; a planeswalker commander has no creature type to share", () => {
    const elf = withIdentity(PATH_BOARD([], [K("cmd", LLANOWAR)], [K("ua", AUTOMATON)]), ["G"]);
    const walker = withIdentity(PATH_BOARD([], [K("cmd", TEFERI)], [K("ua", AUTOMATON)]), ["U"]);
    expect({ elf: scried(elf, "ua"), walker: scried(walker, "ua") }).toEqual({ elf: 1, walker: 0 });
  });
  it("a changeling commander shares a type with any creature spell — in the command zone or on the battlefield; a creature spell with no creature type shares none (synthetic)", () => {
    const TYPELESS = { name: "Synthetic Typeless", type: "Creature", mana: "{1}{U}", cmc: 2, power: "1", toughness: "1", keywords: [], oracle: "" };
    const zone = withIdentity(PATH_BOARD([P("i1", ISLAND)], [K("cmd", ORVAR)], [K("rc", RATTLECHAINS)]), ["U"]);
    const field = withIdentity(PATH_BOARD([P("i1", ISLAND), P("orv", ORVAR, "user", { card: { id: "c-orv", ...ORVAR, isCommander: true } })], [], [K("rc", RATTLECHAINS)]), ["U"]);
    const typeless = withIdentity(PATH_BOARD([P("i1", ISLAND)], [K("cmd", ORVAR)], [K("ty", TYPELESS)]), ["U"]);
    expect({ zone: scried(zone, "rc"), field: scried(field, "rc"), typeless: scried(typeless, "ty") }).toEqual({ zone: 1, field: 1, typeless: 0 });
  });
});

describe("lands, entering, blinking, dying", () => {
  it("⭐ Gilt-Leaf Palace reveals a Bears as an Elf card under Maskwood; a Snarl never takes a changeling for a Mountain (CR 205.3d)", () => {
    const tapped = (user, land, hand) => revealLandEntersTapped(board(user, [], { hand }), land, "user");
    expect({ plain: tapped([], GILT_LEAF, [K("bear", BEARS)]), under: tapped([MW()], GILT_LEAF, [K("bear", BEARS)]), snarl: tapped([MW()], FURYCALM, [K("oc", OUTCAST), K("bear", BEARS)]) })
      .toEqual({ plain: true, under: false, snarl: true });
  });
  it("⭐ Bramblewood Paragon: a Bears enters with the Warrior's extra +1/+1 counter under Maskwood (CR 614.12 — as it will exist on the battlefield)", () => {
    const enter = (user) => {
      const s = board([P("bp", BRAMBLEWOOD), ...user], [], handBearZone());
      const act = legalActionsForPlayer(s, "user").find((a) => a.kind === "cast-spell" && a.cardId === "bear");
      const after = resolveTopOfStack(dispatchAction(s, act));
      return after.players.user.battlefield.find((p) => p.card?.name === "Grizzly Bears")?.counters?.["+1/+1"] || 0;
    };
    expect({ plain: enter([]), under: enter([MW()]) }).toEqual({ plain: 0, under: 1 });
  });
  it("Essence Flux returns a Bears with the Spirit's +1/+1 counter under Maskwood", () => {
    const flux = (user) => {
      const s = board([P("bear", BEARS), ...user], [], { hand: [K("ef", ESSENCE_FLUX)], pool: { U: 1 } });
      const act = legalActionsForPlayer(s, "user").find((a) => a.kind === "cast-spell" && a.cardId === "ef" && a.targets?.some((t) => t.id === "bear"));
      const after = resolveTopOfStack(dispatchAction(s, act));
      return after.players.user.battlefield.find((p) => p.card?.name === "Grizzly Bears")?.counters?.["+1/+1"] || 0;
    };
    expect({ plain: flux([]), under: flux([MW()]) }).toEqual({ plain: 0, under: 1 });
  });
  it("⭐ a creature that died under Maskwood was a Zombie (Headless Rider's look-back) — not without it", () => {
    const died = (user) => firedFrom(checkDiesTriggers(board([P("hr", HEADLESS), ...user]), [{ id: "dead", controller: "user", name: BEARS.name, card: { id: "c-dead", ...BEARS } }]), "hr");
    expect({ plain: died([]), under: died([MW()]) }).toEqual({ plain: 0, under: 1 });
  });
});

describe("the guards — a creature TYPE only (CR 205.3d), and only a chosen type that exists", () => {
  const casts = (s, cardId) => legalActionsForPlayer(s, "user").filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
  const cost = (s, cardId) => { const c = casts(s, cardId)[0]?.cost; return c ? ["generic", "W", "U", "B", "R", "G"].map((k) => c[k] || 0).join(",") : null; };
  it("a chosen-type reducer whose source never chose (Urza's Incubator, Morophon) reduces nothing, Maskwood or not", () => {
    const s = (src) => board([P("src", src), MW()], [], { hand: [K("sd", SHIVAN)], pool: { R: 6 } });
    expect({ incubator: cost(s(INCUBATOR), "sd"), morophon: cost(s(MOROPHON), "sd") }).toEqual({ incubator: "4,0,0,0,2,0", morophon: "4,0,0,0,2,0" });
  });
  it("Vanquisher's Banner that never chose draws nothing for a Bears under Maskwood", () => {
    expect(firedFrom(checkCastTriggers(board([P("vb", VANQUISHER), MW()]), { spellCard: K("spell", BEARS), casterId: "user" }), "vb")).toBe(0);
  });
  it("Sigarda's Aid's \"Aura and Equipment spells as though they had flash\" never reaches an every-type creature spell", () => {
    const s = board([P("sa", SIGARDAS_AID), MW()], [], { hand: [K("bear", BEARS)], pool: { G: 2 }, extra: { activePlayer: "ai", priorityHolder: "user" } });
    expect(casts(s, "bear").length).toBe(0);
  });
  it("Nekrataal Avatar's \"Creature spells cost {B} less\" never reaches a Kindred changeling instant — every creature TYPE is not the creature card type", () => {
    expect(cost(board([P("na", NEKRATAAL_AVATAR)], [], { hand: [K("ni", NAMELESS)], pool: { B: 2 } }), "ni")).toBe("1,0,0,1,0,0");
  });
  it("Mystic Forge's \"cast artifact spells … from the top of your library\" never reaches an every-type creature card", () => {
    const s = board([P("mf", MYSTIC_FORGE), MW()], [], { library: [K("bear", BEARS)], pool: { G: 2 } });
    expect(casts(s, "bear").filter((a) => a.fromZone === "library").length).toBe(0);
  });
});
