/**
 * EVERY CREATURE TYPE ON THE BATTLEFIELD — the play-weighted program, P·39a: Mirror Entity (EDHREC #950), Mutavault (#1915),
 * Faceless Haven — and every battlefield creature-type reader behind them (the half of Maskwood Nexus #490 that needs no zone).
 *
 *   Mirror Entity: "{X}: Until end of turn, creatures you control have base power and toughness X/X and gain all creature types."
 *   Mutavault: "{1}: This land becomes a 2/2 creature with all creature types until end of turn. It's still a land."
 *   Faceless Haven: "{S}{S}{S}: This land becomes a 4/3 creature with vigilance and all creature types until end of turn. …"
 *
 * The representation: a FIXED layer-4 `allCreatureTypes` effect (CR 613.1d) — the derive's `everyCreatureType` flag, ordered against
 * a "becomes the creature type of your choice" replacement by timestamp (CR 613.7), only ever on a creature (CR 205.3d) — read by
 * layers.permIsEveryCreatureType (plus Changeling, CR 702.73a) and, recursion-free, by effectiveTypeIdentity for the selectors.
 * Every creature-type reader that runs on a battlefield permanent asks it; a NEGATED one ("non-Human", "can't be blocked by Walls",
 * Mjölnir's "non-Villain") must, or it does something the rules forbid. Each witness below is a pair: the plain creature, and the
 * same creature made every creature type by the exact effect Mirror Entity's resolution writes.
 *
 * Real oracle fixtures (bundled Scryfall, the 2026-10-01 data, generated by cardIndex.publicCard — never typed by hand).
 */
import { describe, it, expect, beforeEach } from "vitest";
import { createGameState, createPermanent, _resetIdsForTests, creaturePower } from "./gameState.js";
import { addContinuousEffect, permIsEveryCreatureType, permanentIsCreature, deriveCharacteristics, permanentHasKeyword, partyCount, sourceTriggerMultiplierCount, expireContinuousEffects } from "./layers.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { resolveTopOfStack } from "./gameEngine.js";
import { classifyCard } from "./coverage.js";
import { parseActivatedAbilities } from "./effects/abilities.js";
import { parseEffectClause } from "./effects/parser.js";
import { canBlockAttacker } from "./combatEvasion.js";
import { groupWardTaxForStackObject } from "./groupWard.js";
import { checkAttackTriggers, checkEnterTriggers, checkDiesTriggers, checkBlockTriggers, checkCombatDamageToCreatureTriggers, checkAbilityActivatedTriggers } from "./triggers.js";
import { resolveCombatDamage } from "./combatResolution.js";
import { massCreatureTargets, controllerCreatureTargets, countForSpec } from "./effects/atoms/shared.js";
import { applyChampion, advanceSacrificeChain } from "./effects/atoms/removal.js";
import { applyAmass } from "./effects/atoms/amass.js";
import { evaluateInterveningIf } from "./interveningIf.js";
import { manaSources } from "./manaModel.js";
import { consultDamageAmount } from "./damageReplacements.js";
import { applyUrDragonAttackTriggers } from "./urDragonAttack.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (oracle verified against bundled Scryfall data) ──────────
const MIRROR_ENTITY = {"name":"Mirror Entity","type":"Creature — Shapeshifter","mana":"{2}{W}","cmc":3,"power":"1","toughness":"1","keywords":["Changeling"],"oracle":"Changeling (This card is every creature type.)\n{X}: Until end of turn, creatures you control have base power and toughness X/X and gain all creature types."}; // native-activated
const MUTAVAULT = {"name":"Mutavault","type":"Land","mana":"","cmc":0,"keywords":[],"oracle":"{T}: Add {C}.\n{1}: This land becomes a 2/2 creature with all creature types until end of turn. It's still a land."}; // land
const FACELESS_HAVEN = {"name":"Faceless Haven","type":"Snow Land","mana":"","cmc":0,"keywords":[],"oracle":"{T}: Add {C}.\n{S}{S}{S}: This land becomes a 4/3 creature with vigilance and all creature types until end of turn. It's still a land. ({S} can be paid with one mana from a snow source.)"}; // land
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"oracle":""}; // native-body
const ARCHDRUID = {"name":"Elvish Archdruid","type":"Creature — Elf Druid","mana":"{1}{G}{G}","cmc":3,"power":"2","toughness":"2","keywords":[],"oracle":"Other Elf creatures you control get +1/+1.\n{T}: Add {G} for each Elf you control."}; // native-mana
const OUTCAST = {"name":"Changeling Outcast","type":"Creature — Shapeshifter","mana":"{B}","cmc":1,"power":"1","toughness":"1","keywords":["Changeling"],"oracle":"Changeling (This card is every creature type.)\nThis creature can't block and can't be blocked."}; // native-body
const DREAMER = {"name":"Mistform Dreamer","type":"Creature — Illusion","mana":"{2}{U}","cmc":3,"power":"2","toughness":"1","keywords":["Flying"],"oracle":"Flying\n{1}: This creature becomes the creature type of your choice until end of turn."}; // native-activated
const AERONAUT = {"name":"Aeronaut Admiral","type":"Creature — Human Pilot","mana":"{3}{W}","cmc":4,"power":"3","toughness":"1","keywords":["Flying"],"oracle":"Flying\nVehicles you control have flying."}; // native-static
const VANQUISHER = {"name":"Vanquisher's Banner","type":"Artifact","mana":"{5}","cmc":5,"keywords":[],"oracle":"As this artifact enters, choose a creature type.\nCreatures you control of the chosen type get +1/+1.\nWhenever you cast a creature spell of the chosen type, draw a card."}; // native-mixed
const LEGION = {"name":"Sliver Legion","type":"Legendary Creature — Sliver","mana":"{W}{U}{B}{R}{G}","cmc":5,"power":"7","toughness":"7","keywords":[],"oracle":"All Sliver creatures get +1/+1 for each other Sliver on the battlefield."}; // native-static
const REVELERS = {"name":"Night Revelers","type":"Creature — Vampire","mana":"{4}{R}","cmc":5,"power":"4","toughness":"4","keywords":[],"oracle":"This creature has haste as long as an opponent controls a Human."}; // native-static
const BRACERS = {"name":"Bladed Bracers","type":"Artifact — Equipment","mana":"{1}","cmc":1,"keywords":["Equip"],"oracle":"Equipped creature gets +1/+1.\nAs long as equipped creature is a Human or an Angel, it has vigilance.\nEquip {2} ({2}: Attach to target creature you control. Equip only as a sorcery.)"}; // native-equipment
const SPLINTER = {"name":"Splinter, Radical Rat","type":"Legendary Creature — Mutant Ninja Rat","mana":"{1}{W/B}{W/B}","cmc":3,"power":"2","toughness":"4","keywords":[],"oracle":"If a triggered ability of a Ninja creature you control triggers, that ability triggers an additional time.\n{1}{U}: Target Ninja can't be blocked this turn."}; // native-mixed
const PROWLERS_HELM = {"name":"Prowler's Helm","type":"Artifact — Equipment","mana":"{2}","cmc":2,"keywords":["Equip"],"oracle":"Equipped creature can't be blocked except by Walls.\nEquip {2}"}; // native-equipment
const JUGGERNAUT = {"name":"Juggernaut","type":"Artifact Creature — Juggernaut","mana":"{4}","cmc":4,"power":"5","toughness":"3","keywords":[],"oracle":"This creature attacks each combat if able.\nThis creature can't be blocked by Walls."}; // native-body
const DIFFUSION = {"name":"Diffusion Sliver","type":"Creature — Sliver","mana":"{1}{U}","cmc":2,"power":"1","toughness":"1","keywords":[],"oracle":"Whenever a Sliver creature you control becomes the target of a spell or ability an opponent controls, counter that spell or ability unless its controller pays {2}."}; // native-trigger
const ALELA = {"name":"Alela, Cunning Conqueror","type":"Legendary Creature — Faerie Warlock","mana":"{2}{U}{B}","cmc":4,"power":"2","toughness":"4","keywords":["Flying","Goad"],"oracle":"Flying\nWhenever you cast your first spell during each opponent's turn, create a 1/1 black Faerie Rogue creature token with flying.\nWhenever one or more Faeries you control deal combat damage to a player, goad target creature that player controls."}; // native-trigger
const KEEPER = {"name":"Keeper of Fables","type":"Creature — Cat","mana":"{3}{G}{G}","cmc":5,"power":"4","toughness":"5","keywords":[],"oracle":"Whenever one or more non-Human creatures you control deal combat damage to a player, draw a card."}; // native-trigger
const BASILISK = {"name":"Rock Basilisk","type":"Creature — Basilisk","mana":"{4}{R}{G}","cmc":6,"power":"4","toughness":"5","keywords":[],"oracle":"Whenever this creature blocks or becomes blocked by a non-Wall creature, destroy that creature at end of combat."}; // native-trigger
const HEADLESS = {"name":"Headless Rider","type":"Creature — Zombie","mana":"{2}{B}","cmc":3,"power":"3","toughness":"1","keywords":[],"oracle":"Whenever this creature or another nontoken Zombie you control dies, create a 2/2 black Zombie creature token."}; // native-trigger
const SANCTUM = {"name":"Sanctum Seeker","type":"Creature — Vampire Knight","mana":"{2}{B}{B}","cmc":4,"power":"3","toughness":"4","keywords":[],"oracle":"Whenever a Vampire you control attacks, each opponent loses 1 life and you gain 1 life."}; // native-trigger
const BROOD = {"name":"Brood Sliver","type":"Creature — Sliver","mana":"{4}{G}","cmc":5,"power":"3","toughness":"3","keywords":[],"oracle":"Whenever a Sliver deals combat damage to a player, its controller may create a 1/1 colorless Sliver creature token."}; // native-trigger
const CHAMPION_PERISHED = {"name":"Champion of the Perished","type":"Creature — Zombie","mana":"{B}","cmc":1,"power":"1","toughness":"1","keywords":[],"oracle":"Whenever another Zombie you control enters, put a +1/+1 counter on this creature."}; // native-trigger
const VANGUARD = {"name":"Elvish Vanguard","type":"Creature — Elf Warrior","mana":"{1}{G}","cmc":2,"power":"1","toughness":"1","keywords":[],"oracle":"Whenever another Elf enters, put a +1/+1 counter on this creature."}; // native-trigger
const KINDRED_DISCOVERY = {"name":"Kindred Discovery","type":"Enchantment","mana":"{3}{U}{U}","cmc":5,"keywords":[],"oracle":"As this enchantment enters, choose a creature type.\nWhenever a creature you control of the chosen type enters or attacks, draw a card."}; // native-trigger
const TACTICIAN = {"name":"Paired Tactician","type":"Creature — Human Warrior","mana":"{2}{W}","cmc":3,"power":"3","toughness":"2","keywords":[],"oracle":"Whenever this creature and at least one other Warrior attack, put a +1/+1 counter on this creature."}; // native-trigger
const TOXIN = {"name":"Toxin Sliver","type":"Creature — Sliver","mana":"{3}{B}","cmc":4,"power":"3","toughness":"3","keywords":[],"oracle":"Whenever a Sliver deals combat damage to a creature, destroy that creature. It can't be regenerated."}; // native-trigger
const SEARBLADES = {"name":"Ceaseless Searblades","type":"Creature — Elemental Warrior","mana":"{3}{R}","cmc":4,"power":"2","toughness":"4","keywords":[],"oracle":"Whenever you activate an ability of an Elemental, this creature gets +1/+0 until end of turn."}; // native-trigger
const CRUX = {"name":"Crux of Fate","type":"Sorcery","mana":"{3}{B}{B}","cmc":5,"keywords":[],"oracle":"Choose one —\n• Destroy all Dragon creatures.\n• Destroy all non-Dragon creatures."}; // native-spell
const WILDSPEAKER = {"name":"Return of the Wildspeaker","type":"Instant","mana":"{4}{G}","cmc":5,"keywords":[],"oracle":"Choose one —\n• Draw cards equal to the greatest power among non-Human creatures you control.\n• Non-Human creatures you control get +3/+3 until end of turn."}; // native-spell
const DISTANT_MELODY = {"name":"Distant Melody","type":"Sorcery","mana":"{3}{U}","cmc":4,"keywords":[],"oracle":"Choose a creature type. Draw a card for each permanent you control of that type."}; // native-spell
const MAGMA = {"name":"Magma Sliver","type":"Creature — Sliver","mana":"{3}{R}","cmc":4,"power":"3","toughness":"3","keywords":[],"oracle":"All Slivers have \"{T}: Target Sliver creature gets +X/+0 until end of turn, where X is the number of Slivers on the battlefield.\""}; // native-static
const THREE_TREE = {"name":"Three Tree City","type":"Legendary Land","mana":"","cmc":0,"keywords":[],"oracle":"As Three Tree City enters, choose a creature type.\n{T}: Add {C}.\n{2}, {T}: Choose a color. Add an amount of mana of that color equal to the number of creatures you control of the chosen type."}; // land
const WARCHIEF = {"name":"Krosan Warchief","type":"Creature — Beast","mana":"{2}{G}","cmc":3,"power":"2","toughness":"2","keywords":["Regenerate"],"oracle":"Beast spells you cast cost {1} less to cast.\n{1}{G}: Regenerate target Beast."}; // native-mixed
const BREATH = {"name":"Breath Weapon","type":"Instant","mana":"{2}{R}","cmc":3,"keywords":[],"oracle":"Breath Weapon deals 2 damage to each non-Dragon creature."}; // native-spell
const SIEGE_GANG = {"name":"Siege-Gang Commander","type":"Creature — Goblin","mana":"{3}{R}{R}","cmc":5,"power":"2","toughness":"2","keywords":[],"oracle":"When this creature enters, create three 1/1 red Goblin creature tokens.\n{1}{R}, Sacrifice a Goblin: This creature deals 2 damage to any target."}; // native-mixed
const OTHARRI = {"name":"Otharri, Suns' Glory","type":"Legendary Creature — Phoenix","mana":"{3}{R}{W}","cmc":5,"power":"3","toughness":"3","keywords":["Flying","Lifelink","Haste"],"oracle":"Flying, lifelink, haste\nWhenever Otharri attacks, you get an experience counter. Then create a 2/2 red Rebel creature token that's tapped and attacking for each experience counter you have.\n{2}{R}{W}, Tap an untapped Rebel you control: Return this card from your graveyard to the battlefield tapped."}; // native-mixed
const BANNER_KINSHIP = {"name":"Banner of Kinship","type":"Artifact","mana":"{5}","cmc":5,"keywords":[],"oracle":"As this artifact enters, choose a creature type. This artifact enters with a fellowship counter on it for each creature you control of the chosen type.\nCreatures you control of the chosen type get +1/+1 for each fellowship counter on this artifact."}; // native-static
const BOGGART_MOB = {"name":"Boggart Mob","type":"Creature — Goblin Warrior","mana":"{3}{B}","cmc":4,"power":"5","toughness":"5","keywords":["Champion"],"oracle":"Champion a Goblin (When this enters, sacrifice it unless you exile another Goblin you control. When this leaves the battlefield, that card returns to the battlefield.)\nWhenever a Goblin you control deals combat damage to a player, you may create a 1/1 black Goblin Rogue creature token."}; // native-trigger
const PALANI = {"name":"Palani's Hatcher","type":"Creature — Dinosaur","mana":"{3}{R}{G}","cmc":5,"power":"5","toughness":"3","keywords":[],"oracle":"Other Dinosaurs you control have haste.\nWhen this creature enters, create two 0/1 green Dinosaur Egg creature tokens.\nAt the beginning of combat on your turn, if you control one or more Eggs, sacrifice an Egg, then create a 3/3 green Dinosaur creature token."}; // native-mixed
const LAZOTEP = {"name":"Lazotep Plating","type":"Instant","mana":"{1}{U}","cmc":2,"keywords":["Amass"],"oracle":"Amass Zombies 1. (Put a +1/+1 counter on an Army you control. It's also a Zombie. If you don't control an Army, create a 0/0 black Zombie Army creature token first.)\nYou and permanents you control gain hexproof until end of turn. (You and they can't be the targets of spells or abilities your opponents control.)"}; // native-spell
const WILDWOOD = {"name":"Wildwood Tracker","type":"Creature — Elf Warrior","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"oracle":"Whenever this creature attacks or blocks, if you control another non-Human creature, this creature gets +1/+1 until end of turn."}; // native-trigger
const MOX_JASPER = {"name":"Mox Jasper","type":"Legendary Artifact","mana":"{0}","cmc":0,"keywords":[],"oracle":"{T}: Add one mana of any color. Activate only if you control a Dragon."}; // native-mana
const RAPTOR = {"name":"Marauding Raptor","type":"Creature — Dinosaur","mana":"{1}{R}","cmc":2,"power":"2","toughness":"3","keywords":[],"oracle":"Creature spells you cast cost {1} less to cast.\nWhenever another creature you control enters, this creature deals 2 damage to it. If a Dinosaur is dealt damage this way, this creature gets +2/+0 until end of turn."}; // native-mixed
const DWYNEN = {"name":"Dwynen's Elite","type":"Creature — Elf Warrior","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"oracle":"When this creature enters, if you control another Elf, create a 1/1 green Elf Warrior creature token."}; // native-trigger
const SETON = {"name":"Seton, Krosan Protector","type":"Legendary Creature — Centaur Druid","mana":"{G}{G}{G}","cmc":3,"power":"2","toughness":"2","keywords":[],"oracle":"Tap an untapped Druid you control: Add {G}."}; // native-mana
const ALTISAUR = {"name":"Temple Altisaur","type":"Creature — Dinosaur","mana":"{4}{W}","cmc":5,"power":"3","toughness":"4","keywords":[],"oracle":"If a source would deal damage to another Dinosaur you control, prevent all but 1 of that damage."}; // native-static
const CALAMITY = {"name":"Calamity Bearer","type":"Creature — Giant Berserker","mana":"{2}{R}{R}","cmc":4,"power":"3","toughness":"4","keywords":["Double"],"oracle":"If a Giant source you control would deal damage to a permanent or player, it deals double that damage to that permanent or player instead."}; // native-static
const UR_DRAGON = {"name":"The Ur-Dragon","type":"Legendary Creature — Dragon Avatar","mana":"{4}{W}{U}{B}{R}{G}","cmc":9,"power":"10","toughness":"10","keywords":["Flying","Eminence"],"oracle":"Eminence — As long as The Ur-Dragon is in the command zone or on the battlefield, other Dragon spells you cast cost {1} less to cast.\nFlying\nWhenever one or more Dragons you control attack, draw that many cards, then you may put a permanent card from your hand onto the battlefield."}; // native-mixed
const SHAPER = {"name":"Shaper Apprentice","type":"Creature — Merfolk Wizard","mana":"{1}{U}","cmc":2,"power":"2","toughness":"1","keywords":[],"oracle":"This creature has flying as long as you control another Merfolk."}; // native-static
const KRENKO = {"name":"Krenko, Mob Boss","type":"Legendary Creature — Goblin Warrior","mana":"{2}{R}{R}","cmc":4,"power":"3","toughness":"3","keywords":[],"oracle":"{T}: Create X 1/1 red Goblin creature tokens, where X is the number of Goblins you control."}; // native-activated
const THOPTER_SPY = {"name":"Thopter Spy Network","type":"Enchantment","mana":"{2}{U}{U}","cmc":4,"keywords":[],"oracle":"At the beginning of your upkeep, if you control an artifact, create a 1/1 colorless Thopter artifact creature token with flying.\nWhenever one or more artifact creatures you control deal combat damage to a player, draw a card."}; // native-trigger
const WIGHT = {"name":"Reclusive Wight","type":"Creature — Zombie Minion","mana":"{3}{B}","cmc":4,"power":"4","toughness":"4","keywords":[],"oracle":"At the beginning of your upkeep, if you control another nonland permanent, sacrifice this creature."}; // native-trigger
const FACE_BREAKER = {"name":"Professional Face-Breaker","type":"Creature — Human Warrior","mana":"{2}{R}","cmc":3,"power":"2","toughness":"3","keywords":["Treasure","Menace"],"oracle":"Menace\nWhenever one or more creatures you control deal combat damage to a player, create a Treasure token.\nSacrifice a Treasure: Exile the top card of your library. You may play that card this turn."}; // native-mixed
const KURKESH = {"name":"Kurkesh, Onakke Ancient","type":"Legendary Creature — Ogre Spirit","mana":"{2}{R}{R}","cmc":4,"power":"4","toughness":"3","keywords":[],"oracle":"Whenever you activate an ability of an artifact, if it isn't a mana ability, you may pay {R}. If you do, copy that ability. You may choose new targets for the copy."}; // native-trigger
const LASHWRITHE = {"name":"Lashwrithe","type":"Artifact — Equipment","mana":"{4}","cmc":4,"keywords":["Equip","Living weapon"],"oracle":"Living weapon (When this Equipment enters, create a 0/0 black Phyrexian Germ creature token, then attach this to it.)\nEquipped creature gets +1/+1 for each Swamp you control.\nEquip {B/P}{B/P} ({B/P} can be paid with either {B} or 2 life.)"}; // native-equipment
const MAGUS_COFFERS = {"name":"Magus of the Coffers","type":"Creature — Human Wizard","mana":"{4}{B}","cmc":5,"power":"4","toughness":"4","keywords":[],"oracle":"{2}, {T}: Add {B} for each Swamp you control."}; // native-mana
const SHEPHERD = {"name":"Allosaurus Shepherd","type":"Creature — Elf Shaman","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"oracle":"This spell can't be countered.\nGreen spells you control can't be countered.\n{4}{G}{G}: Until end of turn, each Elf creature you control has base power and toughness 5/5 and becomes a Dinosaur in addition to its other creature types."}; // native-mixed
const SWAMP = {"name":"Swamp","type":"Basic Land — Swamp","mana":"","cmc":0,"keywords":[],"oracle":"({T}: Add {B}.)"}; // land
const CAPTAIN_KIRK = {"name":"Captain Kirk, Boldly Going","type":"Legendary Creature — Human Officer","mana":"{1}{G}{W}{U}","cmc":4,"power":"3","toughness":"4","keywords":["Vigilance"],"oracle":"Vigilance\nSpacecraft creatures you control get +3/+3.\nWhenever Captain Kirk enters or attacks, search your library and/or graveyard for a basic land card or a card named Starship Enterprise, reveal it, and put it into your hand. If you search your library this way, shuffle."}; // body-only
const DREAD_PRESENCE = {"name":"Dread Presence","type":"Creature — Nightmare","mana":"{3}{B}","cmc":4,"power":"3","toughness":"3","keywords":[],"oracle":"Whenever a Swamp you control enters, choose one —\n• You draw a card and you lose 1 life.\n• This creature deals 2 damage to any target and you gain 2 life."}; // native-trigger
const ARCBOUND_CRUSHER = {"name":"Arcbound Crusher","type":"Artifact Creature — Juggernaut","mana":"{4}","cmc":4,"power":"0","toughness":"0","keywords":["Modular","Trample"],"oracle":"Trample\nWhenever another artifact enters, put a +1/+1 counter on this creature.\nModular 1 (This creature enters with a +1/+1 counter on it. When it dies, you may put its +1/+1 counters on target artifact creature.)"}; // native-trigger
const YAWNING_FISSURE = {"name":"Yawning Fissure","type":"Sorcery","mana":"{4}{R}","cmc":5,"keywords":[],"oracle":"Each opponent sacrifices a land of their choice."}; // native-spell
const MJOLNIR = {"name":"Mjölnir, Hammer of Thor","type":"Legendary Artifact — Equipment","mana":"{3}{R}","cmc":4,"keywords":["Double"],"oracle":"When Mjölnir enters, it deals 4 damage to up to one target creature.\nDouble all damage equipped creature would deal.\nEquip worthy {1} (A creature is worthy if it's a legendary non-Villain that's red and/or white.)\n{2}{R}, Discard this card: It deals 2 damage to each creature."}; // native-mixed

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
function board(user = [], ai = [], { pool = {}, combat = null, extra = {} } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  return { ...g, turn: 3, activePlayer: "user", priorityHolder: "user", phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    ...(combat ? { combat } : {}),
    players: { ...g.players, user: { ...g.players.user, battlefield: user, manaPool: { ...g.players.user.manaPool, ...pool } }, ai: { ...g.players.ai, battlefield: ai } }, ...extra };
}
/** The exact effect Mirror Entity's resolution writes on each creature (applySetBasePtTeam's allCreatureTypes arm). */
const everyType = (s, ...ids) => ids.reduce((acc, id) => addContinuousEffect(acc, {
  layer: 4, op: { allCreatureTypes: true }, affects: { mode: "fixed", permanentIds: [id] },
  duration: { kind: "endOfTurn", turn: acc.turn }, source: { kind: "resolution", permanentId: null, cardName: "Mirror Entity" },
}).state, s);
const pt = (s, id) => { const c = deriveCharacteristics(s, id); return [c.power, c.toughness]; };
const attack = (...ids) => ({ attackers: ids.map((id) => ({ permanentId: id, attackingPlayer: "user", defender: "ai" })), blockers: [] });
const firedFrom = (s, sourceId) => (s.pendingTriggers || []).filter((t) => (t.sourcePermanentId ?? t.source?.id ?? t.context?.sourcePermanentId) === sourceId).length;
const activations = (s, permId) => legalActionsForPlayer(s, "user").filter((a) => a.kind === "activate-ability" && a.permanentId === permId);

describe("the cards", () => {
  it("classify: Mirror Entity native-activated, Mutavault and Faceless Haven land", () => {
    expect([classifyCard(MIRROR_ENTITY), classifyCard(MUTAVAULT), classifyCard(FACELESS_HAVEN)]).toEqual(["native-activated", "land", "land"]);
  });
  it("the witnesses below that drive a reader by the shape a card parses to stand in for these natively modeled cards", () => {
    const carriers = [CRUX, WILDSPEAKER, DISTANT_MELODY, THREE_TREE, PALANI, LAZOTEP, MOX_JASPER, THOPTER_SPY, YAWNING_FISSURE];
    expect(carriers.filter((c) => !/^(native|land)/.test(classifyCard(c))).map((c) => c.name)).toEqual([]);
  });

  it("⭐ Mirror Entity, X=3: your creatures become 3/3 and every creature type until end of turn — then they are Bears again", () => {
    const s0 = board([P("me", MIRROR_ENTITY), P("bear", BEARS)], [], { pool: { W: 3 } });
    const act = activations(s0, "me").find((a) => a.xValue === 3);
    const s = resolveTopOfStack(dispatchAction(s0, act));
    const after = expireContinuousEffects(s, { atCleanupOfTurn: s.turn });
    const row = { bear: pt(s, "bear"), bearEvery: permIsEveryCreatureType(s, "bear"), entity: pt(s, "me"), nextTurn: [pt(after, "bear"), permIsEveryCreatureType(after, "bear")] };
    console.log("  WITNESS mirrorEntity", JSON.stringify(row)); // vitest 4 needs --disable-console-intercept
    expect(row).toEqual({ bear: [3, 3], bearEvery: true, entity: [3, 3], nextTurn: [[2, 2], false] });
  });

  it("⭐ Mutavault: {1} — a 2/2 creature with all creature types; Mirror Entity then reaches it as the creature it is now", () => {
    const s0 = board([P("mv", MUTAVAULT), P("me", MIRROR_ENTITY)], [], { pool: { C: 1, W: 4 } });
    const animate = activations(s0, "mv").find((a) => !a.isManaAbility && a.cost?.generic === 1);
    const s1 = resolveTopOfStack(dispatchAction(s0, animate));
    const s2 = resolveTopOfStack(dispatchAction(s1, activations(s1, "me").find((a) => a.xValue === 4)));
    const row = { creature: permanentIsCreature(s1, "mv"), every: permIsEveryCreatureType(s1, "mv"), size: pt(s1, "mv"), underEntity: pt(s2, "mv") };
    console.log("  WITNESS mutavault", JSON.stringify(row));
    expect(row).toEqual({ creature: true, every: true, size: [2, 2], underEntity: [4, 4] });
  });

  it("Faceless Haven: its animation carries vigilance AND all creature types", () => {
    const ab = parseActivatedAbilities(FACELESS_HAVEN).find((a) => /all creature types/.test(a.raw));
    expect(ab.program.atoms[0]).toMatchObject({ op: "animate", power: 4, toughness: 3, grantKeywords: ["Vigilance"], allCreatureTypes: true });
  });
});

describe("the flag — CR 613.7 timestamps, CR 205.3d creatures only", () => {
  const dreamerType = (s) => activations(s, "dr").find((a) => !a.isManaAbility);
  it("⭐ a LATER \"becomes the creature type of your choice\" replaces every creature type; an earlier one doesn't", () => {
    const base = board([P("dr", DREAMER), P("ad", ARCHDRUID)], [], { pool: { U: 2 } });
    const later = everyType(base, "dr");
    const thenChosen = resolveTopOfStack(dispatchAction(later, dreamerType(later)));
    const chosenFirst = resolveTopOfStack(dispatchAction(base, dreamerType(base)));
    const thenEvery = everyType(chosenFirst, "dr");
    const row = {
      everyThenChosen: [permIsEveryCreatureType(thenChosen, "dr"), creaturePower(thenChosen.players.user.battlefield.find((p) => p.id === "dr"), thenChosen)],
      chosenThenEvery: [permIsEveryCreatureType(thenEvery, "dr"), creaturePower(thenEvery.players.user.battlefield.find((p) => p.id === "dr"), thenEvery)],
    };
    console.log("  WITNESS timestamps", JSON.stringify(row));
    expect(row).toEqual({ everyThenChosen: [false, 2], chosenThenEvery: [true, 3] }); // the Archdruid's Elf lord reads the same answer
  });
  it("only a creature takes a creature type: the effect on a noncreature artifact makes nothing", () => {
    expect(permIsEveryCreatureType(everyType(board([P("vb", VANQUISHER)]), "vb"), "vb")).toBe(false);
  });
});

describe("statics and selectors (the layer engine)", () => {
  it("⭐ a tribal lord (Elvish Archdruid: other Elves get +1/+1) reaches it", () => {
    const s = board([P("ad", ARCHDRUID), P("bear", BEARS)]);
    expect({ plain: pt(s, "bear"), every: pt(everyType(s, "bear"), "bear") }).toEqual({ plain: [2, 2], every: [3, 3] });
  });
  it("⭐ every CREATURE type, never a Vehicle or a Spacecraft (CR 205.3d): Aeronaut Admiral's \"Vehicles you control have flying\" skips an every-type ARTIFACT creature, Captain Kirk's \"Spacecraft creatures you control get +3/+3\" an every-type creature", () => {
    const s = everyType(board([P("aa", AERONAUT), P("jug", JUGGERNAUT), P("ck", CAPTAIN_KIRK), P("bear", BEARS)]), "jug", "bear");
    expect({ juggernautFlies: permanentHasKeyword(s, "jug", "Flying"), bear: pt(s, "bear") }).toEqual({ juggernautFlies: false, bear: [2, 2] });
  });
  it("the chosen-type anthem (Vanquisher's Banner, Elf chosen)", () => {
    const s = board([P("vb", VANQUISHER, "user", { chosenType: "Elf" }), P("bear", BEARS)]);
    expect({ plain: pt(s, "bear"), every: pt(everyType(s, "bear"), "bear") }).toEqual({ plain: [2, 2], every: [3, 3] });
  });
  it("party: an every-type creature fills any ONE slot (CR 700.8b)", () => {
    const s = board(["b1", "b2", "b3", "b4"].map((id) => P(id, BEARS)));
    expect({ plain: partyCount(s, "user"), one: partyCount(everyType(s, "b1"), "user"), four: partyCount(everyType(s, "b1", "b2", "b3", "b4"), "user") }).toEqual({ plain: 0, one: 1, four: 4 });
  });
  it("the host-subtype gate (Bladed Bracers: a Human or an Angel has vigilance)", () => {
    const s = board([P("bear", BEARS, "user", { attachments: ["bb"] }), P("bb", BRACERS, "user", { attachedTo: "bear" })]);
    expect({ plain: permanentHasKeyword(s, "bear", "Vigilance"), every: permanentHasKeyword(everyType(s, "bear"), "bear", "Vigilance") }).toEqual({ plain: false, every: true });
  });
  it("⭐ Sliver Legion counts it as a Sliver, and buffs it excluding itself — a printed changeling too", () => {
    const s = board([P("sl", LEGION), P("bear", BEARS)]);
    const e = everyType(s, "bear");
    const c = board([P("sl", LEGION), P("oc", OUTCAST)]);
    expect({ plain: [pt(s, "sl"), pt(s, "bear")], every: [pt(e, "sl"), pt(e, "bear")], changeling: pt(c, "sl") })
      .toEqual({ plain: [[7, 7], [2, 2]], every: [[8, 8], [3, 3]], changeling: [8, 8] });
  });
  it("an opponent's every-type creature is a Human (Night Revelers has haste)", () => {
    const s = board([P("nr", REVELERS)], [P("ob", BEARS, "ai")]);
    expect({ plain: permanentHasKeyword(s, "nr", "Haste"), every: permanentHasKeyword(everyType(s, "ob"), "nr", "Haste") }).toEqual({ plain: false, every: true });
  });
  it("the board-count gate (Shaper Apprentice: flying while you control another Merfolk)", () => {
    const s = board([P("sa", SHAPER), P("bear", BEARS)]);
    expect({ plain: permanentHasKeyword(s, "sa", "Flying"), every: permanentHasKeyword(everyType(s, "bear"), "sa", "Flying") }).toEqual({ plain: false, every: true });
  });
  it("the trigger doubler's subject (Splinter: a Ninja creature's triggered ability triggers again)", () => {
    const s = board([P("sp", SPLINTER), P("ss", SANCTUM)]);
    expect({ plain: sourceTriggerMultiplierCount(s, "ss"), every: sourceTriggerMultiplierCount(everyType(s, "ss"), "ss") }).toEqual({ plain: 0, every: 1 });
  });
});

describe("combat", () => {
  it("\"can't be blocked except by Walls\" (Prowler's Helm): an every-type creature may block", () => {
    const s = board([P("atk", BEARS, "user", { attachments: ["ph"] }), P("ph", PROWLERS_HELM, "user", { attachedTo: "atk" })], [P("ob", BEARS, "ai")], { combat: attack("atk") });
    expect({ plain: canBlockAttacker(s, "ob", "atk", "ai"), every: canBlockAttacker(everyType(s, "ob"), "ob", "atk", "ai") }).toEqual({ plain: false, every: true });
  });
  it("⭐ \"can't be blocked by Walls\" (Juggernaut): an every-type creature may NOT block — nor a printed changeling (it used to)", () => {
    const s = board([P("jug", JUGGERNAUT)], [P("ob", BEARS, "ai"), P("oc", OUTCAST, "ai")], { combat: attack("jug") });
    expect({ plain: canBlockAttacker(s, "ob", "jug", "ai"), every: canBlockAttacker(everyType(s, "ob"), "ob", "jug", "ai"), changeling: canBlockAttacker(s, "oc", "jug", "ai") })
      .toEqual({ plain: true, every: false, changeling: false });
  });
  it("the group ward (Diffusion Sliver): an opponent targeting your every-type creature pays {2}", () => {
    const s = board([P("ds", DIFFUSION), P("bear", BEARS)]);
    const spell = { kind: "spell", controller: "ai", source: { name: "Doom Blade" }, targets: [{ type: "creature", id: "bear" }] };
    expect({ plain: groupWardTaxForStackObject(s, spell), every: groupWardTaxForStackObject(everyType(s, "bear"), spell)?.cost?.mana?.generic }).toEqual({ plain: null, every: 2 });
  });
});

describe("triggers", () => {
  const dmg = (s) => resolveCombatDamage(s);
  it("\"one or more Faeries you control deal combat damage\" (Alela) — the batch subtype", () => {
    const s = board([P("al", ALELA), P("bear", BEARS)], [P("ob", BEARS, "ai")], { combat: attack("bear") });
    expect({ plain: firedFrom(dmg(s), "al"), every: firedFrom(dmg(everyType(s, "bear")), "al") }).toEqual({ plain: 0, every: 1 });
  });
  it("⭐ \"non-Human creatures you control deal combat damage\" (Keeper of Fables): an every-type creature is a Human — no draw", () => {
    const s = board([P("kf", KEEPER), P("bear", BEARS)], [], { combat: attack("bear") });
    expect({ plain: firedFrom(dmg(s), "kf"), every: firedFrom(dmg(everyType(s, "bear")), "kf") }).toEqual({ plain: 1, every: 0 });
  });
  it("⭐ \"blocks or becomes blocked by a non-Wall creature\" (Rock Basilisk): an every-type creature is a Wall — no trigger", () => {
    const s = board([P("rb", BASILISK)], [P("ob", BEARS, "ai")], { combat: { attackers: [{ permanentId: "ob", attackingPlayer: "ai", defender: "user" }], blockers: [{ blockerId: "rb", attackerId: "ob" }] } });
    expect({ plain: firedFrom(checkBlockTriggers(s), "rb"), every: firedFrom(checkBlockTriggers(everyType(s, "ob")), "rb") }).toEqual({ plain: 1, every: 0 });
  });
  it("a departed creature answers by its printed Changeling (Headless Rider: another nontoken Zombie died)", () => {
    const s = board([P("hr", HEADLESS)]);
    const died = (card) => checkDiesTriggers(s, [{ id: "dead", controller: "user", name: card.name, card: { id: "c-dead", ...card } }]);
    expect({ bear: firedFrom(died(BEARS), "hr"), changeling: firedFrom(died(OUTCAST), "hr") }).toEqual({ bear: 0, changeling: 1 });
  });
  it("\"Whenever a Vampire you control attacks\" (Sanctum Seeker)", () => {
    const s = board([P("ss", SANCTUM), P("bear", BEARS)], [], { combat: attack("bear") });
    expect({ plain: firedFrom(checkAttackTriggers(s), "ss"), every: firedFrom(checkAttackTriggers(everyType(s, "bear")), "ss") }).toEqual({ plain: 0, every: 1 });
  });
  it("\"Whenever a Sliver deals combat damage to a player\" (Brood Sliver)", () => {
    const s = board([P("br", BROOD), P("bear", BEARS)], [], { combat: attack("bear") });
    expect({ plain: firedFrom(dmg(s), "br"), every: firedFrom(dmg(everyType(s, "bear")), "br") }).toEqual({ plain: 0, every: 1 });
  });
  it("\"another Zombie you control enters\" (Champion of the Perished) — a changeling entering is one", () => {
    const enter = (card) => { const s = board([P("cp", CHAMPION_PERISHED), P("x", card)]); return firedFrom(checkEnterTriggers(s, s.players.user.battlefield[1]), "cp"); };
    expect({ bear: enter(BEARS), changeling: enter(OUTCAST) }).toEqual({ bear: 0, changeling: 1 });
  });
  it("\"another Elf enters\" anywhere (Elvish Vanguard) — an opponent's changeling", () => {
    const enter = (card) => { const s = board([P("ev", VANGUARD)], [P("x", card, "ai")]); return firedFrom(checkEnterTriggers(s, s.players.ai.battlefield[0]), "ev"); };
    expect({ bear: enter(BEARS), changeling: enter(OUTCAST) }).toEqual({ bear: 0, changeling: 1 });
  });
  it("the chosen type attacks (Kindred Discovery, Elf chosen)", () => {
    const s = board([P("kd", KINDRED_DISCOVERY, "user", { chosenType: "Elf" }), P("bear", BEARS)], [], { combat: attack("bear") });
    expect({ plain: firedFrom(checkAttackTriggers(s), "kd"), every: firedFrom(checkAttackTriggers(everyType(s, "bear")), "kd") }).toEqual({ plain: 0, every: 1 });
  });
  it("\"…and at least one other Warrior attack\" (Paired Tactician)", () => {
    const s = board([P("pt", TACTICIAN), P("bear", BEARS)], [], { combat: attack("pt", "bear") });
    expect({ plain: firedFrom(checkAttackTriggers(s), "pt"), every: firedFrom(checkAttackTriggers(everyType(s, "bear")), "pt") }).toEqual({ plain: 0, every: 1 });
  });
  it("\"Whenever a Sliver deals combat damage to a creature\" (Toxin Sliver)", () => {
    const s = board([P("tx", TOXIN), P("bear", BEARS)], [P("ob", BEARS, "ai")]);
    const ev = [{ dealerId: "bear", damagedCreatureId: "ob", dealerController: "user" }];
    expect({ plain: (checkCombatDamageToCreatureTriggers(s, ev).pendingTriggers || []).length, every: (checkCombatDamageToCreatureTriggers(everyType(s, "bear"), ev).pendingTriggers || []).length }).toEqual({ plain: 0, every: 1 });
  });
  it("\"Whenever you activate an ability of an Elemental\" (Ceaseless Searblades)", () => {
    const s = board([P("cs", SEARBLADES), P("bear", BEARS)]);
    const fire = (st) => (checkAbilityActivatedTriggers(st, { permanent: st.players.user.battlefield[1], activatorId: "user", stackObjectId: "stk-x" }).pendingTriggers || []).length;
    expect({ plain: fire(s), every: fire(everyType(s, "bear")) }).toEqual({ plain: 0, every: 1 });
  });
});

describe("effects", () => {
  const ids = (list) => list.map((t) => t.id).sort();
  it("⭐ \"Destroy all non-Dragon creatures\" (Crux of Fate) spares an every-type creature", () => {
    const s = board([P("bear", BEARS), P("b2", BEARS)]);
    expect(ids(massCreatureTargets(everyType(s, "bear"), { subtypeFilter: "Dragon", subtypeNegate: true }))).toEqual(["b2"]);
  });
  it("\"Goblins you control get +1/+1\" includes it; \"Non-Human creatures you control get +3/+3\" (Return of the Wildspeaker) doesn't", () => {
    const s = everyType(board([P("bear", BEARS), P("b2", BEARS)]), "bear");
    expect({ goblins: ids(controllerCreatureTargets(s, "user", { subtypeFilter: "Goblin" })), nonHumans: ids(controllerCreatureTargets(s, "user", { subtypeNegate: "Human" })) })
      .toEqual({ goblins: ["bear"], nonHumans: ["b2"] });
  });
  it("\"the greatest power among non-Human creatures you control\" (Return of the Wildspeaker) leaves it out", () => {
    const s = board([P("big", BEARS, "user", { counters: { "+1/+1": 3 } }), P("bear", BEARS)]);
    const spec = { kind: "greatestPowerYouControl", notSubtype: "Human", per: 1 };
    expect({ plain: countForSpec(s, { controller: "user" }, spec), every: countForSpec(everyType(s, "big"), { controller: "user" }, spec) }).toEqual({ plain: 5, every: 2 });
  });
  it("the tribal counts: Distant Melody's best type, Magma Sliver's Slivers, Three Tree City's chosen type, Krenko's Goblins", () => {
    const s = board([P("ad", ARCHDRUID), P("ms", MAGMA), P("kr", KRENKO), P("bear", BEARS)]);
    const e = everyType(s, "bear");
    const row = (st) => ({
      melody: countForSpec(st, { controller: "user" }, { kind: "chosenTypePermanents" }),
      slivers: countForSpec(st, { controller: "user" }, { kind: "subtypeOnBattlefield", subtype: "Sliver" }),
      chosenElves: countForSpec(st, { controller: "user", source: { chosenType: "Elf" } }, { kind: "creaturesOfSourceChosenType" }),
      goblins: countForSpec(st, { controller: "user" }, { kind: "permanentsYouControl", subtype: "Goblin" }),
    });
    expect({ plain: row(s), every: row(e) }).toEqual({ plain: { melody: 1, slivers: 1, chosenElves: 1, goblins: 1 }, every: { melody: 2, slivers: 2, chosenElves: 2, goblins: 2 } });
  });
  it("Elvish Archdruid taps for {G} per Elf you control", () => {
    const amount = (st) => manaSources(st, "user").filter((src) => src.permanentId === "ad").reduce((n, src) => Math.max(n, src.amount || 1), 0);
    const s = board([P("ad", ARCHDRUID), P("bear", BEARS)]);
    expect({ plain: amount(s), every: amount(everyType(s, "bear")) }).toEqual({ plain: 1, every: 2 });
  });
  it("\"Regenerate target Beast\" (Krosan Warchief) may target it", () => {
    const targets = (st) => [...new Set(activations(st, "kw").flatMap((a) => (a.targets || []).map((t) => t.id)))].sort();
    const s = board([P("kw", WARCHIEF), P("bear", BEARS)], [], { pool: { G: 2 } });
    expect({ plain: targets(s), every: targets(everyType(s, "bear")) }).toEqual({ plain: ["kw"], every: ["bear", "kw"] });
  });
  it("⭐ \"2 damage to each non-Dragon creature\" (Breath Weapon) spares it", () => {
    const s0 = everyType(board([P("bear", BEARS), P("b2", BEARS)], [], { pool: { R: 3 } }), "bear");
    const s = { ...s0, players: { ...s0.players, user: { ...s0.players.user, hand: [{ id: "bw", ...BREATH }] } } };
    const cast = legalActionsForPlayer(s, "user").find((a) => a.kind === "cast-spell" && a.cardId === "bw");
    const after = resolveTopOfStack(dispatchAction(s, cast));
    expect(after.players.user.battlefield.map((p) => p.id).sort()).toEqual(["bear"]);
  });
});

describe("costs and activations", () => {
  it("\"Sacrifice a Goblin\" (Siege-Gang Commander) may sacrifice it", () => {
    const victims = (st) => [...new Set(activations(st, "sg").map((a) => a.sacCreatureId).filter(Boolean))].sort();
    const s = board([P("sg", SIEGE_GANG), P("bear", BEARS)], [], { pool: { R: 2 } });
    expect({ plain: victims(s), every: victims(everyType(s, "bear")) }).toEqual({ plain: ["sg"], every: ["bear", "sg"] });
  });
  it("⭐ Mjölnir's \"worthy\" (a legendary non-Villain): an every-type legend is a Villain — not offered", () => {
    const offered = (st) => activations(st, "mj").flatMap((a) => (a.targets || []).map((t) => t.id));
    const s = board([P("mj", MJOLNIR), P("kr", KRENKO)], [], { pool: { R: 1 } });
    expect({ plain: offered(s), every: offered(everyType(s, "kr")) }).toEqual({ plain: ["kr"], every: [] });
  });
  it("\"Tap an untapped Rebel you control\" (Otharri's return from the graveyard)", () => {
    const s0 = board([P("bear", BEARS)], [], { pool: { C: 2, R: 1, W: 1 } });
    const s = { ...s0, players: { ...s0.players, user: { ...s0.players.user, graveyard: [{ id: "ot", ...OTHARRI }] } } };
    const offered = (st) => legalActionsForPlayer(st, "user").filter((a) => (a.cardId === "ot" || a.permanentId === "ot") && (a.tapIds || []).includes("bear")).length;
    expect({ plain: offered(s), every: offered(everyType(s, "bear")) }).toEqual({ plain: 0, every: 1 });
  });
  it("\"Tap an untapped Druid you control: Add {G}\" (Seton, Krosan Protector) may tap it — the source prefers ANOTHER Druid", () => {
    const tapped = (st) => manaSources(st, "user").find((src) => src.permanentId === "se")?.extraTaps;
    const s = board([P("se", SETON), P("bear", BEARS)]);
    expect({ plain: tapped(s), every: tapped(everyType(s, "bear")) }).toEqual({ plain: ["se"], every: ["bear"] });
  });
});

describe("resolution readers", () => {
  it("Banner of Kinship enters with a fellowship counter for each creature of the chosen type — every type counts", () => {
    const enter = (st) => {
      const s = { ...st, players: { ...st.players, user: { ...st.players.user, hand: [{ id: "bk", ...BANNER_KINSHIP }], manaPool: { ...st.players.user.manaPool, C: 5 } } } };
      const after = resolveTopOfStack(dispatchAction(s, legalActionsForPlayer(s, "user").find((a) => a.kind === "cast-spell" && a.cardId === "bk")));
      const banner = after.players.user.battlefield.find((p) => p.card?.name === "Banner of Kinship");
      return [banner?.chosenType, banner?.counters?.fellowship || 0];
    };
    const s = board([P("ad", ARCHDRUID), P("ev", VANGUARD), P("bear", BEARS)]);
    expect({ plain: enter(s), every: enter(everyType(s, "bear")) }).toEqual({ plain: ["Elf", 2], every: ["Elf", 3] });
  });
  it("\"Champion a Goblin\" (Boggart Mob) exiles it instead of sacrificing the Mob", () => {
    const s = board([P("mob", BOGGART_MOB), P("bear", BEARS)]);
    const champ = (st) => { const after = applyChampion(st, { op: "champion", subtype: "Goblin" }, { controller: "user", sourceId: "mob" }); return { mob: after.players.user.battlefield.some((p) => p.id === "mob"), bearExiled: after.players.user.exile.some((c) => c.id === "c-bear") }; };
    expect({ plain: champ(s), every: champ(everyType(s, "bear")) }).toEqual({ plain: { mob: false, bearExiled: false }, every: { mob: true, bearExiled: true } });
  });
  it("\"sacrifice an Egg\" (Palani's Hatcher's pool) takes it", () => {
    const s = board([P("bear", BEARS)]);
    const sac = (st) => advanceSacrificeChain(st, { queue: [{ playerId: "user", what: "subtype:Egg" }] }).players.user.battlefield.length;
    expect({ plain: sac(s), every: sac(everyType(s, "bear")) }).toEqual({ plain: 1, every: 0 });
  });
  it("⭐ amass reuses it as the Army (no 0/0 token the rules never make) and writes no subtype onto it (CR 701.47a)", () => {
    const s = everyType(board([P("bear", BEARS)]), "bear");
    const after = applyAmass(s, { op: "amass", subtype: "Zombie", amount: 1 }, { controller: "user" });
    const bear = after.players.user.battlefield.find((p) => p.id === "bear");
    expect({ permanents: after.players.user.battlefield.length, counters: bear.counters?.["+1/+1"] || 0, type: bear.card.type }).toEqual({ permanents: 1, counters: 1, type: "Creature — Bear" });
  });
});

describe("conditions, mana, damage, the Ur-Dragon", () => {
  it("⭐ \"if you control another non-Human creature\" (Wildwood Tracker): an every-type creature is a Human", () => {
    const s = board([P("wt", WILDWOOD), P("bear", BEARS)]);
    const holds = (st) => evaluateInterveningIf(st, "you control another non-human creature", "user", { triggeringPermanentId: "wt", sourcePermanentId: "wt" });
    expect({ plain: holds(s), every: holds(everyType(s, "bear")) }).toEqual({ plain: true, every: false });
  });
  it("\"Activate only if you control a Dragon\" (Mox Jasper)", () => {
    const s = board([P("bear", BEARS)]);
    expect({ plain: evaluateInterveningIf(s, "you control a dragon", "user"), every: evaluateInterveningIf(everyType(s, "bear"), "you control a dragon", "user") }).toEqual({ plain: false, every: true });
  });
  it("\"If a Dinosaur is dealt damage this way\" (Marauding Raptor) — a changeling that entered is one", () => {
    const hit = (card) => evaluateInterveningIf(board([P("mr", RAPTOR), P("x", card, "user", { damagedBy: ["mr"] })]), "the triggering creature is a dinosaur dealt damage by this source", "user", { triggeringPermanentId: "x", sourcePermanentId: "mr" });
    expect({ bear: hit(BEARS), changeling: hit(OUTCAST) }).toEqual({ bear: false, changeling: true });
  });
  it("\"if you control another Elf\" (Dwynen's Elite)", () => {
    const s = board([P("de", DWYNEN), P("bear", BEARS)]);
    const holds = (st) => evaluateInterveningIf(st, "you control another elf", "user", { triggeringPermanentId: "de" });
    expect({ plain: holds(s), every: holds(everyType(s, "bear")) }).toEqual({ plain: false, every: true });
  });
  it("Temple Altisaur keeps 1 of the damage to another Dinosaur; Calamity Bearer doubles a Giant's", () => {
    const s = board([P("ta", ALTISAUR), P("cb", CALAMITY), P("bear", BEARS)]);
    const toBear = (st) => consultDamageAmount(st, { sourceId: "x", sourceController: "ai", amount: 5, targetKind: "creature", targetId: "bear" });
    const fromBear = (st) => consultDamageAmount(st, { sourceId: "bear", sourceController: "user", amount: 3, targetKind: "player", targetId: "ai" });
    const e = everyType(s, "bear");
    expect({ plain: [toBear(s), fromBear(s)], every: [toBear(e), fromBear(e)] }).toEqual({ plain: [5, 3], every: [1, 6] });
  });
  it("The Ur-Dragon draws for each attacking Dragon", () => {
    const lib = [1, 2, 3].map((i) => ({ id: `l${i}`, ...BEARS }));
    const s0 = board([P("ur", UR_DRAGON), P("bear", BEARS)], [], { combat: attack("bear") });
    const s = { ...s0, players: { ...s0.players, user: { ...s0.players.user, library: lib } } };
    // Counted off the library: a drawn permanent card may go straight onto the battlefield (the trigger's second half).
    const drew = (st) => st.players.user.library.length - applyUrDragonAttackTriggers(st).players.user.library.length;
    expect({ plain: drew(s), every: drew(everyType(s, "bear")) }).toEqual({ plain: 0, every: 1 });
  });
});

describe("CR 205.3d at the readers a non-creature word reaches: every creature type is never an artifact, a land type or a Treasure", () => {
  it("a Swamp count (Lashwrithe's +1/+1 per Swamp) never counts it", () => {
    const s = everyType(board([P("bear", BEARS, "user", { attachments: ["lw"] }), P("lw", LASHWRITHE, "user", { attachedTo: "bear" }), P("sw", SWAMP), P("b2", BEARS)]), "bear", "b2");
    expect(pt(s, "bear")).toEqual([3, 3]);
  });
  it("…nor the spell-side Swamp count (Magus of the Coffers' \"{B} for each Swamp you control\")", () => {
    const s = everyType(board([P("mc", MAGUS_COFFERS), P("sw", SWAMP), P("bear", BEARS)]), "mc", "bear");
    expect(countForSpec(s, { controller: "user" }, { kind: "permanentsYouControl", subtype: "Swamp" })).toBe(1);
  });
  it("\"if you control an artifact\" (Thopter Spy Network) stays false", () => {
    expect(evaluateInterveningIf(everyType(board([P("bear", BEARS)]), "bear"), "you control an artifact", "user")).toBe(false);
  });
  it("\"if you control another nonland permanent\" (Reclusive Wight) — it IS a nonland permanent", () => {
    const s = everyType(board([P("rw", WIGHT), P("bear", BEARS)]), "bear");
    expect(evaluateInterveningIf(s, "you control another nonland permanent", "user", { triggeringPermanentId: "rw", sourcePermanentId: "rw" })).toBe(true);
  });
  it("\"Sacrifice a Treasure\" (Professional Face-Breaker) never takes it", () => {
    expect(activations(everyType(board([P("pf", FACE_BREAKER), P("bear", BEARS)]), "bear"), "pf").length).toBe(0);
  });
  it("a changeling entering is never a Swamp (Dread Presence) or an artifact (Arcbound Crusher)", () => {
    const enter = (watcher) => { const s = board([P("w", watcher), P("oc", OUTCAST)]); return firedFrom(checkEnterTriggers(s, s.players.user.battlefield[1]), "w"); };
    expect({ dread: enter(DREAD_PRESENCE), crusher: enter(ARCBOUND_CRUSHER) }).toEqual({ dread: 0, crusher: 0 });
  });
  it("a LAND edict (Yawning Fissure's pool) never takes it", () => {
    const what = parseEffectClause(YAWNING_FISSURE.oracle, "Sorcery").atoms[0].what;
    const s = everyType(board([P("bear", BEARS)]), "bear");
    expect({ what, left: advanceSacrificeChain(s, { queue: [{ playerId: "user", what }] }).players.user.battlefield.length }).toEqual({ what: "land", left: 1 });
  });
  it("\"an ability of an artifact\" (Kurkesh) doesn't see its activation", () => {
    const s = everyType(board([P("ku", KURKESH), P("bear", BEARS)]), "bear");
    expect((checkAbilityActivatedTriggers(s, { permanent: s.players.user.battlefield[1], activatorId: "user", stackObjectId: "stk-x" }).pendingTriggers || []).length).toBe(0);
  });
  it("Allosaurus Shepherd's \"each Elf creature you control … 5/5\" reaches it", () => {
    const run = (st) => resolveTopOfStack(dispatchAction(st, activations(st, "as").find((a) => !a.isManaAbility)));
    const s = board([P("as", SHEPHERD), P("bear", BEARS)], [], { pool: { G: 6 } });
    expect({ plain: pt(run(s), "bear"), every: pt(run(everyType(s, "bear")), "bear") }).toEqual({ plain: [2, 2], every: [5, 5] });
  });
});

// ─── P·39 follow-up fixtures (real oracle, generated by cardIndex.publicCard) ──────────
const STEEL_OVERSEER = {"name":"Steel Overseer","type":"Artifact Creature — Construct","mana":"{2}","cmc":2,"power":"1","toughness":"1","keywords":[],"colors":[],"oracle":"{T}: Put a +1/+1 counter on each artifact creature you control."}; // native-activated
const MASKWOOD_P39A = {"name":"Maskwood Nexus","type":"Artifact","mana":"{4}","cmc":4,"keywords":[],"colors":[],"oracle":"Creatures you control are every creature type. The same is true for creature spells you control and creature cards you own that aren't on the battlefield.\n{3}, {T}: Create a 2/2 blue Shapeshifter creature token with changeling. (It is every creature type.)"}; // native-mixed

describe("a CARD-TYPE team filter is never met by every creature type (CR 205.3d)", () => {
  it("⭐ Steel Overseer's \"each artifact creature you control\" counters itself — never a changeling, never a creature made every type by Mirror Entity's effect or Maskwood Nexus", () => {
    const run = (st) => resolveTopOfStack(dispatchAction(st, activations(st, "so").find((a) => !a.isManaAbility)));
    const counters = (s, id) => s.players.user.battlefield.find((p) => p.id === id)?.counters?.["+1/+1"] || 0;
    const s = board([P("so", STEEL_OVERSEER), P("oc", OUTCAST), P("bear", BEARS)]);
    const plain = run(s);
    const every = run(everyType(s, "bear"));
    const maskwood = run(board([P("so", STEEL_OVERSEER), P("oc", OUTCAST), P("bear", BEARS), P("mw", MASKWOOD_P39A)]));
    const row = { plain: [counters(plain, "so"), counters(plain, "oc")], every: counters(every, "bear"), maskwood: [counters(maskwood, "so"), counters(maskwood, "bear"), counters(maskwood, "oc")] };
    expect(row).toEqual({ plain: [1, 0], every: 0, maskwood: [1, 0, 0] });
  });
});
