/**
 * KINDRED DOMINANCE (play-weighted #701; Kindred Judgment prints the same text) and ELDRITCH EVOLUTION (#756).
 *
 * KINDRED DOMINANCE — "Choose a creature type. Destroy all creatures that aren't of the chosen type."
 *   One atom, destroy-not-chosen-type (templateMatchers.matchDestroyNotChosenType — the second sentence reads the first one's
 *   choice, so the two collapse together). At resolution (removal.js):
 *  - THE CHOICE (CR 608.2d — made as the spell resolves; CR 205.3e — one existing creature type, the CR 205.3m list):
 *    choicePolicy.autoPickCreatureTypeToSpare — the type with the most of the caster's creatures net of the other players',
 *    then the most of the caster's own, then the first in sorted order; one type nobody has stands for "spare nothing".
 *  - THE SET: every permanent that is a creature right now and is not of the chosen type. Types are current ones
 *    (layers.permanentCreatureTypes, CR 613.1d): an added type counts, a replaced type does not, a double-faced creature has its
 *    front face's (CR 712.8d), a copy has the copied ones (CR 707.2). Every creature type — Changeling (CR 702.73a), an
 *    all-creature-types effect — is of the chosen type whatever was chosen.
 *  - THE DESTROY: the shared applyDestroyEffect, one event — indestructible (CR 702.12b), regeneration (CR 701.8c) and umbra
 *    armor (CR 702.89a) apply as to any destroy.
 *
 * ELDRITCH EVOLUTION — "As an additional cost to cast this spell, sacrifice a creature. / Search your library for a creature
 *   card with mana value X or less, where X is 2 plus the sacrificed creature's mana value. Put that card onto the battlefield,
 *   then shuffle. Exile Eldritch Evolution."
 *   The cost is the existing single-victim sacrifice lane (legalChoices offers one cast per victim, actionDispatcher pays it).
 *   One tutor atom (templateMatchers.matchTutorMvCapFromSacrificed) capped at 2 + the sacrificed creature's last-known mana
 *   value (CR 608.2h), which the dispatcher now freezes on the spell itself as the cost is paid; the trailing sentence is the
 *   parser's selfExile stamp. The mana value is the object's as it was sacrificed (layers.permanentManaValue): a token that is
 *   not a copy has 0 (CR 202.1b, 202.3a), a copy has the copied value (CR 707.2), an {X} in a cost is 0 (CR 107.3g, 202.3e).
 *   The found card enters through zones.enterCardFromZone, so its entry replacements apply.
 *
 * Real oracle fixtures (bundled Scryfall data, generated by cardIndex.publicCard — never typed by hand). Board states (a regen
 * shield, an attachment, a bestowed Aura, a chosen type stamped as the entry would) are built directly where a test says so;
 * the SYNTHETIC tests are labelled.
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, createGameState, createPermanent } from "./gameState.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { resolveTopOfStack } from "./gameEngine.js";
import { classifyCard } from "./coverage.js";
import { parseEffectClause, parseEffectProgram, programConfidence, programContainsCreatureMassRemoval, programContainsMassRemoval } from "./effects/parser.js";
import { resolveTutorChoice } from "./effects/runProgram.js";
import { ATOM_RESOLVERS, resolveAtom } from "./effects/effectAtoms.js";
import { addContinuousEffect, permanentCreatureTypes, permanentIsCreature, permIsEveryCreatureType } from "./layers.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const KINDRED_DOMINANCE = {"name":"Kindred Dominance","type":"Sorcery","mana":"{5}{B}{B}","cmc":7,"keywords":[],"colors":["B"],"oracle":"Choose a creature type. Destroy all creatures that aren't of the chosen type."}; // native-spell
const KINDRED_JUDGMENT = {"name":"Kindred Judgment","type":"Sorcery","mana":"{5}{W}{W}","cmc":7,"keywords":[],"colors":["W"],"oracle":"Choose a creature type. Destroy all creatures that aren't of the chosen type."}; // native-spell
const ELDRITCH_EVOLUTION = {"name":"Eldritch Evolution","type":"Sorcery","mana":"{1}{G}{G}","cmc":3,"keywords":[],"colors":["G"],"oracle":"As an additional cost to cast this spell, sacrifice a creature.\nSearch your library for a creature card with mana value X or less, where X is 2 plus the sacrificed creature's mana value. Put that card onto the battlefield, then shuffle. Exile Eldritch Evolution."}; // native-spell
const NEOFORM = {"name":"Neoform","type":"Sorcery","mana":"{G}{U}","cmc":2,"keywords":[],"colors":["G","U"],"oracle":"As an additional cost to cast this spell, sacrifice a creature.\nSearch your library for a creature card with mana value equal to 1 plus the sacrificed creature's mana value, put that card onto the battlefield with an additional +1/+1 counter on it, then shuffle."}; // arbiter-spell
const HARSH_MERCY = {"name":"Harsh Mercy","type":"Sorcery","mana":"{2}{W}","cmc":3,"keywords":[],"colors":["W"],"oracle":"Each player chooses a creature type. Destroy all creatures that aren't of a type chosen this way. They can't be regenerated."}; // arbiter-spell
const CRIPPLING_FEAR = {"name":"Crippling Fear","type":"Sorcery","mana":"{2}{B}{B}","cmc":4,"keywords":[],"colors":["B"],"oracle":"Choose a creature type. Creatures that aren't of the chosen type get -3/-3 until end of turn."}; // arbiter-spell
const RAISE_THE_PALISADE = {"name":"Raise the Palisade","type":"Sorcery","mana":"{4}{U}","cmc":5,"keywords":[],"colors":["U"],"oracle":"Choose a creature type. Return all creatures that aren't of the chosen type to their owners' hands."}; // arbiter-spell
const EXTINCTION = {"name":"Extinction","type":"Sorcery","mana":"{4}{B}","cmc":5,"keywords":[],"colors":["B"],"oracle":"Destroy all creatures of the creature type of your choice."}; // arbiter-spell
const LLANOWAR_ELVES = {"name":"Llanowar Elves","type":"Creature — Elf Druid","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G}."}; // native-mana
const FYNDHORN_ELVES = {"name":"Fyndhorn Elves","type":"Creature — Elf Druid","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G}."}; // native-mana
const ELVISH_VISIONARY = {"name":"Elvish Visionary","type":"Creature — Elf Shaman","mana":"{1}{G}","cmc":2,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"When this creature enters, draw a card."}; // native-trigger
const ELVISH_ARCHDRUID = {"name":"Elvish Archdruid","type":"Creature — Elf Druid","mana":"{1}{G}{G}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":"Other Elf creatures you control get +1/+1.\n{T}: Add {G} for each Elf you control."}; // native-mana
const PRIEST_OF_TITANIA = {"name":"Priest of Titania","type":"Creature — Elf Druid","mana":"{1}{G}","cmc":2,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G} for each Elf on the battlefield."}; // native-mana
const RAGING_GOBLIN = {"name":"Raging Goblin","type":"Creature — Goblin Berserker","mana":"{R}","cmc":1,"power":"1","toughness":"1","keywords":["Haste"],"colors":["R"],"oracle":"Haste (This creature can attack and {T} as soon as it comes under your control.)"}; // native-body
const GRIZZLY_BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const WALKING_CORPSE = {"name":"Walking Corpse","type":"Creature — Zombie","mana":"{1}{B}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["B"],"oracle":""}; // native-body
const GRAVEDIGGER = {"name":"Gravedigger","type":"Creature — Zombie","mana":"{3}{B}","cmc":4,"power":"2","toughness":"2","keywords":[],"colors":["B"],"oracle":"When this creature enters, you may return target creature card from your graveyard to your hand."}; // native-trigger
const SCATHE_ZOMBIES = {"name":"Scathe Zombies","type":"Creature — Zombie","mana":"{2}{B}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["B"],"oracle":""}; // native-body
const UNIVERSAL_AUTOMATON = {"name":"Universal Automaton","type":"Artifact Creature — Shapeshifter","mana":"{1}","cmc":1,"power":"1","toughness":"1","keywords":["Changeling"],"colors":[],"oracle":"Changeling (This card is every creature type.)"}; // native-body
const CHAMELEON_COLOSSUS = {"name":"Chameleon Colossus","type":"Creature — Shapeshifter","mana":"{2}{G}{G}","cmc":4,"power":"4","toughness":"4","keywords":["Protection","Changeling"],"colors":["G"],"oracle":"Changeling (This card is every creature type.)\nProtection from black\n{2}{G}{G}: This creature gets +X/+X until end of turn, where X is its power."}; // body-only
const DARKSTEEL_MYR = {"name":"Darksteel Myr","type":"Artifact Creature — Myr","mana":"{3}","cmc":3,"power":"0","toughness":"1","keywords":["Indestructible"],"colors":[],"oracle":"Indestructible (Damage and effects that say \"destroy\" don't destroy this creature. If its toughness is 0 or less, it still dies.)"}; // native-body
const DRUDGE_SKELETONS = {"name":"Drudge Skeletons","type":"Creature — Skeleton","mana":"{1}{B}","cmc":2,"power":"1","toughness":"1","keywords":["Heal","Regenerate"],"colors":["B"],"oracle":"{B}: Regenerate this creature. (The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)"}; // native-activated
const HYENA_UMBRA = {"name":"Hyena Umbra","type":"Enchantment — Aura","mana":"{W}","cmc":1,"keywords":["Umbra armor","Enchant"],"colors":["W"],"oracle":"Enchant creature\nEnchanted creature gets +1/+1 and has first strike.\nUmbra armor (If enchanted creature would be destroyed, instead remove all damage from it and destroy this Aura.)"}; // native-aura
const MUTAVAULT = {"name":"Mutavault","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{1}: This land becomes a 2/2 creature with all creature types until end of turn. It's still a land."}; // land
const DELVER = {"name":"Delver of Secrets // Insectile Aberration","type":"Creature — Human Wizard // Creature — Human Insect","mana":"{U}","cmc":1,"power":"1","toughness":"1","keywords":["Flying","Transform"],"layout":"transform","colors":[],"oracle":"Delver of Secrets - Creature — Human Wizard {U}\nAt the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform this creature.\n//\nInsectile Aberration - Creature — Human Insect \nFlying"}; // body-only
const SCUTE_MOB = {"name":"Scute Mob","type":"Creature — Insect","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"At the beginning of your upkeep, if you control five or more lands, put four +1/+1 counters on this creature."}; // native-trigger
const CAUSTIC_CATERPILLAR = {"name":"Caustic Caterpillar","type":"Creature — Insect","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{1}{G}, Sacrifice this creature: Destroy target artifact or enchantment."}; // native-activated
const GINGERBRUTE = {"name":"Gingerbrute","type":"Artifact Creature — Food Golem","mana":"{1}","cmc":1,"power":"1","toughness":"1","keywords":["Haste"],"colors":[],"oracle":"Haste (This creature can attack and {T} as soon as it comes under your control.)\n{1}: This creature can't be blocked this turn except by creatures with haste.\n{2}, {T}, Sacrifice this creature: You gain 3 life."}; // native-activated
const TENTH_DOCTOR = {"name":"The Tenth Doctor","type":"Legendary Creature — Time Lord Doctor","mana":"{3}{U}{R}","cmc":5,"power":"3","toughness":"5","keywords":["Allons-y!","Time Travel","Timey-Wimey"],"colors":["R","U"],"oracle":"Allons-y! — Whenever you attack, exile cards from the top of your library until you exile a nonland card. Put three time counters on it. If it doesn't have suspend, it gains suspend.\nTimey-Wimey — {7}: Time travel three times. Activate only as a sorcery. (For each suspended card you own and each permanent you control with a time counter on it, you may add or remove a time counter. Then do it two more times.)"}; // body-only
const MISSY = {"name":"Missy","type":"Legendary Creature — Time Lord Rogue","mana":"{3}{U}{B}{R}","cmc":6,"power":"4","toughness":"5","keywords":[],"colors":["B","R","U"],"oracle":"Whenever another nonartifact creature dies, return it to the battlefield under your control face down and tapped. It's a 2/2 Cyberman artifact creature.\nAt the beginning of your end step, each opponent faces a villainous choice — Each artifact creature you control deals 1 damage to that opponent, or you draw a card and chaos ensues."}; // body-only
const CENTAUR_COURSER = {"name":"Centaur Courser","type":"Creature — Centaur Warrior","mana":"{2}{G}","cmc":3,"power":"3","toughness":"3","keywords":[],"colors":["G"],"oracle":""}; // native-body
const HILL_GIANT = {"name":"Hill Giant","type":"Creature — Giant","mana":"{3}{R}","cmc":4,"power":"3","toughness":"3","keywords":[],"colors":["R"],"oracle":""}; // native-body
const SIEGE_MASTODON = {"name":"Siege Mastodon","type":"Creature — Elephant","mana":"{4}{W}","cmc":5,"power":"3","toughness":"5","keywords":[],"colors":["W"],"oracle":""}; // native-body
const COLOSSAL_DREADMAW = {"name":"Colossal Dreadmaw","type":"Creature — Dinosaur","mana":"{4}{G}{G}","cmc":6,"power":"6","toughness":"6","keywords":["Trample"],"colors":["G"],"oracle":"Trample (This creature can deal excess combat damage to the player or planeswalker it's attacking.)"}; // native-body
const WALKING_BALLISTA = {"name":"Walking Ballista","type":"Artifact Creature — Construct","mana":"{X}{X}","cmc":0,"power":"0","toughness":"0","keywords":[],"colors":[],"oracle":"This creature enters with X +1/+1 counters on it.\n{4}: Put a +1/+1 counter on this creature.\nRemove a +1/+1 counter from this creature: It deals 1 damage to any target."}; // native-activated
const SOL_RING = {"name":"Sol Ring","type":"Artifact","mana":"{1}","cmc":1,"keywords":[],"colors":[],"oracle":"{T}: Add {C}{C}."}; // native-mana
const FOREST = {"name":"Forest","type":"Basic Land — Forest","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {G}.)"}; // land
const FLING = {"name":"Fling","type":"Instant","mana":"{1}{R}","cmc":2,"keywords":[],"colors":["R"],"oracle":"As an additional cost to cast this spell, sacrifice a creature.\nFling deals damage equal to the sacrificed creature's power to any target."}; // native-spell
const RAISE_THE_ALARM = {"name":"Raise the Alarm","type":"Instant","mana":"{1}{W}","cmc":2,"keywords":[],"colors":["W"],"oracle":"Create two 1/1 white Soldier creature tokens."}; // native-spell
const BLOOD_ARTIST = {"name":"Blood Artist","type":"Creature — Vampire","mana":"{1}{B}","cmc":2,"power":"0","toughness":"1","keywords":[],"colors":["B"],"oracle":"Whenever this creature or another creature dies, target player loses 1 life and you gain 1 life."}; // native-trigger
const MISTFORM_DREAMER = {"name":"Mistform Dreamer","type":"Creature — Illusion","mana":"{2}{U}","cmc":3,"power":"2","toughness":"1","keywords":["Flying"],"colors":["U"],"oracle":"Flying\n{1}: This creature becomes the creature type of your choice until end of turn."}; // native-activated
const QUASIDUPLICATE = {"name":"Quasiduplicate","type":"Sorcery","mana":"{1}{U}{U}","cmc":3,"keywords":["Jump","Jump-start"],"colors":["U"],"oracle":"Create a token that's a copy of target creature you control.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs. Then exile this card.)"}; // native-spell
const COUNTERSPELL = {"name":"Counterspell","type":"Instant","mana":"{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Counter target spell."}; // native-spell
const TWINCAST = {"name":"Twincast","type":"Instant","mana":"{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Copy target instant or sorcery spell. You may choose new targets for the copy."}; // native-spell
const MASKWOOD_NEXUS = {"name":"Maskwood Nexus","type":"Artifact","mana":"{4}","cmc":4,"keywords":[],"colors":[],"oracle":"Creatures you control are every creature type. The same is true for creature spells you control and creature cards you own that aren't on the battlefield.\n{3}, {T}: Create a 2/2 blue Shapeshifter creature token with changeling. (It is every creature type.)"}; // native-mixed
const BOON_SATYR = {"name":"Boon Satyr","type":"Enchantment Creature — Satyr","mana":"{1}{G}{G}","cmc":3,"power":"4","toughness":"2","keywords":["Bestow","Flash"],"colors":["G"],"oracle":"Flash\nBestow {3}{G}{G} (If you cast this card for its bestow cost, it's an Aura spell with enchant creature. It becomes a creature again if it's not attached.)\nEnchanted creature gets +4/+2."}; // native-aura
const FABLE = {"name":"Fable of the Mirror-Breaker // Reflection of Kiki-Jiki","type":"Enchantment — Saga // Enchantment Creature — Goblin Shaman","mana":"{2}{R}","cmc":3,"keywords":["Transform","Treasure"],"layout":"transform","colors":[],"oracle":"Fable of the Mirror-Breaker - Enchantment — Saga {2}{R}\n(As this Saga enters and after your draw step, add a lore counter.)\nI — Create a 2/2 red Goblin Shaman creature token with \"Whenever this token attacks, create a Treasure token.\"\nII — You may discard up to two cards. If you do, draw that many cards.\nIII — Exile this Saga, then return it to the battlefield transformed under your control.\n//\nReflection of Kiki-Jiki - Enchantment Creature — Goblin Shaman \n{1}, {T}: Create a token that's a copy of another target nonlegendary creature you control, except it has haste. Sacrifice it at the beginning of the next end step."}; // body-only
const IMPOSSIBLE_MAN = {"name":"Impossible Man","type":"Legendary Creature — Alien Shapeshifter","mana":"{2}{U}","cmc":3,"power":"1","toughness":"4","keywords":["Flying"],"colors":["U"],"oracle":"Flying\n{2}{U}: Impossible Man becomes a copy of another target permanent until end of turn, except his name is Impossible Man."}; // native-activated
const ADAPTIVE_AUTOMATON = {"name":"Adaptive Automaton","type":"Artifact Creature — Construct","mana":"{3}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":[],"oracle":"As this creature enters, choose a creature type.\nThis creature is the chosen type in addition to its other types.\nOther creatures you control of the chosen type get +1/+1."}; // native-static
const KALONIAN_HYDRA = {"name":"Kalonian Hydra","type":"Creature — Hydra","mana":"{3}{G}{G}","cmc":5,"power":"0","toughness":"0","keywords":["Trample","Double"],"colors":["G"],"oracle":"Trample\nThis creature enters with four +1/+1 counters on it.\nWhenever this creature attacks, double the number of +1/+1 counters on each creature you control."}; // native-trigger
const KROVIKAN_MIST = {"name":"Krovikan Mist","type":"Creature — Illusion","mana":"{1}{U}","cmc":2,"power":"*","toughness":"*","keywords":["Flying"],"colors":["U"],"oracle":"Flying\nKrovikan Mist's power and toughness are each equal to the number of Illusions on the battlefield."}; // body-only
const JACES_PHANTASM = {"name":"Jace's Phantasm","type":"Creature — Illusion","mana":"{U}","cmc":1,"power":"1","toughness":"1","keywords":["Flying"],"colors":["U"],"oracle":"Flying\nThis creature gets +4/+4 as long as an opponent has ten or more cards in their graveyard."}; // native-static
const THASSA = {"name":"Thassa, God of the Sea","type":"Legendary Enchantment Creature — God","mana":"{2}{U}","cmc":3,"power":"5","toughness":"5","keywords":["Indestructible","Scry"],"colors":["U"],"oracle":"Indestructible\nAs long as your devotion to blue is less than five, Thassa isn't a creature. (Each {U} in the mana costs of permanents you control counts toward your devotion to blue.)\nAt the beginning of your upkeep, scry 1.\n{1}{U}: Target creature you control can't be blocked this turn."}; // native-mixed

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const H = (id, card) => ({ ...card, id });
// Attach aura `auraId` to host `hostId` on a list of permanents (both sides of the link, as the engine stores it).
const attach = (perms, auraId, hostId) => perms.map((p) => (p.id === auraId ? { ...p, attachedTo: hostId } : p.id === hostId ? { ...p, attachments: [...(p.attachments || []), auraId] } : p));
function board({ user = [], ai = [], hand = [], aiHand = [], lib = [], pool = {}, aiPool = {} } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  return { ...g, turn: 5, activePlayer: "user", priorityHolder: "user", phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: { ...g.players,
      user: { ...g.players.user, battlefield: user, hand, manaPool: { ...g.players.user.manaPool, ...pool }, library: lib.map((card, i) => ({ ...card, id: `lib${i}` })) },
      ai: { ...g.players.ai, battlefield: ai, hand: aiHand, manaPool: { ...g.players.ai.manaPool, ...aiPool }, library: [1, 2, 3].map((i) => ({ ...GRIZZLY_BEARS, id: `ai-lib${i}` })) } } };
}
const offers = (s, who, cardId) => legalActionsForPlayer(s, who).filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
// Cast through the real offer → dispatch path; `pick` narrows the offer (a sacrifice victim, a target).
const cast = (s, cardId, pick = () => true, who = "user") => {
  const offer = offers(s, who, cardId).find(pick);
  expect(offer).toBeTruthy();
  return dispatchAction(s, offer);
};
// Activate an ability of `permId` on its controller's own priority and resolve it; priority returns to the user.
const activate = (s, who, permId, pick = () => true) => {
  const as = { ...s, activePlayer: who, priorityHolder: who };
  const offer = legalActionsForPlayer(as, who).find((a) => a.kind === "activate-ability" && a.permanentId === permId && pick(a));
  expect(offer).toBeTruthy();
  return { ...resolveTopOfStack(dispatchAction(as, offer)), activePlayer: "user", priorityHolder: "user" };
};
const ids = (s, who) => s.players[who].battlefield.map((p) => p.id).sort();
const names = (cards) => cards.map((c) => c.name).sort();
const errors = (s) => (s.log || []).filter((e) => e.kind === "stack-resolve-error");
const ctxUser = { controller: "user", sourceId: null, cardName: "test", targets: [] };

// Kindred Dominance: {5}{B}{B} from the pool, cast and resolved.
const KD_POOL = { B: 7 };
const dominate = (s) => resolveTopOfStack(cast(s, "kd"));
const kdBoard = (o = {}) => board({ hand: [H("kd", KINDRED_DOMINANCE)], pool: KD_POOL, ...o });
const kdLog = (s) => (s.log || []).filter((e) => e.effect === "destroy-not-chosen-type").map((e) => ({ chosenType: e.chosenType, notOfType: e.notOfType, ofType: e.ofType }));

// Eldritch Evolution: {1}{G}{G} from the pool; the cast sacrifices `victimId`; the search pauses on the tutor choice.
const EE_POOL = { G: 3 };
const EE_LIBRARY = [LLANOWAR_ELVES, GRIZZLY_BEARS, CENTAUR_COURSER, HILL_GIANT, SIEGE_MASTODON, COLOSSAL_DREADMAW, WALKING_BALLISTA, SOL_RING, FOREST];
const eeBoard = (o = {}) => board({ hand: [H("ee", ELDRITCH_EVOLUTION)], pool: EE_POOL, lib: EE_LIBRARY, ...o });
const evolve = (s, victimId) => resolveTopOfStack(cast(s, "ee", (a) => a.sacCreatureId === victimId));
const candidates = (s) => (s.pendingChoice?.kind === "tutor-search" ? names(s.pendingChoice.candidates) : null);
const fetch = (s, name) => resolveTutorChoice(s, name == null ? null : s.pendingChoice.candidates.find((c) => c.name === name).id);

describe("the cards and their parse", () => {
  it("classify: Kindred Dominance, Kindred Judgment and Eldritch Evolution native-spell; the neighbours this slice must not touch stay where they were", () => {
    const row = Object.fromEntries(Object.entries({ KINDRED_DOMINANCE, KINDRED_JUDGMENT, ELDRITCH_EVOLUTION, NEOFORM, HARSH_MERCY, EXTINCTION, CRIPPLING_FEAR, RAISE_THE_PALISADE }).map(([k, c]) => [k, classifyCard(c)]));
    console.log("  WITNESS classify", JSON.stringify(row)); // vitest 4 needs --disable-console-intercept
    expect(row).toEqual({ KINDRED_DOMINANCE: "native-spell", KINDRED_JUDGMENT: "native-spell", ELDRITCH_EVOLUTION: "native-spell",
      NEOFORM: "arbiter-spell", HARSH_MERCY: "arbiter-spell", EXTINCTION: "arbiter-spell", CRIPPLING_FEAR: "arbiter-spell", RAISE_THE_PALISADE: "arbiter-spell" });
  });

  it("the Kindred Dominance parse: ONE atom, no target, not an X spell — and both printings parse alike", () => {
    const p = parseEffectProgram(KINDRED_DOMINANCE);
    expect({ confidence: programConfidence(p), atoms: p.atoms, xSpell: p.xSpell, costs: p.additionalCosts, selfExile: p.selfExile })
      .toEqual({ confidence: "high", atoms: [{ op: "destroy-not-chosen-type", targetType: null }], xSpell: false, costs: undefined, selfExile: undefined });
    expect(parseEffectProgram(KINDRED_JUDGMENT).atoms).toEqual(p.atoms);
    expect(typeof ATOM_RESOLVERS["destroy-not-chosen-type"]).toBe("function");
  });

  it("the Eldritch Evolution parse: the sacrifice cost, ONE capped tutor to the battlefield, the self-exile stamp, not an X spell", () => {
    const p = parseEffectProgram(ELDRITCH_EVOLUTION);
    expect({ confidence: programConfidence(p), atoms: p.atoms, xSpell: p.xSpell, costs: p.additionalCosts, selfExile: p.selfExile }).toEqual({
      confidence: "high",
      atoms: [{ op: "tutor", filter: { groups: [["creature"]], mvMaxFromSacrificedPlus: 2 }, filterLabel: "creature card with mana value 2 plus the sacrificed creature's or less", destination: "battlefield", entersTapped: false, targetType: null }],
      xSpell: false, costs: [{ kind: "sacrifice", sacType: "creature" }], selfExile: true,
    });
  });

  it("near misses stay unparsed: either sentence alone, another chooser, another verb, another filter, a rider before or after", () => {
    const atoms = (clause) => parseEffectClause(clause, "Sorcery")?.atoms ?? [];
    expect({
      chooseOnly: atoms("Choose a creature type."),
      destroyOnly: atoms("Destroy all creatures that aren't of the chosen type."),
      eachPlayer: atoms("Each player chooses a creature type. Destroy all creatures that aren't of a type chosen this way."),
      ofTheType: atoms("Choose a creature type. Destroy all creatures of the chosen type."),
      exile: atoms("Choose a creature type. Exile all creatures that aren't of the chosen type."),
      riderAfter: atoms("Choose a creature type. Destroy all creatures that aren't of the chosen type. You gain 2 life."),
      riderBefore: atoms("You gain 2 life. Choose a creature type. Destroy all creatures that aren't of the chosen type."),
    }).toEqual({ chooseOnly: [], destroyOnly: [], eachPlayer: [], ofTheType: [], exile: [], riderAfter: [], riderBefore: [] });
    expect({
      searchOnly: atoms("Search your library for a creature card with mana value X or less, where X is 2 plus the sacrificed creature's mana value."),
      putOnly: atoms("Put that card onto the battlefield, then shuffle."),
      artifact: atoms("Search your library for an artifact card with mana value X or less, where X is 2 plus the sacrificed creature's mana value. Put that card onto the battlefield, then shuffle."),
      power: atoms("Search your library for a creature card with mana value X or less, where X is 2 plus the sacrificed creature's power. Put that card onto the battlefield, then shuffle."),
      toHand: atoms("Search your library for a creature card with mana value X or less, where X is 2 plus the sacrificed creature's mana value. Put that card into your hand, then shuffle."),
      riderAfter: atoms("Search your library for a creature card with mana value X or less, where X is 2 plus the sacrificed creature's mana value. Put that card onto the battlefield, then shuffle. You gain 2 life."),
      riderBefore: atoms("You gain 2 life. Search your library for a creature card with mana value X or less, where X is 2 plus the sacrificed creature's mana value. Put that card onto the battlefield, then shuffle."),
    }).toEqual({ searchOnly: [], putOnly: [], artifact: [], power: [], toHand: [], riderAfter: [], riderBefore: [] });
  });

  it("the AI holds Kindred Dominance like any symmetric wipe, and it unlocks as a creature wipe when clearly behind", () => {
    const p = parseEffectProgram(KINDRED_DOMINANCE);
    expect({ held: programContainsMassRemoval(p), creatureWipe: programContainsCreatureMassRemoval(p) }).toEqual({ held: true, creatureWipe: true });
  });

  it("SYNTHETIC SHAPE (the rider stamp): a \"can't be regenerated\" sentence the parse text strips is put back on the atom, and the destroy honours it", () => {
    const p = parseEffectClause("Choose a creature type. Destroy all creatures that aren't of the chosen type. They can't be regenerated.", "Sorcery");
    expect(p.atoms).toEqual([{ op: "destroy-not-chosen-type", targetType: null, cannotRegenerate: true }]);
    const s0 = board({ ai: [P("drudge", DRUDGE_SKELETONS, "ai", { regenShields: 1 })] });
    const out = (atom) => ids(resolveAtom(s0, atom, ctxUser), "ai");
    expect({ printed: out(parseEffectProgram(KINDRED_DOMINANCE).atoms[0]), withRider: out(p.atoms[0]) }).toEqual({ printed: ["drudge"], withRider: [] });
  });
});

describe("⭐ Kindred Dominance — cast, resolved", () => {
  it("⭐ the caster's creatures share a type and the opponent's do not: the opponent's board is destroyed, the caster's stays", () => {
    // user: Llanowar Elves, Fyndhorn Elves (Elf Druid), Elvish Visionary (Elf Shaman) → Elf ×3. ai: a Bear, a Goblin Berserker, a Giant.
    const s0 = kdBoard({ user: [P("llanowar", LLANOWAR_ELVES), P("fyndhorn", FYNDHORN_ELVES), P("visionary", ELVISH_VISIONARY)],
      ai: [P("bears", GRIZZLY_BEARS, "ai"), P("goblin", RAGING_GOBLIN, "ai"), P("giant", HILL_GIANT, "ai")] });
    const onStack = cast(s0, "kd");
    const s = resolveTopOfStack(onStack);
    const row = { castTargets: onStack.stack[0].payload.params.targets, user: ids(s, "user"), ai: ids(s, "ai"), userGraveyard: names(s.players.user.graveyard), aiGraveyard: names(s.players.ai.graveyard),
      log: kdLog(s), stack: s.stack.length, pending: s.pendingChoice ?? null, errors: errors(s).length };
    console.log("  WITNESS sharedType", JSON.stringify(row));
    expect(row).toEqual({ castTargets: [], user: ["fyndhorn", "llanowar", "visionary"], ai: [], userGraveyard: ["Kindred Dominance"], aiGraveyard: ["Grizzly Bears", "Hill Giant", "Raging Goblin"],
      log: [{ chosenType: "elf", notOfType: 3, ofType: 3 }], stack: 0, pending: null, errors: 0 });
  });

  it("⭐ every creature type survives any choice: a changeling on either side, an animated Mutavault, and every creature under Maskwood Nexus", () => {
    // A: both players hold a changeling; the opponent also animates Mutavault ("a 2/2 creature with all creature types").
    const a0 = activate(kdBoard({ user: [P("llanowar", LLANOWAR_ELVES), P("colossus", CHAMELEON_COLOSSUS)],
      ai: [P("automaton", UNIVERSAL_AUTOMATON, "ai"), P("vault", MUTAVAULT, "ai"), P("bears", GRIZZLY_BEARS, "ai")], aiPool: { C: 1 } }), "ai", "vault");
    const a = dominate(a0);
    // B: the caster's Maskwood Nexus makes the caster's creatures every creature type — a Bear and a Giant, no type shared.
    const b0 = kdBoard({ user: [P("nexus", MASKWOOD_NEXUS), P("bears", GRIZZLY_BEARS), P("giant", HILL_GIANT)], ai: [P("corpse", WALKING_CORPSE, "ai"), P("goblin", RAGING_GOBLIN, "ai")] });
    const b = dominate(b0);
    const row = {
      changelings: { vaultIsEveryType: permIsEveryCreatureType(a0, "vault"), user: ids(a, "user"), ai: ids(a, "ai"), log: kdLog(a) },
      nexus: { bearsAreEveryType: permIsEveryCreatureType(b0, "bears"), user: ids(b, "user"), ai: ids(b, "ai"), log: kdLog(b) },
    };
    console.log("  WITNESS everyType", JSON.stringify(row));
    expect(row).toEqual({
      changelings: { vaultIsEveryType: true, user: ["colossus", "llanowar"], ai: ["automaton", "vault"], log: [{ chosenType: "druid", notOfType: 1, ofType: 4 }] },
      // nothing the caster controls names a type, so the pick is the type that spares nothing of the opponent's
      nexus: { bearsAreEveryType: true, user: ["bears", "giant", "nexus"], ai: [], log: [{ chosenType: "advisor", notOfType: 2, ofType: 2 }] },
    });
  });

  it("⭐ Changeling is a copiable value: Impossible Man (an Alien Shapeshifter) as a copy of Chameleon Colossus is every creature type and is spared; as itself it is destroyed", () => {
    const base = () => kdBoard({ user: [P("llanowar", LLANOWAR_ELVES)], ai: [P("man", IMPOSSIBLE_MAN, "ai"), P("colossus", CHAMELEON_COLOSSUS, "ai")], aiPool: { U: 3 } });
    const copied = activate(base(), "ai", "man", (a) => (a.targets || []).some((t) => t.id === "colossus"));
    const row = { asCopy: { everyType: permIsEveryCreatureType(copied, "man"), ai: ids(dominate(copied), "ai") }, asItself: { everyType: permIsEveryCreatureType(base(), "man"), ai: ids(dominate(base()), "ai") } };
    console.log("  WITNESS copiedChangeling", JSON.stringify(row));
    expect(row).toEqual({ asCopy: { everyType: true, ai: ["colossus", "man"] }, asItself: { everyType: false, ai: ["colossus"] } });
  });

  it("⭐ the destroy is the shared one: indestructible, a regeneration shield and umbra armor each keep a creature of another type", () => {
    const ai = attach([P("myr", DARKSTEEL_MYR, "ai"), P("drudge", DRUDGE_SKELETONS, "ai", { regenShields: 1 }), P("bears", GRIZZLY_BEARS, "ai", { damageMarked: 1 }), P("umbra", HYENA_UMBRA, "ai"), P("giant", HILL_GIANT, "ai")], "umbra", "bears");
    const s = dominate(kdBoard({ user: [P("llanowar", LLANOWAR_ELVES)], ai }));
    const drudge = s.players.ai.battlefield.find((p) => p.id === "drudge");
    const bears = s.players.ai.battlefield.find((p) => p.id === "bears");
    const row = { user: ids(s, "user"), ai: ids(s, "ai"), aiGraveyard: names(s.players.ai.graveyard), drudge: { shields: drudge?.regenShields ?? 0, tapped: drudge?.tapped }, bearsDamage: bears?.damageMarked, log: kdLog(s) };
    console.log("  WITNESS sharedDestroy", JSON.stringify(row));
    expect(row).toEqual({ user: ["llanowar"], ai: ["bears", "drudge", "myr"], aiGraveyard: ["Hill Giant", "Hyena Umbra"], drudge: { shields: 0, tapped: true }, bearsDamage: 0,
      log: [{ chosenType: "druid", notOfType: 4, ofType: 1 }] });
  });

  it("⭐ only creatures: a bestowed Aura and a Saga whose back face is a creature are not creatures and are not destroyed", () => {
    // ai: Colossal Dreadmaw wearing a bestowed Boon Satyr (an Aura while attached, CR 702.103), and Fable of the Mirror-Breaker.
    const s0 = kdBoard({ user: [P("llanowar", LLANOWAR_ELVES)],
      ai: [P("maw", COLOSSAL_DREADMAW, "ai", { attachments: ["satyr"] }), P("satyr", BOON_SATYR, "ai", { attachedTo: "maw", bestowed: true }), P("fable", FABLE, "ai", { counters: { lore: 1 } })] });
    const s = dominate(s0);
    const row = { before: { satyrIsCreature: permanentIsCreature(s0, "satyr"), fableIsCreature: permanentIsCreature(s0, "fable") }, ai: ids(s, "ai"), aiGraveyard: names(s.players.ai.graveyard),
      satyrIsCreatureAfter: permanentIsCreature(s, "satyr"), log: kdLog(s) };
    console.log("  WITNESS onlyCreatures", JSON.stringify(row));
    expect(row).toEqual({ before: { satyrIsCreature: false, fableIsCreature: false }, ai: ["fable", "satyr"], aiGraveyard: ["Colossal Dreadmaw"], satyrIsCreatureAfter: true,
      log: [{ chosenType: "druid", notOfType: 1, ofType: 1 }] });
  });

  it("⭐ one event: a Blood Artist destroyed with the rest sees every creature that died", () => {
    const s = dominate(kdBoard({ user: [P("llanowar", LLANOWAR_ELVES), P("fyndhorn", FYNDHORN_ELVES)], ai: [P("artist", BLOOD_ARTIST, "ai"), P("bears", GRIZZLY_BEARS, "ai"), P("giant", HILL_GIANT, "ai")] }));
    const row = { died: s.players.ai.graveyard.length, artistTriggers: s.stack.filter((o) => o.source?.name === "Blood Artist").length + (s.pendingTriggers || []).filter((t) => t.sourceName === "Blood Artist" || t.source?.name === "Blood Artist").length };
    console.log("  WITNESS oneEvent", JSON.stringify(row));
    expect(row).toEqual({ died: 3, artistTriggers: 3 });
  });

  it("Kindred Judgment is the same card in white", () => {
    const s0 = board({ hand: [H("kj", KINDRED_JUDGMENT)], pool: { W: 7 }, user: [P("llanowar", LLANOWAR_ELVES), P("fyndhorn", FYNDHORN_ELVES)], ai: [P("bears", GRIZZLY_BEARS, "ai")] });
    const s = resolveTopOfStack(cast(s0, "kj"));
    expect({ user: ids(s, "user"), ai: ids(s, "ai"), userGraveyard: names(s.players.user.graveyard), log: kdLog(s) })
      .toEqual({ user: ["fyndhorn", "llanowar"], ai: [], userGraveyard: ["Kindred Judgment"], log: [{ chosenType: "druid", notOfType: 1, ofType: 2 }] });
  });
});

describe("⭐ of the chosen type — a creature's CURRENT creature types", () => {
  it("⭐ a type an effect ADDED counts: Adaptive Automaton (a Construct) that chose Elf is an Elf and is spared", () => {
    // The chosen type is stamped as the entry stamps it (enterReplacements: perm.chosenType); layer 4 adds it to the Construct.
    const s0 = kdBoard({ user: [P("llanowar", LLANOWAR_ELVES), P("fyndhorn", FYNDHORN_ELVES), P("automaton", ADAPTIVE_AUTOMATON, "user", { chosenType: "Elf" })], ai: [P("bears", GRIZZLY_BEARS, "ai")] });
    const s = dominate(s0);
    const row = { automatonTypes: permanentCreatureTypes(s0, "automaton"), user: ids(s, "user"), ai: ids(s, "ai"), log: kdLog(s) };
    console.log("  WITNESS addedType", JSON.stringify(row));
    expect(row).toEqual({ automatonTypes: ["construct", "elf"], user: ["automaton", "fyndhorn", "llanowar"], ai: [], log: [{ chosenType: "elf", notOfType: 1, ofType: 3 }] });
  });

  it("⭐ a type an effect REPLACED does not: Mistform Dreamer (printed Illusion) that became a Bear is destroyed when Illusion is chosen", () => {
    // ai activates Mistform Dreamer ("becomes the creature type of your choice until end of turn"; the engine picks the type of
    // its controller's other creatures — Bear). The caster holds two Illusions, so Illusion is chosen.
    const s0 = activate(kdBoard({ user: [P("mist", KROVIKAN_MIST), P("phantasm", JACES_PHANTASM)], ai: [P("dreamer", MISTFORM_DREAMER, "ai"), P("bears", GRIZZLY_BEARS, "ai")], aiPool: { C: 1 } }), "ai", "dreamer");
    const s = dominate(s0);
    const row = { dreamerTypes: permanentCreatureTypes(s0, "dreamer"), user: ids(s, "user"), ai: ids(s, "ai"), log: kdLog(s) };
    console.log("  WITNESS replacedType", JSON.stringify(row));
    expect(row).toEqual({ dreamerTypes: ["bear"], user: ["mist", "phantasm"], ai: [], log: [{ chosenType: "illusion", notOfType: 2, ofType: 2 }] });
  });

  it("⭐ a double-faced creature has its front face's types: Delver of Secrets (Human Wizard // Human Insect) is no Insect, and is a Human once", () => {
    // user: two Insects. ai: Delver of Secrets, front face up (the engine never transforms it).
    const s0 = kdBoard({ user: [P("scute", SCUTE_MOB), P("caterpillar", CAUSTIC_CATERPILLAR)], ai: [P("delver", DELVER, "ai")] });
    const s = dominate(s0);
    const row = { delverTypes: permanentCreatureTypes(s0, "delver"), typesOnceGone: permanentCreatureTypes(s, "delver"), user: ids(s, "user"), ai: ids(s, "ai"), aiGraveyard: names(s.players.ai.graveyard), log: kdLog(s) };
    console.log("  WITNESS frontFace", JSON.stringify(row));
    expect(row).toEqual({ delverTypes: ["human", "wizard"], typesOnceGone: [], user: ["caterpillar", "scute"], ai: [], aiGraveyard: ["Delver of Secrets // Insectile Aberration"], log: [{ chosenType: "insect", notOfType: 1, ofType: 2 }] });
  });

  it("SYNTHETIC LAYER EFFECT (the copy's type line): a double-faced creature that is a copy of a single-faced one has the COPIED types, not its own front face's", () => {
    // No real path reaches this (the become-a-copy offer never targets a double-faced permanent), so the layer-1 effect is
    // built directly, shaped as atoms/becomeCopy.applyBecomeCopy stores it: the caster's Delver is a copy of Llanowar Elves.
    const s0 = kdBoard({ user: [P("llanowar", LLANOWAR_ELVES), P("delver", DELVER)], ai: [P("bears", GRIZZLY_BEARS, "ai")] });
    const { state: s1 } = addContinuousEffect(s0, { layer: 1, op: "copy", copiableCard: { ...LLANOWAR_ELVES, id: "c-delver" }, affects: { mode: "self", permanentId: "delver" }, duration: { kind: "permanent" }, source: { kind: "resolution", permanentId: "delver", cardName: "synthetic" } });
    const s = dominate(s1);
    expect({ asItself: permanentCreatureTypes(s0, "delver"), asCopy: permanentCreatureTypes(s1, "delver"), user: ids(s, "user"), ai: ids(s, "ai"), log: kdLog(s) })
      .toEqual({ asItself: ["human", "wizard"], asCopy: ["elf", "druid"], user: ["delver", "llanowar"], ai: [], log: [{ chosenType: "druid", notOfType: 1, ofType: 2 }] });
  });

  it("SYNTHETIC LAYER EFFECT (the back-face guard's other half): a type a layer-4 effect adds to a double-faced creature counts, even when only its back face prints it", () => {
    const s0 = kdBoard({ user: [P("scute", SCUTE_MOB), P("caterpillar", CAUSTIC_CATERPILLAR), P("delver", DELVER)], ai: [P("bears", GRIZZLY_BEARS, "ai")] });
    const { state: s1 } = addContinuousEffect(s0, { layer: 4, op: { subtypes: ["Insect"] }, affects: { mode: "fixed", permanentIds: ["delver"] }, duration: { kind: "permanent" }, source: { kind: "resolution", permanentId: null, cardName: "synthetic" } });
    const s = dominate(s1);
    expect({ printed: permanentCreatureTypes(s0, "delver"), withEffect: permanentCreatureTypes(s1, "delver"), user: ids(s, "user"), ai: ids(s, "ai"), log: kdLog(s) })
      .toEqual({ printed: ["human", "wizard"], withEffect: ["human", "wizard", "insect"], user: ["caterpillar", "delver", "scute"], ai: [], log: [{ chosenType: "insect", notOfType: 1, ofType: 3 }] });
  });

  it("⭐ only a creature type can be chosen: a Food Golem is a Golem (Food is an artifact type, CR 205.3g); two Time Lords share the two-word type", () => {
    const a0 = kdBoard({ user: [P("ginger", GINGERBRUTE)], ai: [P("bears", GRIZZLY_BEARS, "ai")] });
    const a = dominate(a0);
    // The Tenth Doctor (Time Lord Doctor) and Missy (Time Lord Rogue): Time Lord is the one type both have.
    const b0 = kdBoard({ user: [P("doctor", TENTH_DOCTOR), P("missy", MISSY)], ai: [P("bears", GRIZZLY_BEARS, "ai")] });
    const b = dominate(b0);
    const row = { golem: { types: permanentCreatureTypes(a0, "ginger"), user: ids(a, "user"), log: kdLog(a) },
      timeLord: { types: [permanentCreatureTypes(b0, "doctor"), permanentCreatureTypes(b0, "missy")], user: ids(b, "user"), ai: ids(b, "ai"), log: kdLog(b) } };
    console.log("  WITNESS vocabulary", JSON.stringify(row));
    expect(row).toEqual({ golem: { types: ["golem"], user: ["ginger"], log: [{ chosenType: "golem", notOfType: 1, ofType: 1 }] },
      timeLord: { types: [["doctor", "time lord"], ["rogue", "time lord"]], user: ["doctor", "missy"], ai: [], log: [{ chosenType: "time lord", notOfType: 1, ofType: 2 }] } });
  });
});

describe("⭐ the choice — the type best for the caster", () => {
  it("⭐ the caster's creatures of the type NET of the opponent's: two Elves against three is worse than one Goblin against none", () => {
    // user: Llanowar Elves, Fyndhorn Elves (Elf Druid), Raging Goblin (Goblin Berserker). ai: Elvish Visionary (Elf Shaman),
    // Elvish Archdruid, Priest of Titania (Elf Druid). elf 2−3, druid 2−2, goblin 1−0, berserker 1−0 → Berserker (sorted first).
    const s = dominate(kdBoard({ user: [P("llanowar", LLANOWAR_ELVES), P("fyndhorn", FYNDHORN_ELVES), P("goblin", RAGING_GOBLIN)],
      ai: [P("visionary", ELVISH_VISIONARY, "ai"), P("archdruid", ELVISH_ARCHDRUID, "ai"), P("priest", PRIEST_OF_TITANIA, "ai")] }));
    const row = { user: ids(s, "user"), ai: ids(s, "ai"), log: kdLog(s) };
    console.log("  WITNESS net", JSON.stringify(row));
    expect(row).toEqual({ user: ["goblin"], ai: [], log: [{ chosenType: "berserker", notOfType: 5, ofType: 1 }] });
  });

  it("⭐ a tie on the net goes to the type with more of the caster's own: Zombie (2 against 1) over Bear (1 against 0)", () => {
    const s = dominate(kdBoard({ user: [P("corpse", WALKING_CORPSE), P("digger", GRAVEDIGGER), P("bears", GRIZZLY_BEARS)], ai: [P("scathe", SCATHE_ZOMBIES, "ai")] }));
    const row = { user: ids(s, "user"), ai: ids(s, "ai"), log: kdLog(s) };
    console.log("  WITNESS tieOwn", JSON.stringify(row));
    expect(row).toEqual({ user: ["corpse", "digger"], ai: ["scathe"], log: [{ chosenType: "zombie", notOfType: 1, ofType: 3 }] });
  });

  it("⭐ with no creature of the caster's, the choice is a type nobody has: everything is destroyed", () => {
    const s = dominate(kdBoard({ ai: [P("llanowar", LLANOWAR_ELVES, "ai"), P("fyndhorn", FYNDHORN_ELVES, "ai")] }));
    expect({ ai: ids(s, "ai"), log: kdLog(s) }).toEqual({ ai: [], log: [{ chosenType: "advisor", notOfType: 2, ofType: 0 }] });
  });
});

describe("⭐ Eldritch Evolution — the cost, the search, the exile", () => {
  it("⭐ sacrificing a 3-mana-value creature: creature cards of mana value 5 or less are offered; the chosen one enters; the spell is exiled", () => {
    const s0 = eeBoard({ user: [P("courser", CENTAUR_COURSER), P("bears", GRIZZLY_BEARS)] });
    const victims = offers(s0, "user", "ee").map((a) => a.sacCreatureId).sort();
    const onStack = cast(s0, "ee", (a) => a.sacCreatureId === "courser");
    const paused = resolveTopOfStack(onStack);
    const s = fetch(paused, "Siege Mastodon");
    const row = { victims, paidAtCast: { battlefield: ids(onStack, "user"), graveyard: names(onStack.players.user.graveyard), frozen: onStack.stack[0].payload.params.context.sacrificedForCost },
      candidates: candidates(paused), mayFailToFind: paused.pendingChoice.mayFailToFind,
      battlefield: s.players.user.battlefield.map((p) => p.card.name).sort(), graveyard: names(s.players.user.graveyard), exile: names(s.players.user.exile), library: s.players.user.library.length,
      stack: s.stack.length, pending: s.pendingChoice ?? null, errors: errors(s).length };
    console.log("  WITNESS evolveThree", JSON.stringify(row));
    expect(row).toEqual({ victims: ["bears", "courser"],
      paidAtCast: { battlefield: ["bears"], graveyard: ["Centaur Courser"], frozen: { power: 3, toughness: 3, manaValue: 3 } },
      // Colossal Dreadmaw (6) is over the cap; Sol Ring and Forest are not creature cards; Walking Ballista's {X}{X} is 0 (CR 107.3g)
      candidates: ["Centaur Courser", "Grizzly Bears", "Hill Giant", "Llanowar Elves", "Siege Mastodon", "Walking Ballista"], mayFailToFind: true,
      battlefield: ["Grizzly Bears", "Siege Mastodon"], graveyard: ["Centaur Courser"], exile: ["Eldritch Evolution"], library: EE_LIBRARY.length - 1,
      stack: 0, pending: null, errors: 0 });
  });

  it("⭐ the found card ENTERS: Kalonian Hydra's four +1/+1 counters are on it", () => {
    const paused = evolve(eeBoard({ user: [P("courser", CENTAUR_COURSER)], lib: [KALONIAN_HYDRA, FOREST] }), "courser");
    const s = fetch(paused, "Kalonian Hydra");
    const hydra = s.players.user.battlefield.find((p) => p.card.name === "Kalonian Hydra");
    expect({ candidates: candidates(paused), counters: hydra?.counters?.["+1/+1"], tapped: hydra?.tapped }).toEqual({ candidates: ["Kalonian Hydra"], counters: 4, tapped: false });
  });

  it("⭐ a token that is not a copy has mana value 0 (2 or less is offered); a token that is a copy has the copied mana value", () => {
    // A: Raise the Alarm's Soldier token. B: Quasiduplicate's token copy of Hill Giant (mana value 4) → 6 or less.
    const a0 = resolveTopOfStack(cast(eeBoard({ hand: [H("ee", ELDRITCH_EVOLUTION), H("alarm", RAISE_THE_ALARM)], pool: { G: 3, W: 2 } }), "alarm"));
    const soldier = a0.players.user.battlefield.find((p) => p.card?.token);
    const a = evolve(a0, soldier.id);
    const b0 = resolveTopOfStack(cast(eeBoard({ user: [P("giant", HILL_GIANT)], hand: [H("ee", ELDRITCH_EVOLUTION), H("dup", QUASIDUPLICATE)], pool: { G: 3, U: 3 } }), "dup"));
    const copy = b0.players.user.battlefield.find((p) => p.card?.token);
    const b = evolve(b0, copy.id);
    const row = { soldier: { name: soldier.card.name, cmc: soldier.card.cmc ?? null, candidates: candidates(a) }, copy: { name: copy.card.name, candidates: candidates(b) } };
    console.log("  WITNESS tokens", JSON.stringify(row));
    expect(row).toEqual({ soldier: { name: "Soldier", cmc: null, candidates: ["Grizzly Bears", "Llanowar Elves", "Walking Ballista"] },
      copy: { name: "Hill Giant", candidates: ["Centaur Courser", "Colossal Dreadmaw", "Grizzly Bears", "Hill Giant", "Llanowar Elves", "Siege Mastodon", "Walking Ballista"] } });
  });

  it("⭐ an {X} in the sacrificed creature's cost is 0, whatever it was cast for: Walking Ballista with two counters gives 2 or less", () => {
    const paused = evolve(eeBoard({ user: [P("ballista", WALKING_BALLISTA, "user", { counters: { "+1/+1": 2 }, xValue: 2 })] }), "ballista");
    expect(candidates(paused)).toEqual(["Grizzly Bears", "Llanowar Elves", "Walking Ballista"]);
  });

  it("⭐ a creature that became a copy has the copied mana value: Impossible Man (3) as a copy of Colossal Dreadmaw (6) gives 8 or less; uncopied, 5 or less", () => {
    const base = () => eeBoard({ user: [P("man", IMPOSSIBLE_MAN), P("maw", COLOSSAL_DREADMAW)], pool: { G: 3, U: 3 } });
    const copied = activate(base(), "user", "man", (a) => (a.targets || []).some((t) => t.id === "maw"));
    const row = { asCopy: candidates(evolve(copied, "man")), asItself: candidates(evolve(base(), "man")) };
    console.log("  WITNESS copyValue", JSON.stringify(row));
    expect(row).toEqual({ asCopy: ["Centaur Courser", "Colossal Dreadmaw", "Grizzly Bears", "Hill Giant", "Llanowar Elves", "Siege Mastodon", "Walking Ballista"],
      asItself: ["Centaur Courser", "Grizzly Bears", "Hill Giant", "Llanowar Elves", "Siege Mastodon", "Walking Ballista"] });
  });

  it("⭐ no legal creature card in the library: nothing is found, the library is still searched and the spell is still exiled", () => {
    const paused = evolve(eeBoard({ user: [P("bears", GRIZZLY_BEARS)], lib: [COLOSSAL_DREADMAW, SOL_RING, FOREST] }), "bears");
    const s = fetch(paused, null);
    const row = { candidates: candidates(paused), battlefield: ids(s, "user"), library: names(s.players.user.library), graveyard: names(s.players.user.graveyard), exile: names(s.players.user.exile), stack: s.stack.length, pending: s.pendingChoice ?? null };
    console.log("  WITNESS nothingFound", JSON.stringify(row));
    expect(row).toEqual({ candidates: [], battlefield: [], library: ["Colossal Dreadmaw", "Forest", "Sol Ring"], graveyard: ["Grizzly Bears"], exile: ["Eldritch Evolution"], stack: 0, pending: null });
  });

  it("the searcher may fail to find (CR 701.23b): declining with candidates on offer puts nothing onto the battlefield, and the spell is exiled", () => {
    const s = fetch(evolve(eeBoard({ user: [P("bears", GRIZZLY_BEARS)] }), "bears"), null);
    expect({ battlefield: ids(s, "user"), library: s.players.user.library.length, exile: names(s.players.user.exile) }).toEqual({ battlefield: [], library: EE_LIBRARY.length, exile: ["Eldritch Evolution"] });
  });

  it("the exile is part of resolving: countered, Eldritch Evolution goes to its owner's graveyard — and the sacrifice stays paid", () => {
    let s = eeBoard({ user: [P("courser", CENTAUR_COURSER)], aiHand: [H("counter", COUNTERSPELL)], aiPool: { U: 2 } });
    s = cast(s, "ee", (a) => a.sacCreatureId === "courser");
    s = resolveTopOfStack(cast({ ...s, priorityHolder: "ai" }, "counter", () => true, "ai"));
    expect({ stack: s.stack.length, pending: s.pendingChoice ?? null, battlefield: ids(s, "user"), graveyard: names(s.players.user.graveyard), exile: names(s.players.user.exile), library: s.players.user.library.length })
      .toEqual({ stack: 0, pending: null, battlefield: [], graveyard: ["Centaur Courser", "Eldritch Evolution"], exile: [], library: EE_LIBRARY.length });
  });

  it("⛔ with no creature to sacrifice the spell is not castable", () => {
    expect(offers(eeBoard({ user: [P("ring", SOL_RING)] }), "user", "ee")).toHaveLength(0);
  });

  it("⭐ the cost is a CREATURE as it is paid: an animated Mutavault pays it; a bestowed Aura, a God short of its devotion and a Saga with a creature back face do not", () => {
    // user: Grizzly Bears wearing a bestowed Boon Satyr, Thassa (devotion to blue 1), Fable of the Mirror-Breaker, and Mutavault
    // animated by its own ability.
    const s0 = activate(eeBoard({ user: [P("bears", GRIZZLY_BEARS, "user", { attachments: ["satyr"] }), P("satyr", BOON_SATYR, "user", { attachedTo: "bears", bestowed: true }),
      P("thassa", THASSA), P("fable", FABLE, "user", { counters: { lore: 1 } }), P("vault", MUTAVAULT)], pool: { G: 3, C: 1 } }), "user", "vault");
    const row = { victims: offers(s0, "user", "ee").map((a) => a.sacCreatureId).sort(), vaultCap: candidates(evolve(s0, "vault")) };
    console.log("  WITNESS creatureCost", JSON.stringify(row));
    expect(row).toEqual({ victims: ["bears", "vault"], vaultCap: ["Grizzly Bears", "Llanowar Elves", "Walking Ballista"] });
  });
});

describe("⚠️ the sacrificed creature's values are frozen on the spell (the shared channel could be overwritten)", () => {
  it("⭐ Eldritch Evolution sacrificing Centaur Courser, answered by Fling sacrificing Colossal Dreadmaw: the search is still 5 or less", () => {
    let s = eeBoard({ user: [P("courser", CENTAUR_COURSER)], ai: [P("maw", COLOSSAL_DREADMAW, "ai")], aiHand: [H("fling", FLING)], aiPool: { R: 2 } });
    s = cast(s, "ee", (a) => a.sacCreatureId === "courser");
    s = cast({ ...s, priorityHolder: "ai" }, "fling", (a) => a.sacCreatureId === "maw" && (a.targets || []).some((t) => t.id === "user"), "ai");
    const shared = s.sacrificedForCost.manaValue;
    s = resolveTopOfStack(s);                   // Fling: 6 damage to the caster
    const paused = resolveTopOfStack(s);        // Eldritch Evolution
    const row = { shared, life: paused.players.user.life, candidates: candidates(paused) };
    console.log("  WITNESS frozenSacrifice", JSON.stringify(row));
    expect(row).toEqual({ shared: 6, life: 34, candidates: ["Centaur Courser", "Grizzly Bears", "Hill Giant", "Llanowar Elves", "Siege Mastodon", "Walking Ballista"] });
  });

  it("the stamp is this cast's own payment only: a spell that sacrificed nothing carries none, even while the shared channel still holds an earlier one", () => {
    let s = eeBoard({ user: [P("courser", CENTAUR_COURSER)], hand: [H("ee", ELDRITCH_EVOLUTION), H("kd", KINDRED_DOMINANCE)], pool: { G: 3, B: 7 } });
    s = fetch(evolve(s, "courser"), null);
    const onStack = cast(s, "kd");
    expect({ shared: onStack.sacrificedForCost, context: Object.keys(onStack.stack[0].payload.params.context).sort() })
      .toEqual({ shared: { power: 3, toughness: 3, manaValue: 3 }, context: ["castDuringMainPhase"] });
  });

  it("a copy of the spell uses what the original sacrificed (CR 707.10): Twincast's copy searches for 5 or less too", () => {
    let s = eeBoard({ user: [P("courser", CENTAUR_COURSER)], hand: [H("ee", ELDRITCH_EVOLUTION), H("twin", TWINCAST)], pool: { G: 3, U: 3 } });
    s = cast(s, "ee", (a) => a.sacCreatureId === "courser");
    s = resolveTopOfStack(cast(s, "twin"));     // Twincast resolves: the copy is on the stack above the original
    const paused = resolveTopOfStack(s);        // the copy
    const afterCopy = fetch(paused, "Hill Giant");
    const row = { candidates: candidates(paused), copyLeft: { exile: names(afterCopy.players.user.exile), graveyard: names(afterCopy.players.user.graveyard) }, stack: afterCopy.stack.length };
    console.log("  WITNESS copy", JSON.stringify(row));
    expect(row).toEqual({ candidates: ["Centaur Courser", "Grizzly Bears", "Hill Giant", "Llanowar Elves", "Siege Mastodon", "Walking Ballista"],
      copyLeft: { exile: [], graveyard: ["Centaur Courser", "Twincast"] }, stack: 1 });
  });

  it("SYNTHETIC CONTEXT (the cap's guard): the atom resolved with no frozen sacrifice finds nothing — never an uncapped search, and never the shared channel's value", () => {
    const atom = parseEffectProgram(ELDRITCH_EVOLUTION).atoms[0];
    const s0 = { ...eeBoard(), sacrificedForCost: { power: 6, toughness: 6, manaValue: 6 } };
    const out = resolveAtom(s0, atom, ctxUser);
    const withValue = resolveAtom(s0, atom, { ...ctxUser, sacrificedForCost: { power: 0, toughness: 0, manaValue: 0 } });
    expect({ none: candidates(out), zero: candidates(withValue) }).toEqual({ none: [], zero: ["Grizzly Bears", "Llanowar Elves", "Walking Ballista"] });
  });
});
