/**
 * LIQUIMETAL TORQUE — the play-weighted program, #511 (EDHREC #511): "{T}: Target nonland permanent becomes an artifact in
 * addition to its other types until end of turn." — and its family, the same effect on another target noun: Liquimetal Coating
 * and Argent Mutation ("target permanent"), Myr Landshaper ("target land"); plus Stone by Sunlight's second mode, which filed
 * "Artifact" as a SUBTYPE (no rules reader saw an artifact).
 *
 * The representation: a fixed layer-4 `{ types: ["Artifact"] }` effect (CR 613.1d) on the chosen permanent — "in addition to its
 * other types" keeps everything it had (CR 205.1b) — fixed at resolution (CR 611.2c) and gone at cleanup (CR 514.2), read through
 * layers.permanentHasCardType (the derive's types with the front face's discipline). Every NEGATED artifact reader must see it —
 * a "nonartifact" target or sweep, a "no artifacts" condition, Neurok Spy's defender check — or the engine does what the rules
 * forbid; the positive readers routed here (Shatter's "target artifact", Disenchant's "artifact or enchantment", the "Enchant
 * artifact" hosts, "you control an artifact") gain the legal play. Each witness is a pair: the plain permanent, and the same
 * permanent after Liquimetal Torque (or Coating) resolved at it through the engine's own activation.
 *
 * Real oracle fixtures (bundled Scryfall, the 2026-10-01 data, generated by cardIndex.publicCard — never typed by hand).
 */
import { describe, it, expect, beforeEach } from "vitest";
import { createGameState, createPermanent, _resetIdsForTests, findPermanent } from "./gameState.js";
import { addContinuousEffect, deriveCharacteristics, permanentTypes, permanentHasCardType, permanentHasKeyword, expireContinuousEffects } from "./layers.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { resolveTopOfStack } from "./gameEngine.js";
import { classifyCard } from "./coverage.js";
import { parseActivatedAbilities } from "./effects/abilities.js";
import { parseEffectProgram, parseEffectClause, programConfidence } from "./effects/parser.js";
import { canBlockAttacker } from "./combatEvasion.js";
import { evaluateInterveningIf } from "./interveningIf.js";
import { checkStateTriggers, detectTriggers } from "./triggers.js";
import { checkAllStateBasedActions } from "./sba.js";
import { manaSources } from "./manaModel.js";
import { applyBecomeType } from "./effects/atoms/combat.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (oracle verified against bundled Scryfall data) ──────────
const TORQUE = {"name":"Liquimetal Torque","type":"Artifact","mana":"{2}","cmc":2,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{T}: Target nonland permanent becomes an artifact in addition to its other types until end of turn."}; // native-mana
const COATING = {"name":"Liquimetal Coating","type":"Artifact","mana":"{2}","cmc":2,"keywords":[],"colors":[],"oracle":"{T}: Target permanent becomes an artifact in addition to its other types until end of turn."}; // native-activated
const ARGENT = {"name":"Argent Mutation","type":"Instant","mana":"{2}{U}","cmc":3,"keywords":[],"colors":["U"],"oracle":"Target permanent becomes an artifact in addition to its other types until end of turn.\nDraw a card."}; // native-spell
const LANDSHAPER = {"name":"Myr Landshaper","type":"Artifact Creature — Myr","mana":"{3}","cmc":3,"power":"1","toughness":"1","keywords":[],"colors":[],"oracle":"{T}: Target land becomes an artifact in addition to its other types until end of turn."}; // native-activated
const STONE = {"name":"Stone by Sunlight","type":"Instant","mana":"{1}{W}","cmc":2,"keywords":[],"colors":["W"],"oracle":"Choose one —\n• Destroy target creature with power 4 or greater.\n• Until end of turn, target creature becomes an artifact in addition to its other types and gains indestructible. (Damage and effects that say \"destroy\" don't destroy it.)"}; // native-spell
const AVATAR_STATE = {"name":"Enter the Avatar State","type":"Instant — Lesson","mana":"{W}","cmc":1,"keywords":[],"colors":["W"],"oracle":"Until end of turn, target creature you control becomes an Avatar in addition to its other types and gains flying, first strike, lifelink, and hexproof. (A creature with hexproof can't be the target of spells or abilities your opponents control.)"}; // native-spell
const TRANSMUTER = {"name":"Neurok Transmuter","type":"Creature — Human Wizard","mana":"{2}{U}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["U"],"oracle":"{U}: Target creature becomes an artifact in addition to its other types until end of turn.\n{U}: Until end of turn, target artifact creature becomes blue and isn't an artifact."}; // body-only
const MEMNARCH = {"name":"Memnarch","type":"Legendary Artifact Creature — Wizard","mana":"{7}","cmc":7,"power":"4","toughness":"5","keywords":[],"colors":[],"oracle":"{1}{U}{U}: Target permanent becomes an artifact in addition to its other types. (This effect lasts indefinitely.)\n{3}{U}: Gain control of target artifact. (This effect lasts indefinitely.)"}; // body-only
const THRAN_FORGE = {"name":"Thran Forge","type":"Artifact","mana":"{3}","cmc":3,"keywords":[],"colors":[],"oracle":"{2}: Until end of turn, target nonartifact creature gets +1/+0 and becomes an artifact in addition to its other types."}; // body-only
const TRANSMOGRANT = {"name":"Ashnod's Transmogrant","type":"Artifact","mana":"{1}","cmc":1,"keywords":[],"colors":[],"oracle":"{T}, Sacrifice this artifact: Put a +1/+1 counter on target nonartifact creature. That creature becomes an artifact in addition to its other types."}; // body-only
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const FOREST = {"name":"Forest","type":"Basic Land — Forest","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {G}.)"}; // land
const ARIXMETHES = {"name":"Arixmethes, Slumbering Isle","type":"Legendary Creature — Kraken","mana":"{2}{G}{U}","cmc":4,"power":"12","toughness":"12","keywords":[],"colors":["G","U"],"oracle":"Arixmethes enters tapped with five slumber counters on it.\nAs long as Arixmethes has a slumber counter on it, it's a land. (It's not a creature.)\nWhenever you cast a spell, you may remove a slumber counter from Arixmethes.\n{T}: Add {G}{U}."}; // native-mana
const SOL_RING = {"name":"Sol Ring","type":"Artifact","mana":"{1}","cmc":1,"keywords":[],"colors":[],"oracle":"{T}: Add {C}{C}."}; // native-mana
const EXPLORATION = {"name":"Exploration","type":"Enchantment","mana":"{G}","cmc":1,"keywords":[],"colors":["G"],"oracle":"You may play an additional land on each of your turns."}; // native-static
const GO_FOR_THE_THROAT = {"name":"Go for the Throat","type":"Instant","mana":"{1}{B}","cmc":2,"keywords":[],"colors":["B"],"oracle":"Destroy target nonartifact creature."}; // native-spell
const TERROR = {"name":"Terror","type":"Instant","mana":"{1}{B}","cmc":2,"keywords":[],"colors":["B"],"oracle":"Destroy target nonartifact, nonblack creature. It can't be regenerated."}; // native-spell
const SHRIEKMAW = {"name":"Shriekmaw","type":"Creature — Elemental","mana":"{4}{B}","cmc":5,"power":"3","toughness":"2","keywords":["Evoke","Fear"],"colors":["B"],"oracle":"Fear (This creature can't be blocked except by artifact creatures and/or black creatures.)\nWhen this creature enters, destroy target nonartifact, nonblack creature.\nEvoke {1}{B} (You may cast this spell for its evoke cost. If you do, it's sacrificed when it enters.)"}; // native-trigger
const THEIR_NAME = {"name":"Their Name Is Death","type":"Sorcery","mana":"{3}{B}{B}{B}","cmc":6,"keywords":[],"colors":["B"],"oracle":"Destroy all nonartifact creatures."}; // native-spell
const WHIPFLARE = {"name":"Whipflare","type":"Sorcery","mana":"{1}{R}","cmc":2,"keywords":[],"colors":["R"],"oracle":"Whipflare deals 2 damage to each nonartifact creature."}; // native-spell
const RECLUSIVE_WIGHT = {"name":"Reclusive Wight","type":"Creature — Zombie Minion","mana":"{3}{B}","cmc":4,"power":"4","toughness":"4","keywords":[],"colors":["B"],"oracle":"At the beginning of your upkeep, if you control another nonland permanent, sacrifice this creature."}; // native-trigger
const COVETOUS_DRAGON = {"name":"Covetous Dragon","type":"Creature — Dragon","mana":"{4}{R}","cmc":5,"power":"6","toughness":"5","keywords":["Flying"],"colors":["R"],"oracle":"Flying\nWhen you control no artifacts, sacrifice this creature."}; // native-trigger
const SYNOD_CENTURION = {"name":"Synod Centurion","type":"Artifact Creature — Construct","mana":"{4}","cmc":4,"power":"4","toughness":"4","keywords":[],"colors":[],"oracle":"When you control no other artifacts, sacrifice this creature."}; // native-trigger
const GLIMMERVOID = {"name":"Glimmervoid","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"At the beginning of the end step, if you control no artifacts, sacrifice this land.\n{T}: Add one mana of any color."}; // land
const TEZZERETS_AMBITION = {"name":"Tezzeret's Ambition","type":"Sorcery","mana":"{3}{U}{U}","cmc":5,"keywords":[],"colors":["U"],"oracle":"Draw three cards. If you control no artifacts, discard a card."}; // native-spell
const SCHOLAR = {"name":"Scholar of Stars","type":"Creature — Human Artificer","mana":"{3}{U}","cmc":4,"power":"3","toughness":"2","keywords":[],"colors":["U"],"oracle":"When this creature enters, if you control an artifact, draw a card."}; // native-trigger
const NEUROK_SPY = {"name":"Neurok Spy","type":"Creature — Human Rogue","mana":"{2}{U}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["U"],"oracle":"This creature can't be blocked as long as defending player controls an artifact."}; // native-body
const BOUNCING_BEEBLES = {"name":"Bouncing Beebles","type":"Creature — Beeble","mana":"{2}{U}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["U"],"oracle":"This creature can't be blocked as long as defending player controls an artifact."}; // native-body
const BUBBLING_BEEBLES = {"name":"Bubbling Beebles","type":"Creature — Beeble","mana":"{4}{U}","cmc":5,"power":"3","toughness":"3","keywords":[],"colors":["U"],"oracle":"This creature can't be blocked as long as defending player controls an enchantment."}; // native-body
const HAZY_HOMUNCULUS = {"name":"Hazy Homunculus","type":"Creature — Homunculus Illusion","mana":"{1}{U}","cmc":2,"power":"1","toughness":"1","keywords":[],"colors":["U"],"oracle":"This creature can't be blocked as long as defending player controls an untapped land."}; // native-body
const PADEEM = {"name":"Padeem, Consul of Innovation","type":"Legendary Creature — Vedalken Artificer","mana":"{3}{U}","cmc":4,"power":"1","toughness":"4","keywords":[],"colors":["U"],"oracle":"Artifacts you control have hexproof. (They can't be the targets of spells or abilities your opponents control.)\nAt the beginning of your upkeep, if you control the artifact with the greatest mana value or tied for the greatest mana value, draw a card."}; // native-mixed
const SHATTER = {"name":"Shatter","type":"Instant","mana":"{1}{R}","cmc":2,"keywords":[],"colors":["R"],"oracle":"Destroy target artifact."}; // native-spell
const DISENCHANT = {"name":"Disenchant","type":"Instant","mana":"{1}{W}","cmc":2,"keywords":[],"colors":["W"],"oracle":"Destroy target artifact or enchantment."}; // native-spell
const CRUSH = {"name":"Crush","type":"Instant","mana":"{R}","cmc":1,"keywords":[],"colors":["R"],"oracle":"Destroy target noncreature artifact."}; // native-spell
const PUTREFY = {"name":"Putrefy","type":"Instant","mana":"{1}{B}{G}","cmc":3,"keywords":[],"colors":["B","G"],"oracle":"Destroy target artifact or creature. It can't be regenerated."}; // native-spell
const PILLAGE = {"name":"Pillage","type":"Sorcery","mana":"{1}{R}{R}","cmc":3,"keywords":[],"colors":["R"],"oracle":"Destroy target artifact or land. It can't be regenerated."}; // native-spell
const CREEPING_MOLD = {"name":"Creeping Mold","type":"Sorcery","mana":"{2}{G}{G}","cmc":4,"keywords":[],"colors":["G"],"oracle":"Destroy target artifact, enchantment, or land."}; // native-spell
const BEDEVIL = {"name":"Bedevil","type":"Instant","mana":"{B}{B}{R}","cmc":3,"keywords":[],"colors":["B","R"],"oracle":"Destroy target artifact, creature, or planeswalker."}; // native-spell
const BROKEN_WINGS = {"name":"Broken Wings","type":"Instant","mana":"{2}{G}","cmc":3,"keywords":[],"colors":["G"],"oracle":"Destroy target artifact, enchantment, or creature with flying."}; // native-spell
const HAYWIRE_MITE = {"name":"Haywire Mite","type":"Artifact Creature — Insect","mana":"{1}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":[],"oracle":"When this creature dies, you gain 2 life.\n{G}, Sacrifice this creature: Exile target noncreature artifact or noncreature enchantment."}; // native-mixed
const MOLTEN_FRAME = {"name":"Molten Frame","type":"Instant","mana":"{1}{R}","cmc":2,"keywords":["Cycling"],"colors":["R"],"oracle":"Destroy target artifact creature.\nCycling {2} ({2}, Discard this card: Draw a card.)"}; // native-spell
const STASIS_COCOON = {"name":"Stasis Cocoon","type":"Enchantment — Aura","mana":"{1}{W}","cmc":2,"keywords":["Enchant"],"colors":["W"],"oracle":"Enchant artifact\nEnchanted artifact can't attack or block, and its activated abilities can't be activated."}; // native-aura
const NULL_ROD = {"name":"Null Rod","type":"Artifact","mana":"{2}","cmc":2,"keywords":[],"colors":[],"oracle":"Activated abilities of artifacts can't be activated."}; // native-static
const TEMPERED_STEEL = {"name":"Tempered Steel","type":"Enchantment","mana":"{1}{W}{W}","cmc":3,"keywords":[],"colors":["W"],"oracle":"Artifact creatures you control get +2/+2."}; // native-static
const LUMENGRID_DRAKE = {"name":"Lumengrid Drake","type":"Creature — Drake","mana":"{3}{U}","cmc":4,"power":"2","toughness":"2","keywords":["Flying","Metalcraft"],"colors":["U"],"oracle":"Flying\nMetalcraft — When this creature enters, if you control three or more artifacts, return target creature to its owner's hand."}; // native-trigger
const BOSEIJU = {"name":"Boseiju, Who Endures","type":"Legendary Land","mana":"","cmc":0,"keywords":["Channel"],"colors":[],"oracle":"{T}: Add {G}.\nChannel — {1}{G}, Discard this card: Destroy target artifact, enchantment, or nonbasic land an opponent controls. That player may search their library for a land card with a basic land type, put it onto the battlefield, then shuffle. This ability costs {1} less to activate for each legendary creature you control."}; // land
const OTAWARA = {"name":"Otawara, Soaring City","type":"Legendary Land","mana":"","cmc":0,"keywords":["Channel"],"colors":[],"oracle":"{T}: Add {U}.\nChannel — {3}{U}, Discard this card: Return target artifact, creature, enchantment, or planeswalker to its owner's hand. This ability costs {1} less to activate for each legendary creature you control."}; // land
const SCRAPDIVER = {"name":"Scrapdiver Serpent","type":"Creature — Serpent","mana":"{5}{U}{U}","cmc":7,"power":"5","toughness":"5","keywords":[],"colors":["U"],"oracle":"This creature can't be blocked as long as defending player controls an artifact."}; // native-body
const LLANOWAR = {"name":"Llanowar Elves","type":"Creature — Elf Druid","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G}."}; // native-mana
const ICE_OVER = {"name":"Ice Over","type":"Enchantment — Aura","mana":"{1}{U}","cmc":2,"keywords":["Enchant"],"colors":["U"],"oracle":"Enchant artifact or creature\nEnchanted permanent doesn't untap during its controller's untap step."}; // native-aura
const PLANAR_DISRUPTION = {"name":"Planar Disruption","type":"Enchantment — Aura","mana":"{1}{W}","cmc":2,"keywords":["Enchant"],"colors":["W"],"oracle":"Enchant artifact, creature, or planeswalker\nEnchanted permanent can't attack or block, and its activated abilities can't be activated."}; // native-aura
const IMPOSSIBLE_MAN = {"name":"Impossible Man","type":"Legendary Creature — Alien Shapeshifter","mana":"{2}{U}","cmc":3,"power":"1","toughness":"4","keywords":["Flying"],"colors":["U"],"oracle":"Flying\n{2}{U}: Impossible Man becomes a copy of another target permanent until end of turn, except his name is Impossible Man."}; // native-activated
const BLITZBALL = {"name":"Sidequest: Play Blitzball // World Champion, Celestial Weapon","type":"Enchantment // Legendary Artifact — Equipment","mana":"{2}{R}","cmc":3,"keywords":["Double Overdrive","Transform","Equip","Double"],"layout":"transform","colors":[],"oracle":"Sidequest: Play Blitzball - Enchantment {2}{R}\nAt the beginning of combat on your turn, target creature you control gets +2/+0 until end of turn.\nAt the end of combat on your turn, if a player was dealt 6 or more combat damage this turn, transform this enchantment, then attach it to a creature you control.\n//\nWorld Champion, Celestial Weapon - Legendary Artifact — Equipment \nDouble Overdrive — Equipped creature gets +2/+0 and has double strike.\nEquip {3} ({3}: Attach to target creature you control. Equip only as a sorcery.)"}; // body-only
const COMPASS = {"name":"Thaumatic Compass // Spires of Orazca","type":"Artifact // Land","mana":"{2}","cmc":2,"keywords":["Transform"],"layout":"transform","colors":[],"oracle":"Thaumatic Compass - Artifact {2}\n{3}, {T}: Search your library for a basic land card, reveal it, put it into your hand, then shuffle.\nAt the beginning of your end step, if you control seven or more lands, transform this artifact.\n//\nSpires of Orazca - Land \n(Transforms from Thaumatic Compass.)\n{T}: Add {C}.\n{T}: Untap target attacking creature an opponent controls and remove it from combat."}; // body-only
const SUPPRESSION_BONDS = {"name":"Suppression Bonds","type":"Enchantment — Aura","mana":"{3}{W}","cmc":4,"keywords":["Enchant"],"colors":["W"],"oracle":"Enchant nonland permanent\nEnchanted permanent can't attack or block, and its activated abilities can't be activated."}; // native-aura
const BRAMBLECRUSH = {"name":"Bramblecrush","type":"Sorcery","mana":"{2}{G}{G}","cmc":4,"keywords":[],"colors":["G"],"oracle":"Destroy target noncreature permanent."}; // native-spell

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const H = (id, card) => ({ id, ...card }); // a card in hand
const POOL = { W: 6, U: 6, B: 6, R: 6, G: 6 };
function board(user = [], ai = [], { pool = {}, hand = [], library = [], combat = null } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  return { ...g, turn: 3, activePlayer: "user", priorityHolder: "user", phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    ...(combat ? { combat } : {}),
    players: { ...g.players,
      user: { ...g.players.user, battlefield: user, hand, library, manaPool: { ...g.players.user.manaPool, ...pool } },
      ai: { ...g.players.ai, battlefield: ai } } };
}
const actionsOf = (s) => legalActionsForPlayer(s, "user");
const activations = (s, permId) => actionsOf(s).filter((a) => a.kind === "activate-ability" && a.permanentId === permId);
const ids = (targets) => [...new Set(targets.map((t) => t.id))].sort();
/** The permanents `sourceId`'s targeted ability is offered at (Liquimetal Torque / Coating / Myr Landshaper / Haywire Mite). */
const offered = (s, sourceId) => ids(activations(s, sourceId).flatMap((a) => a.targets || []));
/** Activate `sourceId`'s "becomes an artifact" ability at `targetId` and resolve it — the effect the card writes, through the
 *  engine's own activation (legal actions → dispatcher → stack → resolver). */
function becomeArtifact(s, targetId, sourceId = "lt") {
  const act = activations(s, sourceId).find((a) => (a.targets || []).some((t) => t.id === targetId));
  if (!act) throw new Error(`${sourceId} offers no activation at ${targetId}`);
  return resolveTopOfStack(dispatchAction(s, act));
}
const castActions = (s, cardId) => actionsOf(s).filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
const castTargets = (s, cardId) => ids(castActions(s, cardId).flatMap((a) => a.targets || []));
function cast(s, cardId, targetId = null, pick = () => true) {
  const act = castActions(s, cardId).find((a) => pick(a) && (targetId == null || (a.targets || []).some((t) => t.id === targetId)));
  if (!act) throw new Error(`no cast of ${cardId}${targetId ? ` at ${targetId}` : ""}`);
  return resolveTopOfStack(dispatchAction(s, act));
}
/** Argent Mutation cast at `targetId` (an instant — the type add without leaving an artifact source on the board). */
const mutate = (s, targetId) => cast(s, "am", targetId);
const cleanup = (s) => expireContinuousEffects(s, { atCleanupOfTurn: s.turn });
const isArtifact = (s, id) => permanentHasCardType(s, id, "Artifact");
const onBattlefield = (s) => [...s.players.user.battlefield, ...s.players.ai.battlefield].map((p) => p.id).sort();
const LIB = [1, 2, 3, 4].map((i) => H(`l${i}`, BEARS));
/** The card's own condition text, as the trigger detector reads it off the printed oracle (never retyped here). */
const condOf = (card) => detectTriggers(card).map((d) => d.interveningIf || d.stateCondition).find(Boolean);

describe("the cards", () => {
  it("classify: Liquimetal Torque native-mana; Liquimetal Coating and Myr Landshaper native-activated; Argent Mutation native-spell", () => {
    expect([TORQUE, COATING, LANDSHAPER, ARGENT].map(classifyCard)).toEqual(["native-mana", "native-activated", "native-activated", "native-spell"]);
  });
  it("the family members with another unmodeled clause stay parked: Neurok Transmuter (\"isn't an artifact\"), Memnarch (indefinite, and gain control of target artifact), Thran Forge, Ashnod's Transmogrant", () => {
    expect([TRANSMUTER, MEMNARCH, THRAN_FORGE, TRANSMOGRANT].map(classifyCard)).toEqual(["body-only", "body-only", "body-only", "body-only"]);
  });
  it("⭐ the ability parses to ONE layer-4 card-type add per target noun; the indefinite form (Memnarch) stays unparsed", () => {
    const atomOf = (card, i) => { const ab = parseActivatedAbilities(card)[i]; return { modeled: ab.modeled, atoms: ab.program?.confidence === "high" ? ab.program.atoms : null }; };
    const add = (targetType) => ({ modeled: true, atoms: [{ op: "become-type", targetType, restrictions: [], addTypes: ["Artifact"] }] });
    expect({ torque: atomOf(TORQUE, 1), coating: atomOf(COATING, 0), landshaper: atomOf(LANDSHAPER, 0), transmuter: atomOf(TRANSMUTER, 0), memnarch: atomOf(MEMNARCH, 0) })
      .toEqual({ torque: add("nonlandPermanent"), coating: add("permanent"), landshaper: add("land"), transmuter: add("creature"), memnarch: { modeled: false, atoms: null } });
  });
  it("the becomes-and-gains pump admits only the artifact card type or a CR 205.3m creature type — any other word parks (a parser guard: no printed card reaches it)", () => {
    const parsed = (clause) => { const p = parseEffectClause(clause, "Instant"); return programConfidence(p) === "high" ? p.atoms : null; };
    expect({ enchantment: parsed("Until end of turn, target creature becomes an enchantment in addition to its other types and gains flying."),
      auraSubtype: parsed("Until end of turn, target creature becomes an aura in addition to its other types and gains flying.") })
      .toEqual({ enchantment: null, auraSubtype: null });
  });
  it("⭐ Stone by Sunlight's \"becomes an artifact\" is a card-type add now (it was an \"Artifact\" SUBTYPE); Enter the Avatar State's Avatar stays a subtype", () => {
    const stoneMode = parseEffectProgram(STONE).modal.modes[1].atoms[0];
    const avatar = parseEffectProgram(AVATAR_STATE).atoms[0];
    expect({ stone: [stoneMode.addTypes, stoneMode.addSubtype], avatar: [avatar.addTypes, avatar.addSubtype], tiers: [classifyCard(STONE), classifyCard(AVATAR_STATE)] })
      .toEqual({ stone: [["Artifact"], undefined], avatar: [undefined, "Avatar"], tiers: ["native-spell", "native-spell"] });
  });
});

describe("the type add — layer 4, in addition to its other types, until end of turn", () => {
  it("⭐ Liquimetal Torque at a Grizzly Bears: an artifact creature that is still a Bear; Torque taps; at cleanup it is a plain creature again", () => {
    const s = becomeArtifact(board([P("lt", TORQUE), P("bear", BEARS)]), "bear");
    const after = cleanup(s);
    const row = (st) => ({ types: [...permanentTypes(st, "bear").types].sort(), subtypes: permanentTypes(st, "bear").subtypes, artifact: isArtifact(st, "bear") });
    expect({ now: row(s), torqueTapped: findPermanent(s, "lt").permanent.tapped, nextTurn: row(after) })
      .toEqual({ now: { types: ["Artifact", "Creature"], subtypes: ["Bear"], artifact: true }, torqueTapped: true, nextTurn: { types: ["Creature"], subtypes: ["Bear"], artifact: false } });
  });
  it("⭐ Torque's \"target NONLAND permanent\": a Forest is never offered, nor Arixmethes while it slumbers (a land); awake it is a creature and is", () => {
    const base = [P("lt", TORQUE), P("bear", BEARS), P("sol", SOL_RING), P("ex", EXPLORATION), P("for", FOREST)];
    const asleep = board(base, [P("arx", ARIXMETHES, "ai", { counters: { slumber: 5 } })]);
    const awake = board(base, [P("arx", ARIXMETHES, "ai")]);
    expect({ asleep: offered(asleep, "lt"), awake: offered(awake, "lt"), arxIsLand: [permanentHasCardType(asleep, "arx", "Land"), permanentHasCardType(awake, "arx", "Land")] })
      .toEqual({ asleep: ["bear", "ex", "lt", "sol"], awake: ["arx", "bear", "ex", "lt", "sol"], arxIsLand: [true, false] });
  });
  it("⭐ the layer engine's answer (layers.permanentHasCardType): a type an effect removed is gone (slumbering Arixmethes is a land, not a creature); the face that is up decides a double-faced card; a permanent that became a copy has the copy's types", () => {
    const asleep = board([P("arx", ARIXMETHES, "user", { counters: { slumber: 5 } }), P("tc", COMPASS), P("sq", BLITZBALL)]);
    const awake = board([P("arx", ARIXMETHES)]);
    // Impossible Man: "{2}{U}: Impossible Man becomes a copy of another target permanent until end of turn" — at Haywire Mite.
    const s0 = board([P("im", IMPOSSIBLE_MAN), P("hm", HAYWIRE_MITE)], [], { pool: POOL });
    const copied = becomeArtifact(s0, "hm", "im");
    const has = (st, id, t) => permanentHasCardType(st, id, t);
    expect({ asleep: [has(asleep, "arx", "Creature"), has(asleep, "arx", "Land")], awake: [has(awake, "arx", "Creature"), has(awake, "arx", "Land")],
      compass: [has(asleep, "tc", "Artifact"), has(asleep, "tc", "Land")], blitzball: [has(asleep, "sq", "Enchantment"), has(asleep, "sq", "Artifact")],
      impossibleMan: [has(s0, "im", "Artifact"), has(copied, "im", "Artifact")] })
      .toEqual({ asleep: [false, true], awake: [true, false], compass: [true, false], blitzball: [true, false], impossibleMan: [false, true] });
  });
  it("the resolver: a chosen permanent that already left the battlefield gets nothing (CR 608.2b), the one still there gets the add", () => {
    const s0 = board([P("bear", BEARS)]);
    const atom = parseActivatedAbilities(TORQUE)[1].program.atoms[0];
    const s = applyBecomeType(s0, atom, { controller: "user", sourceId: null, cardName: "Liquimetal Torque", targets: [{ type: "permanent", id: "gone" }, { type: "permanent", id: "bear" }] });
    const ev = s.log.filter((e) => e.effect === "become-type").pop();
    expect({ targets: ev.targets, effects: (s.continuousEffects || []).map((e) => e.affects.permanentIds), artifact: isArtifact(s, "bear") }).toEqual({ targets: ["bear"], effects: [["bear"]], artifact: true });
  });
  it("Liquimetal Coating takes a land (any permanent); Myr Landshaper only a land — each becomes an artifact land", () => {
    const s0 = board([P("lc", COATING), P("ms", LANDSHAPER), P("bear", BEARS), P("for", FOREST), P("f2", FOREST)]);
    const s = becomeArtifact(becomeArtifact(s0, "for", "lc"), "f2", "ms");
    expect({ coating: offered(s0, "lc"), landshaper: offered(s0, "ms"), lands: [isArtifact(s, "for"), isArtifact(s, "f2"), permanentHasCardType(s, "for", "Land")], bear: isArtifact(s, "bear") })
      .toEqual({ coating: ["bear", "f2", "for", "lc", "ms"], landshaper: ["f2", "for"], lands: [true, true, true], bear: false });
  });
  it("Argent Mutation: the target becomes an artifact and you draw a card", () => {
    const s0 = board([P("bear", BEARS)], [], { pool: POOL, hand: [H("am", ARGENT)], library: LIB });
    const s = mutate(s0, "bear");
    expect({ artifact: isArtifact(s, "bear"), drew: s.players.user.hand.map((c) => c.id) }).toEqual({ artifact: true, drew: ["l1"] });
  });
  it("⭐ Stone by Sunlight's second mode: a real artifact creature (no \"Artifact\" subtype) with indestructible, until end of turn", () => {
    const s0 = board([P("bear", BEARS)], [], { pool: POOL, hand: [H("sbs", STONE)] });
    const s = cast(s0, "sbs", "bear", (a) => a.chosenMode === 1);
    const t = permanentTypes(s, "bear");
    expect({ types: [...t.types].sort(), subtypes: t.subtypes, indestructible: permanentHasKeyword(s, "bear", "indestructible"), nextTurn: isArtifact(cleanup(s), "bear") })
      .toEqual({ types: ["Artifact", "Creature"], subtypes: ["Bear"], indestructible: true, nextTurn: false });
  });
  it("Enter the Avatar State still adds the Avatar SUBTYPE — not a card type", () => {
    const s = cast(board([P("bear", BEARS)], [], { pool: POOL, hand: [H("eas", AVATAR_STATE)] }), "eas", "bear");
    expect({ subtypes: [...permanentTypes(s, "bear").subtypes].sort(), artifact: isArtifact(s, "bear") }).toEqual({ subtypes: ["Avatar", "Bear"], artifact: false });
  });
});

describe("NEGATED readers — a missed artifact here is an illegal play", () => {
  const twoBears = (extra = {}) => board([P("lt", TORQUE), P("bear", BEARS), P("b2", BEARS)], [], { pool: POOL, ...extra });
  it("⭐ Go for the Throat (\"target nonartifact creature\") can't target a Torqued creature — and can again once the effect ends", () => {
    const s0 = twoBears({ hand: [H("gft", GO_FOR_THE_THROAT)] });
    const s = becomeArtifact(s0, "bear");
    expect({ plain: castTargets(s0, "gft"), torqued: castTargets(s, "gft"), nextTurn: castTargets(cleanup(s), "gft") })
      .toEqual({ plain: ["b2", "bear"], torqued: ["b2"], nextTurn: ["b2", "bear"] });
  });
  it("…nor Impossible Man while he is a copy of an artifact creature (the copy's types, layer 1)", () => {
    const s0 = board([P("im", IMPOSSIBLE_MAN), P("hm", HAYWIRE_MITE)], [], { pool: POOL, hand: [H("gft", GO_FOR_THE_THROAT)] });
    expect({ plain: castTargets(s0, "gft"), copying: castTargets(becomeArtifact(s0, "hm", "im"), "gft") }).toEqual({ plain: ["im"], copying: [] });
  });
  it("Terror (\"nonartifact, nonblack creature\") — the same restriction in a list", () => {
    const s0 = twoBears({ hand: [H("ter", TERROR)] });
    expect({ plain: castTargets(s0, "ter"), torqued: castTargets(becomeArtifact(s0, "bear"), "ter") }).toEqual({ plain: ["b2", "bear"], torqued: ["b2"] });
  });
  it("⭐ Their Name Is Death (\"destroy all nonartifact creatures\") spares the Torqued creature", () => {
    const s = cast(becomeArtifact(twoBears({ hand: [H("tnd", THEIR_NAME)] }), "bear"), "tnd");
    expect(onBattlefield(s)).toEqual(["bear", "lt"]);
  });
  it("Whipflare (\"2 damage to each nonartifact creature\") doesn't touch it", () => {
    const s = cast(becomeArtifact(twoBears({ hand: [H("wf", WHIPFLARE)] }), "bear"), "wf");
    expect({ left: onBattlefield(s), damage: findPermanent(s, "bear").permanent.damageMarked || 0 }).toEqual({ left: ["bear", "lt"], damage: 0 });
  });
  it("a negated condition word: \"you control another nonland permanent\" (Reclusive Wight) — a slumbering Arixmethes is a land; and the grammar's \"nonartifact creature\" (no printed carrier)", () => {
    const wight = (other) => evaluateInterveningIf(board([P("rw", RECLUSIVE_WIGHT), other]), condOf(RECLUSIVE_WIGHT), "user", { triggeringPermanentId: "rw", sourcePermanentId: "rw" });
    const s0 = board([P("lt", TORQUE), P("bear", BEARS)]);
    const nonartifactCreature = (st) => evaluateInterveningIf(st, "you control a nonartifact creature", "user");
    expect({ asleep: wight(P("arx", ARIXMETHES, "user", { counters: { slumber: 5 } })), awake: wight(P("arx", ARIXMETHES)), compass: wight(P("tc", COMPASS)), plain: nonartifactCreature(s0), torqued: nonartifactCreature(becomeArtifact(s0, "bear")) })
      .toEqual({ asleep: false, awake: true, compass: true, plain: true, torqued: false }); // Thaumatic Compass's face is an artifact — its back face's Land is not on the battlefield
  });
  it("⭐ Covetous Dragon (\"When you control no artifacts, sacrifice this creature\"): a creature made an artifact is one — no trigger", () => {
    const s0 = board([P("cd", COVETOUS_DRAGON), P("bear", BEARS)], [], { pool: POOL, hand: [H("am", ARGENT)], library: LIB });
    const fired = (st) => (checkStateTriggers(st).pendingTriggers || []).length;
    expect({ plain: fired(s0), mutated: fired(mutate(s0, "bear")) }).toEqual({ plain: 1, mutated: 0 });
  });
  it("Synod Centurion (\"no OTHER artifacts\") — the same", () => {
    const s0 = board([P("sc", SYNOD_CENTURION), P("bear", BEARS)], [], { pool: POOL, hand: [H("am", ARGENT)], library: LIB });
    const fired = (st) => (checkStateTriggers(st).pendingTriggers || []).length;
    expect({ plain: fired(s0), mutated: fired(mutate(s0, "bear")) }).toEqual({ plain: 1, mutated: 0 });
  });
  it("⭐ Tezzeret's Ambition (\"If you control no artifacts, discard a card\"): no discard once you control a mutated creature", () => {
    const s0 = board([P("bear", BEARS)], [], { pool: POOL, hand: [H("am", ARGENT), H("ta", TEZZERETS_AMBITION), H("x", BEARS)], library: [...LIB, H("l5", BEARS)] });
    // plain: the discard pauses for the controller's pick; mutated: Argent Mutation resolved first and the rider is skipped.
    const afterAmbition = (st) => { const r = cast(st, "ta"); return { hand: r.players.user.hand.length, pending: r.pendingChoice?.kind ?? null }; };
    expect({ plain: afterAmbition(s0), mutated: afterAmbition(mutate(s0, "bear")) }).toEqual({ plain: { hand: 5, pending: "discard" }, mutated: { hand: 5, pending: null } });
  });
  it("the absence shapes the condition grammar reads, each answered by the layer engine (Glimmervoid's own \"you control no artifacts\"; the rest are the grammar's spellings)", () => {
    const s0 = board([P("bear", BEARS)], [P("ob", BEARS, "ai")], { pool: POOL, hand: [H("am", ARGENT)], library: LIB });
    const row = (st) => [condOf(GLIMMERVOID), "you don't control an artifact", "your opponents control no artifacts", "no artifacts are on the battlefield", "you control one or fewer artifacts"]
      .map((c) => evaluateInterveningIf(st, c, "user"));
    // mine: the bear is mine; theirs: the opponent's bear (an "an artifact you control" question vs an opponents' one).
    const mine = mutate(s0, "bear");
    const theirs = mutate(s0, "ob");
    expect({ plain: row(s0), mine: row(mine), theirs: row(theirs) })
      .toEqual({ plain: [true, true, true, true, true], mine: [false, false, true, false, true], theirs: [true, true, false, false, true] });
  });
  it("\"you control one or fewer artifacts\" counts it (an undercount would pass the gate)", () => {
    const s0 = board([P("lt", TORQUE), P("bear", BEARS)]);
    const gate = (st) => evaluateInterveningIf(st, "you control one or fewer artifacts", "user");
    expect({ plain: gate(s0), torqued: gate(becomeArtifact(s0, "bear")) }).toEqual({ plain: true, torqued: false });
  });
  it("⭐ Neurok Spy / Bouncing Beebles / Scrapdiver Serpent (\"can't be blocked as long as defending player controls an artifact\"): the defender's Torqued creature makes the block illegal", () => {
    const attackers = ["spy", "bb", "ss"];
    const s0 = board([P("lt", TORQUE), P("spy", NEUROK_SPY), P("bb", BOUNCING_BEEBLES), P("ss", SCRAPDIVER)], [P("ob", BEARS, "ai")], { combat: { attackers: attackers.map((id) => ({ permanentId: id, attackingPlayer: "user", defender: "ai" })), blockers: [] } });
    const blocks = (st) => attackers.map((id) => canBlockAttacker(st, "ob", id, "ai"));
    expect({ plain: blocks(s0), torqued: blocks(becomeArtifact(s0, "ob")) }).toEqual({ plain: [true, true, true], torqued: [false, false, false] });
  });
  it("…its enchantment and untapped-land siblings read the layer engine too: Bubbling Beebles (an enchantment by a layer-4 effect — no printed card writes one, so the effect is applied directly) and Hazy Homunculus (a slumbering Arixmethes is an untapped land)", () => {
    const attackBy = (id) => ({ attackers: [{ permanentId: id, attackingPlayer: "user", defender: "ai" }], blockers: [] });
    const s0 = board([P("bub", BUBBLING_BEEBLES)], [P("ob", BEARS, "ai")], { combat: attackBy("bub") });
    const ench = addContinuousEffect(s0, { layer: 4, op: { types: ["Enchantment"] }, affects: { mode: "fixed", permanentIds: ["ob"] }, duration: { kind: "endOfTurn", turn: s0.turn }, source: { kind: "resolution", permanentId: null, cardName: null } }).state;
    const hazy = (arx) => canBlockAttacker(board([P("hz", HAZY_HOMUNCULUS)], [P("ob", BEARS, "ai"), arx], { combat: attackBy("hz") }), "ob", "hz", "ai");
    expect({ bubbling: [canBlockAttacker(s0, "ob", "bub", "ai"), canBlockAttacker(ench, "ob", "bub", "ai")], hazy: [hazy(P("arx", ARIXMETHES, "ai")), hazy(P("arx", ARIXMETHES, "ai", { counters: { slumber: 5 } }))] })
      .toEqual({ bubbling: [true, false], hazy: [true, false] });
  });
  it("⭐ \"an opponent controls more artifacts than you\" counts a Torqued creature on either side", () => {
    const s0 = board([P("lt", TORQUE)], [P("sol", SOL_RING, "ai"), P("ob", BEARS, "ai")]);
    const more = (st) => evaluateInterveningIf(st, "an opponent controls more artifacts than you", "user");
    expect({ plain: more(s0), torqued: more(becomeArtifact(s0, "ob")) }).toEqual({ plain: false, torqued: true });
  });
  it("⭐ Padeem (\"you control the artifact with the greatest mana value or tied\"): an opponent's Torqued 5-drop is the greatest", () => {
    const s0 = board([P("lt", TORQUE), P("pad", PADEEM), P("sol", SOL_RING)], [P("sm", SHRIEKMAW, "ai")]);
    const greatest = (st) => evaluateInterveningIf(st, condOf(PADEEM), "user");
    expect({ plain: greatest(s0), torqued: greatest(becomeArtifact(s0, "sm")) }).toEqual({ plain: true, torqued: false });
  });
});

describe("positive readers — the legal plays an artifact by layer 4 opens", () => {
  // Torque made the Bear an artifact creature; Coating made the Forest an artifact land.
  const HAND = [["sh", SHATTER], ["de", DISENCHANT], ["cr", CRUSH], ["pu", PUTREFY], ["pi", PILLAGE], ["cm", CREEPING_MOLD], ["bd", BEDEVIL], ["bw", BROKEN_WINGS], ["mf", MOLTEN_FRAME], ["bc", BRAMBLECRUSH], ["sc", STASIS_COCOON], ["io", ICE_OVER], ["pd", PLANAR_DISRUPTION]].map(([id, c]) => H(id, c));
  const plain = () => board([P("lt", TORQUE), P("lc", COATING), P("bear", BEARS), P("for", FOREST), P("sol", SOL_RING), P("ex", EXPLORATION), P("hm", HAYWIRE_MITE)], [], { pool: POOL, hand: HAND });
  const changed = () => becomeArtifact(becomeArtifact(plain(), "bear", "lt"), "for", "lc");
  it("⭐ the removal pools: target artifact (Shatter), artifact or enchantment (Disenchant), noncreature artifact (Crush), artifact or creature (Putrefy), artifact or land (Pillage), artifact/enchantment/land (Creeping Mold), artifact/creature/planeswalker (Bedevil), artifact/enchantment/flying creature (Broken Wings), artifact creature (Molten Frame)", () => {
    const pools = (st) => Object.fromEntries(["sh", "de", "cr", "pu", "pi", "cm", "bd", "bw", "mf"].map((id) => [id, castTargets(st, id)]));
    expect({ plain: pools(plain()), changed: pools(changed()) }).toEqual({
      plain: { sh: ["hm", "lc", "lt", "sol"], de: ["ex", "hm", "lc", "lt", "sol"], cr: ["lc", "lt", "sol"], pu: ["bear", "hm", "lc", "lt", "sol"], pi: ["for", "hm", "lc", "lt", "sol"], cm: ["ex", "for", "hm", "lc", "lt", "sol"], bd: ["bear", "hm", "lc", "lt", "sol"], bw: ["ex", "hm", "lc", "lt", "sol"], mf: ["hm"] },
      changed: { sh: ["bear", "for", "hm", "lc", "lt", "sol"], de: ["bear", "ex", "for", "hm", "lc", "lt", "sol"], cr: ["for", "lc", "lt", "sol"], pu: ["bear", "for", "hm", "lc", "lt", "sol"], pi: ["bear", "for", "hm", "lc", "lt", "sol"], cm: ["bear", "ex", "for", "hm", "lc", "lt", "sol"], bd: ["bear", "for", "hm", "lc", "lt", "sol"], bw: ["bear", "ex", "for", "hm", "lc", "lt", "sol"], mf: ["bear", "hm"] },
    });
  });
  it("⭐ fixed on the way: Crush (\"noncreature artifact\") and Bramblecrush (\"noncreature permanent\") cast through their own pools — the legacy destroy parse read \"noncreature\" as a creature target and offered (and destroyed) creatures", () => {
    const s = plain();
    const after = cast(s, "cr", "sol");
    expect({ crush: castTargets(s, "cr"), bramblecrush: castTargets(s, "bc"), crushed: onBattlefield(after).includes("sol") })
      .toEqual({ crush: ["lc", "lt", "sol"], bramblecrush: ["ex", "for", "lc", "lt", "sol"], crushed: false });
  });
  it("Haywire Mite's \"noncreature artifact or noncreature enchantment\" takes the Coated Forest, never the Torqued Bear (a creature)", () => {
    expect({ plain: offered(plain(), "hm"), changed: offered(changed(), "hm") }).toEqual({ plain: ["ex", "lc", "lt", "sol"], changed: ["ex", "for", "lc", "lt", "sol"] });
  });
  it("the channel lands' pools from hand (Boseiju: artifact, enchantment, or nonbasic land an opponent controls; Otawara: artifact, creature, enchantment, or planeswalker)", () => {
    const s0 = board([P("lt", TORQUE), P("lc", COATING)], [P("ob", BEARS, "ai"), P("of", FOREST, "ai")], { pool: POOL, hand: [H("bos", BOSEIJU), H("ota", OTAWARA)] });
    const s = becomeArtifact(becomeArtifact(s0, "ob", "lt"), "of", "lc");
    const pool = (st, cardId) => ids(actionsOf(st).filter((a) => a.kind === "discard-ability" && a.cardId === cardId).flatMap((a) => a.targets || []));
    expect({ boseiju: [pool(s0, "bos"), pool(s, "bos")], otawara: [pool(s0, "ota"), pool(s, "ota")] })
      .toEqual({ boseiju: [[], ["ob", "of"]], otawara: [["lc", "lt", "ob"], ["lc", "lt", "ob", "of"]] });
  });
  it("⭐ Stasis Cocoon (\"Enchant artifact\") may enchant the Torqued Bear, and it resolves ATTACHED — the resolution re-check reads the same types", () => {
    const s = cast(changed(), "sc", "bear");
    expect({ plainHosts: castTargets(plain(), "sc"), hosts: castTargets(changed(), "sc"), attachedTo: s.players.user.battlefield.find((p) => p.card?.name === "Stasis Cocoon")?.attachedTo ?? null })
      .toEqual({ plainHosts: ["hm", "lc", "lt", "sol"], hosts: ["bear", "for", "hm", "lc", "lt", "sol"], attachedTo: "bear" });
  });
  it("the re-check's unions: Ice Over (\"artifact or creature\") and Planar Disruption (\"artifact, creature, or planeswalker\") at the Coated Forest resolve attached", () => {
    const hostOf = (st, name) => st.players.user.battlefield.find((p) => p.card?.name === name)?.attachedTo ?? null;
    expect({ iceOver: hostOf(cast(changed(), "io", "for"), "Ice Over"), planar: hostOf(cast(changed(), "pd", "for"), "Planar Disruption") }).toEqual({ iceOver: "for", planar: "for" });
  });
  it("⭐ the re-check's \"Enchant nonland permanent\" (Suppression Bonds): an Arixmethes given slumber counters in response is a land at resolution — the Aura fizzles", () => {
    // The opponent's Arixmethes (its "whenever you cast a spell" is theirs, so this cast triggers nothing).
    const s0 = board([], [P("arx", ARIXMETHES, "ai")], { pool: POOL, hand: [H("bonds", SUPPRESSION_BONDS)] });
    const act = castActions(s0, "bonds").find((a) => (a.targets || []).some((t) => t.id === "arx"));
    const onStack = dispatchAction(s0, act);
    const asleep = { ...onStack, players: { ...onStack.players, ai: { ...onStack.players.ai, battlefield: onStack.players.ai.battlefield.map((p) => (p.id === "arx" ? { ...p, counters: { slumber: 1 } } : p)) } } };
    const where = (st) => (st.players.user.battlefield.some((p) => p.card?.name === "Suppression Bonds") ? "battlefield" : st.players.user.graveyard.some((c) => c.name === "Suppression Bonds") ? "graveyard" : "elsewhere");
    expect({ awake: where(resolveTopOfStack(onStack)), asleep: where(resolveTopOfStack(asleep)) }).toEqual({ awake: "battlefield", asleep: "graveyard" });
  });
  it("CR 704.5m reads the face that is up: Stasis Cocoon attached to Sidequest: Play Blitzball (an enchantment front, an artifact only on its back face) goes to the graveyard", () => {
    const s = board([P("sq", BLITZBALL, "user", { attachments: ["sc"] }), P("sc", STASIS_COCOON, "user", { attachedTo: "sq" })]);
    expect(checkAllStateBasedActions(s).players.user.graveyard.map((c) => c.name)).toEqual(["Stasis Cocoon"]);
  });
  it("⭐ CR 704.5m: when the type add ends at cleanup, Stasis Cocoon / Ice Over / Planar Disruption on a permanent that is no longer an artifact go to the graveyard; on one that still qualifies they stay", () => {
    // [aura, host] → is the Aura still on the battlefield after the turn's effects end and the SBAs run? (before cleanup: all are)
    const stays = (cardId, hostId) => {
      const s = cast(changed(), cardId, hostId);
      const name = HAND.find((c) => c.id === cardId).name;
      const on = (st) => st.players.user.battlefield.some((p) => p.card?.name === name && p.attachedTo === hostId);
      return [on(checkAllStateBasedActions(s)), on(checkAllStateBasedActions(cleanup(s)))];
    };
    expect({ cocoonOnBear: stays("sc", "bear"), iceOverOnForest: stays("io", "for"), planarOnForest: stays("pd", "for"), iceOverOnBear: stays("io", "bear"), planarOnTorque: stays("pd", "lt") })
      .toEqual({ cocoonOnBear: [true, false], iceOverOnForest: [true, false], planarOnForest: [true, false], iceOverOnBear: [true, true], planarOnTorque: [true, true] });
  });
  it("a positive condition: \"you control an artifact\" (Scholar of Stars) and metalcraft's \"three or more artifacts\" (Lumengrid Drake) count it", () => {
    const s0 = board([P("bear", BEARS)], [], { pool: POOL, hand: [H("am", ARGENT)], library: LIB });
    const s1 = board([P("lt", TORQUE), P("sol", SOL_RING), P("bear", BEARS)]);
    const holds = (st, card) => evaluateInterveningIf(st, condOf(card), "user");
    expect({ scholar: [holds(s0, SCHOLAR), holds(mutate(s0, "bear"), SCHOLAR)], metalcraft: [holds(s1, LUMENGRID_DRAKE), holds(becomeArtifact(s1, "bear"), LUMENGRID_DRAKE)] })
      .toEqual({ scholar: [false, true], metalcraft: [false, true] });
  });
});

describe("already layer-aware — the type add reaches them for free", () => {
  it("⭐ Null Rod (\"Activated abilities of artifacts can't be activated\"): a mutated Llanowar Elves can't tap for mana", () => {
    const s0 = board([P("rod", NULL_ROD), P("elf", LLANOWAR)], [], { pool: POOL, hand: [H("am", ARGENT)], library: LIB });
    const taps = (st) => [actionsOf(st).filter((a) => a.kind === "tap-for-mana" && a.permanentId === "elf").length > 0, manaSources(st, "user").some((src) => src.permanentId === "elf")];
    expect({ plain: taps(s0), mutated: taps(mutate(s0, "elf")) }).toEqual({ plain: [true, true], mutated: [false, false] });
  });
  it("Tempered Steel (\"Artifact creatures you control get +2/+2\")", () => {
    const s0 = board([P("lt", TORQUE), P("ts", TEMPERED_STEEL), P("bear", BEARS)]);
    const pt = (st) => { const c = deriveCharacteristics(st, "bear"); return [c.power, c.toughness]; };
    expect({ plain: pt(s0), torqued: pt(becomeArtifact(s0, "bear")) }).toEqual({ plain: [2, 2], torqued: [4, 4] });
  });
  it("fear (Shriekmaw: \"can't be blocked except by artifact creatures and/or black creatures\") — a Torqued green creature may block", () => {
    const s0 = board([P("lt", TORQUE), P("sm", SHRIEKMAW)], [P("ob", BEARS, "ai")], { combat: { attackers: [{ permanentId: "sm", attackingPlayer: "user", defender: "ai" }], blockers: [] } });
    expect({ plain: canBlockAttacker(s0, "ob", "sm", "ai"), torqued: canBlockAttacker(becomeArtifact(s0, "ob"), "ob", "sm", "ai") }).toEqual({ plain: false, torqued: true });
  });
});
