/**
 * PLAGUECRAFTER, RUINOUS ULTIMATUM, DRAMATIC REVERSAL — the play-weighted program, #639, #651, #666.
 *
 *  - PLAGUECRAFTER "When this creature enters, each player sacrifices a creature or planeswalker of their choice. Each player who
 *    can't discards a card." The edict is the N-count chain (removal.advanceCreatureBatchSacrifice) with a count of one and a
 *    creature-or-planeswalker pool: the active player chooses first, then each other player in turn order, and every chosen
 *    permanent is sacrificed at once (CR 101.4). Plaguecrafter's controller may give up Plaguecrafter itself. "Each player who
 *    can't" reads back to the edict (CR 608.2c): the players with no creature or planeswalker, recorded in APNAP order as the
 *    sacrifice begins (state.couldNotSacrificeThisWay), each discard a card of their choice (CR 701.9b) once the sacrifice is done.
 *    The pool is read layer-aware: an animated land is a creature its controller can give up. A sacrificed planeswalker dies too
 *    (CR 700.4) and its watchers see it.
 *  - RUINOUS ULTIMATUM "Destroy all nonland permanents your opponents control." One destroy over a new one-sided mass scope
 *    (eachOpponentNonlandPermanent): every permanent an opponent controls that is not a land as it exists right now — an animated
 *    land is a land, Arixmethes is one while it has a slumber counter. Indestructible and regeneration keep a permanent as they
 *    do from any destroy. The caster's permanents are never in the set.
 *  - DRAMATIC REVERSAL "Untap all nonland permanents you control." The controller's own untap (untap-lands) with a nonland scope.
 *
 * Every card-type question here (the nonland sets, the edict's pool, the planeswalker that died) goes through the battlefield
 * card-type reader, layers.permanentHasCardType: layer-aware, and read on the face that is up — a double-faced permanent with its
 * front face up has only its front face's characteristics (CR 712.8d), so an untransformed Westvale Abbey is a land and no
 * creature, Legion's Landing an enchantment and no land.
 *
 * The same readers complete Demon's Disciple (the edict alone — no discard), Paradox Engine and Unstoppable Plan (the untap on a cast
 * trigger and an end-step trigger); each is witnessed here.
 *
 * Real oracle fixtures (bundled Scryfall, the 2026-10-01 data, generated by cardIndex.publicCard — never typed by hand).
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, createGameState, createPermanent } from "./gameState.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { advanceStep, chooseTriggerTargets, finalizeStackResolution, flushTriggers, resolveTopOfStack, runStepActions } from "./gameEngine.js";
import { autoPickDiscardCandidate, autoPickSacrificeCandidate, resolveDiscardChoice, resolveOptionalChoice, resolveSacrificeChoice } from "./effects/runProgram.js";
import { classifyCard } from "./coverage.js";
import { parseEffectClause, parseEffectProgram, programConfidence } from "./effects/parser.js";
import { detectTriggers } from "./triggers.js";
import { permanentHasCardType } from "./layers.js";
import { advanceUntilDecision, applyDiscardChoice } from "./learnSession.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const PLAGUECRAFTER = {"name":"Plaguecrafter","type":"Creature — Human Shaman","mana":"{2}{B}","cmc":3,"power":"3","toughness":"2","keywords":[],"colors":["B"],"oracle":"When this creature enters, each player sacrifices a creature or planeswalker of their choice. Each player who can't discards a card."}; // native-trigger
const RUINOUS = {"name":"Ruinous Ultimatum","type":"Sorcery","mana":"{R}{R}{W}{W}{W}{B}{B}","cmc":7,"keywords":[],"colors":["B","R","W"],"oracle":"Destroy all nonland permanents your opponents control."}; // native-spell
const REVERSAL = {"name":"Dramatic Reversal","type":"Instant","mana":"{1}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Untap all nonland permanents you control."}; // native-spell
const DISCIPLE = {"name":"Demon's Disciple","type":"Creature — Human Cleric","mana":"{2}{B}","cmc":3,"power":"3","toughness":"1","keywords":[],"colors":["B"],"oracle":"When this creature enters, each player sacrifices a creature or planeswalker of their choice."}; // native-trigger
const PARADOX = {"name":"Paradox Engine","type":"Legendary Artifact","mana":"{5}","cmc":5,"keywords":[],"colors":[],"oracle":"Whenever you cast a spell, untap all nonland permanents you control."}; // native-trigger
const UNSTOPPABLE = {"name":"Unstoppable Plan","type":"Enchantment","mana":"{2}{U}","cmc":3,"keywords":[],"colors":["U"],"oracle":"At the beginning of your end step, untap all nonland permanents you control."}; // native-trigger
const DEADLY_BREW = {"name":"Deadly Brew","type":"Sorcery","mana":"{B}{G}","cmc":2,"keywords":[],"colors":["B","G"],"oracle":"Each player sacrifices a creature or planeswalker of their choice. If you sacrificed a permanent this way, you may return another permanent card from your graveyard to your hand."}; // arbiter-spell
const PLANAR_CLEANSING = {"name":"Planar Cleansing","type":"Sorcery","mana":"{3}{W}{W}{W}","cmc":6,"keywords":[],"colors":["W"],"oracle":"Destroy all nonland permanents."}; // arbiter-spell
const INTELLECTUAL = {"name":"Intellectual Offering","type":"Instant","mana":"{4}{U}","cmc":5,"keywords":[],"colors":["U"],"oracle":"Choose an opponent. You and that player each draw three cards.\nChoose an opponent. Untap all nonland permanents you control and all nonland permanents that player controls."}; // arbiter-spell
const CURSE_OF_BOUNTY = {"name":"Curse of Bounty","type":"Enchantment — Aura Curse","mana":"{1}{G}","cmc":2,"keywords":["Enchant"],"colors":["G"],"oracle":"Enchant player\nWhenever enchanted player is attacked, untap all nonland permanents you control. Each opponent attacking that player untaps all nonland permanents they control."}; // body-only
const MOMENTUM = {"name":"Momentum Breaker","type":"Enchantment","mana":"{1}{B}","cmc":2,"keywords":["Start your engines!"],"colors":["B"],"oracle":"Start your engines! (If you have no speed, it starts at 1. It increases once on each of your turns when an opponent loses life. Max speed is 4.)\nWhen this enchantment enters, each opponent sacrifices a creature or Vehicle of their choice. Each opponent who can't discards a card.\n{2}, Sacrifice this enchantment: You gain life equal to your speed."}; // body-only
const BARTER = {"name":"Barter in Blood","type":"Sorcery","mana":"{2}{B}{B}","cmc":4,"keywords":[],"colors":["B"],"oracle":"Each player sacrifices two creatures of their choice."}; // native-spell
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const GIANT = {"name":"Hill Giant","type":"Creature — Giant","mana":"{3}{R}","cmc":4,"power":"3","toughness":"3","keywords":[],"colors":["R"],"oracle":""}; // native-body
const SWAMP = {"name":"Swamp","type":"Basic Land — Swamp","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {B}.)"}; // land
const ISLAND = {"name":"Island","type":"Basic Land — Island","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {U}.)"}; // land
const MOUNTAIN = {"name":"Mountain","type":"Basic Land — Mountain","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {R}.)"}; // land
const PLAINS = {"name":"Plains","type":"Basic Land — Plains","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {W}.)"}; // land
const MUTAVAULT = {"name":"Mutavault","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{1}: This land becomes a 2/2 creature with all creature types until end of turn. It's still a land."}; // land
const SOL_RING = {"name":"Sol Ring","type":"Artifact","mana":"{1}","cmc":1,"keywords":[],"colors":[],"oracle":"{T}: Add {C}{C}."}; // native-mana
const MIND_STONE = {"name":"Mind Stone","type":"Artifact","mana":"{2}","cmc":2,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{1}, {T}, Sacrifice this artifact: Draw a card."}; // native-mana
const BLOOD_ARTIST = {"name":"Blood Artist","type":"Creature — Vampire","mana":"{1}{B}","cmc":2,"power":"0","toughness":"1","keywords":[],"colors":["B"],"oracle":"Whenever this creature or another creature dies, target player loses 1 life and you gain 1 life."}; // native-trigger
const CELEBRANT = {"name":"Cruel Celebrant","type":"Creature — Vampire","mana":"{W}{B}","cmc":2,"power":"1","toughness":"2","keywords":[],"colors":["B","W"],"oracle":"Whenever this creature or another creature or planeswalker you control dies, each opponent loses 1 life and you gain 1 life."}; // native-trigger
const LILIANA = {"name":"Liliana of the Veil","type":"Legendary Planeswalker — Liliana","mana":"{1}{B}{B}","cmc":3,"loyalty":"3","keywords":[],"colors":["B"],"oracle":"+1: Each player discards a card.\n−2: Target player sacrifices a creature.\n−6: Separate all permanents target player controls into two piles. That player sacrifices all permanents in the pile of their choice."}; // playable-pw
const MYR = {"name":"Darksteel Myr","type":"Artifact Creature — Myr","mana":"{3}","cmc":3,"power":"0","toughness":"1","keywords":["Indestructible"],"colors":[],"oracle":"Indestructible (Damage and effects that say \"destroy\" don't destroy this creature. If its toughness is 0 or less, it still dies.)"}; // native-body
const DRUDGE = {"name":"Drudge Skeletons","type":"Creature — Skeleton","mana":"{1}{B}","cmc":2,"power":"1","toughness":"1","keywords":["Heal","Regenerate"],"colors":["B"],"oracle":"{B}: Regenerate this creature. (The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)"}; // native-activated
const ELVES = {"name":"Llanowar Elves","type":"Creature — Elf Druid","mana":"{G}","cmc":1,"power":"1","toughness":"1","keywords":[],"colors":["G"],"oracle":"{T}: Add {G}."}; // native-mana
const LANDING = {"name":"Legion's Landing // Adanto, the First Fort","type":"Legendary Enchantment // Legendary Land","mana":"{W}","cmc":1,"keywords":["Transform"],"layout":"transform","colors":[],"oracle":"Legion's Landing - Legendary Enchantment {W}\nWhen Legion's Landing enters, create a 1/1 white Vampire creature token with lifelink.\nWhen you attack with three or more creatures, transform Legion's Landing.\n//\nAdanto, the First Fort - Legendary Land \n(Transforms from Legion's Landing.)\n{T}: Add {W}.\n{2}{W}, {T}: Create a 1/1 white Vampire creature token with lifelink."}; // body-only
const ABBEY = {"name":"Westvale Abbey // Ormendahl, Profane Prince","type":"Land // Legendary Creature — Demon","mana":"","cmc":0,"keywords":["Flying","Lifelink","Indestructible","Transform","Haste"],"layout":"transform","colors":[],"oracle":"Westvale Abbey - Land \n{T}: Add {C}.\n{5}, {T}, Pay 1 life: Create a 1/1 white and black Human Cleric creature token.\n{5}, {T}, Sacrifice five creatures: Transform this land, then untap it.\n//\nOrmendahl, Profane Prince - Legendary Creature — Demon \nFlying, lifelink, indestructible, haste"}; // land-partial
const ARIXMETHES = {"name":"Arixmethes, Slumbering Isle","type":"Legendary Creature — Kraken","mana":"{2}{G}{U}","cmc":4,"power":"12","toughness":"12","keywords":[],"colors":["G","U"],"oracle":"Arixmethes enters tapped with five slumber counters on it.\nAs long as Arixmethes has a slumber counter on it, it's a land. (It's not a creature.)\nWhenever you cast a spell, you may remove a slumber counter from Arixmethes.\n{T}: Add {G}{U}."}; // native-mana
const BOLT = {"name":"Lightning Bolt","type":"Instant","mana":"{R}","cmc":1,"keywords":[],"colors":["R"],"oracle":"Lightning Bolt deals 3 damage to any target."}; // native-spell
const ORRERY = {"name":"Vedalken Orrery","type":"Artifact","mana":"{4}","cmc":4,"keywords":[],"colors":[],"oracle":"You may cast spells as though they had flash."}; // native-static
const DELVER = {"name":"Delver of Secrets // Insectile Aberration","type":"Creature — Human Wizard // Creature — Human Insect","mana":"{U}","cmc":1,"power":"1","toughness":"1","keywords":["Flying","Transform"],"layout":"transform","colors":[],"oracle":"Delver of Secrets - Creature — Human Wizard {U}\nAt the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform this creature.\n//\nInsectile Aberration - Creature — Human Insect \nFlying"}; // body-only

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const H = (id, card) => ({ ...card, id });
const SEATS = ["user", "ai1", "ai2", "ai3"];
// A four-seat Commander table, turn order user → ai1 → ai2 → ai3. `bf` / `hands` are keyed by seat; `pool` is the user's mana pool.
function pod({ bf = {}, hands = {}, pool = {}, active = "user", phase = "precombat-main", step = "main" } = {}) {
  const g = createGameState({ mode: "commander", userDeck: [], opponentDecks: [[], [], []] });
  const seat = (pid) => ({ ...g.players[pid], battlefield: bf[pid] || [], hand: hands[pid] || [], library: [1, 2, 3].map((i) => ({ ...BEARS, id: `${pid}-lib${i}` })),
    ...(pid === "user" ? { manaPool: { ...g.players.user.manaPool, ...pool } } : {}) });
  return { ...g, turn: 5, activePlayer: active, priorityHolder: active, phase, step, stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: Object.fromEntries(SEATS.map((pid) => [pid, seat(pid)])) };
}
const castsOf = (s, who, cardId) => legalActionsForPlayer({ ...s, priorityHolder: who }, who).filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
const activations = (s, who, permId) => legalActionsForPlayer({ ...s, priorityHolder: who }, who).filter((a) => a.kind === "activate-ability" && a.permanentId === permId);
const withPool = (s, who, pool) => ({ ...s, players: { ...s.players, [who]: { ...s.players[who], manaPool: { ...s.players[who].manaPool, ...pool } } } });
// Mutavault's "{1}: … becomes a 2/2 creature …" activated and resolved for `who`, paid with the {C} put in that player's pool.
const animate = (s, who, permId) => {
  const s1 = withPool(s, who, { C: 1 });
  return resolveTopOfStack(dispatchAction({ ...s1, priorityHolder: who }, activations(s1, who, permId).find((a) => !a.isManaAbility && a.cost?.generic === 1)));
};
// The learnSession settles, verbatim: settle the pick, then finalize (flush what it woke) once nothing is pending any more.
const settleSac = (s, pick) => { const n = resolveSacrificeChoice(s, pick); return n.pendingChoice ? n : finalizeStackResolution(n); };
const settleDiscard = (s, pick) => { const n = resolveDiscardChoice(s, pick); return n.pendingChoice ? n : finalizeStackResolution(n); };
// Every open choice settled by the shared AI policy; `asked` records who was asked what, in order.
function autoSettle(s, asked = []) {
  let n = s;
  for (let i = 0; i < 40 && n.pendingChoice; i++) {
    const pc = n.pendingChoice;
    asked.push(`${pc.kind}:${pc.controller}`);
    n = pc.kind === "sacrifice-choice" ? settleSac(n, autoPickSacrificeCandidate(n, pc)) : settleDiscard(n, autoPickDiscardCandidate(n, pc));
  }
  return n;
}
// Cast `cardId` from `who`'s hand, let the creature spell resolve (its enters trigger goes on the stack), then resolve the trigger.
function castAndResolveTrigger(s0, who, cardId) {
  const offer = castsOf(s0, who, cardId);
  const entered = resolveTopOfStack(dispatchAction({ ...s0, priorityHolder: who }, offer[0]));
  return { offered: offer.length, triggered: entered.stack.map((o) => o.source?.name), s: resolveTopOfStack(entered) };
}
const permOf = (s, pid, name) => s.players[pid].battlefield.find((p) => p.card?.name === name);
const ids = (s, pid) => s.players[pid].battlefield.map((p) => p.id).sort();
const gy = (s, pid) => s.players[pid].graveyard.map((c) => c.name).sort();
const handIds = (s, pid) => s.players[pid].hand.map((c) => c.id).sort();
const tappedIds = (s, pid) => s.players[pid].battlefield.filter((p) => p.tapped).map((p) => p.id).sort();
const errors = (s) => (s.log || []).filter((e) => e.kind === "stack-resolve-error");
const stackNames = (s) => s.stack.map((o) => o.source?.name);

describe("the cards and their parse", () => {
  it("classify: the three targets native — and the three cards the same readers complete; the near misses stay parked", () => {
    const row = Object.fromEntries([PLAGUECRAFTER, RUINOUS, REVERSAL, DISCIPLE, PARADOX, UNSTOPPABLE, DEADLY_BREW, PLANAR_CLEANSING, INTELLECTUAL, CURSE_OF_BOUNTY, MOMENTUM]
      .map((c) => [c.name, classifyCard(c)]));
    console.log("  WITNESS classify", JSON.stringify(row)); // vitest 4 needs --disable-console-intercept
    expect(row).toEqual({
      "Plaguecrafter": "native-trigger", "Ruinous Ultimatum": "native-spell", "Dramatic Reversal": "native-spell",
      "Demon's Disciple": "native-trigger", "Paradox Engine": "native-trigger", "Unstoppable Plan": "native-trigger",
      "Deadly Brew": "arbiter-spell", "Planar Cleansing": "arbiter-spell", "Intellectual Offering": "arbiter-spell", "Curse of Bounty": "body-only", "Momentum Breaker": "body-only",
    });
  });

  it("Plaguecrafter's enters trigger: the edict that records who can't, then the discard for those players; Demon's Disciple: the edict alone", () => {
    const parse = (card) => { const [d] = detectTriggers(card); const p = parseEffectClause(d.effectClause, "trigger"); return { event: d.event, confidence: programConfidence(p), atoms: p.atoms }; };
    expect(parse(PLAGUECRAFTER)).toEqual({ event: "etb", confidence: "high", atoms: [
      { op: "sacrifice", who: "eachPlayer", what: "creatureOrPlaneswalker", count: 1, recordUnable: true },
      { op: "discard", who: "couldNotSacrifice", amount: 1, targetType: null },
    ] });
    expect(parse(DISCIPLE)).toEqual({ event: "etb", confidence: "high", atoms: [{ op: "sacrifice", who: "eachPlayer", what: "creatureOrPlaneswalker", count: 1 }] });
  });

  it("Ruinous Ultimatum: one destroy over the opponents' nonland set; Dramatic Reversal: the untap over the controller's nonland permanents", () => {
    const prog = (card) => { const p = parseEffectProgram(card); return { confidence: programConfidence(p), atoms: p.atoms }; };
    expect({ ruinous: prog(RUINOUS), reversal: prog(REVERSAL) }).toEqual({
      ruinous: { confidence: "high", atoms: [{ op: "destroy", targetType: "eachOpponentNonlandPermanent" }] },
      reversal: { confidence: "high", atoms: [{ op: "untap-lands", all: true, scope: "nonland", targetType: null }] },
    });
  });

  it("near misses stay unparsed: the who-can't sentence alone, another subject or pool, the symmetric sweep, the untap without its controller", () => {
    const atoms = (clause) => parseEffectClause(clause, "Sorcery")?.atoms ?? [];
    expect({
      whoCantAlone: atoms("Each player who can't discards a card."),
      eachOpponent: atoms("Each opponent sacrifices a creature or planeswalker of their choice. Each opponent who can't discards a card."),
      vehicle: atoms("Each player sacrifices a creature or Vehicle of their choice. Each player who can't discards a card."),
      symmetric: atoms("Destroy all nonland permanents."),
      exile: atoms("Exile all nonland permanents your opponents control."),
      untapEveryone: atoms("Untap all nonland permanents."),
    }).toEqual({ whoCantAlone: [], eachOpponent: [], vehicle: [], symmetric: [], exile: [], untapEveryone: [] });
  });
});

describe("the card-type reads these cards rely on (layers.permanentHasCardType — layer-aware, the face that is up)", () => {
  it("Westvale Abbey is a land and no creature; Legion's Landing no land; an animated Mutavault a land and a creature; Arixmethes asleep a land and no creature", () => {
    const s0 = pod({ bf: { user: [P("abbey", ABBEY), P("landing", LANDING), P("mv", MUTAVAULT), P("arix", ARIXMETHES, "user", { counters: { slumber: 5 } }), P("delver", DELVER)] } });
    const s = animate(s0, "user", "mv");
    const row = Object.fromEntries(["abbey", "landing", "mv", "arix", "delver"].map((id) => [id, { land: permanentHasCardType(s, id, "Land"), creature: permanentHasCardType(s, id, "Creature") }]));
    console.log("  WITNESS cardTypeReads", JSON.stringify(row));
    expect(row).toEqual({ abbey: { land: true, creature: false }, landing: { land: false, creature: false }, mv: { land: true, creature: true },
      arix: { land: true, creature: false }, delver: { land: false, creature: true } });
  });
});

describe("⭐ Plaguecrafter — each player sacrifices a creature or planeswalker; each player who can't discards a card", () => {
  it("⭐ every player able: one creature or planeswalker apiece, all sacrificed together; nobody discards", () => {
    const s0 = pod({ pool: { B: 1, C: 2 },
      bf: { user: [P("ub", BEARS)], ai1: [P("x1", ELVES, "ai1")], ai2: [P("y1", BEARS, "ai2"), P("y2", GIANT, "ai2")], ai3: [P("lili", LILIANA, "ai3", { counters: { loyalty: 3 } })] },
      hands: { user: [H("pc", PLAGUECRAFTER), H("u-h", BOLT)], ai1: [H("a1-h", BOLT)], ai2: [H("a2-h", BOLT)], ai3: [H("a3-h", BOLT)] } });
    const { offered, triggered, s: paused } = castAndResolveTrigger(s0, "user", "pc");
    const first = { controller: paused.pendingChoice?.controller, candidates: paused.pendingChoice?.candidates.map((c) => c.name).sort() };
    const asked = [];
    const s = autoSettle(settleSac(paused, "ub"), asked); // the human keeps Plaguecrafter and gives up the Bears
    const row = { offered, triggered, first, asked, unable: s.couldNotSacrificeThisWay,
      bf: Object.fromEntries(SEATS.map((pid) => [pid, s.players[pid].battlefield.map((p) => p.card.name).sort()])),
      hands: Object.fromEntries(SEATS.map((pid) => [pid, handIds(s, pid)])), stack: s.stack.length, errors: errors(s).length };
    console.log("  WITNESS plaguecrafterAllAble", JSON.stringify(row));
    expect(row).toEqual({ offered: 1, triggered: ["Plaguecrafter"], first: { controller: "user", candidates: ["Grizzly Bears", "Plaguecrafter"] }, asked: ["sacrifice-choice:ai2"], unable: [],
      bf: { user: ["Plaguecrafter"], ai1: [], ai2: ["Hill Giant"], ai3: [] },
      hands: { user: ["u-h"], ai1: ["a1-h"], ai2: ["a2-h"], ai3: ["a3-h"] }, stack: 0, errors: 0 });
  });

  it("⭐ the controller gives up Plaguecrafter itself; one player has nothing and discards; one has only a planeswalker and loses it; nothing leaves until the last choice", () => {
    const s0 = pod({ pool: { B: 1, C: 2 },
      bf: { user: [P("ub", BEARS)], ai1: [P("x1", SWAMP, "ai1")], ai2: [P("lili", LILIANA, "ai2", { counters: { loyalty: 3 } })], ai3: [P("zb", BEARS, "ai3"), P("zg", GIANT, "ai3")] },
      hands: { user: [H("u-h", BOLT)], ai1: [H("a1-bolt", BOLT), H("a1-giant", GIANT)], ai2: [H("a2-h", BOLT)], ai3: [H("a3-h", BOLT)] } });
    const withPc = { ...s0, players: { ...s0.players, user: { ...s0.players.user, hand: [H("pc", PLAGUECRAFTER), ...s0.players.user.hand] } } };
    const { s: paused } = castAndResolveTrigger(withPc, "user", "pc");
    const pcId = permOf(paused, "user", "Plaguecrafter").id;
    const afterUser = settleSac(paused, pcId);
    const midway = { controller: afterUser.pendingChoice?.controller, candidates: afterUser.pendingChoice?.candidates.map((c) => c.id).sort(),
      plaguecrafterStillThere: !!permOf(afterUser, "user", "Plaguecrafter"), lilianaStillThere: !!permOf(afterUser, "ai2", "Liliana of the Veil"), ai1Hand: handIds(afterUser, "ai1") };
    const asked = [];
    const s = autoSettle(afterUser, asked);
    const order = (s.log || []).filter((e) => e.effect === "sacrifice-together" || (e.effect === "discard" && e.controller === "ai1")).map((e) => e.effect);
    const row = { unable: s.couldNotSacrificeThisWay, midway, asked, order,
      user: { bf: ids(s, "user"), gy: gy(s, "user") }, ai1: { bf: ids(s, "ai1"), gy: gy(s, "ai1"), hand: handIds(s, "ai1") },
      ai2: { bf: ids(s, "ai2"), gy: gy(s, "ai2"), hand: handIds(s, "ai2") }, ai3: { bf: ids(s, "ai3"), gy: gy(s, "ai3"), hand: handIds(s, "ai3") }, stack: s.stack.length, errors: errors(s).length };
    console.log("  WITNESS plaguecrafterBoard", JSON.stringify(row));
    expect(row).toEqual({ unable: ["ai1"],
      midway: { controller: "ai3", candidates: ["zb", "zg"], plaguecrafterStillThere: true, lilianaStillThere: true, ai1Hand: ["a1-bolt", "a1-giant"] },
      asked: ["sacrifice-choice:ai3", "discard:ai1"], order: ["sacrifice-together", "discard"],
      user: { bf: ["ub"], gy: ["Plaguecrafter"] }, ai1: { bf: ["x1"], gy: ["Lightning Bolt"], hand: ["a1-giant"] },
      ai2: { bf: [], gy: ["Liliana of the Veil"], hand: ["a2-h"] }, ai3: { bf: ["zg"], gy: ["Grizzly Bears"], hand: ["a3-h"] }, stack: 0, errors: 0 });
  });

  it("a player who can't with one card discards it with nothing to decide; with no card discards nothing; Plaguecrafter alone is its controller's sacrifice", () => {
    const s0 = pod({ pool: { B: 1, C: 2 }, bf: { ai3: [P("zb", BEARS, "ai3")] },
      hands: { user: [H("pc", PLAGUECRAFTER)], ai1: [], ai2: [H("a2-only", GIANT)], ai3: [H("a3-h", BOLT)] } });
    const { s } = castAndResolveTrigger(s0, "user", "pc");
    const row = { paused: s.pendingChoice?.kind ?? null, unable: s.couldNotSacrificeThisWay, userGy: gy(s, "user"), ai1Gy: gy(s, "ai1"), ai2: { gy: gy(s, "ai2"), hand: handIds(s, "ai2") },
      ai3: { bf: ids(s, "ai3"), hand: handIds(s, "ai3") }, stack: s.stack.length };
    console.log("  WITNESS plaguecrafterForced", JSON.stringify(row));
    expect(row).toEqual({ paused: null, unable: ["ai1", "ai2"], userGy: ["Plaguecrafter"], ai1Gy: [], ai2: { gy: ["Hill Giant"], hand: [] }, ai3: { bf: [], hand: ["a3-h"] }, stack: 0 });
  });

  it("⭐ APNAP (CR 101.4): cast in another player's turn (Vedalken Orrery), the ACTIVE player chooses first, then turn order — and the discards follow in the same order", () => {
    const s0 = pod({ active: "ai2", pool: { B: 1, C: 2 },
      bf: { user: [P("orrery", ORRERY), P("ub", BEARS)], ai1: [P("x1", ELVES, "ai1"), P("x2", BEARS, "ai1")], ai2: [P("y1", ELVES, "ai2"), P("y2", GIANT, "ai2")], ai3: [P("z1", SWAMP, "ai3")] },
      hands: { user: [H("pc", PLAGUECRAFTER)], ai1: [H("a1-h", BOLT)], ai2: [H("a2-h", BOLT)], ai3: [H("a3-bolt", BOLT), H("a3-giant", GIANT)] } });
    const { offered, s: paused } = castAndResolveTrigger(s0, "user", "pc");
    const asked = [];
    let s = paused;
    for (let i = 0; i < 10 && s.pendingChoice; i++) {
      const pc = s.pendingChoice;
      asked.push(`${pc.kind}:${pc.controller}`);
      if (pc.kind === "sacrifice-choice" && pc.controller === "user") s = settleSac(s, "ub");
      else s = pc.kind === "sacrifice-choice" ? settleSac(s, autoPickSacrificeCandidate(s, pc)) : settleDiscard(s, autoPickDiscardCandidate(s, pc));
    }
    const row = { offered, asked, unable: s.couldNotSacrificeThisWay, user: ids(s, "user"), ai1: ids(s, "ai1"), ai2: ids(s, "ai2"), ai3: { gy: gy(s, "ai3"), hand: handIds(s, "ai3") } };
    console.log("  WITNESS plaguecrafterApnap", JSON.stringify(row));
    expect(row).toEqual({ offered: 1, asked: ["sacrifice-choice:ai2", "sacrifice-choice:user", "sacrifice-choice:ai1", "discard:ai3"], unable: ["ai3"],
      user: ["orrery", expect.stringMatching(/^perm-/)], ai1: ["x2"], ai2: ["y2"], ai3: { gy: ["Lightning Bolt"], hand: ["a3-giant"] } });
  });

  it("⭐ a human who can't picks their own discard (the session driver): the chosen card goes, the rest stay", () => {
    // ai1's turn: ai1 casts Plaguecrafter. The user controls only a Mountain (a land is neither a creature nor a planeswalker) and
    // holds a Lightning Bolt it can cast, so the driver stops again at the user's next priority with the board as the effect left it.
    const s0 = pod({ active: "ai1", bf: { user: [P("um", MOUNTAIN)], ai1: [P("x1", SWAMP, "ai1"), P("x2", SWAMP, "ai1"), P("x3", SWAMP, "ai1"), P("xb", BEARS, "ai1")], ai2: [P("y1", BEARS, "ai2")], ai3: [P("z1", BEARS, "ai3")] },
      hands: { user: [H("u-bolt", BOLT), H("u-giant", GIANT), H("u-bears", BEARS)], ai1: [H("pc", PLAGUECRAFTER)] } });
    const { offered, s: paused } = castAndResolveTrigger(s0, "ai1", "pc");
    let r = advanceUntilDecision({ id: "s", status: "active", difficulty: "beginner", state: paused, decisionLog: [] });
    const atDecision = { kind: r.decision.kind, controller: r.session.state.pendingChoice?.controller, candidates: r.session.state.pendingChoice?.candidates.map((c) => c.id).sort() };
    r = applyDiscardChoice(r.session, { cardId: "u-giant" });
    const s = r.session.state;
    const row = { offered, atDecision, unable: s.couldNotSacrificeThisWay, userGy: gy(s, "user"), userHand: handIds(s, "user"), userBf: ids(s, "user"), ai1Gy: gy(s, "ai1").length, ai2: ids(s, "ai2"), ai3: ids(s, "ai3") };
    console.log("  WITNESS plaguecrafterHumanDiscard", JSON.stringify(row));
    expect(row).toEqual({ offered: 1, atDecision: { kind: "discard", controller: "user", candidates: ["u-bears", "u-bolt", "u-giant"] }, unable: ["user"],
      userGy: ["Hill Giant"], userHand: ["u-bears", "u-bolt"], userBf: ["um"], ai1Gy: 1, ai2: [], ai3: [] });
  });

  it("⭐ layer-aware: an animated Mutavault is a creature its controller may give up; an unanimated land never is, nor Westvale Abbey, a land with a creature back face", () => {
    const s0 = pod({
      bf: { user: [P("mv", MUTAVAULT), P("abbey", ABBEY), P("usw", SWAMP)], ai1: [P("xb", BEARS, "ai1")], ai2: [P("lili", LILIANA, "ai2", { counters: { loyalty: 3 } })], ai3: [P("zmv", MUTAVAULT, "ai3")] },
      hands: { user: [H("pc", PLAGUECRAFTER)], ai3: [H("a3-h", BOLT)] } });
    const animated = animate(s0, "user", "mv");
    const { s: paused } = castAndResolveTrigger(withPool(animated, "user", { B: 1, C: 2 }), "user", "pc");
    const candidates = paused.pendingChoice?.candidates.map((c) => c.name).sort();
    const s = settleSac(paused, "mv");
    const row = { mutavaultIsCreature: permanentHasCardType(animated, "mv", "Creature"), candidates, unable: s.couldNotSacrificeThisWay, userBf: ids(s, "user"), userGy: gy(s, "user"),
      ai1Gy: gy(s, "ai1"), ai2Gy: gy(s, "ai2"), ai3: { bf: ids(s, "ai3"), gy: gy(s, "ai3") } };
    console.log("  WITNESS plaguecrafterAnimatedLand", JSON.stringify(row));
    expect(row).toEqual({ mutavaultIsCreature: true, candidates: ["Mutavault", "Plaguecrafter"], unable: ["ai3"],
      userBf: ["abbey", expect.stringMatching(/^perm-/), "usw"], userGy: ["Mutavault"], ai1Gy: ["Grizzly Bears"], ai2Gy: ["Liliana of the Veil"], ai3: { bf: ["zmv"], gy: ["Lightning Bolt"] } });
  });

  it("⭐ a sacrificed planeswalker dies (CR 700.4): Cruel Celebrant drains once for the Liliana its controller gave up", () => {
    const s0 = pod({ pool: { B: 1, C: 2 },
      bf: { user: [P("celebrant", CELEBRANT), P("lili", LILIANA, "user", { counters: { loyalty: 3 } })], ai1: [P("xb", BEARS, "ai1")], ai2: [P("yb", BEARS, "ai2")], ai3: [P("zb", BEARS, "ai3")] },
      hands: { user: [H("pc", PLAGUECRAFTER)] } });
    const { s: paused } = castAndResolveTrigger(s0, "user", "pc");
    const s = settleSac(paused, "lili");
    const celebrant = s.stack.filter((o) => o.source?.name === "Cruel Celebrant");
    const resolved = celebrant.length ? resolveTopOfStack(s) : s;
    const row = { candidates: paused.pendingChoice?.candidates.map((c) => c.name).sort(), userGy: gy(s, "user"), celebrantTriggers: celebrant.length,
      life: SEATS.map((pid) => resolved.players[pid].life) };
    console.log("  WITNESS plaguecrafterWalkerDies", JSON.stringify(row));
    expect(row).toEqual({ candidates: ["Cruel Celebrant", "Liliana of the Veil", "Plaguecrafter"], userGy: ["Liliana of the Veil"], celebrantTriggers: 1, life: [41, 39, 39, 39] });
  });

  it("SYNTHETIC SHAPE (the one-dispatch guard): a permanent that is both a creature and a planeswalker dies ONCE — Cruel Celebrant drains once, not twice", () => {
    // No printed card is a creature and a planeswalker on its front face; the shape arises by layers (an animated Gideon). This
    // invented object stands in for it, to pin that the creature dispatch alone carries its death (applyDestroyEffect's precedence).
    const HYBRID = { name: "Synthetic Walker Beast", type: "Legendary Planeswalker Creature — Beast", mana: "{2}{B}", cmc: 3, power: "2", toughness: "2", keywords: [], colors: ["B"], oracle: "" };
    const s0 = pod({ pool: { B: 1, C: 2 },
      bf: { user: [P("celebrant", CELEBRANT), P("hybrid", HYBRID, "user", { counters: { loyalty: 3 } })], ai1: [P("xb", BEARS, "ai1")], ai2: [P("yb", BEARS, "ai2")], ai3: [P("zb", BEARS, "ai3")] },
      hands: { user: [H("pc", PLAGUECRAFTER)] } });
    const { s: paused } = castAndResolveTrigger(s0, "user", "pc");
    const s = settleSac(paused, "hybrid");
    const row = { userGy: gy(s, "user"), celebrantTriggers: s.stack.filter((o) => o.source?.name === "Cruel Celebrant").length };
    expect(row).toEqual({ userGy: ["Synthetic Walker Beast"], celebrantTriggers: 1 });
  });
});

describe("the cards the same edict completes, and the one it must not touch", () => {
  it("⭐ Demon's Disciple: the same edict — and with no discard clause, a player with nothing to sacrifice keeps their hand", () => {
    const s0 = pod({ pool: { B: 1, C: 2 }, bf: { user: [P("ub", BEARS)], ai2: [P("lili", LILIANA, "ai2", { counters: { loyalty: 3 } })], ai3: [P("zb", BEARS, "ai3"), P("zg", GIANT, "ai3")] },
      hands: { user: [H("dd", DISCIPLE)], ai1: [H("a1-bolt", BOLT), H("a1-giant", GIANT)] } });
    const { offered, triggered, s: paused } = castAndResolveTrigger(s0, "user", "dd");
    const ddId = permOf(paused, "user", "Demon's Disciple").id;
    const s = autoSettle(settleSac(paused, ddId));
    const row = { offered, triggered, unable: s.couldNotSacrificeThisWay ?? null, user: ids(s, "user"), userGy: gy(s, "user"), ai1Hand: handIds(s, "ai1"), ai2Gy: gy(s, "ai2"), ai3: ids(s, "ai3"), stack: s.stack.length };
    console.log("  WITNESS demonsDisciple", JSON.stringify(row));
    expect(row).toEqual({ offered: 1, triggered: ["Demon's Disciple"], unable: null, user: ["ub"], userGy: ["Demon's Disciple"], ai1Hand: ["a1-bolt", "a1-giant"],
      ai2Gy: ["Liliana of the Veil"], ai3: ["zg"], stack: 0 });
  });

  it("Barter in Blood keeps its creature pool: a planeswalker is never one of the two, nor Westvale Abbey (a land with a creature back face)", () => {
    const s0 = pod({ pool: { B: 2, C: 2 }, bf: { user: [P("u1", BEARS), P("u2", BEARS), P("u3", ELVES)],
      ai1: [P("lili", LILIANA, "ai1", { counters: { loyalty: 3 } }), P("xb", BEARS, "ai1"), P("abbey", ABBEY, "ai1")] },
      hands: { user: [H("bb", BARTER)] } });
    const s = autoSettle(resolveTopOfStack(dispatchAction(s0, castsOf(s0, "user", "bb")[0])));
    expect({ ai1: ids(s, "ai1"), user: ids(s, "user").length }).toEqual({ ai1: ["abbey", "lili"], user: 1 });
  });
});

describe("⭐ Ruinous Ultimatum — destroy all nonland permanents your opponents control", () => {
  it("⭐ every opponent's nonland permanent goes; every land stays (an animated Mutavault, Arixmethes asleep, Westvale Abbey); indestructible and regeneration hold; the caster's own board is untouched", () => {
    // ai2's turn: ai2 animates its Mutavault, then the user casts Ruinous Ultimatum through Vedalken Orrery. Control decides, not
    // ownership: the user's Hill Giant that ai1 controls goes (to the user's graveyard); ai3's Bears that the user controls stays.
    const s0 = pod({ active: "ai2", pool: { R: 2, W: 3, B: 2 },
      bf: { user: [P("orrery", ORRERY), P("ub", BEARS), P("usol", SOL_RING), P("ulanding", LANDING), P("uplains", PLAINS), P("artist", BLOOD_ARTIST), P("borrowed", BEARS, "user", { owner: "ai3" })],
        ai1: [P("ab", BEARS, "ai1"), P("asol", SOL_RING, "ai1"), P("alili", LILIANA, "ai1", { counters: { loyalty: 3 } }), P("alanding", LANDING, "ai1"), P("aarix", ARIXMETHES, "ai1"), P("aswamp", SWAMP, "ai1"), P("aabbey", ABBEY, "ai1"), P("stolen", GIANT, "ai1", { owner: "user" })],
        ai2: [P("bmyr", MYR, "ai2"), P("bdrudge", DRUDGE, "ai2", { regenShields: 1 }), P("bb", BEARS, "ai2"), P("bmv", MUTAVAULT, "ai2")],
        ai3: [P("carix", ARIXMETHES, "ai3", { tapped: true, counters: { slumber: 5 } }), P("cstone", MIND_STONE, "ai3"), P("cgiant", GIANT, "ai3"), P("cisland", ISLAND, "ai3")] },
      hands: { user: [H("ru", RUINOUS)] } });
    const s1 = animate(s0, "ai2", "bmv");
    const offer = castsOf(s1, "user", "ru");
    const s = resolveTopOfStack(dispatchAction({ ...s1, priorityHolder: "user" }, offer[0]));
    const row = { offered: offer.length, targets: offer[0].targets?.length ?? 0, mutavaultIsCreature: permanentHasCardType(s1, "bmv", "Creature"), arixAsleepIsLand: permanentHasCardType(s1, "carix", "Land"),
      bf: Object.fromEntries(SEATS.map((pid) => [pid, ids(s, pid)])), ai1Gy: gy(s, "ai1"), userGy: gy(s, "user"), drudgeTapped: !!s.players.ai2.battlefield.find((p) => p.id === "bdrudge")?.tapped,
      artistTriggers: s.stack.filter((o) => o.source?.name === "Blood Artist").length, errors: errors(s).length };
    console.log("  WITNESS ruinousUltimatum", JSON.stringify(row));
    expect(row).toEqual({ offered: 1, targets: 0, mutavaultIsCreature: true, arixAsleepIsLand: true,
      bf: { user: ["artist", "borrowed", "orrery", "ub", "ulanding", "uplains", "usol"], ai1: ["aabbey", "aswamp"], ai2: ["bdrudge", "bmv", "bmyr"], ai3: ["carix", "cisland"] },
      ai1Gy: ["Arixmethes, Slumbering Isle", "Grizzly Bears", "Legion's Landing // Adanto, the First Fort", "Liliana of the Veil", "Sol Ring"],
      userGy: ["Hill Giant", "Ruinous Ultimatum"], drudgeTapped: true, artistTriggers: 5, errors: 0 });
  });
});

describe("⭐ Dramatic Reversal — untap all nonland permanents you control", () => {
  it("⭐ the caster's tapped artifacts, creatures and Legion's Landing untap — one it controls but doesn't own too; their lands stay tapped (an animated Mutavault, Westvale Abbey, Arixmethes asleep, the Islands that paid); a stun counter keeps its creature tapped (CR 122.1d); the opponents' permanents stay tapped, one the caster owns included", () => {
    const tapped = { tapped: true };
    const s0 = pod({ pool: { C: 1 },
      bf: { user: [P("i1", ISLAND), P("i2", ISLAND), P("i3", ISLAND, "user", tapped), P("sol", SOL_RING, "user", tapped), P("stone", MIND_STONE, "user", tapped), P("elves", ELVES, "user", tapped),
        P("stunned", BEARS, "user", { tapped: true, counters: { stun: 1 } }), P("landing", LANDING, "user", tapped), P("mv", MUTAVAULT, "user", tapped), P("abbey", ABBEY, "user", tapped),
        P("arix", ARIXMETHES, "user", { tapped: true, counters: { slumber: 5 } }), P("borrowed", MIND_STONE, "user", { tapped: true, owner: "ai1" })],
        ai1: [P("asol", SOL_RING, "ai1", tapped), P("ab", BEARS, "ai1", tapped), P("aisland", ISLAND, "ai1", tapped), P("lent", ELVES, "ai1", { tapped: true, owner: "user" })] },
      hands: { user: [H("dr", REVERSAL)] } });
    const s1 = animate(s0, "user", "mv");
    const offer = castsOf(s1, "user", "dr");
    const cast = dispatchAction(s1, offer[0]);
    const paidWith = tappedIds(cast, "user").filter((id) => !tappedIds(s1, "user").includes(id));
    // Arixmethes' own "whenever you cast a spell, you may remove a slumber counter" goes on the stack above the spell; declined, it stays asleep.
    const stackOnCast = stackNames(cast);
    const s = resolveTopOfStack(resolveOptionalChoice(resolveTopOfStack(cast), false));
    const row = { offered: offer.length, mutavaultIsCreature: permanentHasCardType(s1, "mv", "Creature"), paidWith, stackOnCast, userTapped: tappedIds(s, "user"), stun: s.players.user.battlefield.find((p) => p.id === "stunned").counters.stun,
      ai1Tapped: tappedIds(s, "ai1"), reversalInGraveyard: gy(s, "user").includes("Dramatic Reversal"), errors: errors(s).length };
    console.log("  WITNESS dramaticReversal", JSON.stringify(row));
    expect(row).toEqual({ offered: 1, mutavaultIsCreature: true, paidWith: ["i1", "i2"], stackOnCast: ["Dramatic Reversal", "Arixmethes, Slumbering Isle"],
      userTapped: ["abbey", "arix", "i1", "i2", "i3", "mv", "stunned"], stun: 0, ai1Tapped: ["ab", "aisland", "asol", "lent"], reversalInGraveyard: true, errors: 0 });
  });
});

describe("the cards the same untap completes", () => {
  it("⭐ Paradox Engine: casting a spell untaps the controller's tapped nonland permanents — never a land", () => {
    const tapped = { tapped: true };
    const s0 = pod({ pool: { R: 1 }, bf: { user: [P("engine", PARADOX), P("sol", SOL_RING, "user", tapped), P("elves", ELVES, "user", tapped), P("i1", ISLAND, "user", tapped)], ai1: [P("asol", SOL_RING, "ai1", tapped)] },
      hands: { user: [H("bolt", BOLT)] } });
    const offer = castsOf(s0, "user", "bolt").find((a) => a.targets?.[0]?.id === "ai1");
    const cast = dispatchAction(s0, offer);
    const s = resolveTopOfStack(cast);
    const row = { stackOnCast: stackNames(cast), userTapped: tappedIds(s, "user"), ai1Tapped: tappedIds(s, "ai1"), stackAfter: stackNames(s) };
    console.log("  WITNESS paradoxEngine", JSON.stringify(row));
    expect(row).toEqual({ stackOnCast: ["Lightning Bolt", "Paradox Engine"], userTapped: ["i1"], ai1Tapped: ["asol"], stackAfter: ["Lightning Bolt"] });
  });

  it("⭐ Unstoppable Plan: at the beginning of its controller's end step, their tapped nonland permanents untap — never a land", () => {
    const tapped = { tapped: true };
    const s0 = pod({ phase: "postcombat-main", step: "main",
      bf: { user: [P("plan", UNSTOPPABLE), P("sol", SOL_RING, "user", tapped), P("elves", ELVES, "user", tapped), P("i1", ISLAND, "user", tapped)], ai1: [P("ab", BEARS, "ai1", tapped)] } });
    let s = flushTriggers(runStepActions(advanceStep(s0)), { chooseTargets: chooseTriggerTargets });
    const step = s.step;
    const triggered = stackNames(s);
    for (let i = 0; i < 4 && s.stack.length; i++) s = flushTriggers(resolveTopOfStack(s), { chooseTargets: chooseTriggerTargets });
    const row = { step, triggered, userTapped: tappedIds(s, "user"), ai1Tapped: tappedIds(s, "ai1") };
    console.log("  WITNESS unstoppablePlan", JSON.stringify(row));
    expect(row).toEqual({ step: "end", triggered: ["Unstoppable Plan"], userTapped: ["i1"], ai1Tapped: ["ab"] });
  });
});
