/**
 * REPRIEVE — the play-weighted program, #603 (EDHREC #603).
 *   "Return target spell to its owner's hand.
 *    Draw a card."
 *
 * THE PARSE: "return target spell to its owner's hand" → { op: "bounce-spell-or-permanent", targetType: "spell", notCounter:
 * true } — Hullbreaker Horror's stack half with no controller scope (any spell, the caster's own included), then the plain draw.
 * The pool is the stack's SPELLS only, copies included (CR 112.1a) — an ability is never a target (CR 113.9: abilities on the
 * stack aren't spells; the enumerator reads `kind: "spell"`). Returning a spell is not countering it (CR 701.6a), so a spell
 * that can't be countered is still a legal target, and the target spell's controller gets nothing back (no refund, none of
 * its effects).
 *
 * THE STACK-LEAVE PRIMITIVE (atoms/stack.counterSpellById — every counter, Remand, Memory Lapse, Venser and this bounce
 * take it), brought to the rules a bounce exercises:
 *  - The card goes to its OWNER's hand (CR 400.3): Ragavan's caster plays the opponent's card, and it goes home.
 *  - The WHOLE card moves: a split half (CR 709.4), a modal DFC face (CR 712.8a), an adventurer's face (CR 715.4) and a
 *    flashback cast's cost view rode the stack as projections; the card taken out of its zone is what leaves.
 *  - A COPY of a spell ceases to exist outside the stack (CR 704.5e, 707.10a) — returned, countered or exiled, it reaches no
 *    zone and enters no graveyard.
 *  - FLASHBACK (CR 702.34a): "exile this card instead of putting it anywhere else any time it would leave the stack" — the
 *    exile beats the hand (and Remand's hand, Memory Lapse's library).
 * And at the cast (actionDispatcher, beside the impulse stamps): CR 400.7 — an adventurer creature cast out of adventure exile
 * leaves that stay's permission behind, so neither a return to hand nor a death brings back a card castable from exile.
 *
 * THE ILLEGAL TARGET (CR 608.2b): with its one target gone Reprieve doesn't resolve — no draw. And the same rule for an
 * Adventure, which the arm also reaches (Take It Back): a fizzled Adventure never resolved, so CR 715.3d's exile doesn't
 * apply — it goes to its owner's graveyard and the creature is not castable from exile (resolvers.js EFFECT_PROGRAM). A copy of
 * an Adventure (CR 715.3c) is no card, so it goes on no adventure either (stack.spellCopyPayload).
 *
 * The arm completes two more cards, each witnessed here: Bilbo's Gambit (the gift is never promised — the engine's gift policy,
 * castModifiers.stripGiftPromise — so its base mode is the whole card) and Spellscorn Coven // Take It Back. Failure // Comply
 * stays parked on Comply; Unsubstantiate ("spell or creature") and Obscura Interceptor ("up to one target spell", reflexive)
 * stay parked on their own wording.
 *
 * Unmodeled, and accepted as a safe under-offer: CR 903.9b lets a commander's owner put it into the command zone instead of a
 * hand; the engine (every bounce, Venser and Remand included) leaves it in the hand, which is a legal outcome of that choice.
 *
 * Real oracle fixtures (bundled Scryfall, the 2026-10-01 data, generated by cardIndex.publicCard — never typed by hand).
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, createGameState, createPermanent } from "./gameState.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { chooseTriggerTargets, flushTriggers, resolveTopOfStack } from "./gameEngine.js";
import { resolveCombatDamage } from "./combatResolution.js";
import { autoPickDiscardCandidate, resolveDiscardChoice } from "./effects/runProgram.js";
import { classifyCard } from "./coverage.js";
import { parseEffectClause, parseEffectProgram, programConfidence } from "./effects/parser.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const REPRIEVE = {"name":"Reprieve","type":"Instant","mana":"{1}{W}","cmc":2,"keywords":[],"colors":["W"],"oracle":"Return target spell to its owner's hand.\nDraw a card."}; // native-spell
const BILBO = {"name":"Bilbo's Gambit","type":"Instant","mana":"{1}{W}","cmc":2,"keywords":["Gift","Treasure"],"colors":["W"],"oracle":"Gift a Treasure (You may promise an opponent a gift as you cast this spell. If you do, they create a Treasure token before its other effects. It's an artifact with \"{T}, Sacrifice this token: Add one mana of any color.\")\nReturn target spell to its owner's hand. If the gift was promised, players can't cast spells this turn."}; // native-spell
const COVEN = {"name":"Spellscorn Coven // Take It Back","type":"Creature — Faerie Warlock // Instant — Adventure","mana":"{3}{B} // {2}{U}","cmc":4,"power":"2","toughness":"3","keywords":["Flying"],"layout":"adventure","colors":["B"],"oracle":"Spellscorn Coven - Creature — Faerie Warlock {3}{B}\nFlying\nWhen this creature enters, each opponent discards a card.\n//\nTake It Back - Instant — Adventure {2}{U}\nReturn target spell to its owner's hand. (Then exile this card. You may cast the creature later from exile.)"}; // native-mixed
const FAILURE = {"name":"Failure // Comply","type":"Instant // Sorcery","mana":"{1}{U} // {W}","cmc":3,"keywords":["Aftermath"],"layout":"split","colors":["U","W"],"oracle":"Failure - Instant {1}{U}\nReturn target spell to its owner's hand.\n//\nComply - Sorcery {W}\nAftermath (Cast this spell only from your graveyard. Then exile it.)\nChoose a card name. Until your next turn, your opponents can't cast spells with the chosen name."}; // arbiter-spell
const UNSUBSTANTIATE = {"name":"Unsubstantiate","type":"Instant","mana":"{1}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Return target spell or creature to its owner's hand."}; // arbiter-spell
const OBSCURA = {"name":"Obscura Interceptor","type":"Creature — Octopus Wizard","mana":"{1}{W}{U}{B}","cmc":4,"power":"3","toughness":"1","keywords":["Lifelink","Flash","Connive"],"colors":["B","U","W"],"oracle":"Flash\nLifelink\nWhen this creature enters, it connives. When it connives this way, return up to one target spell to its owner's hand. (To have a creature connive, draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on that creature.)"}; // body-only
const DIVINATION = {"name":"Divination","type":"Sorcery","mana":"{2}{U}","cmc":3,"keywords":[],"colors":["U"],"oracle":"Draw two cards."}; // native-spell
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const VERDICT = {"name":"Supreme Verdict","type":"Sorcery","mana":"{1}{W}{W}{U}","cmc":4,"keywords":[],"colors":["U","W"],"oracle":"This spell can't be countered.\nDestroy all creatures."}; // native-spell
const COUNTERSPELL = {"name":"Counterspell","type":"Instant","mana":"{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Counter target spell."}; // native-spell
const REMAND = {"name":"Remand","type":"Instant","mana":"{1}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Counter target spell. If that spell is countered this way, put it into its owner's hand instead of into that player's graveyard.\nDraw a card."}; // native-spell
const REVERBERATE = {"name":"Reverberate","type":"Instant","mana":"{R}{R}","cmc":2,"keywords":[],"colors":["R"],"oracle":"Copy target instant or sorcery spell. You may choose new targets for the copy."}; // native-spell
const BOLT = {"name":"Lightning Bolt","type":"Instant","mana":"{R}","cmc":1,"keywords":[],"colors":["R"],"oracle":"Lightning Bolt deals 3 damage to any target."}; // native-spell
const THINK_TWICE = {"name":"Think Twice","type":"Instant","mana":"{1}{U}","cmc":2,"keywords":["Flashback"],"colors":["U"],"oracle":"Draw a card.\nFlashback {2}{U} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"}; // native-spell
const FIRE_ICE = {"name":"Fire // Ice","type":"Instant // Instant","mana":"{1}{R} // {1}{U}","cmc":4,"keywords":[],"layout":"split","colors":["R","U"],"oracle":"Fire - Instant {1}{R}\nFire deals 2 damage divided as you choose among one or two targets.\n//\nIce - Instant {1}{U}\nTap target permanent.\nDraw a card."}; // native-spell
const JWARI = {"name":"Jwari Disruption // Jwari Ruins","type":"Instant // Land","mana":"{1}{U}","cmc":2,"keywords":[],"layout":"modal_dfc","colors":[],"oracle":"Jwari Disruption - Instant {1}{U}\nCounter target spell unless its controller pays {1}.\n//\nJwari Ruins - Land \nThis land enters tapped.\n{T}: Add {U}."}; // native-spell
const KAZANDU = {"name":"Kazandu Mammoth // Kazandu Valley","type":"Creature — Elephant // Land","mana":"{1}{G}{G}","cmc":3,"power":"3","toughness":"3","keywords":["Landfall"],"layout":"modal_dfc","colors":[],"oracle":"Kazandu Mammoth - Creature — Elephant {1}{G}{G}\nLandfall — Whenever a land you control enters, this creature gets +2/+2 until end of turn.\n//\nKazandu Valley - Land \nThis land enters tapped.\n{T}: Add {G}."}; // native-trigger
const BORROWER = {"name":"Brazen Borrower // Petty Theft","type":"Creature — Faerie Rogue // Instant — Adventure","mana":"{1}{U}{U} // {1}{U}","cmc":3,"power":"3","toughness":"1","keywords":["Flying","Flash"],"layout":"adventure","colors":["U"],"oracle":"Brazen Borrower - Creature — Faerie Rogue {1}{U}{U}\nFlash\nFlying\nThis creature can block only creatures with flying.\n//\nPetty Theft - Instant — Adventure {1}{U}\nReturn target nonland permanent an opponent controls to its owner's hand."}; // native-mixed
const PYROMANCER = {"name":"Prodigal Pyromancer","type":"Creature — Human Wizard","mana":"{2}{R}","cmc":3,"power":"1","toughness":"1","keywords":[],"colors":["R"],"oracle":"{T}: This creature deals 1 damage to any target."}; // native-activated
const RAGAVAN = {"name":"Ragavan, Nimble Pilferer","type":"Legendary Creature — Monkey Pirate","mana":"{R}","cmc":1,"power":"2","toughness":"1","keywords":["Treasure","Dash"],"colors":["R"],"oracle":"Whenever Ragavan deals combat damage to a player, create a Treasure token and exile the top card of that player's library. Until end of turn, you may cast that card.\nDash {1}{R} (You may cast this spell for its dash cost. If you do, it gains haste, and it's returned from the battlefield to its owner's hand at the beginning of the next end step.)"}; // native-trigger
const ISLAND = {"name":"Island","type":"Basic Land — Island","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {U}.)"}; // land

// ─── harness ──────────────────────────────────────────────────────────────────
const H = (id, card) => ({ ...card, id });
const P = (id, card, controller) => createPermanent({ id, card: { ...card, id: `c-${id}` }, controller, summoningSick: false });
/** A two-seat table in `active`'s precombat main; each seat's hand / graveyard / battlefield / pool given, three Bears in
 *  each library (so a draw is visible). */
function board({ active = "user", user = {}, ai = {} } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  const lib = (who) => [1, 2, 3].map((i) => ({ ...BEARS, id: `${who}-lib${i}` }));
  const seat = (who, o) => ({ ...g.players[who], battlefield: o.battlefield || [], hand: o.hand || [], graveyard: o.graveyard || [], exile: o.exile || [],
    manaPool: { ...g.players[who].manaPool, ...(o.pool || {}) }, library: o.library || lib(who) });
  return { ...g, turn: 5, activePlayer: active, priorityHolder: active, phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: { ...g.players, user: seat("user", user), ai: seat("ai", ai) } };
}
const castsOf = (s, who, cardId) => legalActionsForPlayer({ ...s, priorityHolder: who }, who).filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
/** Dispatch `who`'s one offered cast of `cardId` that `pick` accepts (the cast must be offered — the test fails otherwise). */
function cast(s, who, cardId, pick = () => true) {
  const a = castsOf(s, who, cardId).find(pick);
  expect(a, `${who} is offered a cast of ${cardId}`).toBeTruthy();
  return dispatchAction({ ...s, priorityHolder: who }, a);
}
const aimedAt = (name) => (a) => (a.targets || []).some((t) => t.name === name);
const names = (cards) => cards.map((c) => c.name);
const zonesOf = (s, who) => ({ hand: names(s.players[who].hand), graveyard: names(s.players[who].graveyard), exile: names(s.players[who].exile) });
const stackNames = (s) => s.stack.map((o) => o.source?.name);
const errors = (s) => (s.log || []).filter((e) => e.kind === "stack-resolve-error");
/** Every card object named `name` anywhere in the game: each seat's zones, the battlefield's cards, the stack's sources. */
function everywhere(s, name) {
  const out = [];
  for (const [pid, p] of Object.entries(s.players)) {
    for (const z of ["hand", "graveyard", "exile", "library"]) for (const c of p[z] || []) if (c.name === name) out.push(`${pid}.${z}`);
    for (const perm of p.battlefield || []) if (perm.card?.name === name) out.push(`${pid}.battlefield`);
  }
  for (const o of s.stack) if (o.source?.name === name) out.push(o.isCopy ? "stack(copy)" : "stack");
  return out.sort();
}
/** The opponent (ai) casts `spell` (card id "sp" — the offered cast `pick` accepts) in their own main phase; the user holds
 *  Reprieve and {W}{1}. */
function theirSpellOnStack(spell, { pick = () => true, userExtra = {}, aiExtra = {} } = {}) {
  const s0 = board({ active: "ai",
    user: { hand: [H("rep", REPRIEVE)], pool: { W: 1, C: 1 }, ...userExtra },
    ai: { hand: [H("sp", spell)], pool: { U: 6, W: 2, R: 2, G: 3, C: 2 }, ...aiExtra } });
  return cast(s0, "ai", "sp", pick);
}

describe("the card and its parse", () => {
  it("classify: Reprieve native-spell, and the two cards the arm completes; the near misses stay parked", () => {
    const row = { reprieve: classifyCard(REPRIEVE), bilbo: classifyCard(BILBO), coven: classifyCard(COVEN),
      failure: classifyCard(FAILURE), unsubstantiate: classifyCard(UNSUBSTANTIATE), obscura: classifyCard(OBSCURA) };
    console.log("  WITNESS classify", JSON.stringify(row)); // vitest 4 needs --disable-console-intercept
    expect(row).toEqual({ reprieve: "native-spell", bilbo: "native-spell", coven: "native-mixed",
      failure: "arbiter-spell", unsubstantiate: "arbiter-spell", obscura: "body-only" });
  });

  it("two atoms: the spell-only bounce (no controller scope, not a counter), then the caster's draw", () => {
    const p = parseEffectProgram(REPRIEVE);
    expect({ confidence: programConfidence(p), atoms: p.atoms }).toEqual({ confidence: "high", atoms: [
      { op: "bounce-spell-or-permanent", targetType: "spell", notCounter: true },
      { op: "draw", amount: 1, targetType: null },
    ] });
  });

  it("the anchor holds: another noun, an \"up to\" count, a narrower spell stay unparsed", () => {
    const conf = (clause) => programConfidence(parseEffectClause(clause, "Instant"));
    expect({
      spellOrCreature: conf("Return target spell or creature to its owner's hand."),
      upToOne: conf("Return up to one target spell to its owner's hand."),
      creatureSpell: conf("Return target creature spell to its owner's hand."),
    }).toEqual({ spellOrCreature: "low", upToOne: "low", creatureSpell: "low" });
  });
});

describe("⭐ in play — the target spell goes to its owner's hand, the caster draws", () => {
  it("⭐ an opponent's sorcery returns to their hand — no refund, none of its effects — and Reprieve's caster draws (WITNESS)", () => {
    const s1 = theirSpellOnStack(DIVINATION);
    const offer = castsOf(s1, "user", "rep");
    const s2 = cast(s1, "user", "rep");
    const s3 = resolveTopOfStack(s2);
    const row = { offered: offer.map((a) => a.targets.map((t) => t.name)), stackBefore: stackNames(s2), stackAfter: stackNames(s3),
      ai: zonesOf(s3, "ai"), aiLibrary: s3.players.ai.library.length, aiManaRefunded: JSON.stringify(s3.players.ai.manaPool) !== JSON.stringify(s1.players.ai.manaPool),
      user: zonesOf(s3, "user"), userLibrary: s3.players.user.library.length, errors: errors(s3).length };
    console.log("  WITNESS reprieve", JSON.stringify(row));
    expect(row).toEqual({ offered: [["Divination"]], stackBefore: ["Divination", "Reprieve"], stackAfter: [],
      ai: { hand: ["Divination"], graveyard: [], exile: [] }, aiLibrary: 3, aiManaRefunded: false,
      user: { hand: ["Grizzly Bears"], graveyard: ["Reprieve"], exile: [] }, userLibrary: 2, errors: 0 });
  });

  it("any spell is a legal target — the caster's own comes back to their own hand", () => {
    const s0 = board({ user: { hand: [H("div", DIVINATION), H("rep", REPRIEVE)], pool: { U: 3, W: 3 } } });
    const s1 = cast(s0, "user", "div");
    const s3 = resolveTopOfStack(cast(s1, "user", "rep", aimedAt("Divination")));
    expect({ stack: stackNames(s3), user: zonesOf(s3, "user") })
      .toEqual({ stack: [], user: { hand: ["Divination", "Grizzly Bears"], graveyard: ["Reprieve"], exile: [] } });
  });

  it("⭐ a spell that can't be countered is still returned (CR 701.6a) — Counterspell has no target, Reprieve has one", () => {
    const s1 = theirSpellOnStack(VERDICT, { userExtra: { hand: [H("rep", REPRIEVE), H("cs", COUNTERSPELL)], pool: { W: 1, C: 1, U: 2 }, battlefield: [P("ub", BEARS, "user")] } });
    const counterOffers = castsOf(s1, "user", "cs").length;
    const s3 = resolveTopOfStack(cast(s1, "user", "rep", aimedAt("Supreme Verdict")));
    const row = { counterOffers, stack: stackNames(s3), aiHand: zonesOf(s3, "ai").hand, bearsAlive: s3.players.user.battlefield.length };
    console.log("  WITNESS uncounterable", JSON.stringify(row));
    expect(row).toEqual({ counterOffers: 0, stack: [], aiHand: ["Supreme Verdict"], bearsAlive: 1 });
  });

  it("⭐ the OWNER's hand (CR 400.3): the card Ragavan's controller cast out of the opponent's exile goes home to the opponent", () => {
    const g = board({ user: { battlefield: [P("rag", RAGAVAN, "user")], hand: [H("rep", REPRIEVE)] }, ai: { library: [H("adiv", DIVINATION), H("ab", BEARS)] } });
    let s = flushTriggers(resolveCombatDamage({ ...g, phase: "combat", step: "combat-damage", combat: { attackers: [{ permanentId: "rag", attackingPlayer: "user", defender: "ai" }], blockers: [] } }), { chooseTargets: chooseTriggerTargets });
    while (s.stack.length) s = resolveTopOfStack(s);
    s = { ...s, phase: "postcombat-main", step: "main", priorityHolder: "user", combat: null, players: { ...s.players, user: { ...s.players.user, manaPool: { ...s.players.user.manaPool, U: 3, W: 1, C: 1 } } } };
    const s1 = cast(s, "user", "adiv");
    const { owner, controller } = s1.stack.find((o) => o.source?.name === "Divination");
    const s3 = resolveTopOfStack(cast(s1, "user", "rep", aimedAt("Divination")));
    const row = { owner, controller, ai: zonesOf(s3, "ai"), userHand: zonesOf(s3, "user").hand };
    console.log("  WITNESS owner", JSON.stringify(row));
    expect(row).toEqual({ owner: "ai", controller: "user", ai: { hand: ["Divination"], graveyard: [], exile: [] }, userHand: ["Grizzly Bears"] });
  });

  it("⭐ a COPY of a spell ceases to exist (CR 704.5e, 707.10a): the Reverberate copy reaches no hand; the original stays", () => {
    const s0 = board({ active: "ai", user: { hand: [H("rep", REPRIEVE)], pool: { W: 1, C: 1 } }, ai: { hand: [H("bolt", BOLT), H("rev", REVERBERATE)], pool: { R: 3 } } });
    const s1 = cast(s0, "ai", "bolt", (a) => a.targets?.[0]?.id === "user");
    const s2 = resolveTopOfStack(cast(s1, "ai", "rev"));
    const copyId = s2.stack.find((o) => o.isCopy).id;
    const s3 = resolveTopOfStack(cast(s2, "user", "rep", (a) => a.targets[0].id === copyId));
    const row = { before: everywhere(s2, "Lightning Bolt"), after: everywhere(s3, "Lightning Bolt"), aiHand: zonesOf(s3, "ai").hand,
      userHand: zonesOf(s3, "user").hand, userLife: s3.players.user.life };
    console.log("  WITNESS copy", JSON.stringify(row));
    expect(row).toEqual({ before: ["stack", "stack(copy)"], after: ["stack"], aiHand: [], userHand: ["Grizzly Bears"], userLife: 40 });
  });

  it("⭐ a FLASHBACK spell is exiled instead (CR 702.34a) — never the hand, never cast again", () => {
    const s0 = board({ active: "ai", user: { hand: [H("rep", REPRIEVE)], pool: { W: 1, C: 1 } }, ai: { graveyard: [H("tt", THINK_TWICE)], pool: { U: 6 } } });
    const s1 = cast(s0, "ai", "tt", (a) => a.flashbackCast === true);
    const s3 = resolveTopOfStack(cast(s1, "user", "rep", aimedAt("Think Twice")));
    const row = { ai: zonesOf(s3, "ai"), exiledMana: s3.players.ai.exile[0]?.mana, castable: castsOf(s3, "ai", "tt").length, userHand: zonesOf(s3, "user").hand };
    console.log("  WITNESS flashback", JSON.stringify(row));
    expect(row).toEqual({ ai: { hand: [], graveyard: [], exile: ["Think Twice"] }, exiledMana: "{1}{U}", castable: 0, userHand: ["Grizzly Bears"] });
  });

  it("⭐ the WHOLE card (CR 709.4): Fire returns as Fire // Ice — and either half can be cast again", () => {
    const s1 = theirSpellOnStack(FIRE_ICE, { pick: (a) => a.faceCard?.name === "Fire", aiExtra: { battlefield: [P("isl", ISLAND, "ai")] } });
    const s3 = resolveTopOfStack(cast(s1, "user", "rep", aimedAt("Fire")));
    const back = s3.players.ai.hand[0];
    const faces = castsOf(s3, "ai", "sp").map((a) => a.faceCard?.name).sort();
    expect({ name: back.name, type: back.type, oracle: back.oracle, faces }).toEqual({ name: "Fire // Ice", type: "Instant // Instant", oracle: FIRE_ICE.oracle, faces: ["Fire", "Ice"] });
  });

  it("the whole modal DFC (CR 712.8a): Jwari Disruption returns as the two-face card — its land face is a land drop again", () => {
    const s0 = board({ user: { hand: [H("bears", BEARS), H("rep", REPRIEVE)], pool: { G: 2, W: 2 } }, ai: { hand: [H("jw", JWARI)], pool: { U: 2 } } });
    const s1 = cast(s0, "user", "bears");
    const s2 = cast(s1, "ai", "jw", aimedAt("Grizzly Bears"));
    const s3 = resolveTopOfStack(cast(s2, "user", "rep", aimedAt("Jwari Disruption")));
    const back = s3.players.ai.hand[0];
    const later = { ...s3, stack: [], activePlayer: "ai", priorityHolder: "ai", turn: 6 };
    const landDrops = legalActionsForPlayer(later, "ai").filter((a) => a.kind === "play-land" && a.cardId === "jw").map((a) => a.name);
    expect({ stack: stackNames(s3), name: back.name, type: back.type, landDrops }).toEqual({ stack: ["Grizzly Bears"], name: "Jwari Disruption // Jwari Ruins", type: "Instant // Land", landDrops: ["Jwari Ruins"] });
  });

  it("the whole modal DFC from a PERMANENT front: Kazandu Mammoth returns as Kazandu Mammoth // Kazandu Valley", () => {
    const s1 = theirSpellOnStack(KAZANDU);
    const s3 = resolveTopOfStack(cast(s1, "user", "rep", aimedAt("Kazandu Mammoth")));
    const back = s3.players.ai.hand[0];
    expect({ battlefield: s3.players.ai.battlefield.length, name: back.name, type: back.type, oracle: back.oracle })
      .toEqual({ battlefield: 0, name: "Kazandu Mammoth // Kazandu Valley", type: "Creature — Elephant // Land", oracle: KAZANDU.oracle });
  });

  it("an Adventure on the stack returns as the whole card (CR 715.4) — to the hand, not adventure exile (that is only as it resolves)", () => {
    const s1 = theirSpellOnStack(BORROWER, { pick: (a) => a.adventureCast === true, userExtra: { battlefield: [P("ub", BEARS, "user")] } });
    expect(stackNames(s1)).toEqual(["Petty Theft"]);
    const s3 = resolveTopOfStack(cast(s1, "user", "rep", aimedAt("Petty Theft")));
    const faces = castsOf(s3, "ai", "sp").map((a) => a.faceCard?.name).sort();
    expect({ ai: zonesOf(s3, "ai"), faces, bears: s3.players.user.battlefield.length })
      .toEqual({ ai: { hand: ["Brazen Borrower // Petty Theft"], graveyard: [], exile: [] }, faces: ["Brazen Borrower", "Petty Theft"], bears: 1 });
  });

  it("⭐ CR 400.7: the adventurer cast out of adventure exile comes back without that exile's permission", () => {
    const s0 = board({ active: "ai", user: { hand: [H("rep", REPRIEVE)], pool: { W: 1, C: 1 }, battlefield: [P("ub", BEARS, "user")] }, ai: { hand: [H("bb", BORROWER)], pool: { U: 6 } } });
    const t1 = resolveTopOfStack(cast(s0, "ai", "bb", (a) => a.adventureCast === true)); // Petty Theft resolves; the card goes on its adventure
    const t2 = cast(t1, "ai", "bb", (a) => a.fromZone === "exile");                     // Brazen Borrower, cast from exile (flash)
    const t3 = resolveTopOfStack(cast(t2, "user", "rep", aimedAt("Brazen Borrower")));
    const back = t3.players.ai.hand[0];
    const row = { onAdventureBefore: t1.players.ai.exile[0]?._onAdventure === true, stackBefore: stackNames(t2), ai: zonesOf(t3, "ai"),
      permissionKept: Object.prototype.hasOwnProperty.call(back, "_onAdventure") };
    console.log("  WITNESS adventurer", JSON.stringify(row));
    expect(row).toEqual({ onAdventureBefore: true, stackBefore: ["Brazen Borrower"], ai: { hand: ["Brazen Borrower // Petty Theft"], graveyard: [], exile: [] }, permissionKept: false });
  });

  it("CR 400.7, the same permission off the battlefield: the adventurer cast from adventure exile dies into the graveyard without it", () => {
    const s0 = board({ active: "ai", user: { hand: [H("bolt", BOLT)], pool: { R: 1 }, battlefield: [P("ub", BEARS, "user")] }, ai: { hand: [H("bb", BORROWER)], pool: { U: 6 } } });
    const t1 = resolveTopOfStack(cast(s0, "ai", "bb", (a) => a.adventureCast === true));
    const t2 = resolveTopOfStack(cast(t1, "ai", "bb", (a) => a.fromZone === "exile"));
    const borrowerId = t2.players.ai.battlefield.find((p) => p.card?.name === "Brazen Borrower").id;
    const t3 = resolveTopOfStack(cast(t2, "user", "bolt", (a) => a.targets?.[0]?.id === borrowerId));
    const dead = t3.players.ai.graveyard[0];
    expect({ graveyard: zonesOf(t3, "ai").graveyard, permissionKept: Object.prototype.hasOwnProperty.call(dead, "_onAdventure") })
      .toEqual({ graveyard: ["Brazen Borrower // Petty Theft"], permissionKept: false });
  });

  it("⭐ an ability is never a target (CR 113.9): an activated or a triggered ability alone — no cast; beside a spell — only the spell", () => {
    const s0 = board({ active: "ai", user: { hand: [H("rep", REPRIEVE)], pool: { W: 1, C: 1 } },
      ai: { hand: [H("bolt", BOLT), H("cov", COVEN)], pool: { R: 1, B: 1, C: 3 }, battlefield: [P("pyro", PYROMANCER, "ai")] } });
    const ping = legalActionsForPlayer(s0, "ai").find((a) => a.kind === "activate-ability" && a.permanentId === "pyro" && a.targets?.[0]?.id === "user");
    const a1 = dispatchAction(s0, ping);
    const withBolt = cast(a1, "ai", "bolt", (a) => a.targets?.[0]?.id === "user");
    const coven = resolveTopOfStack(cast(s0, "ai", "cov", (a) => a.faceCard?.name === "Spellscorn Coven")); // its enters trigger goes on the stack
    const row = {
      activated: { stack: a1.stack.map((o) => o.kind), offers: castsOf(a1, "user", "rep").length },
      triggered: { stack: coven.stack.map((o) => o.kind), offers: castsOf(coven, "user", "rep").length },
      beside: { stack: withBolt.stack.map((o) => o.kind), targets: castsOf(withBolt, "user", "rep").map((a) => a.targets.map((t) => t.name)) },
    };
    console.log("  WITNESS abilities", JSON.stringify(row));
    expect(row).toEqual({
      activated: { stack: ["activated-ability"], offers: 0 },
      triggered: { stack: ["triggered-ability"], offers: 0 },
      beside: { stack: ["activated-ability", "spell"], targets: [["Lightning Bolt"]] },
    });
  });

  it("no spell on the stack: Reprieve is not castable (CR 601.2, 601.2c — a target it can't choose makes the cast illegal)", () => {
    expect(castsOf(board({ user: { hand: [H("rep", REPRIEVE)], pool: { W: 1, C: 1 } } }), "user", "rep")).toEqual([]);
  });

  it("⭐ its target gone, Reprieve doesn't resolve (CR 608.2b) — no draw; it goes to the graveyard", () => {
    const s1 = theirSpellOnStack(DIVINATION, { aiExtra: { hand: [H("sp", DIVINATION), H("cs", COUNTERSPELL)] } });
    const s2 = cast(s1, "user", "rep", aimedAt("Divination"));
    const s3 = resolveTopOfStack(cast(s2, "ai", "cs", aimedAt("Divination"))); // Counterspell resolves first: Divination is countered
    const s4 = resolveTopOfStack(s3);
    const row = { stackBetween: stackNames(s3), aiGraveyard: zonesOf(s4, "ai").graveyard, user: zonesOf(s4, "user"), userLibrary: s4.players.user.library.length,
      fizzle: s4.log.some((e) => e.kind === "spell-fizzle" && e.source === "Reprieve") };
    console.log("  WITNESS fizzle", JSON.stringify(row));
    expect(row).toEqual({ stackBetween: ["Reprieve"], aiGraveyard: ["Divination", "Counterspell"], user: { hand: [], graveyard: ["Reprieve"], exile: [] }, userLibrary: 3, fizzle: true });
  });
});

describe("the shared stack-leave primitive — the counters read the same rules", () => {
  it("Counterspell on a copy: it ceases to exist — no card in the graveyard, no graveyard entry counted", () => {
    const s0 = board({ active: "ai", user: { hand: [H("cs", COUNTERSPELL)], pool: { U: 2 } }, ai: { hand: [H("bolt", BOLT), H("rev", REVERBERATE)], pool: { R: 3 } } });
    const s1 = cast(s0, "ai", "bolt", (a) => a.targets?.[0]?.id === "user");
    const s2 = resolveTopOfStack(cast(s1, "ai", "rev"));
    const copyId = s2.stack.find((o) => o.isCopy).id;
    const s3 = resolveTopOfStack(cast(s2, "user", "cs", (a) => a.targets[0].id === copyId));
    expect({ bolts: everywhere(s3, "Lightning Bolt"), aiGraveyard: zonesOf(s3, "ai").graveyard, entered: [s2.players.ai.gyEnteredThisTurn || 0, s3.players.ai.gyEnteredThisTurn || 0] })
      .toEqual({ bolts: ["stack"], aiGraveyard: ["Reverberate"], entered: [1, 1] });
  });

  it("Remand on a flashback spell: exiled, not returned (CR 702.34a — the exile overrides the hand)", () => {
    const s0 = board({ active: "ai", user: { hand: [H("rem", REMAND)], pool: { U: 1, C: 1 } }, ai: { graveyard: [H("tt", THINK_TWICE)], pool: { U: 6 } } });
    const s1 = cast(s0, "ai", "tt", (a) => a.flashbackCast === true);
    const s3 = resolveTopOfStack(cast(s1, "user", "rem", aimedAt("Think Twice")));
    expect(zonesOf(s3, "ai")).toEqual({ hand: [], graveyard: [], exile: ["Think Twice"] });
  });

  it("Counterspell on a split half: the whole Fire // Ice goes to the graveyard", () => {
    const s0 = board({ active: "ai", user: { hand: [H("cs", COUNTERSPELL)], pool: { U: 2 } }, ai: { hand: [H("fi", FIRE_ICE)], pool: { R: 1, C: 1 } } });
    const s3 = resolveTopOfStack(cast(cast(s0, "ai", "fi"), "user", "cs", aimedAt("Fire")));
    expect({ graveyard: zonesOf(s3, "ai").graveyard, oracle: s3.players.ai.graveyard[0].oracle }).toEqual({ graveyard: ["Fire // Ice"], oracle: FIRE_ICE.oracle });
  });
});

describe("the other cards the arm completes", () => {
  it("⭐ Bilbo's Gambit: the gift is never promised, so the base mode is the whole spell — the bounce, no Treasure, no cast lock", () => {
    const s1 = theirSpellOnStack(DIVINATION, { userExtra: { hand: [H("bg", BILBO)] } });
    const offers = castsOf(s1, "user", "bg");
    const s3 = resolveTopOfStack(cast(s1, "user", "bg"));
    const row = { offers: offers.map((a) => ({ atoms: a.program.atoms.map((x) => x.op), targets: a.targets.map((t) => t.name) })),
      ai: zonesOf(s3, "ai"), permanents: [s3.players.ai.battlefield.length, s3.players.user.battlefield.length], userHand: zonesOf(s3, "user").hand,
      aiCanRecast: castsOf(s3, "ai", "sp").length };
    console.log("  WITNESS bilbo", JSON.stringify(row));
    expect(row).toEqual({ offers: [{ atoms: ["bounce-spell-or-permanent"], targets: ["Divination"] }],
      ai: { hand: ["Divination"], graveyard: [], exile: [] }, permanents: [0, 0], userHand: [], aiCanRecast: 1 });
  });

  it("⭐ Spellscorn Coven // Take It Back: the Adventure returns the spell, goes on its adventure, and the Coven is cast from exile", () => {
    const s0 = board({ user: { hand: [H("div", DIVINATION), H("u2", BEARS)], pool: { U: 3 } }, ai: { hand: [H("cov", COVEN)], pool: { U: 1, C: 2 } } });
    const s1 = cast(s0, "user", "div");
    const s2 = cast(s1, "ai", "cov", (a) => a.adventureCast === true && aimedAt("Divination")(a));
    const s3 = resolveTopOfStack(s2);
    const adventure = { stack: stackNames(s3), userHand: zonesOf(s3, "user").hand.sort(), aiExile: zonesOf(s3, "ai").exile, onAdventure: s3.players.ai.exile[0]?._onAdventure === true };
    // The ai's next turn: the Coven is cast from exile and its enters trigger makes the user discard.
    const t0 = { ...s3, turn: 6, activePlayer: "ai", priorityHolder: "ai", players: { ...s3.players, ai: { ...s3.players.ai, manaPool: { ...s3.players.ai.manaPool, B: 1, C: 3 } } } };
    let t = resolveTopOfStack(cast(t0, "ai", "cov", (a) => a.fromZone === "exile"));
    t = resolveTopOfStack(t);
    while (t.pendingChoice?.kind === "discard") t = resolveDiscardChoice(t, autoPickDiscardCandidate(t, t.pendingChoice));
    const coven = { aiBattlefield: t.players.ai.battlefield.map((p) => p.card?.name), aiExile: zonesOf(t, "ai").exile, userHand: t.players.user.hand.length, userGraveyard: zonesOf(t, "user").graveyard.length };
    console.log("  WITNESS coven", JSON.stringify({ adventure, coven }));
    expect({ adventure, coven }).toEqual({
      adventure: { stack: [], userHand: ["Divination", "Grizzly Bears"], aiExile: ["Spellscorn Coven // Take It Back"], onAdventure: true },
      coven: { aiBattlefield: ["Spellscorn Coven"], aiExile: [], userHand: 1, userGraveyard: 1 },
    });
  });

  it("⭐ a fizzled Adventure never resolved (CR 608.2b, 715.3d): Take It Back goes to the graveyard, no Coven from exile — and the next one resolves normally", () => {
    // The user answers Take It Back by returning their own Divination first — Take It Back's only target is gone.
    const s0 = board({ user: { hand: [H("div", DIVINATION), H("rep", REPRIEVE)], pool: { U: 9, W: 4 } }, ai: { hand: [H("cov", COVEN), H("cov2", COVEN)], pool: { U: 6 } } });
    const s1 = cast(s0, "user", "div");
    const s2 = cast(cast(s1, "ai", "cov", (a) => a.adventureCast === true), "user", "rep", aimedAt("Divination"));
    const s3 = resolveTopOfStack(s2);  // Reprieve: Divination back to the user's hand
    const s4 = resolveTopOfStack(s3);  // Take It Back: its target gone
    const fizzled = { ai: zonesOf(s4, "ai"), fromExile: castsOf({ ...s4, activePlayer: "ai" }, "ai", "cov").filter((a) => a.fromZone === "exile").length };
    // The same game later: the second Coven's Take It Back resolves against a real spell and goes on its adventure.
    const s5 = cast(s4, "user", "div");
    const s6 = resolveTopOfStack(cast(s5, "ai", "cov2", (a) => a.adventureCast === true && aimedAt("Divination")(a)));
    const resolved = { aiExile: zonesOf(s6, "ai").exile, userHand: zonesOf(s6, "user").hand.sort() };
    console.log("  WITNESS adventureFizzle", JSON.stringify({ fizzled, resolved }));
    expect({ fizzled, resolved }).toEqual({
      fizzled: { ai: { hand: ["Spellscorn Coven // Take It Back"], graveyard: ["Spellscorn Coven // Take It Back"], exile: [] }, fromExile: 0 },
      resolved: { aiExile: ["Spellscorn Coven // Take It Back"], userHand: ["Divination", "Grizzly Bears"] },
    });
  });

  it("⭐ a COPY of Take It Back is an Adventure but no card (CR 715.3c, 707.10a): it goes on no adventure — one Coven card in the game", () => {
    const s0 = board({ user: { hand: [H("div", DIVINATION)], pool: { U: 3 } }, ai: { hand: [H("cov", COVEN), H("rev", REVERBERATE)], pool: { U: 3, R: 2 } } });
    const s1 = cast(s0, "user", "div");
    const s2 = cast(s1, "ai", "cov", (a) => a.adventureCast === true);
    const s3 = resolveTopOfStack(cast(s2, "ai", "rev", aimedAt("Take It Back"))); // the copy goes on the stack, aimed at Divination
    const copied = s3.stack.map((o) => (o.isCopy ? `${o.source?.name} (copy)` : o.source?.name));
    const s4 = resolveTopOfStack(s3); // the copy returns Divination
    const s5 = resolveTopOfStack(s4); // the original finds its target gone
    const row = { copied, covens: everywhere(s5, "Spellscorn Coven // Take It Back"), ai: zonesOf(s5, "ai"), userHand: zonesOf(s5, "user").hand, errors: errors(s5).length };
    console.log("  WITNESS adventureCopy", JSON.stringify(row));
    expect(row).toEqual({ copied: ["Divination", "Take It Back", "Take It Back (copy)"], covens: ["ai.graveyard"],
      ai: { hand: [], graveyard: ["Reverberate", "Spellscorn Coven // Take It Back"], exile: [] }, userHand: ["Divination"], errors: 0 });
  });

  it("the same rule for an adventure already native: a fizzled Petty Theft goes to the graveyard, not its adventure", () => {
    const s0 = board({ active: "ai", user: { hand: [H("bolt", BOLT)], pool: { R: 1 }, battlefield: [P("ub", BEARS, "user")] }, ai: { hand: [H("bb", BORROWER)], pool: { U: 2 } } });
    const s1 = cast(s0, "ai", "bb", (a) => a.adventureCast === true);
    const s2 = resolveTopOfStack(cast(s1, "user", "bolt", (a) => a.targets?.[0]?.id === "ub")); // the user kills their own Bears in response
    const s3 = resolveTopOfStack(s2);
    expect(zonesOf(s3, "ai")).toEqual({ hand: [], graveyard: ["Brazen Borrower // Petty Theft"], exile: [] });
  });
});
