/**
 * SPELLS THAT ACT ON A SPELL — the play-weighted program, #720 Narset's Reversal, #675 Dualcaster Mage, #658 Imp's Mischief.
 *   Narset's Reversal — "Copy target instant or sorcery spell, then return it to its owner's hand. You may choose new targets
 *                        for the copy."
 *   Dualcaster Mage  — "Flash / When this creature enters, copy target instant or sorcery spell. You may choose new targets
 *                        for the copy."
 *   Imp's Mischief   — "Change the target of target spell with a single target. You lose life equal to that spell's mana
 *                        value."
 *
 * THE PARSE (atoms/stack.spellOnStackSentenceAtoms — two sentences read whole, exact anchors):
 *  - the copy atom with `newTargets` (the printed CR 707.10c permission), and for Narset's Reversal `returnOriginal`;
 *  - Swerve's change-target atom, then `lose-life-spell-mana-value` bound to that atom's target (bindPreviousTargets).
 * Dualcaster Mage's trigger is the same copy atom; its target intent is "any" (the copy is the copier's whichever spell it
 * copies — CR 707.10), so the flush chooser takes any legal spell, and with none the trigger is removed (CR 603.3d).
 *
 * THE COPY (atoms/stack.applyCopyInstantOrSorcery): the copier controls it (CR 707.10) and it keeps the original's mode, kick
 * and X. NEW TARGETS (newTargetsForCopy): every target is kept when it already sits where its slot's effect wants it for the
 * copier; otherwise the first legal set under the copy's new controller that fills the same slots on the wanted sides —
 * judged with the copy's own colours — and the originals when there is none. Then, for Narset's Reversal, the original leaves
 * the stack: to its owner's hand, to exile if it was a flashback cast (CR 702.34a), to nowhere if it was a copy (CR 704.5e).
 * A spell that "can't be copied" is not copied (CR 101.2). Each copy is a "copy" event for magecraft.
 *
 * THE MANA VALUE (atoms/stack.stackSpellManaValue, CR 202.3): the half or Adventure actually cast (202.3d, 715.3b), the
 * printed cost under a flashback cast (118.9c), the chosen X once per {X} (202.3e). Mana Drain reads the same function.
 *
 * THE CHANGE OF TARGET (targeting.changeTargetAlternatives — Swerve's arm, CR 115.7a) now enumerates with the spell's own
 * colours and X, so a target can't be changed to a permanent with protection from the spell (CR 702.16b).
 *
 * Accepted under-reads (documented false negatives): the new-target choice is the engine's default policy, not a pause for
 * the player; a copy's targets are changed as one whole set (the rule also allows changing some and leaving others); an Aura
 * spell's target is not moved by a change-target effect (it carries no effect program to re-enumerate) — the life is still
 * lost; CR 903.9b's command-zone choice for a returned commander is not offered (every bounce).
 *
 * Real oracle fixtures (bundled Scryfall, generated by cardIndex.publicCard — never typed by hand). The one synthetic card
 * is labelled where it is built.
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, createGameState, createPermanent } from "./gameState.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { resolveTopOfStack } from "./gameEngine.js";
import { autoPickChangeTarget, resolveChangeTargetChoice } from "./effects/runProgram.js";
import { changeTargetAlternatives } from "./effects/targeting.js";
import { classifyCard } from "./coverage.js";
import { atomTargetIntent, parseEffectClause, parseEffectProgram, programConfidence } from "./effects/parser.js";
import { detectTriggers } from "./triggers.js";
import { triggerRoutesNatively } from "./triggerRouting.js";
import { permanentPower } from "./layers.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const NARSETS_REVERSAL = {"name":"Narset's Reversal","type":"Instant","mana":"{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Copy target instant or sorcery spell, then return it to its owner's hand. You may choose new targets for the copy."}; // native-spell
const DUALCASTER_MAGE = {"name":"Dualcaster Mage","type":"Creature — Human Wizard","mana":"{1}{R}{R}","cmc":3,"power":"2","toughness":"2","keywords":["Flash"],"colors":["R"],"oracle":"Flash\nWhen this creature enters, copy target instant or sorcery spell. You may choose new targets for the copy."}; // native-trigger
const IMPS_MISCHIEF = {"name":"Imp's Mischief","type":"Instant","mana":"{1}{B}","cmc":2,"keywords":[],"colors":["B"],"oracle":"Change the target of target spell with a single target. You lose life equal to that spell's mana value."}; // native-spell
const REVERBERATE = {"name":"Reverberate","type":"Instant","mana":"{R}{R}","cmc":2,"keywords":[],"colors":["R"],"oracle":"Copy target instant or sorcery spell. You may choose new targets for the copy."}; // native-spell
const FORK = {"name":"Fork","type":"Instant","mana":"{R}{R}","cmc":2,"keywords":[],"colors":["R"],"oracle":"Copy target instant or sorcery spell, except that the copy is red. You may choose new targets for the copy."}; // arbiter-spell
const DIVERT = {"name":"Divert","type":"Instant","mana":"{U}","cmc":1,"keywords":[],"colors":["U"],"oracle":"Change the target of target spell with a single target unless that spell's controller pays {2}."}; // arbiter-spell
const NARU_MEHA = {"name":"Naru Meha, Master Wizard","type":"Legendary Creature — Human Wizard","mana":"{2}{U}{U}","cmc":4,"power":"3","toughness":"3","keywords":["Flash"],"colors":["U"],"oracle":"Flash\nWhen Naru Meha enters, copy target instant or sorcery spell you control. You may choose new targets for the copy.\nOther Wizards you control get +1/+1."}; // body-only
const SIGIL_TRACER = {"name":"Sigil Tracer","type":"Creature — Merfolk Wizard","mana":"{1}{U}{U}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["U"],"oracle":"{1}{U}, Tap two untapped Wizards you control: Copy target instant or sorcery spell. You may choose new targets for the copy."}; // body-only
const SWORDS = {"name":"Swords to Plowshares","type":"Instant","mana":"{W}","cmc":1,"keywords":[],"colors":["W"],"oracle":"Exile target creature. Its controller gains life equal to its power."}; // native-spell
const BOLT = {"name":"Lightning Bolt","type":"Instant","mana":"{R}","cmc":1,"keywords":[],"colors":["R"],"oracle":"Lightning Bolt deals 3 damage to any target."}; // native-spell
const COUNTERSPELL = {"name":"Counterspell","type":"Instant","mana":"{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Counter target spell."}; // native-spell
const DIVINATION = {"name":"Divination","type":"Sorcery","mana":"{2}{U}","cmc":3,"keywords":[],"colors":["U"],"oracle":"Draw two cards."}; // native-spell
const FIREBOLT = {"name":"Firebolt","type":"Sorcery","mana":"{R}","cmc":1,"keywords":["Flashback"],"colors":["R"],"oracle":"Firebolt deals 2 damage to any target.\nFlashback {4}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"}; // native-spell
const GIANT_GROWTH = {"name":"Giant Growth","type":"Instant","mana":"{G}","cmc":1,"keywords":[],"colors":["G"],"oracle":"Target creature gets +3/+3 until end of turn."}; // native-spell
const PREY_UPON = {"name":"Prey Upon","type":"Sorcery","mana":"{G}","cmc":1,"keywords":["Fight"],"colors":["G"],"oracle":"Target creature you control fights target creature you don't control. (Each deals damage equal to its power to the other.)"}; // native-spell
const ABRADE = {"name":"Abrade","type":"Instant","mana":"{1}{R}","cmc":2,"keywords":[],"colors":["R"],"oracle":"Choose one —\n• Abrade deals 3 damage to target creature.\n• Destroy target artifact."}; // native-spell
const BLOODCHIEFS_THIRST = {"name":"Bloodchief's Thirst","type":"Sorcery","mana":"{B}","cmc":1,"keywords":["Kicker"],"colors":["B"],"oracle":"Kicker {2}{B} (You may pay an additional {2}{B} as you cast this spell.)\nDestroy target creature or planeswalker with mana value 2 or less. If this spell was kicked, instead destroy target creature or planeswalker."}; // native-spell
const DISSECTION_PRACTICE = {"name":"Dissection Practice","type":"Instant","mana":"{B}","cmc":1,"keywords":[],"colors":["B"],"oracle":"Target opponent loses 1 life and you gain 1 life.\nUp to one target creature gets +1/+1 until end of turn.\nUp to one target creature gets -1/-1 until end of turn."}; // native-spell
const CURSE_OF_THE_SWINE = {"name":"Curse of the Swine","type":"Sorcery","mana":"{X}{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Exile X target creatures. For each creature exiled this way, its controller creates a 2/2 green Boar creature token."}; // native-spell
const BLAZE = {"name":"Blaze","type":"Sorcery","mana":"{X}{R}","cmc":1,"keywords":[],"colors":["R"],"oracle":"Blaze deals X damage to any target."}; // native-spell
const FIRE_ICE = {"name":"Fire // Ice","type":"Instant // Instant","mana":"{1}{R} // {1}{U}","cmc":4,"keywords":[],"layout":"split","colors":["R","U"],"oracle":"Fire - Instant {1}{R}\nFire deals 2 damage divided as you choose among one or two targets.\n//\nIce - Instant {1}{U}\nTap target permanent.\nDraw a card."}; // native-spell
const BORROWER = {"name":"Brazen Borrower // Petty Theft","type":"Creature — Faerie Rogue // Instant — Adventure","mana":"{1}{U}{U} // {1}{U}","cmc":3,"power":"3","toughness":"1","keywords":["Flying","Flash"],"layout":"adventure","colors":["U"],"oracle":"Brazen Borrower - Creature — Faerie Rogue {1}{U}{U}\nFlash\nFlying\nThis creature can block only creatures with flying.\n//\nPetty Theft - Instant — Adventure {1}{U}\nReturn target nonland permanent an opponent controls to its owner's hand."}; // native-mixed
const DISPLAY_OF_POWER = {"name":"Display of Power","type":"Instant","mana":"{1}{R}{R}","cmc":3,"keywords":[],"colors":["R"],"oracle":"This spell can't be copied.\nCopy any number of target instant and/or sorcery spells. You may choose new targets for the copies."}; // arbiter-spell
const MANA_DRAIN = {"name":"Mana Drain","type":"Instant","mana":"{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Counter target spell. At the beginning of your next main phase, add an amount of {C} equal to that spell's mana value."}; // native-spell
const GELATINOUS_GENESIS = {"name":"Gelatinous Genesis","type":"Sorcery","mana":"{X}{X}{G}","cmc":1,"keywords":[],"colors":["G"],"oracle":"Create X X/X green Ooze creature tokens."}; // native-spell
const ARCHMAGE_EMERITUS = {"name":"Archmage Emeritus","type":"Creature — Human Wizard","mana":"{2}{U}{U}","cmc":4,"power":"2","toughness":"2","keywords":["Magecraft"],"colors":["U"],"oracle":"Magecraft — Whenever you cast or copy an instant or sorcery spell, draw a card."}; // native-trigger
const KOR_FIREWALKER = {"name":"Kor Firewalker","type":"Creature — Kor Soldier","mana":"{W}{W}","cmc":2,"power":"2","toughness":"2","keywords":["Protection"],"colors":["W"],"oracle":"Protection from red\nWhenever a player casts a red spell, you may gain 1 life."}; // native-trigger
const HILL_GIANT = {"name":"Hill Giant","type":"Creature — Giant","mana":"{3}{R}","cmc":4,"power":"3","toughness":"3","keywords":[],"colors":["R"],"oracle":""}; // native-body
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const SOL_RING = {"name":"Sol Ring","type":"Artifact","mana":"{1}","cmc":1,"keywords":[],"colors":[],"oracle":"{T}: Add {C}{C}."}; // native-mana
const PACIFISM = {"name":"Pacifism","type":"Enchantment — Aura","mana":"{1}{W}","cmc":2,"keywords":["Enchant"],"colors":["W"],"oracle":"Enchant creature\nEnchanted creature can't attack or block."}; // native-aura
const PYROMANCER = {"name":"Prodigal Pyromancer","type":"Creature — Human Wizard","mana":"{2}{R}","cmc":3,"power":"1","toughness":"1","keywords":[],"colors":["R"],"oracle":"{T}: This creature deals 1 damage to any target."}; // native-activated
const TWINCAST = {"name":"Twincast","type":"Instant","mana":"{U}{U}","cmc":2,"keywords":[],"colors":["U"],"oracle":"Copy target instant or sorcery spell. You may choose new targets for the copy."}; // native-spell

// ─── harness ──────────────────────────────────────────────────────────────────
const H = (id, card) => ({ ...card, id });
const P = (id, card, controller) => createPermanent({ id, card: { ...card, id: `c-${id}` }, controller, summoningSick: false });
/** A two-seat table in `active`'s precombat main; each seat's hand / graveyard / battlefield / pool given, three Bears in
 *  each library (so a draw is visible). Life 40 each. */
function board({ active = "ai", user = {}, ai = {} } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  const lib = (who) => [1, 2, 3].map((i) => ({ ...BEARS, id: `${who}-lib${i}` }));
  const seat = (who, o) => ({ ...g.players[who], battlefield: o.battlefield || [], hand: o.hand || [], graveyard: o.graveyard || [], exile: [],
    manaPool: { ...g.players[who].manaPool, ...(o.pool || {}) }, library: lib(who) });
  return { ...g, turn: 5, activePlayer: active, priorityHolder: active, phase: "precombat-main", step: "main", stack: [], pendingTriggers: [], consecutivePasses: 0,
    players: { ...g.players, user: seat("user", user), ai: seat("ai", ai) } };
}
const castsOf = (s, who, cardId) => legalActionsForPlayer({ ...s, priorityHolder: who }, who).filter((a) => a.kind === "cast-spell" && a.cardId === cardId);
/** Dispatch `who`'s one offered cast of `cardId` that `pick` accepts (the cast must be offered — the test fails otherwise). */
function cast(s, who, cardId, pick = () => true) {
  const a = castsOf(s, who, cardId).find(pick);
  expect(a, `${who} is offered a cast of ${cardId}`).toBeTruthy();
  return dispatchAction({ ...s, priorityHolder: who }, a);
}
const at = (id) => (a) => (a.targets || []).some((t) => t.id === id);
const only = (...ids) => (a) => (a.targets || []).map((t) => t.id).join(",") === ids.join(",");
const spell = (s, name) => s.stack.find((o) => o.source?.name === name && !o.isCopy);
const copyOf = (s, name) => s.stack.find((o) => o.source?.name === name && o.isCopy);
const onSpell = (s, name) => at(spell(s, name).id);
const drain = (s) => { let n = s, g = 0; while (n.stack?.length && !n.pendingChoice && g++ < 30) n = resolveTopOfStack(n); return n; };
const names = (cards) => cards.map((c) => c.name);
const stackNames = (s) => s.stack.map((o) => `${o.source?.name}${o.isCopy ? " (copy)" : ""}`);
const onBf = (s, who, id) => s.players[who].battlefield.some((p) => p.id === id);
const life = (s) => ({ user: s.players.user.life, ai: s.players.ai.life });
const logged = (s, pred) => (s.log || []).filter(pred);
/** Every card object named `name` anywhere in the game: each seat's zones, the battlefield's cards, the stack's sources. */
function everywhere(s, name) {
  const out = [];
  for (const [pid, p] of Object.entries(s.players)) {
    for (const z of ["hand", "graveyard", "exile", "library"]) for (const c of p[z] || []) if (c.name === name) out.push(`${pid}.${z}`);
    for (const perm of p.battlefield || []) if (perm.card?.name === name) out.push(`${pid}.battlefield`);
  }
  for (const o of s.stack) if (o.source?.name === name) out.push(o.isCopy ? "stack(copy)" : "stack");
  return out.sort();
}
/** The opponent (ai), in their main phase, casts `card` (id "sp" — the offered cast `pick` accepts); the user holds `hold`. */
function theirSpell(card, pick, { hold = [], pool = {}, mine = [], theirs = [], aiHand = [], aiGraveyard = null, aiPool = {} } = {}) {
  const s0 = board({
    user: { hand: hold, pool, battlefield: mine },
    ai: { hand: aiGraveyard ? aiHand : [H("sp", card), ...aiHand], graveyard: aiGraveyard || [], battlefield: theirs, pool: { W: 3, U: 4, B: 4, R: 6, G: 4, C: 4, ...aiPool } },
  });
  return cast(s0, "ai", "sp", pick);
}
const NARSET = () => [H("nar", NARSETS_REVERSAL)];
const IMPS = () => [H("imp", IMPS_MISCHIEF)];

describe("the cards and their parse", () => {
  it("classify: the three targets read native; the near misses stay parked", () => {
    const row = { narset: classifyCard(NARSETS_REVERSAL), dualcaster: classifyCard(DUALCASTER_MAGE), imps: classifyCard(IMPS_MISCHIEF),
      reverberate: classifyCard(REVERBERATE), twincast: classifyCard(TWINCAST),
      fork: classifyCard(FORK), divert: classifyCard(DIVERT), naruMeha: classifyCard(NARU_MEHA), sigilTracer: classifyCard(SIGIL_TRACER) };
    console.log("  WITNESS classify", JSON.stringify(row)); // vitest 4 needs --disable-console-intercept
    expect(row).toEqual({ narset: "native-spell", dualcaster: "native-trigger", imps: "native-spell", reverberate: "native-spell", twincast: "native-spell",
      fork: "arbiter-spell", divert: "arbiter-spell", naruMeha: "body-only", sigilTracer: "body-only" });
  });

  it("Narset's Reversal: one copy atom — new targets allowed, the original returned; Reverberate: the same atom without the return", () => {
    const copy = { op: "copy-instant-or-sorcery", targetType: "spell", spellFilter: "instantSorcery", copyNotCounter: true, newTargets: true };
    const n = parseEffectProgram(NARSETS_REVERSAL);
    const r = parseEffectProgram(REVERBERATE);
    expect({ narset: [programConfidence(n), n.atoms], reverberate: [programConfidence(r), r.atoms] })
      .toEqual({ narset: ["high", [{ ...copy, returnOriginal: true }]], reverberate: ["high", [copy]] });
  });

  it("Imp's Mischief: Swerve's change-target atom, then the life loss bound to that atom's target", () => {
    const p = parseEffectProgram(IMPS_MISCHIEF);
    expect({ confidence: programConfidence(p), atoms: p.atoms }).toEqual({ confidence: "high", atoms: [
      { op: "change-target", targetType: "spell", singleTargetOnly: true, notCounter: true },
      { op: "lose-life-spell-mana-value", bindPreviousTargets: true, targetType: null },
    ] });
  });

  it("Dualcaster Mage: one enters trigger, the copy atom with new targets; any legal spell is a correct pick, so it routes natively", () => {
    const triggers = detectTriggers(DUALCASTER_MAGE);
    const p = parseEffectClause(triggers[0].effectClause, "Instant", { sourceScoped: true });
    expect({ n: triggers.length, event: triggers[0].event, scope: triggers[0].scope, optional: triggers[0].optional, confidence: programConfidence(p), atoms: p.atoms,
      intent: atomTargetIntent(p.atoms[0]), routes: triggerRoutesNatively(triggers[0]) })
      .toEqual({ n: 1, event: "etb", scope: "self", optional: false, confidence: "high",
        atoms: [{ op: "copy-instant-or-sorcery", targetType: "spell", spellFilter: "instantSorcery", copyNotCounter: true, newTargets: true }], intent: "any", routes: true });
  });

  it("the anchors hold: a scope on the copied spell, a changed copy, a missing rider, another payoff stay unparsed", () => {
    const conf = (clause) => programConfidence(parseEffectClause(clause, "Instant"));
    expect({
      youControl: conf("Copy target instant or sorcery spell you control. You may choose new targets for the copy."),
      fork: conf("Copy target instant or sorcery spell, except that the copy is red. You may choose new targets for the copy."),
      returnNoRider: conf("Copy target instant or sorcery spell, then return it to its owner's hand."),
      returnToTop: conf("Copy target instant or sorcery spell, then put it on top of its owner's library. You may choose new targets for the copy."),
      divert: conf("Change the target of target spell with a single target unless that spell's controller pays {2}."),
      gainLife: conf("Change the target of target spell with a single target. You gain life equal to that spell's mana value."),
      orAbility: conf("Change the target of target spell or ability with a single target. You lose life equal to that spell's mana value."),
    }).toEqual({ youControl: "low", fork: "low", returnNoRider: "low", returnToTop: "low", divert: "low", gainLife: "low", orAbility: "low" });
  });
});

describe("⭐ Narset's Reversal — the copy is yours and re-aimed; the original goes back", () => {
  it("⭐ their Swords to Plowshares on your Bears: the copy exiles THEIR Bears, the original returns to their hand (WITNESS)", () => {
    const s1 = theirSpell(SWORDS, at("mine"), { hold: NARSET(), pool: { U: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    const offered = castsOf(s1, "user", "nar").map((a) => a.targets.map((t) => t.name));
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const copy = copyOf(s2, "Swords to Plowshares");
    const s3 = drain(s2);
    const row = { offered, stackAfterNarset: stackNames(s2), copyController: copy.controller, copyTargets: copy.targets.map((t) => t.id),
      aiHand: names(s2.players.ai.hand), mineAlive: onBf(s3, "user", "mine"), theirsAlive: onBf(s3, "ai", "theirs"), theirExile: names(s3.players.ai.exile),
      life: life(s3), userGraveyard: names(s3.players.user.graveyard), swords: everywhere(s3, "Swords to Plowshares") };
    console.log("  WITNESS narset", JSON.stringify(row));
    expect(row).toEqual({ offered: [["Swords to Plowshares"]], stackAfterNarset: ["Swords to Plowshares (copy)"], copyController: "user", copyTargets: ["theirs"],
      aiHand: ["Swords to Plowshares"], mineAlive: true, theirsAlive: false, theirExile: ["Grizzly Bears"],
      life: { user: 40, ai: 42 }, userGraveyard: ["Narset's Reversal"], swords: ["ai.hand"] });
  });

  it("⭐ a FLASHBACK spell is exiled instead of returned (CR 702.34a); its copy is re-aimed all the same", () => {
    const s0 = board({ user: { hand: NARSET(), pool: { U: 2 } }, ai: { graveyard: [H("sp", FIREBOLT)], pool: { R: 5 } } });
    const s1 = cast(s0, "ai", "sp", (a) => a.flashbackCast && at("user")(a));
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const copyTargets = copyOf(s2, "Firebolt").targets.map((t) => t.id);
    const s3 = drain(s2);
    const row = { copyTargets, firebolt: everywhere(s3, "Firebolt"), life: life(s3) };
    console.log("  WITNESS flashback", JSON.stringify(row));
    expect(row).toEqual({ copyTargets: ["ai"], firebolt: ["ai.exile"], life: { user: 40, ai: 38 } });
  });

  it("⭐ a COPY ceases to exist (CR 704.5e, 707.10a): returned, it reaches no hand — and the copy made of it is yours", () => {
    const s0 = board({ user: { hand: NARSET(), pool: { U: 2 } }, ai: { hand: [H("bolt", BOLT), H("rev", REVERBERATE)], pool: { R: 3 } } });
    const s1 = cast(s0, "ai", "bolt", at("user"));
    const s2 = resolveTopOfStack(cast(s1, "ai", "rev"));                       // their copy of their Bolt, still aimed at you
    const theirCopy = copyOf(s2, "Lightning Bolt");
    const s3 = resolveTopOfStack(cast(s2, "user", "nar", at(theirCopy.id)));
    const mine = s3.stack.filter((o) => o.isCopy).map((o) => [o.controller, o.targets.map((t) => t.id)]);
    const s4 = drain(s3);
    const row = { theirCopy: [theirCopy.controller, theirCopy.targets.map((t) => t.id)], stackAfter: stackNames(s3), copies: mine,
      bolt: everywhere(s4, "Lightning Bolt"), aiHand: names(s4.players.ai.hand), life: life(s4) };
    console.log("  WITNESS copy-of-a-copy", JSON.stringify(row));
    expect(row).toEqual({ theirCopy: ["ai", ["user"]], stackAfter: ["Lightning Bolt", "Lightning Bolt (copy)"], copies: [["user", ["ai"]]],
      bolt: ["ai.graveyard"], aiHand: [], life: { user: 37, ai: 37 } });
  });

  it("your own spell: the copy keeps its target (nothing is on the wrong side), and the original comes back to your hand", () => {
    const s0 = board({ active: "user", user: { hand: [H("bolt", BOLT), ...NARSET()], pool: { R: 1, U: 2 } }, ai: { battlefield: [P("theirs", BEARS, "ai")] } });
    const s1 = cast(s0, "user", "bolt", at("ai"));
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const row = { copyTargets: copyOf(s2, "Lightning Bolt").targets.map((t) => t.id), userHand: names(s2.players.user.hand), aiLife: drain(s2).players.ai.life };
    expect(row).toEqual({ copyTargets: ["ai"], userHand: ["Lightning Bolt"], aiLife: 37 });
  });

  it("a beneficial spell comes to YOUR side: their Giant Growth on their Bears — the copy pumps yours", () => {
    const s1 = theirSpell(GIANT_GROWTH, at("theirs"), { hold: NARSET(), pool: { U: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const copyTargets = copyOf(s2, "Giant Growth").targets.map((t) => t.id);
    const s3 = drain(s2);
    expect({ copyTargets, mine: permanentPower(s3, "mine"), theirs: permanentPower(s3, "theirs") }).toEqual({ copyTargets: ["mine"], mine: 5, theirs: 2 });
  });

  it("⭐ the copy keeps its MODE (CR 707.10): an Abrade destroying your Sol Ring destroys THEIR Sol Ring — never their creature", () => {
    const s1 = theirSpell(ABRADE, (a) => a.chosenMode === 1 && at("myring")(a),
      { hold: NARSET(), pool: { U: 2 }, mine: [P("myring", SOL_RING, "user")], theirs: [P("theirs", BEARS, "ai"), P("ring", SOL_RING, "ai")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const copy = copyOf(s2, "Abrade");
    const s3 = drain(s2);
    expect({ mode: copy.payload.params.chosenMode, copyTargets: copy.targets.map((t) => t.id), bears: onBf(s3, "ai", "theirs"), theirRing: onBf(s3, "ai", "ring"), myRing: onBf(s3, "user", "myring") })
      .toEqual({ mode: 1, copyTargets: ["ring"], bears: true, theirRing: false, myRing: true });
  });

  it("⭐ the copy keeps its KICK (CR 707.10): a kicked Bloodchief's Thirst on your Hill Giant destroys THEIR Hill Giant", () => {
    const s1 = theirSpell(BLOODCHIEFS_THIRST, (a) => a.kicked === true && at("mine")(a),
      { hold: NARSET(), pool: { U: 2 }, mine: [P("mine", HILL_GIANT, "user")], theirs: [P("theirs", HILL_GIANT, "ai")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const copyTargets = copyOf(s2, "Bloodchief's Thirst").targets.map((t) => t.id);
    const s3 = drain(s2);
    expect({ copyTargets, mine: onBf(s3, "user", "mine"), theirs: onBf(s3, "ai", "theirs") }).toEqual({ copyTargets: ["theirs"], mine: true, theirs: false });
  });

  it("⭐ the copy keeps its X (CR 707.10): a Curse of the Swine for X = 1 on your Bears exiles THEIR Bears", () => {
    const s1 = theirSpell(CURSE_OF_THE_SWINE, (a) => a.xValue === 1 && only("mine")(a),
      { hold: NARSET(), pool: { U: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const copy = copyOf(s2, "Curse of the Swine");
    const s3 = drain(s2);
    expect({ x: copy.payload.params.xValue, copyTargets: copy.targets.map((t) => t.id), mine: onBf(s3, "user", "mine"), theirs: onBf(s3, "ai", "theirs"),
      theirBoars: s3.players.ai.battlefield.filter((p) => /Boar/.test(p.card?.name || "")).length })
      .toEqual({ x: 1, copyTargets: ["theirs"], mine: true, theirs: false, theirBoars: 1 });
  });

  it("⭐ a copy never gains or drops a target, and each stays in its SLOT (CR 601.2c, 707.10): Dissection Practice", () => {
    // Theirs: you lose 1 (atom 0), no +1/+1 target (atom 2 declined), your Bears get -1/-1 (atom 3). Your copy fills the same two
    // slots — them, and their Bears in the -1/-1 slot. Sets that would also pump your Bears (a third target), or put a target
    // in the +1/+1 slot instead of the -1/-1 one (two targets, another effect), are enumerated first and are not the copy.
    const s1 = theirSpell(DISSECTION_PRACTICE, (a) => a.targets.map((t) => `${t.atomIndex}:${t.id}`).join(" ") === "0:user 3:mine",
      { hold: NARSET(), pool: { U: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const copyTargets = copyOf(s2, "Dissection Practice").targets.map((t) => [t.atomIndex, t.id]);
    const s3 = resolveTopOfStack(s2);
    const row = { atoms: parseEffectProgram(DISSECTION_PRACTICE).atoms.map((a) => a.op), copyTargets, minePower: permanentPower(s3, "mine"), theirsPower: permanentPower(s3, "theirs"), life: life(s3) };
    console.log("  WITNESS slots", JSON.stringify(row));
    expect(row).toEqual({ atoms: ["lose-life", "gain-life", "pump", "pump"], copyTargets: [[0, "ai"], [3, "theirs"]], minePower: 2, theirsPower: 1, life: { user: 41, ai: 39 } });
  });

  it("no legal set on the wanted side: the original target stands (CR 707.10c) — their Swords, and they control no creature", () => {
    const s1 = theirSpell(SWORDS, at("mine"), { hold: NARSET(), pool: { U: 2 }, mine: [P("mine", BEARS, "user")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const copyTargets = copyOf(s2, "Swords to Plowshares").targets.map((t) => t.id);
    const s3 = drain(s2);
    expect({ copyTargets, mineAlive: onBf(s3, "user", "mine"), life: life(s3), aiHand: names(s3.players.ai.hand) })
      .toEqual({ copyTargets: ["mine"], mineAlive: false, life: { user: 42, ai: 40 }, aiHand: ["Swords to Plowshares"] });
  });

  it("the copy's own colours judge its targets (CR 702.16b): a Bolt copy skips their Kor Firewalker for their face", () => {
    const s1 = theirSpell(BOLT, at("mine"), { hold: NARSET(), pool: { U: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("kor", KOR_FIREWALKER, "ai")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    expect(copyOf(s2, "Lightning Bolt").targets.map((t) => t.id)).toEqual(["ai"]);
  });

  it("⭐ a spell aimed at a spell: the copy of their Counterspell counters their OTHER spell, not the Counterspell that is leaving", () => {
    const s0 = board({ active: "user", user: { hand: [H("div", DIVINATION), ...NARSET()], pool: { U: 5 } }, ai: { hand: [H("cs", COUNTERSPELL), H("bolt", BOLT)], pool: { U: 2, R: 1 } } });
    const s1 = cast(cast(cast(s0, "user", "div"), "ai", "cs"), "ai", "bolt", at("user"));   // Divination ← Counterspell, then their Bolt at you
    const s2 = resolveTopOfStack(cast(s1, "user", "nar", onSpell(s1, "Counterspell")));
    const copyTargets = copyOf(s2, "Counterspell").targets.map((t) => s2.stack.find((o) => o.id === t.id)?.source?.name);
    const s3 = drain(s2);
    const row = { copyTargets, aiHand: names(s3.players.ai.hand), aiGraveyard: names(s3.players.ai.graveyard), userLife: s3.players.user.life, userHand: s3.players.user.hand.length };
    console.log("  WITNESS counterspell", JSON.stringify(row));
    expect(row).toEqual({ copyTargets: ["Lightning Bolt"], aiHand: ["Counterspell"], aiGraveyard: ["Lightning Bolt"], userLife: 40, userHand: 2 });
  });

  it("with no other spell of theirs, the copy takes the leaving Counterspell — it fizzles rather than counter your own spell", () => {
    const s0 = board({ active: "user", user: { hand: [H("div", DIVINATION), ...NARSET()], pool: { U: 5 } }, ai: { hand: [H("cs", COUNTERSPELL)], pool: { U: 2 } } });
    const s1 = cast(cast(s0, "user", "div"), "ai", "cs");
    const original = spell(s1, "Counterspell").id;
    const s2 = resolveTopOfStack(cast(s1, "user", "nar", at(original)));
    const copyTargets = copyOf(s2, "Counterspell").targets.map((t) => t.id);
    const s3 = drain(s2);
    expect({ aimedAtOriginal: copyTargets[0] === original, aiHand: names(s3.players.ai.hand), userHand: s3.players.user.hand.length, divination: everywhere(s3, "Divination") })
      .toEqual({ aimedAtOriginal: true, aiHand: ["Counterspell"], userHand: 2, divination: ["user.graveyard"] });
  });

  it("Reverberate (no return): the copy of their Counterspell counters the Counterspell itself, their Bolt still resolves", () => {
    const s0 = board({ active: "user", user: { hand: [H("div", DIVINATION), H("rev", REVERBERATE)], pool: { U: 3, R: 2 } }, ai: { hand: [H("cs", COUNTERSPELL), H("bolt", BOLT)], pool: { U: 2, R: 1 } } });
    const s1 = cast(cast(cast(s0, "user", "div"), "ai", "cs"), "ai", "bolt", at("user"));
    const s2 = resolveTopOfStack(cast(s1, "user", "rev", onSpell(s1, "Counterspell")));
    const copyTargets = copyOf(s2, "Counterspell").targets.map((t) => s2.stack.find((o) => o.id === t.id)?.source?.name);
    const s3 = drain(s2);
    expect({ copyTargets, stackAfterReverberate: stackNames(s2), aiGraveyard: names(s3.players.ai.graveyard).sort(), userLife: s3.players.user.life, userHand: s3.players.user.hand.length })
      .toEqual({ copyTargets: ["Counterspell"], stackAfterReverberate: ["Divination", "Counterspell", "Lightning Bolt", "Counterspell (copy)"],
        aiGraveyard: ["Counterspell", "Lightning Bolt"], userLife: 37, userHand: 2 });
  });

  it("⭐ \"This spell can't be copied\" (CR 101.2): Display of Power is a legal target, no copy is made, and it is still returned", () => {
    const s1 = theirSpell(DISPLAY_OF_POWER, () => true, { hold: NARSET(), pool: { U: 2 } });
    const s2 = resolveTopOfStack(cast(s1, "user", "nar"));
    const row = { stack: stackNames(s2), aiHand: names(s2.players.ai.hand), copies: logged(s2, (e) => e.effect === "copy-instant-or-sorcery").map((e) => e.count) };
    console.log("  WITNESS cant-be-copied", JSON.stringify(row));
    expect(row).toEqual({ stack: [], aiHand: ["Display of Power"], copies: [0] });
  });

  it("magecraft sees the copy (CR 707.10): Archmage Emeritus draws once for the cast and once for the copy", () => {
    const s1 = theirSpell(SWORDS, at("mine"), { hold: NARSET(), pool: { U: 2 }, mine: [P("mine", BEARS, "user"), P("arch", ARCHMAGE_EMERITUS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    const s3 = drain(cast(s1, "user", "nar"));
    expect({ drawn: s3.players.user.hand.length, library: s3.players.user.library.length }).toEqual({ drawn: 2, library: 1 });
  });

  it("the target gone before it resolves (CR 608.2b): no copy, nothing returned", () => {
    const s0 = board({ user: { hand: [...NARSET(), H("cs", COUNTERSPELL)], pool: { U: 4 } }, ai: { hand: [H("sp", BOLT)], pool: { R: 1 } } });
    const s1 = cast(s0, "ai", "sp", at("user"));
    const s2 = cast(cast(s1, "user", "nar"), "user", "cs", onSpell(s1, "Lightning Bolt"));
    const s3 = drain(s2);
    expect({ bolt: everywhere(s3, "Lightning Bolt"), copies: logged(s3, (e) => e.effect === "copy-instant-or-sorcery").length, life: life(s3), narset: everywhere(s3, "Narset's Reversal") })
      .toEqual({ bolt: ["ai.graveyard"], copies: 0, life: { user: 40, ai: 40 }, narset: ["user.graveyard"] });
  });

  it("only an instant or sorcery SPELL is a target: not a creature spell, not an ability (CR 113.9)", () => {
    const creatureSpell = theirSpell(BEARS, () => true, { hold: [...NARSET(), ...IMPS()], pool: { U: 2, B: 2 } });
    const s0 = board({ user: { hand: [...NARSET(), ...IMPS()], pool: { U: 2, B: 2 } }, ai: { battlefield: [P("pyro", PYROMANCER, "ai")] } });
    const ping = legalActionsForPlayer(s0, "ai").find((a) => a.kind === "activate-ability" && at("user")(a));
    const ability = dispatchAction(s0, ping);
    expect({ creatureSpellOnStack: stackNames(creatureSpell), narsetOnCreature: castsOf(creatureSpell, "user", "nar").length, impsOnCreature: castsOf(creatureSpell, "user", "imp").length,
      abilityOnStack: ability.stack.map((o) => o.kind), abilityTargets: ability.stack[0].targets.length, narsetOnAbility: castsOf(ability, "user", "nar").length, impsOnAbility: castsOf(ability, "user", "imp").length })
      .toEqual({ creatureSpellOnStack: ["Grizzly Bears"], narsetOnCreature: 0, impsOnCreature: 0,
        abilityOnStack: ["activated-ability"], abilityTargets: 1, narsetOnAbility: 0, impsOnAbility: 0 });
  });
});

describe("the guard no printed card reaches", () => {
  it("SYNTHETIC — the bare sentence (no \"You may choose new targets\" printed) keeps the original's targets", () => {
    // No corpus card prints "Copy target instant or sorcery spell." alone, but the bare arm exists (it is what the rider-stripped
    // forms reach), and without the printed permission a copy has no new targets (CR 707.10).
    const BARE = { name: "Bare Echo (synthetic)", type: "Instant", mana: "{U}{U}", cmc: 2, keywords: [], colors: ["U"], oracle: "Copy target instant or sorcery spell." };
    const s1 = theirSpell(SWORDS, at("mine"), { hold: [H("bare", BARE)], pool: { U: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "bare"));
    const copy = copyOf(s2, "Swords to Plowshares");
    expect({ atoms: parseEffectProgram(BARE).atoms, controller: copy.controller, copyTargets: copy.targets.map((t) => t.id), original: !!spell(s2, "Swords to Plowshares") })
      .toEqual({ atoms: [{ op: "copy-instant-or-sorcery", targetType: "spell", spellFilter: "instantSorcery", copyNotCounter: true }], controller: "user", copyTargets: ["mine"], original: true });
  });
});

describe("⭐ Dualcaster Mage — flash, and an enters trigger that copies a spell", () => {
  /** In response to what is on the stack, the user flashes in the Mage; it resolves and its trigger is put on the stack. */
  function flashIn(s) {
    const entered = resolveTopOfStack(cast(s, "user", "mage"));
    return { entered, trigger: entered.stack[entered.stack.length - 1] };
  }

  it("⭐ flashed in on their Lightning Bolt at you: the trigger copies it, the copy is yours and hits THEM (WITNESS)", () => {
    const s1 = theirSpell(BOLT, at("user"), { hold: [H("mage", DUALCASTER_MAGE)], pool: { R: 3 } });
    const offeredAtInstantSpeed = castsOf(s1, "user", "mage").length;
    const { entered, trigger } = flashIn(s1);
    const s3 = resolveTopOfStack(entered);                                    // the trigger resolves: the copy goes on the stack
    const copy = copyOf(s3, "Lightning Bolt");
    const s4 = drain(s3);
    const row = { offeredAtInstantSpeed, trigger: [trigger.kind, trigger.controller, trigger.targets.map((t) => entered.stack.find((o) => o.id === t.id)?.source?.name)],
      stackAfterTrigger: stackNames(s3), copy: [copy.controller, copy.targets.map((t) => t.id)], life: life(s4), mageOnBattlefield: s4.players.user.battlefield.map((p) => p.card.name),
      bolt: everywhere(s4, "Lightning Bolt") };
    console.log("  WITNESS dualcaster", JSON.stringify(row));
    expect(row).toEqual({ offeredAtInstantSpeed: 1, trigger: ["triggered-ability", "user", ["Lightning Bolt"]],
      stackAfterTrigger: ["Lightning Bolt", "Lightning Bolt (copy)"], copy: ["user", ["ai"]], life: { user: 37, ai: 37 },
      mageOnBattlefield: ["Dualcaster Mage"], bolt: ["ai.graveyard"] });
  });

  it("⭐ your own spell is a target too: Giant Growth on your Bears, the Mage flashed in — +6/+6", () => {
    const s0 = board({ active: "user", user: { hand: [H("gg", GIANT_GROWTH), H("mage", DUALCASTER_MAGE)], pool: { G: 1, R: 3 }, battlefield: [P("mine", BEARS, "user")] } });
    const { entered, trigger } = flashIn(cast(s0, "user", "gg", at("mine")));
    const s3 = drain(entered);
    expect({ triggerTargets: trigger.targets.length, power: permanentPower(s3, "mine") }).toEqual({ triggerTargets: 1, power: 8 });
  });

  it("⭐ with no spell on the stack the trigger has no legal target and is removed (CR 603.3d) — the Mage is just a 2/2", () => {
    const s0 = board({ active: "user", user: { hand: [H("mage", DUALCASTER_MAGE)], pool: { R: 3 } } });
    const entered = resolveTopOfStack(cast(s0, "user", "mage"));
    const row = { stack: stackNames(entered), removed: logged(entered, (e) => e.kind === "trigger-removed-no-target").map((e) => e.source),
      pendingArbiter: !!entered.pendingArbiter, battlefield: entered.players.user.battlefield.map((p) => p.card.name) };
    console.log("  WITNESS dualcaster-no-spell", JSON.stringify(row));
    expect(row).toEqual({ stack: [], removed: ["Dualcaster Mage"], pendingArbiter: false, battlefield: ["Dualcaster Mage"] });
  });

  it("an ability on the stack is not a spell: with only their Pyromancer's ping there, the trigger is removed", () => {
    const s0 = board({ user: { hand: [H("mage", DUALCASTER_MAGE)], pool: { R: 3 } }, ai: { battlefield: [P("pyro", PYROMANCER, "ai")] } });
    const ability = dispatchAction(s0, legalActionsForPlayer(s0, "ai").find((a) => a.kind === "activate-ability" && at("user")(a)));
    const entered = resolveTopOfStack(cast(ability, "user", "mage"));
    expect({ stack: entered.stack.map((o) => o.kind), removed: logged(entered, (e) => e.kind === "trigger-removed-no-target").length })
      .toEqual({ stack: ["activated-ability"], removed: 1 });
  });
});

describe("⭐ Imp's Mischief — the target moves, and you lose life equal to that spell's mana value", () => {
  it("⭐ their Swords to Plowshares on your Bears moves to THEIR Bears; you lose 1 (WITNESS)", () => {
    const s1 = theirSpell(SWORDS, at("mine"), { hold: IMPS(), pool: { B: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    const offered = castsOf(s1, "user", "imp").map((a) => a.targets.map((t) => t.name));
    const s2 = resolveTopOfStack(cast(s1, "user", "imp"));
    const moved = spell(s2, "Swords to Plowshares").targets.map((t) => t.id);
    const s3 = drain(s2);
    const row = { offered, moved, lifeAfterImps: life(s2), mineAlive: onBf(s3, "user", "mine"), theirsAlive: onBf(s3, "ai", "theirs"), life: life(s3),
      userGraveyard: names(s3.players.user.graveyard) };
    console.log("  WITNESS imps", JSON.stringify(row));
    expect(row).toEqual({ offered: [["Swords to Plowshares"]], moved: ["theirs"], lifeAfterImps: { user: 39, ai: 40 }, mineAlive: true, theirsAlive: false,
      life: { user: 39, ai: 42 }, userGraveyard: ["Imp's Mischief"] });
  });

  it("⭐ several other legal targets: the choice pauses, the pick moves the target, and THEN the life is lost", () => {
    const s1 = theirSpell(BOLT, at("mine"), { hold: IMPS(), pool: { B: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    const paused = resolveTopOfStack(cast(s1, "user", "imp"));
    const pc = paused.pendingChoice;
    const s3 = resolveChangeTargetChoice(paused, autoPickChangeTarget(paused, pc));
    const s4 = drain(s3);
    const row = { kind: pc.kind, chooser: pc.controller, candidates: pc.candidates.map((c) => c.id), lifeWhilePaused: paused.players.user.life,
      moved: spell(s3, "Lightning Bolt").targets.map((t) => t.id), lifeAfter: s3.players.user.life, theirsAlive: onBf(s4, "ai", "theirs"), mineAlive: onBf(s4, "user", "mine"),
      imps: everywhere(s4, "Imp's Mischief") };
    console.log("  WITNESS imps-choice", JSON.stringify(row));
    expect(row).toEqual({ kind: "change-target", chooser: "user", candidates: ["theirs", "user", "ai"], lifeWhilePaused: 40, moved: ["theirs"], lifeAfter: 39,
      theirsAlive: false, mineAlive: true, imps: ["user.graveyard"] });
  });

  it("⛔ a spell with two targets is not \"a spell with a single target\" (CR 115.9a): Prey Upon is never offered", () => {
    const s1 = theirSpell(PREY_UPON, (a) => a.targets.length === 2, { hold: IMPS(), pool: { B: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    expect({ targets: spell(s1, "Prey Upon").targets.length, offered: castsOf(s1, "user", "imp").length }).toEqual({ targets: 2, offered: 0 });
  });

  it("⭐ the new target must be legal for that spell (CR 115.7a, 702.16b): a Bolt can't move onto their Kor Firewalker", () => {
    const s1 = theirSpell(BOLT, at("mine"), { hold: IMPS(), pool: { B: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("kor", KOR_FIREWALKER, "ai"), P("theirs", BEARS, "ai")] });
    const alternatives = changeTargetAlternatives(s1, spell(s1, "Lightning Bolt")).map((t) => t.id);
    const paused = resolveTopOfStack(cast(s1, "user", "imp"));
    expect({ alternatives, candidates: paused.pendingChoice.candidates.map((c) => c.id) })
      .toEqual({ alternatives: ["theirs", "user", "ai"], candidates: ["theirs", "user", "ai"] });
  });

  it("an ABILITY is judged by its source's colours (the shared arm — Bolt Bend's pool): a red Pyromancer's ping can't move onto Kor Firewalker", () => {
    const s0 = board({ user: { battlefield: [P("mine", BEARS, "user")] }, ai: { battlefield: [P("pyro", PYROMANCER, "ai"), P("kor", KOR_FIREWALKER, "ai")] } });
    const s1 = dispatchAction(s0, legalActionsForPlayer(s0, "ai").find((x) => x.kind === "activate-ability" && at("mine")(x)));
    expect(changeTargetAlternatives(s1, s1.stack[0]).map((t) => t.id)).toEqual(["pyro", "user", "ai"]);
  });

  it("no other legal target: the target stays (CR 115.7a) and the life is lost all the same", () => {
    const s1 = theirSpell(SWORDS, at("mine"), { hold: IMPS(), pool: { B: 2 }, mine: [P("mine", BEARS, "user")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "imp"));
    const s3 = drain(s2);
    expect({ unchanged: logged(s2, (e) => e.effect === "change-target-unchanged").map((e) => e.reason), target: spell(s2, "Swords to Plowshares").targets.map((t) => t.id),
      life: life(s3), mineAlive: onBf(s3, "user", "mine") })
      .toEqual({ unchanged: ["no-other-legal-target"], target: ["mine"], life: { user: 41, ai: 40 }, mineAlive: false });
  });

  describe("⭐ the life lost is the spell's mana value ON THE STACK (CR 202.3)", () => {
    /** The user casts Imp's Mischief on the one spell named `name`, settles a paused pick with the default, and reports the life lost. */
    function lifeLost(s1, name) {
      let s2 = resolveTopOfStack(cast(s1, "user", "imp", onSpell(s1, name)));
      if (s2.pendingChoice) s2 = resolveChangeTargetChoice(s2, autoPickChangeTarget(s2, s2.pendingChoice));
      return s1.players.user.life - s2.players.user.life;
    }
    const table = (o) => ({ hold: IMPS(), pool: { B: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")], ...o });

    it("⭐ an X spell counts its X (CR 202.3e): Blaze for X = 3 costs you 4", () => {
      const s1 = theirSpell(BLAZE, (a) => a.xValue === 3 && at("user")(a), table());
      expect({ mana: spell(s1, "Blaze").source.mana, cmc: spell(s1, "Blaze").source.cmc, lost: lifeLost(s1, "Blaze") }).toEqual({ mana: "{X}{R}", cmc: 1, lost: 4 });
    });

    it("⭐ a split card on the stack is the HALF that was cast (CR 202.3d): Ice costs you 2, not Fire // Ice's 4", () => {
      const s1 = theirSpell(FIRE_ICE, (a) => a.faceCard?.name === "Ice" && at("mine")(a), table());
      expect({ cmc: spell(s1, "Ice").source.cmc, lost: lifeLost(s1, "Ice") }).toEqual({ cmc: 4, lost: 2 });
    });

    it("⭐ an Adventure on the stack has its own mana cost (CR 715.3b): Petty Theft costs you 2, not Brazen Borrower's 3", () => {
      const s1 = theirSpell(BORROWER, (a) => a.faceCard?.name === "Petty Theft" && at("mine")(a), table());
      const before = spell(s1, "Petty Theft").targets.map((t) => t.id);
      expect({ cmc: spell(s1, "Petty Theft").source.cmc, before, lost: lifeLost(s1, "Petty Theft") }).toEqual({ cmc: 3, before: ["mine"], lost: 2 });
    });

    it("⭐ a flashback cast keeps its printed mana cost (CR 118.9c): Firebolt flashed back for {4}{R} costs you 1", () => {
      const s0 = board({ user: { hand: IMPS(), pool: { B: 2 }, battlefield: [P("mine", BEARS, "user")] }, ai: { graveyard: [H("sp", FIREBOLT)], pool: { R: 5 }, battlefield: [P("theirs", BEARS, "ai")] } });
      const s1 = cast(s0, "ai", "sp", (a) => a.flashbackCast && at("mine")(a));
      expect({ paidView: spell(s1, "Firebolt").source.mana, lost: lifeLost(s1, "Firebolt") }).toEqual({ paidView: "{4}{R}", lost: 1 });
    });

    it("⭐ an X-target spell enumerates at its X: Curse of the Swine for X = 1 moves to their Bears and costs you 3", () => {
      const s1 = theirSpell(CURSE_OF_THE_SWINE, (a) => a.xValue === 1 && only("mine")(a), table());
      let s2 = resolveTopOfStack(cast(s1, "user", "imp"));
      expect({ moved: spell(s2, "Curse of the Swine").targets.map((t) => t.id), lost: 40 - s2.players.user.life }).toEqual({ moved: ["theirs"], lost: 3 });
      s2 = drain(s2);
      expect({ mine: onBf(s2, "user", "mine"), theirs: onBf(s2, "ai", "theirs") }).toEqual({ mine: true, theirs: false });
    });

    it("⭐ a copy has its original's mana value, X included (CR 707.10): a copy of Blaze for X = 2 costs you 3", () => {
      const s0 = board({ user: { hand: IMPS(), pool: { B: 2 } }, ai: { hand: [H("sp", BLAZE), H("rev", REVERBERATE)], pool: { R: 5 } } });
      const s1 = resolveTopOfStack(cast(cast(s0, "ai", "sp", (a) => a.xValue === 2 && at("user")(a)), "ai", "rev"));
      const copy = copyOf(s1, "Blaze");
      let s2 = resolveTopOfStack(cast(s1, "user", "imp", at(copy.id)));
      if (s2.pendingChoice) s2 = resolveChangeTargetChoice(s2, autoPickChangeTarget(s2, s2.pendingChoice));
      expect({ copyX: copy.payload.params.xValue, lost: 40 - s2.players.user.life, copyNow: copyOf(s2, "Blaze").targets.map((t) => t.id) }).toEqual({ copyX: 2, lost: 3, copyNow: ["ai"] });
    });
  });

  it("the target gone before it resolves (CR 608.2b): Imp's Mischief doesn't resolve — no life is lost", () => {
    const s0 = board({ user: { hand: [...IMPS(), H("cs", COUNTERSPELL)], pool: { B: 1, U: 3 } }, ai: { hand: [H("sp", BOLT)], pool: { R: 1 } } });
    const s1 = cast(s0, "ai", "sp", at("user"));
    const s3 = drain(cast(cast(s1, "user", "imp"), "user", "cs", onSpell(s1, "Lightning Bolt")));
    expect({ life: life(s3), imps: everywhere(s3, "Imp's Mischief") }).toEqual({ life: { user: 40, ai: 40 }, imps: ["user.graveyard"] });
  });

  it("documented under-read: an Aura spell (one target) is a legal target but is not moved — the life is still lost", () => {
    const s1 = theirSpell(PACIFISM, at("mine"), { hold: IMPS(), pool: { B: 2 }, mine: [P("mine", BEARS, "user")], theirs: [P("theirs", BEARS, "ai")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "imp"));
    expect({ unchanged: logged(s2, (e) => e.effect === "change-target-unchanged").map((e) => e.reason), life: life(s2) })
      .toEqual({ unchanged: ["no-program"], life: { user: 38, ai: 40 } });
  });
});

describe("Mana Drain reads the same stack mana value", () => {
  const drainFor = (card, pick) => {
    const s1 = theirSpell(card, pick, { hold: [H("md", MANA_DRAIN)], pool: { U: 2 }, mine: [P("mine", BEARS, "user")] });
    const s2 = resolveTopOfStack(cast(s1, "user", "md"));
    return (s2.delayedTriggers || []).map((d) => d.effectClause);
  };

  it("⭐ {X}{X}{G} for X = 2 is 5 (CR 202.3e — each {X} counts): Gelatinous Genesis", () => {
    expect(drainFor(GELATINOUS_GENESIS, (a) => a.xValue === 2)).toEqual(["add " + "{c}".repeat(5)]);
  });

  it("⭐ the half that was cast (CR 202.3d): Ice is 2", () => {
    expect(drainFor(FIRE_ICE, (a) => a.faceCard?.name === "Ice" && at("mine")(a))).toEqual(["add {c}{c}"]);
  });
});
