/**
 * TALON GATES OF MADARA — the play-weighted program, #570 (EDHREC #570). A "Land — Gate":
 *   "When this land enters, up to one target creature phases out.
 *    {T}: Add {C}.
 *    {1}, {T}: Add one mana of any color.
 *    {4}: Put this card from your hand onto the battlefield."
 *
 * Two lines held it at land-partial:
 *  - THE ENTERS TRIGGER parsed HIGH ({ op: "phase-out", targetType: "creature", minTargets: 0, maxTargets: 1 }), but the trigger
 *    flush's side allowlist had no answer for a phase-out, so the trigger routed to the Arbiter. An OPTIONAL, UNRESTRICTED
 *    phase-out now reads "enemy" (programQueries.atomTargetIntent): an opponent's creature is treated as though it doesn't exist
 *    until its controller's next untap step (CR 702.26b, 502.1), and "up to one" lets the chooser take no target when no
 *    opponent has a creature (CR 115.6). The mandatory and the controller-restricted forms keep their old answer.
 *  - THE HAND ABILITY: an ability that moves its own card out of a zone functions only in that zone (CR 113.6m), so "{4}: Put
 *    this card from your hand onto the battlefield." is activated from the HAND, whenever its owner has priority (CR 117.1b). One
 *    parse (abilities.parseHandSelfPutAbility) feeds the hand offer (legalChoices), the dispatcher and the land coverage lane;
 *    the ability goes on the stack with the card still in hand (revealed, CR 602.2a) and resolves through the HAND_SELF_PUT
 *    resolver — enterPermanent, then landfall. Putting a land onto the battlefield is not playing a land (CR 305.4): no land
 *    drop is spent, and a "when you play a land" watcher stays quiet.
 *
 * THE COMBAT FIX the instant-speed entry needed: gameState.phaseOutPermanents now removes a phasing attacker from combat
 * (CR 702.26b, 506.4). An attacker phased out mid-combat used to stay declared, and the defender was offered a block against a
 * creature that no longer existed. A phased-out blocker's records stay: the attacker it blocked remains blocked (CR 509.1h).
 *
 * THE DOCUMENTED UNDER-READ: "{1}, {T}: Add one mana of any color." is read COLORLESS-only by the runtime mana model — the
 * filter-land read every land of that shape carries today (Unknown Shores reads identically and is native). The engine gives
 * the player less than printed, never more; pinned below so a mana-model slice that lifts it re-points this file.
 *
 * Real oracle fixtures (bundled Scryfall, the 2026-10-01 data, generated by cardIndex.publicCard — never typed by hand), except
 * the clearly labelled SYNTHETIC shapes in the false-positive guards.
 */
import { beforeEach, describe, expect, it } from "vitest";
import { _resetIdsForTests, createGameState, createPermanent } from "./gameState.js";
import { legalActionsForPlayer } from "./legalChoices.js";
import { dispatchAction } from "./actionDispatcher.js";
import { chooseTriggerTargets, flushTriggers, resolveTopOfStack, runStepActions } from "./gameEngine.js";
import { classifyCard, isNativeTier } from "./coverage.js";
import { parseActivatedAbilities, parseHandSelfPutAbility } from "./effects/abilities.js";
import { atomTargetIntent, parseEffectClause, programConfidence } from "./effects/parser.js";
import { detectTriggers } from "./triggers.js";
import { triggerRoutesNatively } from "./triggerRouting.js";
import { manaActivationCost, manaProduction, manaSources, planPayment } from "./manaModel.js";
import { pickAction } from "./opponentAI.js";

beforeEach(() => _resetIdsForTests());

// ─── real card fixtures (generated from the bundled Scryfall data) ──────────────
const TALON = {"name":"Talon Gates of Madara","type":"Land — Gate","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"When this land enters, up to one target creature phases out.\n{T}: Add {C}.\n{1}, {T}: Add one mana of any color.\n{4}: Put this card from your hand onto the battlefield."}; // land
const BEARS = {"name":"Grizzly Bears","type":"Creature — Bear","mana":"{1}{G}","cmc":2,"power":"2","toughness":"2","keywords":[],"colors":["G"],"oracle":""}; // native-body
const WASTES = {"name":"Wastes","type":"Basic Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {C}."}; // land
const FOREST = {"name":"Forest","type":"Basic Land — Forest","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"({T}: Add {G}.)"}; // land
const KROSAN_GRIP = {"name":"Krosan Grip","type":"Instant","mana":"{2}{G}","cmc":3,"keywords":["Split second"],"colors":["G"],"oracle":"Split second (As long as this spell is on the stack, players can't cast spells or activate abilities that aren't mana abilities.)\nDestroy target artifact or enchantment."}; // native-spell
const CLEVER_CONCEALMENT = {"name":"Clever Concealment","type":"Instant","mana":"{2}{W}{W}","cmc":4,"keywords":["Convoke"],"colors":["W"],"oracle":"Convoke (Your creatures can help cast this spell. Each creature you tap while casting this spell pays for {1} or one mana of that creature's color.)\nAny number of target nonland permanents you control phase out. (Treat them and anything attached to them as though they don't exist until your next turn.)"}; // native-spell
const VODALIAN_ILLUSIONIST = {"name":"Vodalian Illusionist","type":"Creature — Merfolk Wizard","mana":"{2}{U}","cmc":3,"power":"2","toughness":"2","keywords":[],"colors":["U"],"oracle":"{U}{U}, {T}: Target creature phases out. (While it's phased out, it's treated as though it doesn't exist. It phases in before its controller untaps during their next untap step.)"}; // native-activated
const URBAN_RETREAT = {"name":"Urban Retreat","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"This land enters tapped.\n{T}: Add {G}, {W}, or {U}.\n{2}, Return a tapped creature you control to its owner's hand: Put this card from your hand onto the battlefield. Activate only as a sorcery."}; // land-partial
const ZARETH_SAN = {"name":"Zareth San, the Trickster","type":"Legendary Creature — Merfolk Rogue","mana":"{3}{U}{B}","cmc":5,"power":"4","toughness":"4","keywords":["Flash"],"colors":["B","U"],"oracle":"Flash\n{2}{U}{B}, Return an unblocked attacking Rogue you control to its owner's hand: Put this card from your hand onto the battlefield tapped and attacking.\nWhenever Zareth San deals combat damage to a player, you may put target permanent card from that player's graveyard onto the battlefield under your control."}; // body-only
const TATYOVA = {"name":"Tatyova, Benthic Druid","type":"Legendary Creature — Merfolk Druid","mana":"{3}{G}{U}","cmc":5,"power":"3","toughness":"3","keywords":["Landfall"],"colors":["G","U"],"oracle":"Landfall — Whenever a land you control enters, you gain 1 life and draw a card."}; // native-trigger
const CITY_OF_TRAITORS = {"name":"City of Traitors","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"When you play another land, sacrifice this land.\n{T}: Add {C}{C}."}; // land
const UNKNOWN_SHORES = {"name":"Unknown Shores","type":"Land","mana":"","cmc":0,"keywords":[],"colors":[],"oracle":"{T}: Add {C}.\n{1}, {T}: Add one mana of any color."}; // land

// ─── harness ──────────────────────────────────────────────────────────────────
const P = (id, card, controller = "user", extra = {}) => ({ ...createPermanent({ id, card: { id: `c-${id}`, ...card }, controller, summoningSick: false }), ...extra });
const H = (id, card) => ({ ...card, id });
const wastes = (n, controller = "user") => Array.from({ length: n }, (_, i) => P(`w${i + 1}`, WASTES, controller));
/** The user's precombat main phase by default; `user`/`ai` are battlefields, `hand` the user's hand (Talon Gates by default). */
function board({ user = wastes(4), ai = [P("theirs", BEARS, "ai")], hand = [H("talon", TALON)], active = "user", holder = active, step = "main", phase = "precombat-main", stack = [], passes = 0 } = {}) {
  const g = createGameState({ userDeck: [], aiDeck: [] });
  const lib = (who) => [1, 2, 3].map((i) => ({ ...BEARS, id: `${who}-lib${i}` }));
  return { ...g, turn: 5, activePlayer: active, priorityHolder: holder, phase, step, stack, pendingTriggers: [], consecutivePasses: passes,
    players: { ...g.players,
      user: { ...g.players.user, battlefield: user, hand, library: lib("user") },
      ai: { ...g.players.ai, battlefield: ai, hand: [], library: lib("ai") } } };
}
const offers = (s, who = "user") => legalActionsForPlayer(s, who).filter((a) => a.kind === "activate-hand-self-put");
const putAction = (s) => offers(s)[0];
/** Resolve the stack down to empty (each resolution flushes what it woke, CR 603.3). */
const drain = (s) => { let n = s; for (let i = 0; i < 10 && n.stack.length; i++) n = resolveTopOfStack(n); return n; };
const ids = (zone) => (zone || []).map((x) => x.id).sort();
const untapFor = (s, who) => runStepActions({ ...s, activePlayer: who, phase: "beginning", step: "untap", turn: s.turn + 1, stack: [] });
const talonOnField = (s) => s.players.user.battlefield.find((p) => p.card?.id === "talon");
const errorCode = (fn) => { try { fn(); } catch (e) { return e.code || e.name; } return null; };

describe("the card", () => {
  it("⭐ classifies native (land); both formerly-unmodeled lines are read", () => {
    const tier = classifyCard(TALON);
    expect({ tier, native: isNativeTier(tier) }).toEqual({ tier: "land", native: true });
  });

  it("the enters trigger: one self-ETB, a HIGH optional creature phase-out, an enemy-side pick, routed natively", () => {
    const [d, ...rest] = detectTriggers(TALON);
    const program = parseEffectClause(d.effectClause, "Instant", { sourceScoped: true });
    expect({ extra: rest.length, event: d.event, scope: d.scope, clause: d.effectClause, conf: programConfidence(program), atoms: program.atoms,
      intent: atomTargetIntent(program.atoms[0]), routes: triggerRoutesNatively(d) })
      .toEqual({ extra: 0, event: "etb", scope: "self", clause: "up to one target creature phases out", conf: "high",
        atoms: [{ op: "phase-out", targetType: "creature", minTargets: 0, maxTargets: 1 }], intent: "enemy", routes: true });
  });

  it("the hand line: read by the hand parse ({4}), and never offered as a battlefield ability (CR 113.6m)", () => {
    const line = "{4}: Put this card from your hand onto the battlefield.";
    const asBattlefieldAbility = parseActivatedAbilities(TALON).find((a) => a.raw === line);
    expect({ hand: parseHandSelfPutAbility(TALON), battlefieldModeled: asBattlefieldAbility?.modeled })
      .toEqual({ hand: { manaPips: "{4}", raw: line }, battlefieldModeled: false });
  });

  it("the near misses keep their residue: Urban Retreat (a returned creature + sorcery timing), Zareth San (a creature; tapped and attacking)", () => {
    expect({ urban: parseHandSelfPutAbility(URBAN_RETREAT), urbanTier: classifyCard(URBAN_RETREAT), zareth: parseHandSelfPutAbility(ZARETH_SAN), zarethTier: classifyCard(ZARETH_SAN) })
      .toEqual({ urban: null, urbanTier: "land-partial", zareth: null, zarethTier: "body-only" });
  });

  it("a mandatory or controller-restricted phase-out keeps its old side (ambiguous): Vodalian Illusionist, Clever Concealment", () => {
    const atomOf = (card, re) => parseEffectClause(card.oracle.split("\n").find((l) => re.test(l)).replace(/^.*?: /, "").replace(/\s*\(.*\)\s*$/, ""), "Instant").atoms[0];
    const vodalian = atomOf(VODALIAN_ILLUSIONIST, /phases out/);
    const clever = atomOf(CLEVER_CONCEALMENT, /phase out/);
    expect({ vodalian: [vodalian.op, vodalian.minTargets ?? null, atomTargetIntent(vodalian)], clever: [clever.op, clever.minTargets, atomTargetIntent(clever)] })
      .toEqual({ vodalian: ["phase-out", null, "ambiguous"], clever: ["phase-out", 0, "ambiguous"] });
  });

  it("⛔ SYNTHETIC false-positive guards: a non-land carrier, a {T} or {X} cost, and a 'tapped' rider are not read", () => {
    // SYNTHETIC (no printed card has these shapes): an Aura put onto the battlefield must be attached as it enters (CR 303.4f) —
    // the lane enters cards with nothing attached; a {T}/{X} cost has no reading for a card in hand; a land that must enter
    // tapped would enter untapped through a lane that read only the cost.
    const synth = (type, oracle) => ({ name: "Synthetic Hand Put", type, mana: "", cmc: 0, keywords: [], colors: [], oracle });
    expect({
      aura: parseHandSelfPutAbility(synth("Enchantment — Aura", "Enchant creature\n{2}: Put this card from your hand onto the battlefield.")),
      tapCost: parseHandSelfPutAbility(synth("Land", "{T}: Put this card from your hand onto the battlefield.")),
      xCost: parseHandSelfPutAbility(synth("Land", "{X}: Put this card from your hand onto the battlefield.")),
      tappedRider: parseHandSelfPutAbility(synth("Land", "{4}: Put this card from your hand onto the battlefield tapped.")),
    }).toEqual({ aura: null, tapCost: null, xCost: null, tappedRider: null });
  });
});

describe("⭐ the hand activation (CR 113.6m, 117.1b, 305.4)", () => {
  it("offered with {4} available (for the carrier only — not the Forest beside it), refused with three lands", () => {
    const hand = [H("talon", TALON), H("forest", FOREST)];
    const four = offers(board({ hand }));
    const three = offers(board({ user: wastes(3), hand }));
    console.log(`WITNESS talonOffer ${JSON.stringify({ four: four.map((a) => [a.cardId, a.cmc]), three: three.length })}`);
    expect({ four: four.map((a) => [a.cardId, a.cmc, a.abilityText]), three: three.length })
      .toEqual({ four: [["talon", 4, "{4}: Put this card from your hand onto the battlefield."]], three: 0 });
  });

  it("⭐ end to end: paid, on the stack with the card still in hand; it enters untapped, spends no land drop, and its trigger phases out the opponent's creature", () => {
    const s = board({ user: [...wastes(4), P("mine", BEARS)], hand: [H("talon", TALON), H("forest", FOREST)] });
    const activated = dispatchAction(s, putAction(s));
    const onStack = { stack: activated.stack.map((o) => [o.kind, o.payload?.resolver]), inHand: ids(activated.players.user.hand), tapped: ids(activated.players.user.battlefield.filter((p) => p.tapped)), holder: activated.priorityHolder };
    const entered = resolveTopOfStack(activated);
    const talon = talonOnField(entered);
    const afterEntry = { tapped: talon?.tapped, landsPlayed: entered.players.user.landsPlayedThisTurn, inHand: ids(entered.players.user.hand),
      trigger: entered.stack.map((o) => [o.kind, o.source?.name, (o.targets || []).map((t) => t.id)]) };
    const out = resolveTopOfStack(entered);
    // The land drop is still there once the stack is empty again (CR 305.1 — a land is played only with an empty stack).
    const row = { onStack, afterEntry, theirsPhasedOut: ids(out.players.ai.phasedOut), mineStays: out.players.user.battlefield.some((p) => p.id === "mine"),
      landDropStillOffered: out.stack.length === 0 && legalActionsForPlayer(out, "user").some((a) => a.kind === "play-land" && a.cardId === "forest") };
    console.log(`WITNESS talonHandPut ${JSON.stringify(row)}`);
    expect(row).toEqual({
      onStack: { stack: [["activated-ability", "hand.self-put"]], inHand: ["forest", "talon"], tapped: ["w1", "w2", "w3", "w4"], holder: "user" },
      afterEntry: { tapped: false, landsPlayed: 0, inHand: ["forest"], trigger: [["triggered-ability", "Talon Gates of Madara", ["theirs"]]] },
      theirsPhasedOut: ["theirs"],
      mineStays: true,
      landDropStillOffered: true,
    });
  });

  it("⭐ instant speed: on the opponent's turn, after they pass, the activation is offered — and they get to respond to it", () => {
    const s = board({ active: "ai", holder: "user", phase: "combat", step: "declare-attackers", passes: 1 });
    const act = putAction(s);
    const activated = dispatchAction(s, act);
    const passed = dispatchAction(activated, { kind: "pass-priority", playerId: "user" });
    expect({ offered: !!act, holder: activated.priorityHolder, passes: activated.consecutivePasses, afterPass: [passed.priorityHolder, passed.stack.length] })
      .toEqual({ offered: true, holder: "user", passes: 0, afterPass: ["ai", 1] });
  });

  it("not offered to a player who doesn't hold priority", () => {
    expect(offers(board({ holder: "ai" })).length).toBe(0);
  });

  it("⛔ withheld under split second (CR 702.61a) — the mana abilities stay", () => {
    const grip = { id: "stk-grip", kind: "spell", controller: "ai", source: { ...KROSAN_GRIP, id: "grip" }, targets: [], payload: {} };
    const actions = legalActionsForPlayer(board({ stack: [grip] }), "user");
    expect({ put: actions.some((a) => a.kind === "activate-hand-self-put"), mana: actions.some((a) => a.kind === "tap-for-mana") }).toEqual({ put: false, mana: true });
  });

  it("not a land play: landfall fires (Tatyova), a 'when you play another land' watcher stays quiet (City of Traitors) — and does fire on a real land drop", () => {
    const field = [...wastes(4), P("tat", TATYOVA), P("city", CITY_OF_TRAITORS)];
    const s = board({ user: field });
    const put = drain(dispatchAction(s, putAction(s)));
    const dropped = flushTriggers(dispatchAction(board({ user: field }), { kind: "play-land", playerId: "user", cardId: "talon" }), { chooseTargets: chooseTriggerTargets });
    const row = {
      put: { life: put.players.user.life - s.players.user.life, drew: put.players.user.hand.length, cityStays: put.players.user.battlefield.some((p) => p.id === "city") },
      landDrop: { cityTriggered: dropped.stack.some((o) => o.source?.name === "City of Traitors") },
    };
    console.log(`WITNESS talonNotAPlay ${JSON.stringify(row)}`);
    expect(row).toEqual({ put: { life: 1, drew: 1, cityStays: true }, landDrop: { cityTriggered: true } });
  });

  it("the card left the hand in response: the ability does nothing (a logged fizzle), the {4} stays spent", () => {
    const s = board();
    const activated = dispatchAction(s, putAction(s));
    const discarded = { ...activated, players: { ...activated.players, user: { ...activated.players.user, hand: [], graveyard: [H("talon", TALON)] } } };
    const out = resolveTopOfStack(discarded);
    expect({ entered: !!talonOnField(out), inGraveyard: ids(out.players.user.graveyard), fizzle: out.log.some((e) => e.effect === "hand-self-put" && e.fizzled === true),
      tapped: out.players.user.battlefield.filter((p) => p.tapped).length })
      .toEqual({ entered: false, inGraveyard: ["talon"], fizzle: true, tapped: 4 });
  });

  it("on the battlefield the {4} line is no ability at all; its mana abilities are", () => {
    const s = board({ user: [...wastes(4), P("tg", TALON)], hand: [] });
    const actions = legalActionsForPlayer(s, "user");
    expect({ activations: actions.filter((a) => a.kind === "activate-ability" && a.permanentId === "tg").length, handPut: actions.some((a) => a.kind === "activate-hand-self-put"),
      taps: actions.filter((a) => a.kind === "tap-for-mana" && a.permanentId === "tg").map((a) => a.color) })
      .toEqual({ activations: 0, handPut: false, taps: ["C"] });
  });

  it("⛔ the dispatcher refuses a card not in hand, a card without the ability, and an unpaid cost", () => {
    const s = board({ hand: [H("talon", TALON), H("forest", FOREST)] });
    const act = putAction(s);
    expect({
      notInHand: errorCode(() => dispatchAction(s, { ...act, cardId: "nope" })),
      noAbility: errorCode(() => dispatchAction(s, { ...act, cardId: "forest" })),
      unpaid: errorCode(() => dispatchAction(board({ user: wastes(3) }), act)),
    }).toEqual({ notInHand: "CARD_NOT_IN_HAND", noAbility: "NO_ABILITY", unpaid: "MANA_SHORT" });
  });

  it("the AI picker never takes it (its play is unchanged — it passes rather than activate)", () => {
    const s = board({ active: "ai", holder: "ai", user: [P("mine", BEARS)], ai: wastes(4, "ai") });
    const ai = { ...s, players: { ...s.players, ai: { ...s.players.ai, hand: [H("talon", TALON)], landsPlayedThisTurn: 1 } } };
    const actions = legalActionsForPlayer(ai, "ai");
    expect({ offered: actions.some((a) => a.kind === "activate-hand-self-put"), picked: pickAction(ai, "ai", actions)?.kind }).toEqual({ offered: true, picked: "pass-priority" });
  });
});

describe("⭐ the enters trigger (CR 702.26, 115.6)", () => {
  it("played as the land drop: the opponent's creature phases out until ITS controller's untap step, not yours", () => {
    const s = board({ user: [P("mine", BEARS)] });
    const played = dispatchAction(s, { kind: "play-land", playerId: "user", cardId: "talon" });
    const out = drain(flushTriggers(played, { chooseTargets: chooseTriggerTargets }));
    const row = { landsPlayed: out.players.user.landsPlayedThisTurn, theirsOut: ids(out.players.ai.phasedOut), mineStays: out.players.user.battlefield.some((p) => p.id === "mine"),
      stillOutOnYourUntap: ids(untapFor(out, "user").players.ai.phasedOut), backOnTheirs: untapFor(out, "ai").players.ai.battlefield.some((p) => p.id === "theirs") };
    console.log(`WITNESS talonLandDrop ${JSON.stringify(row)}`);
    expect(row).toEqual({ landsPlayed: 1, theirsOut: ["theirs"], mineStays: true, stillOutOnYourUntap: ["theirs"], backOnTheirs: true });
  });

  it("⭐ flashed in against an attack: the phased-out attacker is removed from combat (CR 702.26b, 506.4) — no block is offered against it and it deals no damage; the other attacker fights on", () => {
    let s = board({ active: "ai", holder: "ai", phase: "combat", step: "declare-attackers", user: [...wastes(4), P("mine", BEARS)], ai: [P("theirs", BEARS, "ai"), P("theirs2", BEARS, "ai")] });
    for (const id of ["theirs", "theirs2"]) s = dispatchAction(s, legalActionsForPlayer(s, "ai").find((a) => a.kind === "declare-attacker" && a.permanentId === id));
    s = dispatchAction(s, { kind: "pass-priority", playerId: "ai" }); // the attacker passes; the defender holds priority
    const out = resolveTopOfStack(resolveTopOfStack(dispatchAction(s, putAction(s))));
    const gone = ids(out.players.ai.phasedOut);
    const other = ["theirs", "theirs2"].find((id) => !gone.includes(id));
    let blk = out;
    for (let i = 0; i < 6 && blk.step !== "declare-blockers"; i++) blk = dispatchAction(blk, { kind: "pass-priority", playerId: blk.priorityHolder });
    const blockTargets = [...new Set(legalActionsForPlayer({ ...blk, priorityHolder: "user" }, "user").filter((a) => a.kind === "declare-blocker").map((a) => a.attackerId))];
    let end = blk; // no block declared: the remaining Bear connects
    for (let i = 0; i < 12 && end.phase === "combat"; i++) end = dispatchAction(end, { kind: "pass-priority", playerId: end.priorityHolder });
    const row = { gone: gone.length, attackers: out.combat.attackers.map((a) => a.permanentId), blockTargets, lifeLost: s.players.user.life - end.players.user.life };
    console.log(`WITNESS talonVsAttack ${JSON.stringify({ ...row, other })}`);
    expect(row).toEqual({ gone: 1, attackers: [other], blockTargets: [other], lifeLost: 2 });
  });

  it("a phased-out BLOCKER leaves its attacker blocked (CR 509.1h, 510.1c): the attacker deals no damage to the player", () => {
    let s = board({ phase: "combat", step: "declare-attackers", user: [...wastes(4), P("mine", BEARS)] });
    s = dispatchAction(s, legalActionsForPlayer(s, "user").find((a) => a.kind === "declare-attacker" && a.permanentId === "mine"));
    for (let i = 0; i < 6 && s.step !== "declare-blockers"; i++) s = dispatchAction(s, { kind: "pass-priority", playerId: s.priorityHolder });
    s = dispatchAction(s, legalActionsForPlayer(s, "ai").find((a) => a.kind === "declare-blocker" && a.permanentId === "theirs"));
    const out = resolveTopOfStack(resolveTopOfStack(dispatchAction(s, putAction(s))));
    let end = out;
    for (let i = 0; i < 12 && end.phase === "combat"; i++) end = dispatchAction(end, { kind: "pass-priority", playerId: end.priorityHolder });
    expect({ blockerOut: ids(out.players.ai.phasedOut), blockRecordKept: out.combat.blockers.map((b) => [b.blockerId, b.attackerId]), aiLifeLost: s.players.ai.life - end.players.ai.life })
      .toEqual({ blockerOut: ["theirs"], blockRecordKept: [["theirs", "mine"]], aiLifeLost: 0 });
  });

  it("⭐ zero targets is a legal choice: with no opposing creature it targets nothing — your own creature stays", () => {
    const s = board({ user: [...wastes(4), P("mine", BEARS)], ai: [] });
    const entered = resolveTopOfStack(dispatchAction(s, putAction(s)));
    const out = resolveTopOfStack(entered);
    expect({ trigger: entered.stack.map((o) => [o.kind, (o.targets || []).length]), mineStays: out.players.user.battlefield.some((p) => p.id === "mine"),
      phased: [...out.players.user.phasedOut || [], ...out.players.ai.phasedOut || []].length, stack: out.stack.length })
      .toEqual({ trigger: [["triggered-ability", 0]], mineStays: true, phased: 0, stack: 0 });
  });
});

describe("the mana abilities", () => {
  it("{T}: Add {C} taps and pays", () => {
    const s = board({ user: [P("tg", TALON)], hand: [] });
    const tap = legalActionsForPlayer(s, "user").find((a) => a.kind === "tap-for-mana" && a.permanentId === "tg");
    const tapped = dispatchAction(s, tap);
    const plan = planPayment(s.players.user.manaPool, manaSources(s, "user"), { generic: 0, W: 0, U: 0, B: 0, R: 0, G: 0, C: 1, hybrid: [] });
    expect({ pool: tapped.players.user.manaPool.C, tappedTalon: tapped.players.user.battlefield.find((p) => p.id === "tg").tapped, plan: plan?.taps })
      .toEqual({ pool: 1, tappedTalon: true, plan: [{ permanentId: "tg", color: "C", amount: 1 }] });
  });

  it("THE UNDER-READ: the {1} filter line is read colorless-only, exactly as Unknown Shores (native) — never a free colored mana", () => {
    const s = board({ user: [P("tg", TALON), P("w1", WASTES)], hand: [] });
    const green = planPayment(s.players.user.manaPool, manaSources(s, "user"), { generic: 0, W: 0, U: 0, B: 0, R: 0, G: 1, C: 0, hybrid: [] });
    expect({ talon: manaProduction(TALON), shores: manaProduction(UNKNOWN_SHORES), talonCost: manaActivationCost(TALON), shoresTier: classifyCard(UNKNOWN_SHORES), green })
      .toEqual({ talon: { colors: ["C"], amount: 1, requiresTap: true }, shores: { colors: ["C"], amount: 1, requiresTap: true }, talonCost: null, shoresTier: "land", green: null });
  });
});
